### ISSUE TITLE
Swift 4.2 Support with Xcode 10

### ISSUE THREAD

**Issue by techmehra** [Hearst-DD/ObjectMapper#1001]

**Comment by johnpool3** [comment]
Updating to the latest version resolves this issue.

**Comment by techmehra** [comment]
@johnpool3 What version currently you are using, What can I see form pod spec It still point to 4.0

**Comment by gcharita** [comment]
@techmehra support for swift 4.2 and Xcode 10 added since version 3.3.0

**Comment by shenwawa** [comment]
How can I upgrade to 3.3, 
`pod 'ObjectMapper', '~> 3.3'`
`pod install`

`Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "ObjectMapper":
  In Podfile:
    ObjectMapper (~> 3.3)
`
my xcode version is 10

**Comment by gcharita** [comment]
For everyone who want to make sure that they have the latest version
- Check if your `Podfile.lock` have something like this:
```
- ObjectMapper (3.3.0)
```
- If not, update your regular `Podfile` to have this:
```ruby
pod 'ObjectMapper', '3.3' 
```

- Then run `pod repo update`
- And then run `pod install`

**Comment by kajensen** [comment]
This is not working for me. I still have a "Convert to Swift 4.2" for *only* ObjectMapper. I am using 3.3, many pod update/installs/resets/etc. Seems to be an issue with this library in particular.

**Comment by kajensen** [comment]
#1012

**Comment by tristanhimmelman** [comment]
Swift 4.2 support has now been released
