### ISSUE TITLE
Invalid redeclaration of '<-' error in Xcode 10

### ISSUE THREAD

**Issue by Kanika-Sharma** [Hearst-DD/ObjectMapper#1004]
Everything was working fine in xcode 9.4. After updating to xcode 10, the below errors started appearing.
![screen shot 2018-09-21 at 2 45 24 pm](https://user-images.githubusercontent.com/25525009/45872544-e5f79500-bdad-11e8-82f4-1044abf919b4.png)
![screen shot 2018-09-21 at 2 46 12 pm](https://user-images.githubusercontent.com/25525009/45872551-e8f28580-bdad-11e8-9c1b-71542c7e7830.png)

**Comment by gcharita** [comment]
@Kanika-Sharma just update to the latest version (this fixed in version 3.3.0)

**Comment by Kanika-Sharma** [comment]
> @Kanika-Sharma just update to the latest version (this fixed in version 3.3.0)

Working fine.... Thanks

**Comment by HelioVieiraSilvaJr** [comment]
Tks.. its working for me also.

**Comment by rahul-inspired-iosdeveloper** [comment]
> > @Kanika-Sharma just update to the latest version (this fixed in version 3.3.0)
> 
> Working fine.... Thanks

Hi which library you updated to fix this issue

**Comment by gcharita** [comment]
@chika-kasymov yes swift 3 is also supported

**Comment by umair151** [comment]
Yes, it fixed for swift 3.0. Thanks

**Comment by osiellima** [comment]
> > @Kanika-Sharma just update to the latest version (this fixed in version 3.3.0)
> 
> Working fine.... Thanks

Can you say what do I need to update, please be more specific.

**Comment by rharikrishnan84** [comment]
Hi i am using Xcode 10.1 && swift 3.0 but still i am  facing the same error.can you say which library you updated to fix this issue.Thanks in advance.
![screen shot 2018-11-13 at 10 45 46 am](https://user-images.githubusercontent.com/9457754/48392444-6644d180-e731-11e8-8540-d6bb122fa338.png)

**Comment by rahul-inspired-iosdeveloper** [comment]
> Hi i am using Xcode 10.1 && swift 3.0 but still i am facing the same error.can you say which library you updated to fix this issue.Thanks in advance.
> ![screen shot 2018-11-13 at 10 45 46 am](https://user-images.githubusercontent.com/9457754/48392444-6644d180-e731-11e8-8540-d6bb122fa338.png)

In my case I have updated cocoapods in my system and updated pods in the project

$ [sudo] gem install cocoapods

$ pod install - on projects

**Comment by gcharita** [comment]
@osiellima you need to update ObjectMapper to the latest version.

@rharikrishnan84 @rahul-inspired-iosdeveloper 
Please refer to this comment: https://github.com/tristanhimmelman/ObjectMapper/issues/1001#issuecomment-424267483

> For everyone who want to make sure that they have the latest version
> - Check if your `Podfile.lock` have something like this:
> ```
> - ObjectMapper (3.3.0)
> ```
> - If not, update your regular `Podfile` to have this:
> ```ruby
> pod 'ObjectMapper', '3.3' 
> ```
> 
> - Then run `pod repo update`
> - And then run `pod install`
