### ISSUE TITLE
Xcode 10 compile error

### ISSUE THREAD

**Issue by shenwawa** [Hearst-DD/ObjectMapper#1008]
How can I upgrade to 3.3?
`pod 'ObjectMapper', '~> 3.3'`
`pod install`

`Analyzing dependencies [!] CocoaPods could not find compatible versions for pod "ObjectMapper": In Podfile: ObjectMapper (~> 3.3)`
my xcode version is 10

**Comment by gcharita** [comment]
@shenwawa just run `pod repo update` before `pod install`

**Comment by shenwawa** [comment]
Thanks, buddy. It's cool.
