### ISSUE TITLE
Xcode 6.3 and ObjectMapper 0.9

### ISSUE THREAD

**Issue by J-Sizzle** [Hearst-DD/ObjectMapper#110]
Hey has anyone seen this? I recently updated my xcode to 6.3.  So I updated my cartfile as well to the new github "Hearst-DD/ObjectMapper" ~> 0.9  But everytime I run carthage update I get this:

>*** Building scheme "ObjectMapper-iOS" in ObjectMapper.xcodeproj
>** BUILD FAILED **
>The following build commands failed:
>CompileSwift normal x86_64 .../Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Mapper.swift
>CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
>(2 failures)

**Comment by tristanhimmelman** [comment]
Hi @J-Sizzle, you should using version 0.10, if you are on Xcode 6.3. I will update the Read Me doc.

**Comment by J-Sizzle** [comment]
Yep that was the problem.  You da man :+1:
