### ISSUE TITLE
put the transform dir in 1 swift file

### ISSUE THREAD

**Issue by EvilClay** [Hearst-DD/ObjectMapper#111]
Hi,

first of all, great gob with this ObjectMapper!. Just a small request, it is not required for Swift to have a file for each class separately. So perhaps you could merge the whole Transformation directory into one swift file. The swift files contain mostly 1 class with 10 lines of code. I think its better to have one class with maybe 100 lines with all that stuff inhere, and it can reside win the core dir with other files...

**Comment by tristanhimmelman** [comment]
Hi @EvilClay,
I'm glad you like the library :). 

I'm not convinced that it is better practice to combine all the transforms into one file. As a project grows, maintaining separation of code helps keep things organized. Other than reducing the number of files in the project, I don't really see a benefit to doing this. Thanks for your input though.

Cheers,
Tristan
