### ISSUE TITLE
fail to import ObjectMapper from cocoapods

### ISSUE THREAD

**Issue by hirohisa** [Hearst-DD/ObjectMapper#113]
I tried to use ObjectMapper, then failed to import caused by `Use of undeclared type Mappable`.

This project
https://github.com/hirohisa/toys/tree/object_mapper/swift/samples/ObjectMapper

Podfile:
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

pod 'ObjectMapper', '~> 0.10'
```

please help me.

**Comment by hirohisa** [comment]
![aeeac7575d0fa28e4e21db2810ef699d](https://cloud.githubusercontent.com/assets/1519837/7347806/0f0e7fae-ed27-11e4-9678-f199e84a4473.png)

**Comment by tristanhimmelman** [comment]
Hi there,
The main problem here is that you have created a sample project with the exact same name as ObjectMapper. This is causing the compiler to be confused when you write `import ObjectMapper`.

You should start with a fresh project that has a different name like ObjectMapperSample or something.

Hope this helps.
Tristan

**Comment by hirohisa** [comment]
Thabks!
