### ISSUE TITLE
A little help with nested objects needed

### ISSUE THREAD

**Issue by pfitz** [Hearst-DD/ObjectMapper#114]
I need a little guidance with mapping nested objects. I managed to use ObjectMapper with built in types perfect. But how do I map nested custom objects?

Given something like this:

```swift
class A {
    let b: B
    let c: [C]
}
```
As I said I managed to map B and C alone. But how do I map it from inside A? Do I need to write a custom transform? Or do I need to make B and C conform to some protocol? I am guessing it is quite simple but I just can't get my head around it.

**Comment by tristanhimmelman** [comment]
Here is an example from the tests included in the framework. The key is that any nested objects also need to conform to the `Mappable` protocol. Also, by default ObjectMapper does not support immutable types (`let`) as member variables.

Hope this helps

```
class Plan: Mappable {
	var primaryTask: Task?
	var tasks: [Task]?
	
	required init?(_ map: Map) {
		mapping(map)
	}

	func mapping(map: Map) {
		tasks <- map["tasks"]
	}
}

class Task: Mappable {
	var taskId: Int?
	var percentage: Double?

	init() {}
	
	required init?(_ map: Map) {
		mapping(map)
	}

	func mapping(map: Map) {
		taskId <- map["taskId"]
		percentage <- map["percentage"]
	}
}
```

**Comment by pfitz** [comment]
Ah ok. Did not believed it to be THAT easy. With Mantle you had to say which class is should map to. It is working. Thanks!!!

**Comment by tristanhimmelman** [comment]
Glad to help :+1:
