### ISSUE TITLE
Trying to use TransformOf, to Map [lat, lon] Array to CLLocation

### ISSUE THREAD

**Issue by perforator85** [Hearst-DD/ObjectMapper#118]
Hello, 

thanks for this awesome library! I'm trying to make a small custom transformation.
**[lat, lon]** -> **CLLocation()**

I started with your sample code to map a **String** to an **Int**
I'm relatively new to Swift and I am unsure how to achieve my transformation.
Any advice would help me a lot.

Below is the code, that I wrote: (ERROR -> Expected an argument list of type '(fromJSON: JSONType? -> ObjectType?, toJSON: ObjectType? -> JSONType?)'

        let transform = TransformOf<[Double], String>(fromJSON: { (value: [Double]?) -> CLLocation? in
            if let coordList = value as? [Double]
                where coordList.count == 2 {
                    return CLLocation(latitude: coordList[1], longitude: coordList[0])
            }
            return nil
            }, toJSON: { (value: CLLocation?) -> [Double]? in
                if let location = value {
                    return [Double(location.coordinate.longitude), Double(location.coordinate.latitude)]
                }
                return nil
        })

Working sample code:

		let transform = TransformOf<Int, String>(fromJSON: { (value: String?) -> Int? in 
		    // transform value from String? to Int?
		    return value?.toInt()
		}, toJSON: { (value: Int?) -> String? in
		    // transform value from Int? to String?
		    if let value = value {
		        return String(value)
		    }
		    return nil
		})

Working custom Transformer Class:

		import CoreLocation
		
		public class SPLocationTransform: TransformType {
		    public typealias Object = CLLocation
		    public typealias JSON = [Double]
		
		    public init() {}
		
		    public func transformFromJSON(value: AnyObject?) -> CLLocation? {
		        if let coordList = value as? [Double]
		            where coordList.count == 2 {
		                return CLLocation(latitude: coordList[1], longitude: coordList[0])
		        }
		        return nil
		    }
		
		    public func transformToJSON(value: CLLocation?) -> [Double]? {
		        if let location = value {
		            return [Double(location.coordinate.longitude), Double(location.coordinate.latitude)]
		        }
		        return nil
		    }
		}

**Comment by tristanhimmelman** [comment]
Hi there,

I think the error is in the types you are setting when creating the TransformOf. I believe it should be:
`TransformOf<[Double], CLLocation>` instead of `TransformOf<[Double], String>`

So the whole transform would look like this
```
  let transform = TransformOf<[Double], CLLocation>(fromJSON: { (value: [Double]?) -> CLLocation? in
        if let coordList = value as? [Double]
            where coordList.count == 2 {
                return CLLocation(latitude: coordList[1], longitude: coordList[0])
        }
        return nil
        }, toJSON: { (value: CLLocation?) -> [Double]? in
            if let location = value {
                return [Double(location.coordinate.longitude), Double(location.coordinate.latitude)]
            }
            return nil
    })
```

**Comment by perforator85** [comment]
Thanks! … here is the final working snippet (at least compileable - I'll try it soon)

        let transform = TransformOf<CLLocation, [Double]>(fromJSON: { (value: [Double]?) -> CLLocation? in
            if let coordList = value
                where coordList.count == 2 {
                    return CLLocation(latitude: coordList[1], longitude: coordList[0])
            }
            return nil
            }, toJSON: { (value: CLLocation?) -> [Double]? in
                if let location = value {
                    return [Double(location.coordinate.longitude), Double(location.coordinate.latitude)]
                }
                return nil
        })

**Comment by dinaraja** [comment]
How do you make sure that coordList[1] is always **latitude** and coordList[0] is always **longitude**?
