### ISSUE TITLE
Empty dictionaries/arrays of custom types not reflected in JSON

### ISSUE THREAD

**Issue by Carpemeid** [Hearst-DD/ObjectMapper#119]
As advised on stackoverflow ->  (this is my first issue description on git)

I have a class that has as an array of a custom class something like this:

    class StyleSheet : Mappable
    {
         var images : [StyleSheetImage]?
    }

    class StyleSheetImage : Mappable
    {
        var pins : [Pin]?
    }

Now, if the images property has an empty array, it will not be reflected at all in the produced JSON. Unfortunately on the project I work the server needs to receive empty arrays to understand that the elements have been deleted, otherwise it does not modify anything.

I tried to drill down in the library, but got stuck.

Of course my issue appears approximately here:

    class func objectArray<N: Mappable>(field: Array<N>, key: String, inout dictionary: [String : AnyObject]) {
		let JSONObjects = Mapper().toJSONArray(field)

        if !JSONObjects.isEmpty {
            setValue(JSONObjects, forKey: key, dictionary: &dictionary)
        }
        else
        {
            //dictionary = [key : [""]]
        }
	    }

because the Mapper().toJSONArray(field) returns JSONObjects with 0 values and in this way the dictionary parameters is not assigned anything. I tried assigning manually a value to the dictionary variable, but that did not help at all (the naive commented line). I also tried modifying the "setValue" function, but also did something wrong and it does not map empty array of custom objects. I am relatively new with Swift and iOS in general so I was hoping you can bring some light.

Thank you.

**Comment by tobiasoleary** [comment]
The commented line is not an empty array. It's an array with an empty string.

**Comment by tobiasoleary** [comment]
You probably want something like this

dictionary[key] = []

**Comment by tristanhimmelman** [comment]
Hi there,
I think the simplest solution is to not use an optional value for you image array. So you class would look like this instead:
```
class StyleSheet : Mappable
{
     var images: [StyleSheetImage] = []
}
```

**Comment by tristanhimmelman** [comment]
I read this question and responded too quickly. Disregard my last message.

I believe @tobiasoleary is correct.

**Comment by Carpemeid** [comment]
It works fine with that corrected comment) thank you)
