### ISSUE TITLE
Cannot invoke '<=' with custom transformer

### ISSUE THREAD

**Issue by nmccann** [Hearst-DD/ObjectMapper#12]
Hi, I've been having an issue with custom transformers. Take the following model object:

```
class Example: MapperProtocol {
    var date: NSDate?
    
    required init(){}
    
    func map(mapper: Mapper) {
        date <= (mapper["birthday"], DateTransform<NSDate, Int>())
    }
}
```

If `DateTransform` is defined in a file within my project, I receive the following error: "Cannot invoke '<=' with an argument list of type '(@lvalue NSDate?, (@lvalue Mapper, DateTransform<NSDate, Int>))'"

If `DateTransform` is defined in the ObjectMapper project, I do not receive this error and the mapping works as expected.

Note: The `DateTransform` defined in my project was exactly the same as the built-in `DateTransform` and I deleted the built-in one to avoid conflicts.

**Comment by tristanhimmelman** [comment]
Great :+1: Thanks for the update
