### ISSUE TITLE
Can't get the sample work

### ISSUE THREAD

**Issue by jlouazel** [Hearst-DD/ObjectMapper#120]
Hi. I'm trying to get your sample works but actually I can't find what I'm doing wrong.

This line fails:
``let JSONString = Mapper().toJSONString(user, prettyPrint: true)``

I took your entire class to try to make it work but I'm getting this error:
``Cannot invoke 'toJSONString' with an argument list of type '(User?, prettyPrint: Bool)'``

Do you know this problem?

**Comment by tristanhimmelman** [comment]
I believe you are getting this error because you are passing in an optional User object into the `toJSONString` function. 

I suppose my sample could be updated to the following:
```swift
let user = Mapper<User>().map(JSONString)

if let user = user {
     let JSONString = Mapper().toJSONString(user, prettyPrint: true)
}
```

or you can force unwrap the user object 
```
let JSONString = Mapper().toJSONString(user!, prettyPrint: true)
```

Hope this helps

**Comment by jlouazel** [comment]
Thanks for your quick answer. Indeed my error was there, thanks for your time.
