### ISSUE TITLE
Dictionaries of Arrays?

### ISSUE THREAD

**Issue by bennichols** [Hearst-DD/ObjectMapper#121]
Hi, I love the library you've written. It works for just about all my use cases except I need to store dictionaries of arrays. Is that something that would be difficult to add the way this is architected?

**Comment by tristanhimmelman** [comment]
Hi there, happy you like the library :).

Yes I believe it would be possible to add support for Dictionaries with Arrays as values. Specifically what type of Dictionaries are you interested in? Dictionary <String, [T: Mappable]> or Dictionary <String, [AnyObject]>?

I will add this functionality to my to do list.

**Comment by bennichols** [comment]
I'm not sure what you're asking? I'm interested in [String: [N]].

**Comment by tristanhimmelman** [comment]
ahh github messed up my comment. it was supposed to say `Dictionary<String, [T:Mappable]>` or `Dictionary<String, [AnyObject]>`. 

That clears it up!

**Comment by tristanhimmelman** [comment]
Hey there, I've just released a new version with this functionality: 
https://github.com/Hearst-DD/ObjectMapper/releases/tag/0.12

Check it out and let me know if you have any issues.
