### ISSUE TITLE
Implicit mapping from underscore to camel case?

### ISSUE THREAD

**Issue by allaire** [Hearst-DD/ObjectMapper#122]
Is there a way to map auto. underscore key to camel case if nothing is set in the `mapping` method?

**Comment by tristanhimmelman** [comment]
No at the moment that functionality does not exist. You have to explicitly let ObjectMapper know how to map each variable.

**Comment by RishabhTayal** [comment]
Any update on this? Can we parse dictionary with uppercase and camel case keys for the same field?
