### ISSUE TITLE
Possible Enhancement: DateTransform could/should handle epoch time in milliseconds

### ISSUE THREAD

**Issue by mccrackend** [Hearst-DD/ObjectMapper#123]
I'm dealing with an API returning a date like so: 1432821600000

http://www.epochconverter.com/ handles this fine and converts it to the proper date of: Thu, 28 May 2015 14:00:00 GMT assuming that is is in milliseconds.

Wondering if DateTransform should be smart enough to deal with a date like this and divide by 1000 to give it a chance at being the correct date.

Thoughts?

**Comment by tobiasoleary** [comment]
This sounds like a perfect case for using a Custom transform
