### ISSUE TITLE
Code=3840 "The operation couldn’t be completed."

### ISSUE THREAD

**Issue by Bill-Niz** [Hearst-DD/ObjectMapper#126]
Hi,
Impossible to parse my Json string in -  parseJSONString(JSON: String) -> AnyObject? 

Error:

Error Domain=NSCocoaErrorDomain Code=3840 "The operation couldn’t be completed. (Cocoa error 3840.)" (Garbage at end.) UserInfo=0x7f8730567000 {NSDebugDescription=Garbage at end.}

**Comment by tobiasoleary** [comment]
That error means your string is not JSON it's a invalid format.

**Comment by SinghBabita** [comment]
i have pass the same string twice. first time it execute perfectly but in second time it show the error Error Domain=NSCocoaErrorDomain Code=3840 "The operation couldn’t be completed. (Cocoa error 3840.)" (Garbage at end.) UserInfo=0x7f8730567000 {NSDebugDescription=Garbage at end.}
