### ISSUE TITLE
Support mapping to/from Set

### ISSUE THREAD

**Issue by nmccann** [Hearst-DD/ObjectMapper#128]
Sometimes a set better represents the behaviour of some data. It doesn't seem like this is currently supported by ObjectMapper.

It's not exactly difficult to workaround this (I just use an Array in my model objects and convert to a Set when needed), but it would be nice if a workaround wasn't needed.

**Comment by tristanhimmelman** [comment]
I agree, I think this would be a good feature addition. 

I will add it when I have some free time. 

Thanks

**Comment by Busta117** [comment]
i already send a pull request with that 
https://github.com/Hearst-DD/ObjectMapper/pull/159

**Comment by tristanhimmelman** [comment]
Closing this issue as it will be supported when swift-2.0 is merged into master.

**Comment by nmccann** [comment]
Thanks @Busta117!
