### ISSUE TITLE
Help with dynamic mapping

### ISSUE THREAD

**Issue by jaischeema** [Hearst-DD/ObjectMapper#131]
Hi, I am looking for some help on how to get the following json string mapped into different kind of objects based on the `itemType` value.

The only way of doing this I can see is to map the items into `[String: AnyObject]` variable and then manually instantiate the class based on the `itemType`.  I was wondering if there is a straightforward/idiomatic way of doing it. 

```json
{
   "items": [
      {
         "itemType": "TypeA",
         "attr1": "Attribute 1",
         "attr2": "Attribute 2"
      },
      {
         "itemType": "TypeB",
         "attr3": "Attribute 3",
         "attr4": "Attribute 4"
      },
   ]
}
```
```swift
class TypeA: Mappable {
   var attr1: String?
   var attr2: String?

   required init?(_ map: Map) {
      super.init(map)
   }

   func mapping(map: Map) {
      attr1 <- map["attr1"]
      attr2 <- map["attr2"]
   }
}

class TypeB: Mappable {
   var attr3: String?
   var attr4: String?

   required init?(_ map: Map) {
      super.init(map)
   }

   func mapping(map: Map) {
      attr3 <- map["attr3"]
      attr4 <- map["attr4"]
   }
}
```
Thanks in advance for your help, much appreciated.

And <b>super work</b> with the library, it has made my life so much easier and the code so much cleaner.

**Comment by tristanhimmelman** [comment]
Hey there, I'm glad you like the library :).

Below is an example of how you could dynamically map based on a field returned in the JSON.

Hope this helps.

```
class Response: Mappable {
	var items: [AnyObject]?
	
	required init?(_ map: Map) {
		mapping(map)
	}
	
	func mapping(map: Map) {

		// map items to an array of json dictionaries
		var itemsJSON: Array<Dictionary<String, AnyObject>>?
		itemsJSON <- map["items"]
		
		if let itemsJSON = itemsJSON {
			items = []
			
			// loop through the array, checking the type and mapping it accordingly
			for item in itemsJSON {
				let type = item["type"] as? String
				if type == "type 1" {
					if let mappedItem = Mapper<TypeA>().map(item){
						items?.append(mappedItem)
					}
				} else if type == "type 2" {
					if let mappedItem = Mapper<TypeB>().map(item){
						items?.append(mappedItem)
					}
				}
			}
		}
	}
}
```

**Comment by jaischeema** [comment]
Thank you, that exactly what I was looking for :smile:

**Comment by Urkman** [comment]
Isn't there a way to optimize this?
So if we have the correct classname in "type".

Is there no way to get this line to work with the "Classname String"

let mappedItem = Mapper<"type">().map(item)

**Comment by cezheng** [comment]
You can, by doing this with reflection but that is the old objc way of doing the job and it relies on runtime information which is slow compared to static compile time information and not what apple is recommending at the moment. You can do it by either implementing an @objc class or have a look into the documentation of 'MirrorType'. If you dig into the latter you will see there will be a whole lot of unnecessary string manipulation at runtime

**Comment by muescha** [comment]
FYI: https://github.com/Hearst-DD/ObjectMapper#staticmappable-protocol would also to the job

**Comment by tristanhimmelman** [comment]
Thats right @muescha. My response above was before `StaticMappable` was even added to the project!
