### ISSUE TITLE
Problem with serializing empty list of objects to JSON String.

### ISSUE THREAD

**Issue by pawelpuam** [Hearst-DD/ObjectMapper#137]
Hi!
First of all I just want to say how much i like this library :) Reminds me of Google Gson.
But I have a problem with serialization of empty list of objects. Serializing empty list does not create it in json. Here's my snippet code.

var searchConditions: SearchConditionsDTO = SearchConditionsDTO()
searchConditions.documentClassKeyDTO = keyDTO
searchConditions.searchLimit = 20
searchConditions.conditions = [SearchConditionDTO]()
        
let jsonString = Mapper().toJSONString(searchConditions, prettyPrint: true)!
println(jsonString)

This is what i get:
{
  "searchLimit" : 20,
  "documentClassKeyDTO" : {
    "id" : 123123123123123,
    "kind" : "DocumentClass"
  }
}

This is what want to achieve:
{
  "searchLimit" : 20,
  "documentClassKeyDTO" : {
    "id" : 123123123123123,
    "kind" : "DocumentClass"
  },
  "conditions" : [ ]
}

Is there a way to do it?

Rest api i connect to accepts empty list, but not null value :/

**Comment by tristanhimmelman** [comment]
Hey there, 

Until today this wasn't possible. I have just added updated the library to support this. If you pull the latest from master you can access the changes.

Cheers!
