### ISSUE TITLE
"<-" operator is duplicate with SQLite.swift's "<-"

### ISSUE THREAD

**Issue by cooliceman** [Hearst-DD/ObjectMapper#138]
Both ObjectMapper and SQLite.swift defined "<-"operator,People who used both will get build error:"<-" is  not a known binary operator. It costed me two hours to find out the real problem reason. I solved the problem by replace "<-" in ObjectMapper with "<==". Can you do something to avoid this? people who use both ObjectMapper and SQLite.swift will thank you.

**Comment by xyyc** [comment]
i hit the same problem.

**Comment by wenxin3262** [comment]
I don't have SQLite, but still have this error, I am sure I didn't define this operator myself somewhere. Any  thoughts?

**Comment by cezheng** [comment]
The conflicting operator overload might be in one of the other Pods you use. Try checking other pods in your project

**Comment by wenxin3262** [comment]
Thanks you cezheng! Although I fixed it by just import ObjectMapper at top of swift class file. I don't know why, but it did the job...

**Comment by tristanhimmelman** [comment]
I don't intend on changing the custom operator at this time `<-`. Depending on which 3rd party libraries you are using there is always a risk that the operator could conflict. I would suggest making a fork of the library and changing the operator to something new as @cooliceman did.
