### ISSUE TITLE
Dynamic Nesting Attributes Support

### ISSUE THREAD

**Issue by cezheng** [Hearst-DD/ObjectMapper#139]
Hi there. I am currently migrating a project from Restkit to Realm + ObjectMapper.

Say if I have a rest api response like this
```
{
"adam": {
    "email": "adam@objectmapper.org",
    "phone_number": "0987654321"
    },
"smith": {
    "email": "smith@objectmapper.org",
    "phone_number": "1234567890"
    }
}
```

and I would like to map it to a collection of objects with this model

```
class Contact: Mappable {
	var name: String?
	var email: String?
	var phoneNumber: String?
}
```

Restkit can handle Dynamic Nesting Attributes like this
https://github.com/RestKit/RestKit/wiki/Object-mapping#handling-dynamic-nesting-attributes

I have not found a way to work around this in Object Mapper yet, but here is my work around.

I modified the Map class's contructor

```
public final class Map {
	//...
	private init(mappingType: MappingType, JSONDictionary: [String : AnyObject]) {
		self.mappingType = mappingType
		self.JSONDictionary = JSONDictionary
        self.currentValue = JSONDictionary // I added this line
	}
	//...
}
```
Then I defined my model like this

```
class ContactDict: Mappable {
	var dict: [String: Contact]?
	init() {}
	required init?(_ map: Map) {
		mapping(map)
		// assign key of contact to name here
		if let dict = dict {
			for (name, contact) in dict {
				contact.name = name
			}
		}
	}
	func mapping(map: Map) {
		// currently objectMapper does not support mapping this map without a subscript
		// the line I added in constructor enabled this
		dict <- map
	}
}
class Contact: Mappable {
	var name: String?
	var email: String?
	var phoneNumber: String?
	init() {}
	required init?(_ map: Map) {
		mapping(map)
	}
	func mapping(map: Map) {
		email <- map["email"]
		phoneNumber <- map["phone_number"]
	}
}
```

Do you have better ways to work around this? I've been thinking about adding this feature to ObjectMapper but I haven't yet come up with a elegant way to do it yet. This would be a awesome feature.

**Comment by tristanhimmelman** [comment]
Hey there,

This is an interesting idea/problem. Dynamic nested attributes would indeed be a nice addition to ObjectMapper but I can't think of a great solution at the moment (I will put some more thought into it though).

I do have a suggestion to make your above code simpler. Instead of modifying the map class you can do something like this following (using your Contact class):
```
var contactDict = Mapper<Contact>().mapDictionary(apiResponse)
if let contactDict = contactDict {
     for (name, contact) in dict {
           contact.name = name
      }
}
```

Hope this helps out
Tristan

**Comment by cezheng** [comment]
Thank you, I overlooked the mapDictionary method
