### ISSUE TITLE
Compilation failed in the iPhone 5 or less

### ISSUE THREAD

**Issue by jpallenk** [Hearst-DD/ObjectMapper#140]
Hi,

I want to use ObjectMapper in my project but i have a build failed when i compile it on iPhone 5 (but it compiles on iPhone 5S and higher).

Here are the issue logs:
Swift compiler error
Use of undeclared type 'Mapper'
Swift compiler error
Use of undeclared type 'MapperProtocol'

Regards,
João Paulo

![captura de tela 2015-06-22 as 17 44 43](https://cloud.githubusercontent.com/assets/11141745/8292540/9842d44a-1906-11e5-9960-a69ef66ce147.png)

**Comment by tristanhimmelman** [comment]
Hi there,

I am not able to reproduce the problem you are having. I just tested on a project using the iPhone 5 simulator and everything is fine. 

Are you using Cocoapods or Carthage to include ObjectMapper?

Also, do you have the latest version of ObjectMapper? `MapperProtocol` has been removed from the project for some time now.

Tristan

**Comment by jpallenk** [comment]
I'm using Cocoapods , but I think the version was even wrong .
I downloaded again and it worked.

thank you very much

João Paulo
