### ISSUE TITLE
init?(_ map: Map) is not good idea

### ISSUE THREAD

**Issue by baryon** [Hearst-DD/ObjectMapper#141]
I have a realm model object, I want add Mappable protocol for mapping.
BUT, the init?(_ map: Map) in my object, will become a exception.

ref: https://github.com/realm/realm-cocoa/issues/1849

Could you modify the protocol?

**Comment by robertjpayne** [comment]
yea I'll concur would be great if Mappable didn't require an initialiser for CoreData/Realm support.

**Comment by hwaxxer** [comment]
:+1:

**Comment by schickling** [comment]
+1

**Comment by mladen107** [comment]
+1

**Comment by alexbredy** [comment]
+1

**Comment by mladen107** [comment]
I forked branch and changed protocol Mappable. All tests are passing please check and give me your thoughts https://github.com/mladen107/ObjectMapper/commit/8ff25cfc87309215822639e2111239c8b2235a77

**Comment by tristanhimmelman** [comment]
By popular demand I have changed the Mappable protocol to the following:
```
public protocol Mappable {
	static func newInstance() -> Mappable
	mutating func mapping(map: Map)
}
```

Thanks @mladen107 for your fork :+1: , I used a similar approach but simplified a few things.

Let me know if anybody has issues with the new release https://github.com/Hearst-DD/ObjectMapper/releases/tag/0.14

**Comment by mladen107** [comment]
Well thank you very much for this great library, but still I would like to decide how to create newInstance based on JSON data or Map.
For example I want to implement some kind of cache layer that will reuse objects that represent the same entity (I think Realm does this already). 
Also, for example we can have {"fruits": ["type":"apple"...],["type":"lemon"...]} and then we should be able to decide to create different Swift type (Abstract Factory Method Pattern).

**Comment by tristanhimmelman** [comment]
@mladen107 interesting use case. I will consider adding that functionality. Thanks for your feedback

The reason I didn't include the map variable in the newInstance() function is because it creates addition boilerplate code that each Mappable model will need to include. I have been making a concerted effort to keep the protocol as simple as possible so I will take some time to think about this change. Also I'll wait to see if anybody else would like this kind of functionality as well.

**Comment by mladen107** [comment]
After checking the changes you made leaving, the only argument **(map: Map)** should be enough for my cases without any other modifications.

I agree about boilerplate. Anyways I can always fork for my usage :+1: .

**Comment by tristanhimmelman** [comment]
I have made another minor update to the protocol (including the map paramater to the newInstance function for validation purposes).

However, a strategy for supporting Realm using the old protocol was brought to my attention in #168, so I am considering reverting to the old protocol.
