### ISSUE TITLE
Why not let the standard types implements `Mappable`?

### ISSUE THREAD

**Issue by sugarwyc** [Hearst-DD/ObjectMapper#144]
like:
```swift
extension String: Mappable {...}
extension Int: Mappable {...}

let a = Mapper<Int>().map("123")
```

**Comment by tristanhimmelman** [comment]
Interesting idea. This could useful for many situations. 

I will consider adding this functionality

**Comment by nickygerritsen** [comment]
This would be really useful for me, as I have an API that can return "just a string" etc.

I could create a PR if that would help?

**Comment by nickygerritsen** [comment]
To add to this: I think it would also make sense to let `[Mappable]` conform to `Mappable`. I now have to add an extra function just to be able to map an array of `Mappable` objects.

I think for this, and also for letter `String`, etc. conform to `Mappable` we need to modify the `Map` structure, as it now always assumes a `[String: AnyObject]` structure, which is not the case for both of these ideas.

**Comment by kidsedu** [comment]
I'm just looking for the usage like `Mapper<String>`, and linked to this site from search engine. Anybody know how to implement it?

**Comment by hjhcn** [comment]
I'm just looking for the usage like Mapper<String>, and linked to this site from search engine. Anybody know how to implement it?

**Comment by hjhcn** [comment]
I'm just looking for the usage like `Mapper<String>`, and linked to this site from search engine. Anybody know how to implement it?

**Comment by hjhcn** [comment]
@tristanhimmelman have you added this functionality already? if so , how to use?  Thank you!

**Comment by tristanhimmelman** [comment]
@hjhcn sorry but I haven't added this feature yet. I don't really have time at the moment to add this either. I will open the ticket to keep it visible though.

**Comment by tristanhimmelman** [comment]
Closing this off.

I don't think this functionality adds that much value to this project. Standard types are easy enough to map.
