### ISSUE TITLE
Add operator for bidirectional mapping (<->)

### ISSUE THREAD

**Issue by damienrambout** [Hearst-DD/ObjectMapper#146]
It would be great to have several operators to supporter `FromJSON` mapping or `ToJSON` mapping or both at the same time.

- `<-` or `<=` for `FromJSON`
- `->` (not allowed) or `=>` for `ToJSON`
- `<->` or `<=>` for `FromJSON` and `ToJSON`

This way I could do something like this:

```swift
mutating public func mapping(map: ObjectMapper.Map) {
    id <- map["user_id"]
    phone <-> map["phone"]
    email <-> map["email"]
    firstName <-> map["firstname"]
    lastName <-> map["lastname"]
    countryCode <-> map["country_id"]
    languageCode <-> map["language"]
    pictureURL <- (map["picture_url"], URLTransform())
}
```
In this situations, I don't want to send the `user_id` and `picture_url` in my `POST` requests. 
The `=>` operator could be used to define another JSON key:
```
pictureURL => (map["pic_url"], URLTransform())
pictureURL <= (map["picture_url"], URLTransform())
```
This would import `pictureURL` using `picture_url` but would export it as `pic_url`.

I know that it would break the serialisation of the object into JSON to save it on disk, as properties won't be serialised. 

Let's just think about it...

**Comment by angelolloqui** [comment]
This would be a nice addition! +1

**Comment by tristanhimmelman** [comment]
I've thought about this and although it is a neat idea I think it's best to keep the number of custom operators to a minimum to avoid conflicts with other libraries.

You can achieve exactly what you are doing above by using the following code however:
```
func mapping(map: Map){
    if map.mappingType == .FromJSON {
        name <- map["username"]
    } else {
        name <- map["name"]
    }
}
```
