### ISSUE TITLE
Can't transform arrays to JSON string

### ISSUE THREAD

**Issue by RomuloVitoi** [Hearst-DD/ObjectMapper#147]
How am I supposed to transform an array to JSON String?
This doesn't work:

        var stringArray : [String] = [ "hello", "world" ]
        var jsonString : String = Mapper().toJSONString(stringArray, prettyPrint: false)

Error: Cannot invoke 'toJSONString' with an argument list of type '([String], prettyPrint: Bool)'

**Comment by tristanhimmelman** [comment]
At the moment ObjectMapper doesn't support creating JSON from Arrays of Basic types. 

I may add this functionality down the line as it would be a useful feature.

**Comment by wieseljonas** [comment]
Great Library! Any workaround for this atm?

**Comment by tristanhimmelman** [comment]
Thanks! Unfortunately this feature is still not supported.
