### ISSUE TITLE
Array of Array of Object not mapping 

### ISSUE THREAD

**Issue by Trevor-L** [Hearst-DD/ObjectMapper#152]
Does ObjectMapper support the following? In the test cases, there is a test for map["nested.nested.nested.objectArray"], however a top level objectArray doesn't seem to be working.

Response from web service:
```json
{
    "x": [
           [
            {
                "a": "1",
                "b": "2"
            },
            {
                "a": "3",
                "b": "4"
            }
           ],
           [
            {
                "a": "10",
                "b": "11"
            },
            {
                "a": "12",
                "b": "13"
            }
           ]
  ]
}
```
```swift
var obj = Mapper<Obj>().map(json)
// should produce an object accessible like:
var Foo = obj[0][1]
```
```swift
class Obj: Mappable {
  var x: [[Foo]] = []

  required init?(_ map: Map) {
        mapping(map)
    }

  func mapping(map: Map) {
        x <- map["x"]
  }
}

class Foo: Mappable {
  var a: String!
  var b: String!

  required init?(_ map: Map) {
    mapping(map)
  }
  func mapping(map: Map) {
    a <- map["a"]
    b <- map["b"]      
  }
}
```

**Comment by tomco** [comment]
Have a look at [my fork](https://github.com/tomco/ObjectMapper). It adds exactly what you're looking for to ObjectMapper. 

Haven't been able to fully test it, but I hope to find time do to it soon and create a pull request.

**Comment by Trevor-L** [comment]
@tomco Thanks for the heads up.  Your fork works.

**Comment by pignataa** [comment]
@tomco I got your fork but I had errors on the Mapper.swift file. Is there something else I need to add or is this maybe a Podfile issue?

**Comment by ninjazoete** [comment]
@tomco what is the status on this? :) I have exact same situation and wondering what to do

**Comment by tristanhimmelman** [comment]
I am working on adding this functionality to master based on @tomco's work. It should be in master soon

**Comment by tristanhimmelman** [comment]
I have now merged my work back into master #207 . Mapping arrays of arrays should now be functional if you get the latest.

I plan to tag a new release in the next few days.

**Comment by tomco** [comment]
cool! (sorry for not finding time to actually creating a pull request on my own)

**Comment by GRGBISHOW** [comment]
I got the latest one 1.3.0 not not wokring.

**Comment by hbzdkc** [comment]
{
  
  "action": 300000,
  
  "orderinfo": {
    
    "mp": [
      [
        31.20196,
        101.43682
      ]
    ],
 
    "mda": [
      "TT",
      "TT",
      "TT"
    ]
  },
  "title": "TT"
}

var mp:[[Float]]?
mp ->    Array of Array of Object not mapping ！
How to write ？-->     “var mp:[[Float]]?
