### ISSUE TITLE
Array of NSURL

### ISSUE THREAD

**Issue by ivangodfather** [Hearst-DD/ObjectMapper#157]
If i have an array of NSURL i have to make my custom transform? I can't use URLTransform() ?

**Comment by tristanhimmelman** [comment]
Yes that is correct, you will need a custom transform to make this work.

**Comment by alibasta** [comment]
Attached you can find my implementation of a custom transform:

`class URLListTransform: TransformType {
    typealias Object = Array<NSURL>
    typealias JSON = Array<AnyObject>
    
    init() {}
    
    func transformFromJSON(value: AnyObject?) -> Array<NSURL>? {
        if let URLStrings = value as? [String] {
            var listOfUrls = [NSURL]()
            for item in URLStrings {
                if let url = NSURL(string: item) {
                    listOfUrls.append(url)
                }
            }
            return listOfUrls
        }
        return nil
    }
    
    func transformToJSON(value: [NSURL]?) -> JSON? {
        if let urls = value {
            var urlStrings = [String]()
            for url in urls {
                urlStrings.append(url.absoluteString)
            }
            return urlStrings
        }

        return nil
    }
}`
