### ISSUE TITLE
Incorrect mapping Object-> Json when is an array of objects which implements the Mapping protocol

### ISSUE THREAD

**Issue by ivangodfather** [Hearst-DD/ObjectMapper#160]
I don't understand why if i have a transform of NSURL i have to make a custom transform of NSURL to send an array of NSURL, since when i map JSON->Object i get a correct mapping, but when i send the objects OBJECT-JSON seems the mapping is incorrect.
For example, i have an array of Address that i get from the server, i implemeted the protocol Mapping in the class Address, and everything is ok, i get 'N' addresses mapped, but when i send it back as an array of Address, the mapping is incorrect. What im missing?

**Comment by ivangodfather** [comment]
class Address: Equatable, Mappable {
    var id: Int?
    var address, addressName, phone, nonSelectableArea: String?
    var idDeliveryArea: Int?
    
    func mapping(map: Map) {
        id <= map["id"]
        address <= map["address"]
        addressName <= map["addressName"]
        phone <= map["phone"]
        nonSelectableArea <= map["nonSelectableArea"]
        idDeliveryArea <= map["idDeliveryArea"]
    }
    
    required init() { }
}

![screen shot 2015-07-23 at 14 33 38](https://cloud.githubusercontent.com/assets/1838117/8850379/e31032fc-3147-11e5-93b9-a77f28a835ad.png)

**Comment by ikesyo** [comment]
`Mapper.toJSON()` takes a single `N` as its parameter. You should use `to JSONArray()` instead.

**Comment by ivangodfather** [comment]
you mean like toJSONArray?
        let customer = Mapper().toJSONArray(CurrentCustomer.getCustomer().addresses)

**Comment by ivangodfather** [comment]
This is what i get in the server using toJSONArray:
[23-Jul-2015 15:26:52 Europe/Berlin] Array
(
    [customer] => Array
        (
            [0] => Array
                (
                    [nonSelectableArea] => Elda
                )

            [1] => Array
                (
                    [address] => c/ Juan Ricardo de Dios, Madrid
                )

            [2] => Array
                (
                    [idDeliveryArea] => 1
                )

            [3] => Array
                (
                    [id] => 1
                )

            [4] => Array
                (
                    [addressName] => Mi primo Richard
                )

            [5] => Array
                (
                    [phone] => 96543234
                )

            [6] => Array
                (
                    [nonSelectableArea] => Petrer
                )

            [7] => Array
                (
                    [address] => c/ Fernando Soria
                )

            [8] => Array
                (
                    [idDeliveryArea] => 2
                )

            [9] => Array
                (
                    [id] => 2
                )

            [10] => Array
                (
                    [addressName] => Hermano Juan
                )

            [11] => Array
                (
                    [phone] => 96542134
                )

        )

    [lang] => en
)

**Comment by ikesyo** [comment]
The type of `CurrentCustomer.getCustomer().addresses` isn't `[Address]`?

**Comment by ivangodfather** [comment]
Yes, they are [Address]
    var addresses: [Address] = []

**Comment by ikesyo** [comment]
The text you pasted above is a JSON dictionary and has additional values, so definitely it is not the original value returned from `toJSONArray(addresses)`. Could you provide more detailed context or the correct JSON representation in your Swift code what you did sent to the server?

**Comment by ivangodfather** [comment]
let address = Mapper().toJSONArray(CurrentCustomer.getCustomer().addresses)
        let params: [String: AnyObject] = ["lang": getLang(), "customer": address]
        request(.POST, PROFILE_URL, parameters: params, encoding: ParameterEncoding.URL).responseJSON(options: NSJSONReadingOptions.AllowFragments) { (request, response, json, error) -> Void in

**Comment by ivangodfather** [comment]
By the way im trying to sent a "Customer" object, whichs contains an array of Address [Address]. So i'll not use that method, but if i send  a full customer i get the same problem with the addresses inside the customer.

**Comment by ivangodfather** [comment]
If i set a breakpoint before sending de request, i get this:
(lldb) po params
["lang": en, "customer": (
        {
        address = "c/ Juan Ricardo de Dios, Madrid";
        addressName = "Mi primo Richard";
        id = 1;
        idDeliveryArea = 1;
        nonSelectableArea = Elda;
        phone = 96543234;
    },
        {
        address = "c/ Fernando Soria";
        addressName = "Hermano Juan";
        id = 2;
        idDeliveryArea = 2;
        nonSelectableArea = Petrer;
        phone = 96542134;
    }
)]

(lldb)

**Comment by ikesyo** [comment]
That looks correct to me.

**Comment by ivangodfather** [comment]
@ikesyo so the problem is how i'm seding the params with alamofire?

**Comment by ivangodfather** [comment]
I opened an issue in Alamofire github: https://github.com/Alamofire/Alamofire/issues/604

**Comment by ikesyo** [comment]
Or your server side? I'm sorry but I don't know why that does not work well anymore. :sweat: Anyway, it seems that there is no problem in the `toJSONArray()` implementation.

**Comment by ivangodfather** [comment]
So theres no need to do custom transforms for arrays of objects that conforms the mapping protocol? isnt? Cause yesterday someone told me ( https://github.com/Hearst-DD/ObjectMapper/issues/157 ) that for mapping an array of NSURL like (Address) i need to do a custom transform for handling the array.

**Comment by ikesyo** [comment]
If the type cotained in an array is a `Mappable`, yes.

**Comment by ikesyo** [comment]
FYI: that would be handled by [this](https://github.com/Hearst-DD/ObjectMapper/blob/0.6/ObjectMapper/Core/Operators.swift#L234-240).

**Comment by ivangodfather** [comment]
http://postimg.org/image/qsky93tlb/full/

**Comment by ikesyo** [comment]
What I said is about the type that conforms to `Mappable`, and `NSURL` isn't `Mappable`.

The functionality you want exists in its latest version, but does not in the version you are using currently (`<=` operator is a bit old.).

**Comment by ikesyo** [comment]
I think you should check the releases and the documentaion comments at first. :trollface:

**Comment by ivangodfather** [comment]
@ikesyo i dunno where the problem is, i updated the library, isolated the problem with dummy datta, and everything, if you can have a lookt at it i'll apreciate: 
http://stackoverflow.com/questions/31607189/problems-retrieving-json-from-php-server-using-alamofire
