### ISSUE TITLE
Map Enum composed - With different types

### ISSUE THREAD

**Issue by GuyKahlon** [Hearst-DD/ObjectMapper#162]
How can I map Enum composed - With different types.
 such as:

enum Status{
    case Failure(String)
    case Success
}

class ServerResponse: Mappable{
    let status: Status?

    required init?(_ map: Map) {
        mapping(map)
    }
    
    func mapping(map: Map) {
        status    <- map["status"]
    }
}

This code doesn't work (And doesn't  compile)

Thanks,
Guy

**Comment by mladen107** [comment]
Check documentation again protocol Mappable has been changed

````
public protocol Mappable {
    static func newInstance() -> Mappable
    mutating func mapping(map: Map)
}
````

**Comment by ikesyo** [comment]
That isn't related to the issue. ObjectMapper's enum support requires `RawRepresentable` enum, something like:

```swift
enum Status: Int {
    case Failure = 0
    case Success = 1
}

// or

enum Status: String {
    case Failure = "failure"
    case Success = "success"
}
```

If you'd like to have an enum which has associated values (that is not a `RawRepresentable` conformant enum), you should define your own custom transform for that enum type.
