### ISSUE TITLE
Is DateFormaterTransform meant to be subclassed only?

### ISSUE THREAD

**Issue by allaire** [Hearst-DD/ObjectMapper#164]
Is `DateFormaterTransform` meant to be subclassed only? Otherwise I struggle to see where I should initialize my date formatter. I see `CustomDateFormatTransform` subclass it and makes it easy to define a specific format.

If it's meant to only be subclassed, I suggest to add some kind of comments.

Thanks!

**Comment by tristanhimmelman** [comment]
It can be subclassed or used directly. But when I created it I did so to simplify two other transform classes that were duplicating functionality. 

I haven't personally used it directly but you could do something like this: 
```
let formatter = NSDateFormatter()
formatter.locale = NSLocale(localeIdentifier: "en_US_POSIX")
formatter.dateFormat = "some format string"

let transform = DateFormaterTransform(dateFormatter: formatter)

date <- (map["date"], transform)
```

**Comment by allaire** [comment]
@tristanhimmelman but where that formatter init would go so it's instantiated during the mapping?

**Comment by tristanhimmelman** [comment]
It can go directly in the mapping function
```
func mapping(map: Map){
    let formatter = NSDateFormatter()
    formatter.locale = NSLocale(localeIdentifier: "en_US_POSIX")
    formatter.dateFormat = "some format string"

    let transform = DateFormaterTransform(dateFormatter: formatter)

    date <- (map["date"], transform)
}

**Comment by allaire** [comment]
@tristanhimmelman Super, thanks for the explanation!

**Comment by tristanhimmelman** [comment]
no problem :+1:
