### ISSUE TITLE
Some thoughts about the Realm issue & recent protocol update

### ISSUE THREAD

**Issue by cezheng** [Hearst-DD/ObjectMapper#168]
This is a follow-up issue regarding https://github.com/Hearst-DD/ObjectMapper/issues/163 & https://github.com/Hearst-DD/ObjectMapper/issues/141.

I'm using Realm with ObjectMapper, too, yet I find the old protocol far better since I defined a base class that inherits Realm's Object class implementing Mappable, because for some of the Models I will need to do some extra initialization(some times before mapping & sometime after mapping) apart from mapping the data. But the mapping function is shared for both encoding & decoding which means I should not put them in this function.

For Realm compatibility, All I needed to do is to add a init(realm:schema:) that calls super.init(realm:schema:) & a init() that calls super.init(). And My base model class looks like this:
```
class Model: Object, Mappable {
  required init() {
    super.init()
  }
  
  override init(realm: RLMRealm, schema: RLMObjectSchema) {
    super.init(realm: realm, schema: schema)
  }
  
  required convenience init?(_ map: Map) {
    self.init()
    mapping(map)
    if autoExtraInit {
      doExtraInit()
    }
  }
  
  var autoExtraInit: Bool {
    return true
  }
  
  func mapping(map: Map) {
  }
  
  func doExtraInit() {
  }
}
```

Yet with the new protocol, I can no longer doExtraInit in the init?(_ map: Map), I have to find a workaround. I ended up adding a doMapping(map: Map) function to actually deals with the data mapping, and the mapping function has to settle with an if-condition which only calls doExtraInit() when mappingType is .FromJSON, and overriding the doMapping method rather than method mapping method in all subclasses
It looks like this.
```
protocol RealmMappable: Mappable {
  func doMapping(map: Map)
  func doExtraInit()
  var autoExtraInit: Bool {get}
}

extension RealmMappable where Self: Object {
  static func newInstance() -> Mappable {
    return self.init()
  }
  
  func mapping(map: Map) {
    doMapping(map)
    if map.mappingType == .FromJSON {
      if autoExtraInit {
        doExtraInit()
      }
    }
  }
  
  var autoExtraInit: Bool {
    return true
  }
}

class Model: Object, RealmMappable {
  func doMapping(map: Map) {
    
  }
  
  func doExtraInit() {
    
  }
}
```

Althought I managed to get both versions work with my code, I definitely think the previous one is better. And thats why I don't understand why there is a popular demand to alter the protocol in such way. If you have better workaround than mine, I'll appreciate it if you could share it. And I hope my use case could provide some inspiration on improving ObjectMapper.

Thank you:)

**Comment by nrbrook** [comment]
I agree, intuitively I think people expect variables to be ready in init but with the new protocol format they are not ready until after `mapping()`. I think extra documentation would be useful and a transition guide when changes like this are made is essential.

**Comment by nrbrook** [comment]
And what happened to the validation of the object? I thought ObjectMapper should return a nil object if the mapping cannot map an element to an implicitly unwrapped optional?

**Comment by tristanhimmelman** [comment]
Thanks for the feedback @cezheng. I wasn't aware of your solution for supporting Realm with the old protocol as I haven't used realm myself for iOS development. I will consider reverting to the old protocol based on what you have said. This will have to wait 2-3 weeks however as I am going away for some time. In the mean time, feel free to use a previous version of ObjectMapper as very little has changed other than the removal of init? in the protocol.

@nrbrook, I will be merging a PR shortly that includes the map variable in the `newInstance` function to allow for validation prior to mapping.

**Comment by tristanhimmelman** [comment]
Just a quick update: I have reverted the protocol in the swift-2.0 branch to `init?(_ map: Map)` instead of `newInstance`. Thanks for your input guys.
