### ISSUE TITLE
Mapping a json string fails

### ISSUE THREAD

**Issue by msfeldstein** [Hearst-DD/ObjectMapper#169]
```
        let jsonPath = NSBundle.mainBundle().pathForResource("user", ofType: "json") as String!
        let error : NSError?
        let json : NSString? = NSString(contentsOfFile: jsonPath, encoding: NSUTF8StringEncoding, error: nil)
        println(json)
        return Mapper<User>().map(json)
```

If i have code that tries to map a json string it fails.  When it calls .map(json) it goes through the 

`public func map(JSON: AnyObject?) -> N? `
instead of the 
`public func map(JSONString: NSString) -> N?`

If i change the signature of the second method to be JSONString: NSString! it works ok, but as I'm new to swift I'm not an optionals expert.  Can someone tell me if this is a bug in Object mapper or in my calling code?

**Comment by cezheng** [comment]
This is basic swift syntax. Your json variable has type 'NSString?', and it only matches the function parameter 'AnyObject?', the JSONString parameter has type 'NSString' which is not an optional so you will need to unwrap it

**Comment by msfeldstein** [comment]
Hmm i guess it does work, i thought i had tried that.  Sorry for bothering you guys but thanks for confirming.
