### ISSUE TITLE
Parse json object with unknown keys

### ISSUE THREAD

**Issue by dboris** [Hearst-DD/ObjectMapper#17]
Hi,
Suppose you have json like this:

{
    "someUUID": {"name": "Joe", "age": 20},
    "otherUUID": {"name": "Tom", "age": 25},
    ...
}

The UUID keys are not known at compile time, so cannot be hardcoded. How can this be parsed and mapped with ObjectMapper?

**Comment by oniikal3** [comment]
@tristanhimmelman  Should I do in `func mapping(map: Map)` ?
