### ISSUE TITLE
Xcode 7 beta 5 incompatibility (swift2)

### ISSUE THREAD

**Issue by vadim-fueled** [Hearst-DD/ObjectMapper#172]
.../Core/Mapper.swift:76:15: error: 'dropFirst' is unavailable: Use the dropFirst() method instead.
.../Core/ToJSON.swift:12:33: error: 'split(_:maxSplit:allowEmptySlices:isSeparator:)' is unavailable: Use the split() method instead.
.../Core/ToJSON.swift:31:14: error: 'dropFirst' is unavailable: Use the dropFirst() method instead.

**Comment by ikesyo** [comment]
I've already submitted a pull request #170.

**Comment by vadim-fueled** [comment]
@ikesyo cool, but anybody merging it?

**Comment by tristanhimmelman** [comment]
I just merged it.

**Comment by vadim-fueled** [comment]
Thanks!
