### ISSUE TITLE
Cannot inherit Mappable protocol

### ISSUE THREAD

**Issue by SashaKrstev** [Hearst-DD/ObjectMapper#174]
Not sure what the problem is, but I tried inheriting the `Mappable` protocol and implement them in a concrete class.

But whenever I try to create a `Mapper` object I get 'Segmentation Fault: 11' ( the code does not compile )
```swift
protocol DummyProtocol: Mappable {}
var mapper = Mapper<DummyProtocol>()
```
Reults in a Segmentation Fault

However
```swift
class DummyClass: DummyProtocol {}
var mapper = Mapper<DummyClass>()
```
Compiles with no problems

Am I restricted to using concrete classes instead of protocols?

**Comment by cezheng** [comment]
I guess so. Think about what kinda object would a Mapper<Protocol> produce when it maps a object, you don't even have a mapping rule.

However in Swift 2.0 which allows you to define default implementation for a protocol, it might be possible to use a protocol in your case. I haven't tried it yet, but I will when I get my hands on my mac soon.

**Comment by cezheng** [comment]
I guess so. Think about what kinda object is this Mapper<Protocol> supposed to produce, you can't instantiate a protocol that has no mapping rules.

**Comment by SashaKrstev** [comment]
The ultimate goal I was trying to achieve is to work with objects that conform to a given protocol + Mappable, without knowing their actual class.
Working with a class that conforms to that protocol does solve the problem, but I'm forcing clients to subclass rather than just conform.

**Comment by cezheng** [comment]
If you already have a bunch of instantiated DummyProtocol objects, and would like to do something related to json encode, I guess you can use a generic function
```
func doSomethingRelatedToToJSON<T: DummyProtocol>(obj: T) {
    let mapper = Mapper<T>()
    //...
}
```

But if you want the other way around, i.e. doing JSON decode, mapping a JSON string/dictionary to a object that confirms to DummyProtocol, that is not possible cuz you don't know the mapping rules.

**Comment by SashaKrstev** [comment]
Right, so I guess its working as intended. Close the issue if this is the case.
