### ISSUE TITLE
Build issue on Xcode 7 beta 5

### ISSUE THREAD

**Issue by vigyanhoon** [Hearst-DD/ObjectMapper#176]
Hi I am having problem with building ObjectMapper. Attached is the pic of issues.

I tried with 
pod 'ObjectMapper', '~> 0.14' 
as well as with 
pod 'ObjectMapper', '~> 0.15'

Can you please let me know what's wrong? I am using swift-2 of Alamofire branch

![objectmapperissue](https://cloud.githubusercontent.com/assets/8503526/9250949/2e19a15a-41ee-11e5-8a03-febe38db6ad1.png)

**Comment by ikesyo** [comment]
Swift 2 support is still under development in `swift-2.0` branch, so you should use:

```ruby
pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git', :branch => 'swift-2.0'
```

**Comment by cfraz89** [comment]
These errors still occur for me with swift-2.0 branch.

**Comment by cezheng** [comment]
Would you please paste the error messages after you switched to swift-2.0 branch?

**Comment by cfraz89** [comment]
/Users/crusher/Downloads/moonrock-ios/Pods/ObjectMapper/ObjectMapper/Core/Mapper.swift:76:15: error: 'dropFirst' is unavailable: Use the dropFirst() method instead.
                        let tail = dropFirst(keyPathComponents)
                                   ^~~~~~~~~
Swift.dropFirst:1:80: note: 'dropFirst' has been explicitly marked unavailable here
@available(*, unavailable, message="Use the dropFirst() method instead.") func dropFirst<Seq : CollectionType>(s: Seq) -> Seq.SubSequence


/Users/crusher/Downloads/moonrock-ios/Pods/ObjectMapper/ObjectMapper/Core/ToJSON.swift:12:33: error: 'split(_:maxSplit:allowEmptySlices:isSeparator:)' is unavailable: Use the split() method instead.
        let keyComponents = ArraySlice(split(key.characters) { $0 == "." })
                                       ^~~~~
Swift.split:1:76: note: 'split(_:maxSplit:allowEmptySlices:isSeparator:)' has been explicitly marked unavailable here
@available(*, unavailable, message="Use the split() method instead.") func split<S : CollectionType, R : BooleanType>(elements: S, maxSplit: Int = default, allowEmptySlices: Bool = default, @noescape isSeparator: (S.Generator.Element) -> R) -> [S.SubSequence]
                                                                           ^
/Users/crusher/Downloads/moonrock-ios/Pods/ObjectMapper/ObjectMapper/Core/ToJSON.swift:31:14: error: 'dropFirst' is unavailable: Use the dropFirst() method instead.
                let tail = dropFirst(components)
                           ^~~~~~~~~
Swift.dropFirst:1:80: note: 'dropFirst' has been explicitly marked unavailable here
@available(*, unavailable, message="Use the dropFirst() method instead.") func dropFirst<Seq : CollectionType>(s: Seq) -> Seq.SubSequence

**Comment by cfraz89** [comment]
Btw I noticed that thsi doesnt happen building the objectmapper project itself from git. These errors occur after importing it with cocoapods.

**Comment by cezheng** [comment]
@cfraz89 These errors were fixed in https://github.com/Hearst-DD/ObjectMapper/pull/170, so I guess your branch is not up to date. Try running pod update

**Comment by cfraz89** [comment]
Ah mb mb
