### ISSUE TITLE
Optionals mapping configuration (a setting that allows optionals to map to 'null' when creating JSON)

### ISSUE THREAD

**Issue by tishin** [Hearst-DD/ObjectMapper#177]
Is there a way to map 'nil' values of object optional properties to 'null' values in JSON?

**Comment by tristanhimmelman** [comment]
At the moment there is no way to do this

**Comment by mirzadelic** [comment]
+1
Really need this..

**Comment by Tramvai** [comment]
Is there any solid "solution" or workaround to this request?

**Comment by cwalo** [comment]
+1
Still trying to find a way around this.

**Comment by jpaas** [comment]
I've also been struggling to figure this out. Ideally I'd like to see the JSONDictionary use the type [String: Any?] instead of [String: AnyObject].

**Comment by cnsilvan** [comment]
+1

**Comment by KevM** [comment]
We ran into this and worked around it for an array of optionals per a suggestion in #263. I added a generic version. This should be adoptable for non array mappings.

**Comment by Koranda** [comment]
+1

**Comment by mohitagrawal** [comment]
+1

**Comment by mirzadelic** [comment]
Any news for `NULL` values?

**Comment by tristanhimmelman** [comment]
@mirzadelic unfortunately I am short on time so I haven't had any time to work on ObjectMapper apart from supporting all the Xcode betas

**Comment by txaiwieser** [comment]
Just commenting here to endorse the feature! Currently im using the method described in this issue #263

**Comment by mortenbekditlevsen** [comment]
We have a working solution for this. It is an optional boolean parameter for the Mapper initializer.
The parameter is passed on to the Map instances and the value is checked in all the 
class func optionalXXX() -methods in ToJSON.swift.

Currently we have called the parameter 'mapNilToNull' (defaulting to existing behaviour of course).
Can anyone suggest a better name? Then we can make a pull request for the change.

**Comment by adozenlines** [comment]
But shouldn't the server be smart enough to know that apply a null the incoming field isn't in the payload?

**Comment by tristanhimmelman** [comment]
After a long delay, we finally have this functionality. See release 2.2.2. `Mapper` now has a variable `shouldIncludeNilValues` which if set to true will include null values when generating JSON.

**Comment by txaiwieser** [comment]
Awesome! Thanks! 👍
