### ISSUE TITLE
Auto-Mapping properties with same name

### ISSUE THREAD

**Issue by sddhhanover** [Hearst-DD/ObjectMapper#179]
Is it possible to auto-map properties dynamically? I have written the code needed to fetch the property names dynamically, but how do I use that information with the `<-` notation required by `mapping`?    
    
    public func mapping(map: Map) {
        var count : UInt32 = 0
        let classToInspect = Food.self
        let properties : UnsafeMutablePointer <objc_property_t> = class_copyPropertyList(classToInspect, &count)
        var propertyNames : [String] = []
        let intCount = Int(count)
        for var i = 0; i < intCount; i++ {
            let property : objc_property_t = properties[i]
            let propertyName = NSString(UTF8String: property_getName(property))!
            propertyNames.append(propertyName as String)
        }
        free(properties)
        println(propertyNames) //prints ["createdAt", "isActive"]
        
        //What to do to replace this?
        createdDate    <- map["createdDate"]
        isActive       <- map["isActive"]
    }

**Comment by cezheng** [comment]
Auto property name matching requires reflection which I guess is not recommended in swift. ObjectMapper is a strongly typed mapper. If you're trying do this you'd better use a objc framework with swift compatibility
