### ISSUE TITLE
Cannot invoke 'map' with an argument list of type '([String : AnyObject])'

### ISSUE THREAD

**Issue by vova-matukh** [Hearst-DD/ObjectMapper#182]
if let data = json["data.user"] as? [String : AnyObject]{
                                        let user = Mapper<User>.map(data)
                                } 
what wrong in this line? I can`t build my app

**Comment by cezheng** [comment]
There are 2 mistakes in you code.
1. Mapper is a class, and map() is not a class method. So you need to create a Mapper instance
2. Mapper is a Generic class. Specify the Object type(that conforms to Mappable protocol) you would like to map to, like this:
```
let user = Mapper<User>().map(data)
```
The README of the repo includes examples like this, so refer to the README before you create any issues

**Comment by vova-matukh** [comment]
Ty
