### ISSUE TITLE
Does ObjectMapper support Generics ?

### ISSUE THREAD

**Issue by MrPainter** [Hearst-DD/ObjectMapper#183]
Hello! 
Tried to map generic class. All properties mapped successfully except of generic properties.

Code below is not being mapped properly:
```swift
public class GenericResponse<T> : Mappable{
    var status: Int?
    var response: T?
    var error:ErrorResponse?
    
    public static func newInstance(map: Map) -> Mappable? {
        return GenericResponse<T>()
    }
    
    public func mapping(map: Map) {
        status <- map["status"]
        response <- map["response"]
        error <- map["error"]
    }
}
```
But if we specifies T class explicitly it will be mapped with no problems.

Is there any way to map generics ?

Thanks

**Comment by cezheng** [comment]
Because you are mapping "response" to response, T has to confirm to mappable.
```
public class GenericResponse<T: Mappable> : Mappable{
```
will do the job
