### ISSUE TITLE
Swift 2.0 Xcode 7 beta 5

### ISSUE THREAD

**Issue by vigyanhoon** [Hearst-DD/ObjectMapper#184]
Hi,

Can you please tell me whats wrong in this code?

![screen shot 2015-08-24 at 8 39 14 am](https://cloud.githubusercontent.com/assets/8503526/9432173/e0585df2-4a3b-11e5-9b02-b5736c1e0b8d.png)

**Comment by tobiasoleary** [comment]
You need to implement the Mappable protocol, there needs to be an init method that takes a map.

**Comment by fresswolf** [comment]
Your newInstance method shouldn't return an Optional and shouldn't take any parameters:

    class func newInstance() -> Mappable {
        return User()
    }

**Comment by tristanhimmelman** [comment]
@fresswolf is correct. The swift-2.0 branch is a bit out of date. I will update it today so that it reflects the updated protocol in master.
