### ISSUE TITLE
NSDate crash

### ISSUE THREAD

**Issue by Urkman** [Hearst-DD/ObjectMapper#187]
Hi,

I have an Object with a date field:
var date:NSDate?

Mapper:
date                    <- (map["date"], CustomDateFormatTransform(formatString: "yyyy-MM-dd HH:mm:ss"))

Everything works fine, when I load the data from JSON.
But, when I set the date to a new NSDate like this:
object,date = NSDate()

I get a Crash in "DateFormaterTransform" in this line:
return dateFormatter.stringFromDate(date)

Any idea how to fix this?

**Comment by tristanhimmelman** [comment]
I'm not sure what is happening here... have you resolved the problem?

If not, can you please post a full example so we can better understand what is happening.
