### ISSUE TITLE
Shouldn't mapArray() return [N]? instead of [N]

### ISSUE THREAD

**Issue by jschmid** [Hearst-DD/ObjectMapper#188]
(I am referring to the swift 2 branch. I did not check the master branch)

Currently the mapArray() function returns an array, no matter if the deserialization worked or not. ([See the code](https://github.com/Hearst-DD/ObjectMapper/blob/swift-2.0/ObjectMapper/Core/Mapper.swift#L177-L191))

I was creating a simple deserialization module for Alamofire and wanted to return an error if deserialization failed. However, deserializing an array never fails. 

I feel that instead of returning an empty array, it should return nil. 

What do you think about that?

**Comment by tristanhimmelman** [comment]
Sorry for the slow response to this issue. I am currently working on a branch that changes the return types for all mapping functions to optionals.

Thanks for your feedback.
