### ISSUE TITLE
Carthage fail to build Xcode 7 beta 6

### ISSUE THREAD

**Issue by brianhei** [Hearst-DD/ObjectMapper#190]
The project cannot build in Xcode 7 beta 6
![screen shot 2015-09-07 at 5 26 05 pm](https://cloud.githubusercontent.com/assets/13816317/9713669/8bb00c64-5585-11e5-8f78-1f80dcc070ff.png)

**Comment by cezheng** [comment]
xcode 7 is in beta so the swift 2 version is still in the`swift-2.0` branch.
