### ISSUE TITLE
Is there a way to test the newInstance method

### ISSUE THREAD

**Issue by elpic** [Hearst-DD/ObjectMapper#191]
I'm not able to test newInstance method because I'm not able to create a Map instance since the constructor is private, could you provide a way to create a map to allow newInstance method testing?

**Comment by tristanhimmelman** [comment]
Hey there, 
I've made the Map init public. This is in the swift-2.0 branch which will be merged into master soon.

Note: the Mappable protocol has been reverted to what it was before, so the newInstance equivalent function is now init?
```
public protocol Mappable {
	init?(_ map: Map)
	mutating func mapping(map: Map)
}
```
