### ISSUE TITLE
Map key containing dots

### ISSUE THREAD

**Issue by gooner22** [Hearst-DD/ObjectMapper#192]
Hi,

First of all - *thx for a great Mapper library!*

I've faced problem with mapping from JSON to object, when my key is a complex string: *"com.companyname.system.property"*

Currently, the line below makes it clear - we should avoid *"."* in our dictionary keys:
``` swift
currentValue = valueFor(ArraySlice(key.componentsSeparatedByString(".")), dictionary: JSONDictionary)
```

1. Unfortunately, we couldn't change server responses sometimes.
2. Replacing all JSON key dots to smth. else is also not a good approach.

However, I think there should be a way to get value by fully qualified key from *JSONDictionary*.
This is definitely a feature request.
What do you think on that?

**Comment by tristanhimmelman** [comment]
Hey @gooner22, you bring up a good point :+1: . I went ahead and added the feature. It is currently on the swift-2.0 branch which will be merged into master quite soon.

You can now specify on a per mapping basis whether key nesting is enabled:
```swift
identifier <- map["non.nested.identifier", nested: false]
```

You can see an example in the NestedKeysTests.swift file.

**Comment by gooner22** [comment]
@tristanhimmelman that's really great!

However, I can't find it in your latest commit(only readme update):
https://github.com/Hearst-DD/ObjectMapper/commit/c810f62d9cd9cde75aa214fb403752019629ad4b

**Comment by tristanhimmelman** [comment]
Oops, I forgot to push the code! You should be good to go now.

**Comment by gooner22** [comment]
@tristanhimmelman works like a charm.
cheers!
