### ISSUE TITLE
Trying to map, but class does not conform the protocol 'Mappable'

### ISSUE THREAD

**Issue by bit0001** [Hearst-DD/ObjectMapper#193]
I would like to map a JSON that I am receiving, but I am getting a message saying that:
Type 'City' does not conform to protocol 'Mappable'.

This is my class definition:

public protocol Mappable {
    static func newInstance(map: Map) -> Mappable?
    mutating func mapping(map: Map)
}

class City: Mappable {
    var state: String?
    var name: String?
    var id: String?
    
    class func newInstance(map: Map) -> Mappable? {
        return City()
    }
    
    func mapping(map: Map) {
        state   <- map["state"]
        name    <- map["name"]
        id      <- map["id"]
    }
}

and I trying to map using this line:

let city = Mapper<City>().map(data)

However, I am getting the error message I have mentioned.

**Comment by tristanhimmelman** [comment]
To map data to an object of type City, you must do so as follows:
```
let city = Mapper<City>().map(data)
```
