### ISSUE TITLE
Trying to map, but class does not conform the protocol 'Mappable'

### ISSUE THREAD

**Issue by bit0001** [Hearst-DD/ObjectMapper#194]
I would like to map a JSON that I am receiving, but I am getting a message saying that:
Type 'City' does not conform to protocol 'Mappable'.

This is my class definition:

public protocol Mappable {
    static func newInstance(map: Map) -> Mappable?
    mutating func mapping(map: Map)
}

class City: Mappable {
    var state: String?
    var name: String?
    var id: String?
    
    class func newInstance(map: Map) -> Mappable? {
        return City()
    }
    
    func mapping(map: Map) {
        state   <- map["state"]
        name    <- map["name"]
        id      <- map["id"]
    }
}

and I trying to map using this line:

let city = Mapper< City >().map(data)

However, I am getting the error message I have mentioned.

**Comment by bit0001** [comment]
Sorry it seems that <City> is considered as a comment by GitHub, so although it was written, it didn't appear.

**Comment by tristanhimmelman** [comment]
```
class City: Mappable {
	var state: String?
	var name: String?
	var id: String?
	
	class func newInstance(map: Map) -> Mappable? {
        return City()
    }
	
	func mapping(map: Map) {
		state   <- map["state"]
		name    <- map["name"]
		id      <- map["id"]
	}
}
```
The above class definition works when I test it. Mapping is done with the following code:

```
let city = Mapper<City>().map(JSON)
```

Are you including the Mappable protocol code within your class? If so, you should not. All you need to do is import ObjectMapper at the top of your class
```
import ObjectMapper
```

**Comment by bit0001** [comment]
Thanks it worked. I was including the Mappable protocol at the beginning of the file. Once again thank you so much.

**Comment by Shajeel-Afzal** [comment]
@tristanhimmelman I still see this problem. Following is my code: 

import Foundation
import ObjectMapper

```
class Thumb: Mappable {
    var thumbnail_480_url : String?
	var thumbnail_720_url : String?
	var thumbnail_url : String?
    
    class func newInstance(map: Map) -> Mappable? {
        return Thumb()
    }
    
    func mapping(map: Map) {
        thumbnail_url <- map["thumbnail_url"]
        thumbnail_480_url <- map["thumbnail_480_url"]
        thumbnail_720_url <- map["thumbnail_720_url"]
    }
}
```
