### ISSUE TITLE
Mappable definition in swift 2.0 is totally different as master branch for e.g.

### ISSUE THREAD

**Issue by alexliubj** [Hearst-DD/ObjectMapper#195]
init?(_ map: Map)
	mutating func mapping(map: Map)

**Comment by AFcgi** [comment]
Why remove the "Merge pull request #161 from Hearst-DD/remove-init-from-mappable" in swift 2.0 branch?

Mappable-Protocoll in
Swift 1.2:
* static func newInstance(map: Map) -> Mappable?
* mutating func mapping(map: Map)

Swift 2.0:
* init?(_ map: Map)
* mutating func mapping(map: Map)

**Comment by tristanhimmelman** [comment]
I apologize for multiple changes to the protocol, I understand that it is frustrating to have to update your models. The protocol should stay consistent moving forward.

I originally made the change to the protocol to make ObjectMapper compatible with Realm (see #141) . However, it turns out that the change was not necessary for Realm compatibility (see #168).

I evaluated both versions of the protocol and decided that the original protocol was better. Using `init?(_ map: Map)` follows typical platform conventions and thus is clearer and more developer friendly. Furthermore, using `init?` means we can remove the need for a `static` function in the protocol which could not be subclassed unless the `static` keyword was swapped with `class` (see #186).

**Comment by edias** [comment]
Any chance you guys add implicit mapping? It would reduce a lot of extra work mapping large objects and it also would simplify the code.

**Comment by damienrambout** [comment]
@tristanhimmelman How is it possible to create a swift type based on a json value inside the json payload?

Let me clarify. Let's say we receive a json array from an API, this array is composed of "Media" objects that can be a movie, a series or an episode. The type will be defined thanks to a `type` value set to `movie` / `series` / `episode`. 
With the static function version of `Mappable`, it was possible to make a type `Media` mappable and check the `type` value at runtime to return a `Movie` / `Series` / `Episode` based on it.

```swift
extension Media: Mappable {
    static func newInstance(map: Map) -> Media {
        // Check `type` and return `Movie` or `Series` or `Episode`.
    }
}

struct Movie: Media { ... }
struct Series: Media { ... }
struct Episode: Media { ... }
```

With the `init?(map:)` version, I don't see a way to achieve something like that. I will have to stick to a `Media` type and its real type will be based on an enum `type` property.

**Comment by tristanhimmelman** [comment]
@damienrambout, I have done something similar to what you are trying to do. Below is code that should handle your situation. It should go within the mapping function of whatever object contains your array of media.

Side note: As far as I know, using your previous implementation with newInstance, only the Media specific mappings would be made (ie the variables within the Movie struct that are not within Media, would not get parsed). I may be wrong about this, but I don't think ObjectMapper can do this...

```
// map raw json data to mediaJSON variable (array of JSON objects)
var mediaJSON: Array<Dictionary<String, AnyObject>>?
mediaJSON <- map["media"]

var media = Array<Media>()

// loop through mediaJSON and map each item based on the 'type' key within the JSON
if let mediaJSON = mediaJSON {
	for JSON in mediaJSON {
		let type = JSON["type"] as? String
		if let type = type {
			var mediaItem: Media?
			
			switch type {
			case "Movie":
				mediaItem = Mapper<Movie>().map(JSON)
				break
			case "Series":
				mediaItem = Mapper<Series>().map(JSON)
				break
			case "Episode":
				mediaItem = Mapper<Episode>().map(JSON)
				break
			default:
				mediaItem = nil
			}
			if let mediaItem = mediaItem {
				media?.append(mediaItem)
			}
		}
	}
}
```

**Comment by tristanhimmelman** [comment]
@edias what do you mean by implicit mapping? Do you mean that mappings are automatically generated based on the member variables within a class?

**Comment by edias** [comment]
@tristanhimmelman, exactly. Otherwise all we are doing is copying and pasting properties from a dictionary. Moreover it's absolutely non sense to configure manually large objects where properties don't change anything from its original source. It's very redundant and verbose. It would be really beneficial to have something more similar to a real serialisation.

**Comment by tristanhimmelman** [comment]
@edias, as ObjectMapper is currently designed, this is not possible. ObjectMapper uses static compile time information to map JSON to objects. What you are requesting would require analyzing objects at runtime using reflection which is comparatively very slow (and not very well supported in Swift). So although it would be more developer friendly to not need to define mappings, it would slow down your app performance significantly.

**Comment by andrebraga** [comment]
Below are some code snippets from the project I'm working on that should "inspire" the reasons I believe init? is not going to make it: class clusters (as mentioned above, for message types) and fetching existing objects from a persistent store (in my case, Core Data) by using an unique key. I am pretty much sure init? can't be coerced into returning anything other than nil, which makes it necessary to use newInstance, but open for suggestions :)

```
extension Message: Cluster, ModelMappable {
	class func modelKeyPathForType() -> String {
		return "type"
	}

	class func clusterFromType(type: String) -> AnyClass {
		switch type {
		case "text":
			return TextMessage.self

		case "image":
			return ImageMessage.self

		case "audio":
			return AudioMessage.self

		case "video":
			return AudioMessage.self

		case "location":
			return LocationMessage.self

		case "invitation":
			return LocationMessage.self

		default:
			fatalError("Message type not implemented!")
		}
	}

	public func mapping(map: Map) {
		iD <- (map["id"], UInt64Transform)
		date <- (map["created_at"], timestampTransform)
		text <- map["data.message"]

		if let mmm = self as? MultimediaMessage {
			mmm.attachmentURL <- (map["attachment_url"], stringToURLTransform)
			mmm.attachmentMIMEType <- (map["attachment_url"], extensionToMIMETransform)
		}

		if let lm = self as? LocationMessage {
			lm.location <- map["location"]
		}

		if let im = self as? InvitationMessage {
			im.reason <- (map["reason"], reasonTransform)
		}
	}
}
```

Below is a the newInstance method that's added to BaseObject (which is the class my Core Data entities inherit from) via an extension:

```
public class func newInstance(aMap: Map) -> Mappable? {
	let keys = uniqueKeys()
	var values = [AnyObject]()

	for kp in uniqueModelKeyPaths() {
		if let value: AnyObject = aMap[kp].value() as AnyObject? {
			values.append(value)
		}
		else {
			values.append(NSNull())
		}
	}

	var mappable: BaseObject? = nil

	if let unique = unique(keys, values: values) {
		mappable = unique
	}
	else {
		let moc = ModelMapper.privateMoc!

		var FinalClass = self

		if let cls = self as? Cluster.Type {
			let modelKeyPath = cls.modelKeyPathForType()
			FinalClass = cls.clusterFromType(aMap[modelKeyPath].value()!) as! BaseObject.Type
		}

		mappable = FinalClass.init(entity: FinalClass.entity(moc), insertIntoManagedObjectContext: moc)
	}

	return mappable as? Mappable
}
```

unique works as follows:

```
public class func unique(keyPaths: [String], values: [AnyObject]) -> Self? {
	let format = [String](count: min(keyPaths.count, values.count), repeatedValue: "%K = %@").joinWithSeparator(" && ")

	let argArray = zip(keyPaths, values).flatMap { (pair) -> [AnyObject] in
		return [pair.0, pair.1]
	}

	let predicate = NSPredicate(format: format, argumentArray: argArray)

	let uniquePredicateFormat = predicate.predicateFormat
	let klass: AnyClass = (self as Any.Type) as! AnyClass
	let stringFromClass = NSStringFromClass(klass)

	let cacheKey = String(format: "%@ %@", stringFromClass, uniquePredicateFormat)

	var instance: BaseObject? = ModelMapper.objectCache.objectForKey(cacheKey) as? BaseObject

	if instance == nil {
		let request = fetchRequest()
		request.predicate = predicate
		request.fetchLimit = 1

		let moc = ModelMapper.privateMoc!

		do {
			let results = try moc.executeFetchRequest(request)

			if results.count > 0 {
				instance = unsafeBitCast(results.first!, BaseObject.self)
				ModelMapper.objectCache.setObject(instance!, forKey: cacheKey)
			}
		}
		catch let error as NSError {
			print(error)
		}
	}

	if let instance = instance {
		return unsafeBitCast(instance, self)
	}
	else {
		return nil
	}
}
```

By the way, this is what the unadorned BaseObject looks like:

```
import Foundation
import CoreData

public class BaseObject: NSManagedObject {
	dynamic public class func uniqueKeys() -> [String] {
		return ["iD"]
	}

	dynamic public class func uniqueModelKeyPaths() -> [String] {
		return ["id"]
	}

	class func entityName() -> String {
		preconditionFailure("MUST OVERRIDE!")
	}

	required override public init(entity: NSEntityDescription, insertIntoManagedObjectContext context: NSManagedObjectContext?) {
		super.init(entity: entity, insertIntoManagedObjectContext: context)
	}

	public class func entity(managedObjectContext: NSManagedObjectContext!) -> NSEntityDescription! {
		return NSEntityDescription.entityForName(self.entityName(), inManagedObjectContext: managedObjectContext);
	}

	public class func fetchRequest() -> NSFetchRequest {
		// Core Data + Swift bug workaround
		let _entityName = entityName() as NSString
		return NSFetchRequest(entityName: _entityName as String)
	}

	public convenience init(managedObjectContext: NSManagedObjectContext) {
		let entity = self.dynamicType.entity(managedObjectContext)
		self.init(entity: entity, insertIntoManagedObjectContext: managedObjectContext)
	}
}
```

And the protocols:

```
public protocol UniquelyKeyed {
	static func uniqueKeys() -> [String]
	static func uniqueModelKeyPaths() -> [String]
}

public protocol ModelMappable: Mappable, UniquelyKeyed {}

@objc protocol Cluster {
	static func clusterFromType(type: String) -> AnyClass
	static func modelKeyPathForType() -> String
}

```

**Comment by mladen107** [comment]
I agree that init? doesn't put a lot of freedom during the construction of objects. For our project. I'll recreate fork that uses newInstance. Based on JSON sometimes I have to create subtype, and sometimes I need to use existing object from cache. I don't see easy way to achieve this with init.

**Comment by tristanhimmelman** [comment]
@mladen107 @damienrambout I added Class cluster support in a branch as an experimental feature #211. Feedback appreciated
