### ISSUE TITLE
How to map from Alamofire JSON response AnyObject?

### ISSUE THREAD

**Issue by SSA111** [Hearst-DD/ObjectMapper#20]
As the title says. How do I map from Alamofire JSON response AnyObject?

 Alamofire.request(.GET, URL + "Timetable").responseJSON { (_, _, JSON, _) in
           let timeTable = Mapper().map(JSON, toType: Timetable.self)
        }
JSON is AnyObject? but the map function does not accept that. How can I proceed?

**Comment by helllth** [comment]
Thank you :+1:
