### ISSUE TITLE
Cannot map parameters started with . (dot)

### ISSUE THREAD

**Issue by aleufms** [Hearst-DD/ObjectMapper#205]
A json: 
{
        "access_token": "abcdefgh",
        "token_type": "bearer",
        "expires_in": "1800",
        ".issued": "9/14/2015 10:21:56 PM +00:00",
        ".expires": "9/14/2015 10:51:56 PM +00:00"
}

cannot be mapped with:
       issuedDate <- (map[".issued"], LongDateTransform())
       expiresDate <- (map[".expires"], LongDateTransform())

**Comment by tristanhimmelman** [comment]
By default, when there is a . in a key, ObjectMapper assumes the key is a nested key: https://github.com/Hearst-DD/ObjectMapper#easy-mapping-of-nested-objects

However, I recently added the ability to turn off nesting. You can do so with the following code:
```
func mapping(map: Map){
    issuedDate <- (map[".issued", nested: false], LongDateTransform())
} 
```
