### ISSUE TITLE
Add tvOS support

### ISSUE THREAD

**Issue by RyanCodes** [Hearst-DD/ObjectMapper#208]
Would be great!

**Comment by tristanhimmelman** [comment]
A tvOS branch has been created: https://github.com/Hearst-DD/ObjectMapper/tree/tvOS

**Comment by HadiYaac** [comment]
Hi @tristanhimmelman, I couldn't find the tvOS branch! Is supporting tvOS still available?

**Comment by DrJapan** [comment]
Agreed! Would love to see something for tvOS. :)
