### ISSUE TITLE
Map dict/array to existing object

### ISSUE THREAD

**Issue by vani2** [Hearst-DD/ObjectMapper#21]
It'll be convenient to map inside init(dict:) for instance.

**Comment by tristanhimmelman** [comment]
The following function already exists to map a JSON string onto an existing object
```
public func map<N: MapperProtocol>(string JSON: String, toObject object: N) -> N! 
```

Is this what you were looking for?

**Comment by vani2** [comment]
@tristanhimmelman that's workaround. I suppose it'll very convenient to call initializers for `MapperProtocol` inherited objects instead of create instance and then call map func.
