### ISSUE TITLE
Drop `inout` flag to support Realm usage?

### ISSUE THREAD

**Issue by hyouuu** [Hearst-DD/ObjectMapper#213]
Since the "<-" operator is not actually writing, is it possible to drop the 'inout' flag so a Realm write is not required? I'm asking because for Realm objects with primaryKeys, any writes to the primaryKey property is disallowed, but we are just trying to read its property to generate the JSON file properly.

**Comment by andrebraga** [comment]
Where did you get the idea that <- doesn't write? It certainly does when you're reading from JSON.

**Comment by hyouuu** [comment]
Ah sorry I got the idea from the explanation on realm integration. In that case I guess it has to be dealt with from realm's side?

**Comment by tristanhimmelman** [comment]
I don't think Realm will change this requirement. I think your best bet is to add some logic prior to mapping the primary key. Something like this maybe:

```swift
func mapping(map: Map){

    if primaryKey == nil {
        primaryKey <- map["primaryKey"]
    }
}
```

**Comment by hyouuu** [comment]
The thing is that I want to read the primary key if it's not nil. Currently
what I have to do is to make a copy of the object and do mapping on that,
which is a performance waste although insignificant. Is there a way to
arbitrarily return a value for a mapping so that the primary key field is
not touched but I can still return its value?

**Comment by tristanhimmelman** [comment]
You can map the primary key value to a local variable if you need to inspect it. Or you could map it to another member variable that is not set as the primaryKey
```
func mapping(map: Map){
	var key: String?
	test <- map["primaryKey"]
}

**Comment by hyouuu** [comment]
Good idea - I'll just go with this :)

**Comment by wieseljonas** [comment]
I did it like this:

    dynamic var uniqueID = ""
    dynamic var id = ""
    
        override static func primaryKey() -> String? {
        return "uniqueID"
    }
    func mapping(map: Map) {
        if uniqueID == "" {
            uniqueID <- map["_id.id"]
        }
        id              <- map["_id.id"]
    }

**Comment by marksbren** [comment]
I now have to move away from ObjectMapper because of this issue. I want to be able to map to and from objects without Realm triggering an error
