### ISSUE TITLE
Map object members' key

### ISSUE THREAD

**Issue by emrahu** [Hearst-DD/ObjectMapper#215]
This is my example JSON object. totals object has member objects with a date defined as object key. I need the date key as defined in totals object for later use. What's the way to map object members' key?

    {
      customer_id: 555,
      totals: {
        2015-09-01: {
            sales: "50.00"
            orders: 3
        },
        2015-09-02: {
            sales: "12.75"
            orders: 1
        }
      }
    }

This is how I currently map, and it fails.

    class ReportMapper:Mappable{
        var customerID:Int?
        var totals:[TotalMapper]?

        func mapping(map: Map){
             customerID <- map["customer_id"]
             totals <- map["totals"]
        }
    }

    struct TotalMapper: Mappable{
         var date:String?
         var sales:String?
         var orders: Int?
        required init?(_ map: Map) {
            mapping(map)
        }
    
        func mapping(map: Map) {
           // date <- map["???"]   This date property should be the object key as in the JSON example "2015-09-01" or "2015-09-02"
            sales <- map["sales"]
            orders <- map["orders"]
    }

**Comment by tristanhimmelman** [comment]
You cannot get the date into the TotalMapper object automatically but you can map the data into a dictionary of TotalMapper objects where the keys are the dates.

I think something like this should work
```swift
class ReportMapper:Mappable{
    var customerID:Int?
    var totals:[String:TotalMapper]?

    func mapping(map: Map){
         customerID <- map["customer_id"]
         totals <- map["totals"]
    }
}
```
