### ISSUE TITLE
ObjectMapper seems like not support generic type?

### ISSUE THREAD

**Issue by bjzhou** [Hearst-DD/ObjectMapper#220]
I have a struct like

```
struct Result<T> {
    var code = 0
    var msg = ""
    var data: T?
}
```

How can it work?

**Comment by tristanhimmelman** [comment]
Your struct should look something like the following. If you want to map generic types, you need to ensure that the generic type conforms to `Mappable` as well.

```swift
struct Result<T: Mappable>: Mappable {
    var code = 0
    var msg = ""
    var data: T?

    required init?(_ map: Map){

    }

    mutating func mapping(map: Map) {
        code <- map["code"]
        msg <- map["msg"]
        data  <- map["data"]
    }
}
```

**Comment by bjzhou** [comment]
@tristanhimmelman Somtimes the generic type conforms to `Mappable`, like `String` or `Array`.

**Comment by tristanhimmelman** [comment]
ObjectMapper cannot handle a generic type that is sometimes Mappable and sometimes not. So you will have to structure your code differently to make things work in this case
