### ISSUE TITLE
Fail if json-string contains unmappable properties

### ISSUE THREAD

**Issue by Siamaster** [Hearst-DD/ObjectMapper#223]
Hi, 
I didn't know where it's most appropriate to ask a question.

Is it possible to have ObjectMapper fail if the json-string contains properties that the class does not?

Say my mapping function looks like this: 
    
mutating func mapping(map: Map) {
        a <- map["a"]
        b <- map["b"]
        c <- map["c"]
    }

and the json-string looks like this {"b":5,"x":14} 

How can I force a failure?

**Comment by tristanhimmelman** [comment]
At the moment this functionality does not exist.

**Comment by Siamaster** [comment]
Implement it bro

**Comment by wrutkowski** [comment]
@Siamaster FTW? Implement yourself and make a pull request. @tristanhimmelman is doing great job here (and thank you for that), but it isn't his duty to do it.

**Comment by Siamaster** [comment]
It was a joke. Thank you @tristanhimmelman for your efforts. 

@wrutkowski  I believe you mean "WTF" not "FTW". FTW stands for for the win, which doesn't make any sense here. 

Happy Friday.

**Comment by wrutkowski** [comment]
@Siamaster you are right. I meant WTF. There are a lot of people requesting for new functionalities instead of suggesting or helping.

Happy Friday too :)

**Comment by tristanhimmelman** [comment]
Happy Friday fellas! Thanks for the appreciation :+1:
