### ISSUE TITLE
EXEC_BAD_ACCESS in failable init when a key does not exist

### ISSUE THREAD

**Issue by fwielstra** [Hearst-DD/ObjectMapper#224]
I was evaluating ObjectMapper to see if we can use it instead of 'vanilla' JSON parsing, but ran into a crash when checking if it gives a readable error if it's missing a required field. This issue occurs in my case when implementing Mappable on a struct with immutable members, as shown in "Mapping Immutable Properties" in the readme. The issue occurs in version 0.17 and 0.16, in both a unit test environment (like the demo code) and running the app (in debug mode). It happens both when I change the key used in map[], or a key in the source json file. Done in Swift 2, XCode 7, under iOS 9.

Demo code (can probably be converted to a storyboard, but this is how I reproduced it) https://gist.github.com/fwielstra/dd02aaac645ac7445653

![pastedgraphic-2](https://cloud.githubusercontent.com/assets/394435/10099821/960b7e58-638d-11e5-9639-dfbe1507575a.png)

What I expected to happen was the '!map.isValid' branch being called; a bonus would be if ObjectMapper said "I did not find this required field in the response object".

**Comment by fwielstra** [comment]
Actually, nested objects and nested arrays of mappables don't seem to work properly when using the failable init method, similar errors. Is that one tested properly? I don't see it being used in the tests much. I'd rather not make large changes to my data model (i.e. make my fields mutable and explicitly unwrapped) to make this library work.

**Comment by tristanhimmelman** [comment]
@fwielstra support for immutable properties is a relatively new feature and definitely has not been tested as throughly the standard mapping.
