### ISSUE TITLE
 Pod spec lint fetches ObjectMapper (0.9)

### ISSUE THREAD

**Issue by diogoguimaraes** [Hearst-DD/ObjectMapper#225]
When executing  pod spec lint it fetches ObjectMapper (0.9) when having dependency to ObjectMapper 0.16.

I think it's related with https://github.com/Hearst-DD/ObjectMapper/blob/master/ObjectMapper/ObjectMapper.podspec pointing to tag 0.9.

Do we need to have two different podspecs?

**Comment by tristanhimmelman** [comment]
Good catch. No we definitely do not need two podspecs. I will remove this one. Thanks

**Comment by diogoguimaraes** [comment]
Could you please make a release with this change? 
It will prevent the double checkout being performed by `pod spec lint` and it will solve the errors when building a project that uses ObjectMapper using Xcode7 because v0.9 doesn't work with Xcode7.
Thanks!

**Comment by tristanhimmelman** [comment]
I just cut a new release, 0.18. Cheers!
