### ISSUE TITLE
tvOS branch with Carthage does not build scheme

### ISSUE THREAD

**Issue by mabril** [Hearst-DD/ObjectMapper#227]
When using Carthage to build the tvOS branch:

git "https://github.com/Hearst-DD/ObjectMapper" "tvOS"

carthage update
*** Fetching ObjectMapper
*** Checking out ObjectMapper at "61c91a8c71f32fc8e3adc4df296d798507bcc1e1"
*** xcodebuild output can be found in /var/folders/19/xzwjb7553p74ghltct8tb6gw0000gq/T/carthage-xcodebuild.AqkOOG.log
*** Building scheme "ObjectMapper-Mac" in ObjectMapper.xcworkspace
*** Building scheme "ObjectMapper-watchOS" in ObjectMapper.xcworkspace
*** Building scheme "ObjectMapper-iOS" in ObjectMapper.xcworkspace

The problem is that tvOS is not being built.
Maybe there is something you need to configure to get it working with Carthage? Is there a tvOS scheme?

Thanks

**Comment by mabril** [comment]
![captura de pantalla 2015-10-01 a las 12 13 47](https://cloud.githubusercontent.com/assets/1352739/10218283/f0e44dda-6835-11e5-9273-7a450d7ff55d.png)
It seems that it needs the build scheme...

**Comment by tristanhimmelman** [comment]
The tvOS branch should now build correctly. Make sure xcode 7.1 is selected on the command line and you are using the latest version of Carthage.
