### ISSUE TITLE
Chooses wrong method on Optional String

### ISSUE THREAD

**Issue by najiji** [Hearst-DD/ObjectMapper#228]
# Chooses wrong function footprint

## Situation
When the function `map()` is called with a `String?` as argument the method `public func map(JSON: AnyObject?) -> N? ` is called, since it is the only function with an optional value as paramter and thus gets called.

## Problem
This function assumes the data to be `[String : AnyObject]`. If the data is not in this form it just silently returns `nil`. It is unclear why the library can handle optionals of this type and not strings.

## Proposed solution
Add a method that takes optional Strings as arguments and unwraps if not nil, or remove the possibility to map optionals of `[String : AnyObject]`.
An error handling system to better being able to detect issues like this.

Correct me if I'm wrong!

**Comment by tristanhimmelman** [comment]
Hi @najiji, thanks for you feedback. You bring up a good point. Many people seem to get confused by this. I have a branch where I has added this which I hope to merge into master soon.
