### ISSUE TITLE
How to Maintain Strong reference to an object.

### ISSUE THREAD

**Issue by rajavikram** [Hearst-DD/ObjectMapper#230]
Hi ,
I am using ObjectMapper along with AlamofireObjectMapper to parse JSON responses into objects.
My requirement is to retain the values of certain variable in the object while other variables are assigned values obtained from the server call.
Ex:

    class Person: NSObject , Mappable {
       var firstName:String! 
       var lastName:String! 
       var email:String! 
       var phoneNo:String!
       var password: String! 
       var authToken:String!

       required init?(_ map: Map){

        }

      public func mapping(map: Map) {
        firstName                <- map["firstName"]
        lastName                <- map["lastName"]
        email                      <- map["email"]
        phoneNo                 <- map["phoneNo"]
        authToken            <- map["X-AUTH-TOKEN"]
       }
    }
    
Here when user performs login , i save his email and password into the Person object .
And the server call returns his other details which are with the help of AlamofireObjectMapper converted to Person object, but this clears his password and email properties.(set to nil)

So how do i save the new incoming details without loosing the existing details(overwriting if necessary)

NOTE: This is just an example, my class has many more properties which get populated in different calls which happen in different flows of the app.

Previously, i was just returning a strong reference to the object to achieve this as follows:

    public class func newInstance() -> Mappable {
        return SharedConstants.sharedInstance.user
    }

**Comment by tristanhimmelman** [comment]
Hi @rajavikram, using AlamofireObjectMapper, I don't believe there is any way to do this yet (although it sounds like a good feature which I will consider adding).

If you use ObjectMapper separately to map your JSON, you can use the following function to map JSON to an existing object:
```
public func map(JSON: AnyObject?, toObject object: N) -> N
```
