### ISSUE TITLE
How to apply custom transform during mapping of immutable properties?

### ISSUE THREAD

**Issue by aphex3k** [Hearst-DD/ObjectMapper#232]
The Readme explains how to apply custom transform and how to map immutable properties. Is it possible to achieve both? I'd like to apply a transform to an immutable property.

**Comment by tristanhimmelman** [comment]
Immutable mappings in ObjectMapper are an experimental feature so unfortunately they do not support all data types or transformations.

**Comment by aphex3k** [comment]
Thanks for clarification
