### ISSUE TITLE
How to map a required property that uses a transform

### ISSUE THREAD

**Issue by rokob** [Hearst-DD/ObjectMapper#233]
```swift
struct Thing: Mappable {
    private(set) var id: String
    private(set) var date: NSDate
    private(set) var title: String?
    
    struct K {
        static let id = "id"
        static let date = "date"
        static let title = "title"
    }
    
    init(id: String, date: NSDate, title: String?) {
        self.id = id
        self.date = date
        self.title = title
    }

    init?(_ map: Map) {
        id = map[K.id].valueOrFail()
        let d: Double = map[K.date].valueOrFail()
        if let jsonDate = DateTransform().transformFromJSON(d) {
            date = jsonDate
        } else {
            date = NSDate()
        }
        title = map[K.title].value()
        guard map.isValid else { return nil }
    }
    
    mutating func mapping(map: Map) {
        id <- map[K.id]
        date <- (map[K.date], DateTransform())
        title <- map[K.title]
    }
}
```

So I need a value for `date` in `init?` because the property is non-optional. But, the above is the nicest way I could find to get `valueOrFail` to work with the `DateTransform`. Using `valueOrFail` in the normal way causes NSDate to be the inferred type which is not how the value is stored in json (obviously).

The above hack uses a type annotation to force the inference to work correctly. As there is no way to manipulate the failedCount directly, this is the best I could come up with.

I think it might be nice to have `value(transform: TransformType)` and `valueOrFail(transform: TransformType)`. I can put up a PR if this seems reasonable.

**Comment by tristanhimmelman** [comment]
As I mentioned here #232, immutable mappings in ObjectMapper are an experimental feature so unfortunately they do not support all data types or transformations.
