### ISSUE TITLE
changing build configuration name error-ed out

### ISSUE THREAD

**Issue by wyefei** [Hearst-DD/ObjectMapper#235]
After I changed the build configuration name from `Debug` to `Development`, then running the project will produce `No such module 'ObjectMapper'` error while all the rest libraries I am using are fine. 
![error](http://take.ms/n5xpg)

and it will work as soon as I change the name back.

**Comment by tristanhimmelman** [comment]
Seems like this is an issue with Xcode. I tested it with a couple frameworks and they both had the problem you mentioned above. See the following for a potential solution:
http://stackoverflow.com/questions/26073088/swift-frameworks-do-not-work-with-build-configurations-named-other-than-debug
