### ISSUE TITLE
Can not convert back with map()?

### ISSUE THREAD

**Issue by alexliubj** [Hearst-DD/ObjectMapper#236]
I use this to convert to string:
 ` let messages = MessagesBaseModel()
                                messages.messageArray = self.chatList
                                let JSONString = Mapper().toJSONString(messages, prettyPrint: true)`

and use this to convert back:

`let model = Mapper<MessagesBaseModel>().map(JSONString)`

return nil though...

my data models:
`
class MessagesBaseModel : Mappable
{
    var messageArray: [MessagesModel]?
    
    init() {}
    
    required init?(_ map: Map){
        
    }
    
    func mapping(map: Map) {
        messageArray <- map["messageArray"]
    }
}

class MessagesModel:  Mappable{
    var messagesList: [ChatRecModel]?
    var from: String?

    init() {}
    
    required init?(_ map: Map){
        
    }
    
    func mapping(map: Map) {
        messagesList <- map["messages"]
        from <- map["from"]
    }
}`

**Comment by alexliubj** [comment]
public func map(JSON: AnyObject?) -> N? {
		if let JSON = JSON as? [String : AnyObject] {
			return map(JSON)
		}

		return nil
	}

here return nil

**Comment by tristanhimmelman** [comment]
The reason this is happening is that the function toJSONString returns String?. You need unwrap the string before mapping it to an object using 
```
public func map(JSONString: String) -> N? 
```

**Comment by alexliubj** [comment]
Good thanks,
