### ISSUE TITLE
Using toJSON to return dictionary of specified properties only?

### ISSUE THREAD

**Issue by u10int** [Hearst-DD/ObjectMapper#238]
Thanks for the awesome mapping library!

Is there an easy way to return a dictionary of certain properties using a method similar to `toJSON()` for a Mappable object? For instance, I only want to send a payload of properties that have changed to an api instead of the entire object's data, most of which had never changed. So sending everything via `toJSON()` isn't always ideal.

Or maybe there's an easy way to return the mapped key from a Mappable instance property that the API expects?

**Comment by tristanhimmelman** [comment]
Hi @u10int, unfortunately, at the moment there is no way to do this.
