### ISSUE TITLE
toJSONString() issue with Realm Objects with Nested Lists

### ISSUE THREAD

**Issue by wieseljonas** [Hearst-DD/ObjectMapper#240]
Hi I'm struggling to get the toJSONString() working with realm objects. I get nil when I try to turn it into a string.

    var jsonStringPipeline:String?
            realm.write({ () -> Void in
               jsonPipeline = Mapper().toJSONString(pipelines, prettyPrint: false)}
            })
     return jsonStringPipeline

I really can't figure out where the error is. Thanks in advance

    class Pipeline : Object, Mappable {
    dynamic var id = ""
    dynamic var uniqueID = ""
    dynamic var name = ""
    var stages = List<Stage>()
    
    override static func primaryKey() -> String? {
        return "uniqueID"
    }
    required convenience init?(_ map: Map){
        self.init()
    }
    // Mappable
    func mapping(map: Map) {
        if uniqueID == "" {
            uniqueID <- map["_id.id"]
        }
        id              <- map["_id.id"]
        name            <- map["name"]
        stages          <- (map["stages"], ArrayTransform<Stage>())
        }
    }

    class Stage : Object, Mappable {
    dynamic var id = ""
    dynamic var uniqueID = ""
    dynamic var name = ""

    override static func primaryKey() -> String? {
        return "uniqueID"
    }
    
    required convenience init?(_ map: Map){
        self.init()
    }
    // Mappable
    func mapping(map: Map) {
        if uniqueID == "" {
            uniqueID <- map["_id.id"]
        }
        id              <- map["_id.id"]
        name            <- map["name"]
        }
    }

And this is my ArrayTransform

    class ArrayTransform<T:RealmSwift.Object where T:Mappable> : TransformType {
    typealias Object = List<T>
    typealias JSON = Array<AnyObject>
    
    func transformFromJSON(value: AnyObject?) -> List<T>? {
        let result = List<T>()
        if let tempArr = value as! Array<AnyObject>? {
            for entry in tempArr {
                let mapper = Mapper<T>()
                let model : T = mapper.map(entry)!
                result.append(model)
            }
        }
        return result
    }
    
    func transformToJSON(value: List<T>?) -> Array<AnyObject>? {
        if (value?.count > 0)
        {
            var result = Array<T>()
            for entry in value! {
                result.append(entry)
            }
            return result
        }
        return nil
    }

**Comment by tristanhimmelman** [comment]
Hey @wieseljonas,

The reason this fails has to do with your transforToJSON function. It should be return an array of JSON dictionaries and not Mappable objects.

This should work:
```
func transformToJSON(value: List<T>?) -> Array<AnyObject>? {
        if value?.count > 0 {
            var result = Array<AnyObject>()
            for entry in value! {
                result.append(Mapper().toJSON(entry))
            }
            return result
        }
        return nil
    }
```

**Comment by wieseljonas** [comment]
Thanks works like a charm!
