### ISSUE TITLE
[Question] Do you see an overlap with SwiftyJSON?

### ISSUE THREAD

**Issue by allaire** [Hearst-DD/ObjectMapper#242]
Hey,

I know GH issues is not the preferred place for questions, so feel free to reply and close right after.

Currently in my project I have both SwiftyJSON/ObjectMapper + Alamofire.

I like having SwiftyJSON because I can play with the JSON response much more easily (like the meta data for exemple).

I still use ObjectMapper to map any entity my API returns (using a custom Alamofire response handler similar to https://github.com/SwiftyJSON/Alamofire-SwiftyJSON), i.e. :

```swift
        Alamofire.request(Router.ReadSchedule(from: from.stringFromFormat("YYYY-MM-dd"), to: to.stringFromFormat("YYYY-MM-dd"))).validate().responseAppJSON { (request, response, json, error) in
            if error != nil {
                ProgressHUDManager.serverError()
            } else {
                self.schedule = Mapper<Schedule>().map(json["schedule"].rawValue)!e
                self.tableView.reloadData()
            }
        }
```

Do you think it's fine to use both ObjectMapper and SwiftyJSON? Is there an overlap here?

Thanks!

**Comment by kaandedeoglu** [comment]
I've been using both in a project without any problems, I have a custom `Alamofire` serializer for `ObjectMapper` similar to yours for my API calls.

SwiftyJSON comes in handy for me when a response doesn't really deserve its own class/struct, usually when you're not planning to pass the data around, or you just need look a value up quickly.

I actually created another `Alamofire` serializer just for `SwiftyJSON` usage as well, it looks something like this:

```swift
    func responseSwiftyJSON(completionHandler: (NSURLRequest?, NSHTTPURLResponse?, SwiftyJSON.JSON?, NSError?) -> Void) -> Self {
        return response(responseSerializer: Request.JSONResponseSerializer(options: .AllowFragments)) {
            JSONResponse in
            
            dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)) {
                var JSONResult: SwiftyJSON.JSON? = nil
                if let obj = JSONResponse.result.value {
                    JSONResult = SwiftyJSON.JSON(obj)
                }
                
                dispatch_async(dispatch_get_main_queue()) {
                    completionHandler(JSONResponse.request, JSONResponse.response, JSONResult, JSONResponse.result.error)
                }                
            }
        }
    }
    
    func responseSwiftyJSON(completionHandler: (SwiftyJSON.JSON?, NSError?) -> Void) -> Self {
        return responseSwiftyJSON({ (_, _, json, error) -> Void in
            completionHandler(json, error)
        })
    }
```

**Comment by allaire** [comment]
@kaandedeoglu Cool, we have a similar way of doing things then, thanks for taking the time to write this down!

**Comment by tristanhimmelman** [comment]
I also don't really see a problem to using both SwiftyJSON and ObjectMapper in a project.

I also have created an Alamofire extension... shameless plug:
https://github.com/tristanhimmelman/AlamofireObjectMapper

I'd be interested to see the extensions you guys have created.

**Comment by kaandedeoglu** [comment]
@tristanhimmelman Actually I checked AlamofireObjectMapper a while back to see we almost have identical implementations (I don't have a queue parameter)

One interesting thing I use is a serializer just for pretty printing the JSON response, it looks something like this:

```swift
extension Alamofire.Request {
    func responseDebugPrint() -> Self {
        return responseJSON() {
            response in
            if let  JSON: AnyObject = response.result.value,
                    JSONData = try? NSJSONSerialization.dataWithJSONObject(JSON, options: .PrettyPrinted),
                    prettyString = NSString(data: JSONData, encoding: NSUTF8StringEncoding) {
             print(prettyString)
            } else if let error = response.result.error {
                print("Error Debug Print: \(error.localizedDescription)")
            }
        }
    }
}
```

With this I can go 

```swift
Alamofire.request(...).responseObject {

//Code here

}.responseDebugPrint()
```

and have it print without touching my main response block

**Comment by tristanhimmelman** [comment]
@kaandedeoglu, interesting... I might add that. Thanks for sharing :+1:
