### ISSUE TITLE
Pretty print not pretty in Swift 2.0?

### ISSUE THREAD

**Issue by wenxin3262** [Hearst-DD/ObjectMapper#244]
I use
debugPrint(Mapper().toJSONString(user, prettyPrint: true))
to print and it shows all stuff together with \n print out in the middle.

turn prettyPrint to false will make it looks the same besides no \n in the string.

I like ObjectMapper very much, hope you guys can get this better!

Thanks!

**Comment by tristanhimmelman** [comment]
Hey @wenxin3262, pretty print is still working for me. However, I did notice that it doesnt work if you print() an optional value. You have to make sure the value is unwrapped.

Hope this helps
