### ISSUE TITLE
Array support?

### ISSUE THREAD

**Issue by hengchengfei** [Hearst-DD/ObjectMapper#246]
if T is array,return nil.

![2015-10-19 6 41 47](https://cloud.githubusercontent.com/assets/3182964/10575675/bc38c494-7690-11e5-891a-9fb2d85ed416.png)
![2015-10-19 6 41 24](https://cloud.githubusercontent.com/assets/3182964/10575679/c1498a7c-7690-11e5-9334-8818f0711c6a.png)

**Comment by Trevor-L** [comment]
If you change your code to:
```swift
public var data:[CFSCommentModel]?
```

**Comment by tristanhimmelman** [comment]
ObjectMapper supports mapping arrays using the `mapArray` function. Setting the generic type of Mapper with an array type may work in certain circumstances, but is not actually supported.

**Comment by hengchengfei** [comment]
I really appreciate
