### ISSUE TITLE
Get object from classname in string

### ISSUE THREAD

**Issue by Urkman** [Hearst-DD/ObjectMapper#250]
Hello,

we have a web service, that returns a wide array of types...
So, the web services tells us for every object, what it is.

So we handle this fine with the code:

    if className == "ObjectJson" {
        if let mappedItem = Mapper<ObjectJson>().map(item){
            object = mappedItem
        }
    }

This works fine, but as I said, we have a long list of object types..

So my question:
Is'n there a more generic way to get from the classname string to the object?

Thanks,
Uriman

**Comment by tristanhimmelman** [comment]
At the moment, ObjectMapper doesn't officially support a better solution for this. 

I do however, have a branch `class-clusters` which has a potential solution.

It provides a Mappable sub protocol called MappableCluster. This subprotocol allows you to return a new instance used for mapping based on the passed `Map` variable. This would allow you to inspect the map for a specific key and return the correct type of object for mapping. 
```
static func newInstance(map: Map) -> Mappable? 
```

See https://github.com/Hearst-DD/ObjectMapper/blob/class-clusters/ObjectMapperTests/ClassClusterTests.swift

This isn't a generic approach, but it does encapsulate the code used for selecting the type of object that is mapping. 

Hope this helps

**Comment by rikoschmidt** [comment]
Hey,

our webservice also returns an array of different types. However, the types are encoded in the key of the dictionaries inside the array:

     {"animals": [
      {"Cat": {"name": "foo"}},
      {"Dog":{"name": "bar", "color": "brown"}}
     ]}

As far as I can tell, with this JSON structure, one could only select the right type in the mapping process by inspecting the key property of the JSONDictionary variable of the Map Object. But as the JSONDictionary is an internal property we can not access it. 

Is there maybe any other way we can achieve polymorphic mapping with the JSON structure above?

Thanks,
Riko

**Comment by tristanhimmelman** [comment]
Hi @rikoschmidt, in your case, I think just making the `currentKey` value public would work using the class cluster branch. 

Otherwise using the latest version of ObjectMapper, you can do something like the following within your mapping function:
```
var animalsJSON: Array<Dictionary<String, AnyObject>>?
animalsJSON	<- map["animals"]
if let animalsJSON = animalsJSON {
    for JSON in animalsJSON {
        // inspect key JSON key and map object accordingly 
    }
}
```
