### ISSUE TITLE
Mapping when property is sometimes a Mappable and sometimes an ID String

### ISSUE THREAD

**Issue by scottrhoyt** [Hearst-DD/ObjectMapper#253]
First of all, thank you for ObjectMapper. It's a great tool and I'm really appreciating it.

I have run into a situation that I feel is probably not all that uncommon. I'm mapping JSON output from an API that used an ORM--I believe it's Waterline in this case. This ORM has circular relationships. `Object1` -> `Object2` -> `Object1`. To deal with this potential infinite recursion, the API (through the ORM) will only return two levels deep/nested in the JSON, and beyond that it will just return the ID's of the related objects. What this means to me in my Swift client, is that if I a model for `Object2` that has a property `object1`, I cannot statically type that property because if I am getting my `Object2`s from a call to the object2 API endpoint, I will receive nested `Object1`s, but if I get it from a call to the object1 API endpoint, I will only receive ID strings. I was wondering if you had any ideas on how to accommodate this use case?

The way I see it, you either have to do a conditional mapping to two different properties in the Swift model (not sure if ObjectMapper supports that), you need to have two separate versions of the models depending on whether they include a string or a full object, or you need to have a different type receive the mapping. I chose route 3, and I was inspired by the Swift implementation of optionals. Let me know what you think, if you have any better ideas, or if you'd like to use this technique in your library (excuse any potential small errors in the code, I had to rip this out of my more complicated case).

    import ObjectMapper
    
    protocol HasID {
        var id: String! { get }
    }
    
    enum ObjOrID<T: Mappable> {
        case Obj(T)
        case ID(String)
        
        var obj: T? {
            switch self {
            case .ID:
                return nil
            case .Obj(let x):
                return x
            }
        }
    }
    
    extension ObjOrID where T : HasID {
        
        var id: String {
            switch self {
            case .ID(let id):
                return id
            case .Obj(let x):
                return x.id
            }
        }
        
    }
    
    
    func ==<T: Equatable>(lhs: ObjOrID<T>, rhs: ObjOrID<T>) -> Bool {
        switch (lhs, rhs) {
        case (.Obj(let x), .Obj(let y)):
            return x == y
        case (.ID(let x), .ID(let y)):
            return x == y
        default:
            return false
        }
    }
    
    func ==<T: Equatable>(lhs: ObjOrID<T>?, rhs: ObjOrID<T>?) -> Bool {
        if let lhs = lhs, let rhs = rhs {
            return lhs == rhs
        }
        if let _ = lhs {
            return false
        }
        if let _ = rhs {
            return false
        }
        
        return true
    }
    
    struct ObjOrIDTransform<T: Mappable> : TransformType {
        
        func transformFromJSON(value: AnyObject?) -> ObjOrID<T>? {
            if let value = value as? String {
                return ObjOrID<T>.ID(value)
            }
            
            if let value = Mapper<T>().map(value) {
                return ObjOrID.Obj(value)
            }
            
            return nil
        }
        
        func transformToJSON(value: ObjOrID<T>?) -> AnyObject? {
            
            if let value = value {
                switch value {
                case .Obj(let obj):
                    return Mapper().toJSON(obj)
                case .ID(let id):
                    return id
                }
            }
            
            return nil
        }
    }
    
    class Object1 : Mappable, HasID {
        var id: String!
        var object2: ObjOrID<Object2>?
    
        required init?(_ map: Map) { }
    
        func mapping(map: Map) {
            id <- map["id"]
            object2 <- (map["object2"], ObjOrIDTransform<Object2>())
        }
    }
    
    class Object2 : Mappable, HasID {
        var id: String!
        var object1: ObjOrID<Object2>?
    
        required init?(_ map: Map) { }
    
        func mapping(map: Map) {
            id <- map["id"]
            object1 <- (map["object1"], ObjOrIDTransform<Object1>())
        }
    }

Then you can use it like this:

    if let obj = object1.object2.obj {
       // Do Something with obj
    }

or

    print(object2.object1.id)

**Comment by tristanhimmelman** [comment]
Hi @scottrhoyt, thanks for the details of you're implementation. I haven't had to deal with anything like this but your approach is seems great :+1: . Off the top of my head I can't think of a better way to approach the problem.

I haven't heard of anybody else dealing with this situation so at this point in time I don't think I will be incorporating this into the project. However, if others bring up the same issue, I will look to this for reference.

Cheers,
Tristan
