### ISSUE TITLE
Attributes are not sorted when performing toJSONString

### ISSUE THREAD

**Issue by diogoguimaraes** [Hearst-DD/ObjectMapper#254]
Is there any reason why the attributes of an object N are not sorted by the order of the mapping in the result String after performing toJSONString(object: N, prettyPrint: Bool) ? What is the sort criteria for the JSON fields?

**Comment by tristanhimmelman** [comment]
JSON String generation is handled by `NSJSONSerialization.dataWithJSONObject()`. ObjectMapper simply passes it a dictionary of the mapped object. So the sorting of the generated JSON string is out of our control

**Comment by SnitramDev** [comment]
Isn't really a way around this? The GSON library for Android allows to add custom JsonSerializers to define the order of the elements. There's got to be a way.

**Comment by haritowa** [comment]
You have to implement OrderedDictionary to achieve ordered keys access. Not sure this feature will be so useful. In addition JSON is unordered by spec

**Comment by SnitramDev** [comment]
Do you have any example on how to do this? I'm not being able to find anything. Thanks.

**Comment by haritowa** [comment]
Maybe you get me wrong: OrderedDictionary should be used in ObjectMapper implementation. It's relativitely easy to implement, i guess(users will receive possibility to return list of keys with proper order).

You can check out [this](http://stackoverflow.com/questions/15125562/keeping-the-order-of-nsdictionary-keys-when-converted-to-nsdata-with-nsjsonseri) SO question which contains several links to OrderedDictionary implementation. If you have time for experiments: please check if it fix JSON serializing order and maybe ObjectMapper can receive new feature(with @tristanhimmelman approvement obviously)

**Comment by SnitramDev** [comment]
Do you mean using this class to convert to JSON? 
http://www.cocoawithlove.com/2008/12/ordereddictionary-subclassing-cocoa.html

As pointed in the SO question you've mentioned, this feature of maintaining the order of the attributes is really important "if you serialize the json to NSData and you use an MD5 string to determine whether the data has changed, it's good to know that it hasn't."
