### ISSUE TITLE
support to swift List Realm class

### ISSUE THREAD

**Issue by alfonso-matos-financefox-ch** [Hearst-DD/ObjectMapper#258]
Hi all,

We are developing with swift 2.0 and we're using alamofire 3.0, Realm 0.96, and your last version of ObjectMapper
We have some entities that inherits from Object (to persist in Realm) and implements Mappable protocol. We have the following classes 

class A: Object, Mappable{

dynamic var name    : String?
let productGroup       = List<ProductGroup>()
 
required convenience init?(_ map: Map) {
        self.init()
    }
    
  func mapping(map: Map) {
      name <- map["name"]
      productGroup <- map["productGroup"]

}

class ProductGroup: Mappable {
    dynamic var name                    : String?
    dynamic var urlPhoto                : String?
    dynamic var currency                : String?

    required convenience init?(_ map: Map) {
        self.init()
    }
    
      func mapping(map: Map) {
           name <- map["name"]
           currency <- map["currency"]
           urlPhoto <- map["urlPhoto"]
      }

}
object A has a list of productGroup (supported by Realm to keep them persistently). When we parse them within the A class mapping , productGroup is not populated because is not entering to the ProductGroup mapping function.

Are you going to support nested objects using List?

Best regards,

Alfonso

**Comment by tristanhimmelman** [comment]
Hi @alfonso-matos-financefox-ch,

As I mentioned in the AlamofireObjectMapper issues response, you should be able to find some CustomTransforms that handles Realm Lists if you search the closed issues here.
