### ISSUE TITLE
Mapping empty JSON array gives nil

### ISSUE THREAD

**Issue by zuziakaxel** [Hearst-DD/ObjectMapper#262]
Hi, first of all great work with ObjectMapper👏

Lets say that I have JSON like this:

```JSON
{
"status":"success",
"data":
           {
                  "categories":[]
            }
}
```

and mapping:
```swift
    func mapping(map: Map) {
        categories <- map["data.categories"]
        if categories == nil {
            self.showAlert()
        }
    }
```

In 0.18 ```(categories == nil)``` only if data did not contain ```"categories"``` field. If contained empty array like in example JSON, ```categories``` array was just empty array.
But in 0.19 ```categories``` array is nil in both cases.

**Comment by fscherer** [comment]
Same issue here.

The Mapper methods mapArray(...), mapDictionary(...), etc. should not return nil for an empty but existing JSON.

Thanks in advance

**Comment by tristanhimmelman** [comment]
I agree this could be improved. I have marked as an enhancement to keep track. Pull requests are welcomed

**Comment by ArsalanReal** [comment]
Please fix it. Same issue to me :(

**Comment by tristanhimmelman** [comment]
This has been fixed on master thanks to @jdzak
