### ISSUE TITLE
Array of optional element

### ISSUE THREAD

**Issue by mishimay** [Hearst-DD/ObjectMapper#263]
A json array that contains null always fails to be mapped to a swift array that has optional elements.

```
    public var result: [Product?]!
```
```
    required public init?(_ map: Map) {
        result <- map["result"] // `result` will always be nil
    }
```

**Comment by tristanhimmelman** [comment]
ObjectMapper doesn't actually support arrays of optionals. When mapping arrays, it only adds objects that have been successfully mapped.

**Comment by Narayane** [comment]
Hi,

I have really stuck on this issue with a [Int?]? attribute which I get from a web service.

Is there any workaround you could suggest me to deal with it: maybe a custom transform (which would transform nil values into 0) could work?

Thanks.

**Comment by Narayane** [comment]
Ok, I have a workaround if someone has the same problem, I guess it should work also with a custom object.

import ObjectMapper

class MyDto: Mappable {

    var dangerLevels: [Int]? // in json, it is in fact a [Int?]? representation

    required init?(_ map: Map) {
        let levels = map["dangers_levels"].value() as [AnyObject]?
        if let levels = levels {
            dangerLevels = []
            for level in levels {
                if level is NSNull {
                    dangerLevels!.append(0)
                } else {
                    dangerLevels!.append(level as! Int)
                }
            }
        }
    }
    
    func mapping(map: Map) {
        //dangerLevels <- map["dangers_levels"]
    }
}

**Comment by KevM** [comment]
Here is a swipe at a generic version that is working for us.

```swift
final class MapHelper<T> {
    
    let map: Map
    
    init(map: Map) {
        self.map = map
    }
    
    func mapArrayOfOptionals(field: String) -> [T?] {
        if let values = map[field].value() as [AnyObject]? {
            var resultValues = [T?]()
            for value in values {
                if value is NSNull {
                    resultValues.append(nil)
                } else {
                    resultValues.append(value as? T)
                }
            }
            
            return resultValues
        }
        return []
    }
}
```
## Usage

```swift

struct SomeDTO: Mappable {
    private(set) var optionalStrings: [String?]!
 
    init?(_ map: Map) {}
    
    mutating func mapping(map: Map) {
        optionalStrings = MapHelper<String>(map: map).mapArrayOfOptionals("items")
    }
}
```

Is something along these lines viable as a PR for the project. Happy to take suggestions and take a stab at it if desired.

**Comment by txaiwieser** [comment]
Awesome, thanks!!

**Comment by austinzmchen** [comment]
Thanks for the solution! Kinda get caught off guard when knowing the following JSON validates. 
`[
	{
		"name": "a",
		"type": 1
	},
	null,
	{
		"name": "a",
		"type": 1
	}
]`

**Comment by amirsaifi77** [comment]
@KevM Having a hard time implementing the generic solution for my custom object. If my custom struct has nested custom structs that rely on Object Mapper to parse it, is this solution sill expected to work?

**Comment by amirsaifi77** [comment]
To add onto @KevM's solution above. This implementation allows nested mapping if your optional value is Mappable.
Same usage as the solution by @KevM above.

```swift
final class MapHelper<T:Mappable> {
    
    let map: Map
    
    init(map: Map) {
        self.map = map
    }
    
    func flatMapArrayOfOptionals(field: String) -> [T] {
        if let values = map[field].value() as [AnyObject]? {
            var resultValues = [T]()
            for value in values {
                if value is NSNull {
                    // do nothing
                } else {
                    if let mappableValue = Mapper<T>().map(value) {
                        resultValues.append(mappableValue)
                    } else if let nonMappableValue = value as? T {
                        resultValues.append(nonMappableValue)
                    }
                }
            }
            
            return resultValues
        }
        return []
    }
    
    func mapArrayOfOptionals(field: String) -> [T?] {
        if let values = map[field].value() as [AnyObject]? {
            var resultValues = [T?]()
            for value in values {
                if value is NSNull {
                    resultValues.append(nil)
                } else {
                    if let mappableValue = Mapper<T>().map(value) {
                        resultValues.append(mappableValue)
                    } else {
                        resultValues.append(value as? T)
                    }
                }
            }
            
            return resultValues
        }
        return []
    }
    
}
```

**Comment by RafaelPlantard** [comment]
Guys I have the following object:

```
struct Repo: ImmutableMappable {
    let name: String
    let description: String?
    let author: String
    let profilePicture: URL
    let stars: Int
    let forks: Int
    let fullName: String

    // MARK: Non-argument initializer

    init() {
        name = ""
        description = nil
        author = ""
        profilePicture = EnvironmentVariable.profileURL.url
        stars  = 0
        forks = 0
        fullName = ""
    }

    // MARK: ImmutableMappable conforms

    init(map: Map) throws {
        name = try map.value("name")
        description = try map.value("description")
        author = try map.value("owner.login")
        profilePicture = try map.value("owner.avatar_url", using: URLTransform())
        stars = try map.value("stargazers_count")
        forks = try map.value("forks_count")
        fullName = try map.value("full_name")
    }
}
```

And it's failing when `description` property is `null`, how can I handle it?
