### ISSUE TITLE
Mapper().toJSON() returning an expected result

### ISSUE THREAD

**Issue by dotmike** [Hearst-DD/ObjectMapper#265]
This is a really fantastic library. Thanks. I have been using it in conjunction with Alamofire 3, but I'm noticing some odd things with the Mapper().toJSON() method.

What I'm trying to do is map my object to a JSON object so that I can pass it as a parameter for a `.POST` request. But, when I do `let params = Mapper().toJSON(login)`, it returns `["email": user@domain.com, "password": pass]` and when I tried `Mapper().toJSONString(login, prettyPrint: false)`, I'm getting `{\"email\":\"user@domain.com\",\"password\":\"pass\"}`.

My expected output is something like this:
```json
{
   "login":"user@domain.com",
   "password":"pass"
}
```
Am I missing something obvious? Would really appreciate any feedback.

Here is my object and the Alamofire request.

```swift
class login: Mappable {
    
    var login:      String? = nil
    var password:   String? = nil
    
    init(forLogin login: String, forPassword password: String) {
        self.login      = login
        self.password   = password
    }
    
    
    required init?(_ map: Map){
        
    }
    
    func mapping(map: Map) {
        
        login       <- map["email"]
        password    <- map["password"]
        
    }

}
```

```swift
let params = Mapper().toJSON(login)

Alamofire
  .request(.POST, URL!, parameters: params, encoding: .JSON)
  .validate()
  .responseJSON { response in
    debugPrint(response)
}
```

**Comment by tristanhimmelman** [comment]
Hi @dotmike, this is actually the expected output. ObjectMapper uses the keys passed into the `map` object to construct the JSON string.

**Comment by dotmike** [comment]
I see. Thanks, @tristanhimmelman. Do you recommend any other method to have the `values` to be wrapped in double quotes like so: `["email": "user@domain.com", "password": "pass"]`? Appreciate the help and 🍺 for the library.

**Comment by tristanhimmelman** [comment]
@dotmike, you can check the `mappingType` property of `Map` to detect when the mapping is FromJSON or ToJSON. ex:
```
func mapping(map: Map) {	
	if map.mappingType == .FromJSON {
	     login <- map["email"]		
	} else {
	     login <- map["login"]
	}
}
```
