### ISSUE TITLE
ios7 + objectmapper submission error

### ISSUE THREAD

**Issue by pcompassion** [Hearst-DD/ObjectMapper#268]
I can compile my project fine which is targeted minimum 7.1

However when I try to submit the app using xcode7,  I get errors
```
Error ITMS-90362: "Invalid Info.plist value. The value for the key 'MinimumOSVersion' in bundle my.app/Frameworks/ObjectMapper.framework is invalid. The minimum value is 8.0"
```

How can I avoid this error?

**Comment by ikesyo** [comment]
Dynamic frameworks can be used only on iOS 8 and later. That is an requirements Apple forces us to follow. You must include all the souces files directly to your app target.

**Comment by pcompassion** [comment]
oh I followed instrunction at the git main.
```
Otherwise, ObjectMapper can be added as a submodule:
```

I have the ObjectMapper.xcodeproj included under my project workspace

**Comment by ikesyo** [comment]
That isn't related to the issue. _File -> Add Files to “YourProjectName”_, then select the files in `ObjectMapper/Core` and `ObjectMapper/Transforms`.

**Comment by pcompassion** [comment]
Are you saying that, having the ObjectMapper project under my workspace isn't enough and I should add those files again?

**Comment by pcompassion** [comment]
You should add files directly as ikesyo suggested. I though `Otherwise, ObjectMapper can be added as a submodule` part was for 7.1 users. and it's not.
