### ISSUE TITLE
Create a new release/tag with podspec file

### ISSUE THREAD

**Issue by ararog** [Hearst-DD/ObjectMapper#27]
Hi,

I'm using cocopods 0.36 beta 1 to manage dependencies in my Swift project, this project has ObjectMapper as dependency and I missed a release with podspec file, can you create a new release based on master branch which already has the podspec file commited?

Thanks!

**Comment by tristanhimmelman** [comment]
Hey there,
I've added a new release tag and updated the podspec.

Let me know if you have any issues.
Tristan
