### ISSUE TITLE
Mapping does not work correctly with NSTaggedPointerString

### ISSUE THREAD

**Issue by vherrin** [Hearst-DD/ObjectMapper#270]
The mapper function works very well in almost all of my use cases except for the following.  If the response is mapped as a NSTaggedPointerString then the value is not retrieved.  Please take a look at the following.  
    
public init?(_ map: Map) {}
    
    public mutating func mapping(map: Map) {
        height      <- map[ImageFaceEnum.Height.rawValue]
        width       <- map[ImageFaceEnum.Width.rawValue]
        positionX   <- map[ImageFaceEnum.PostionX.rawValue]
        positionY   <- map[ImageFaceEnum.PostionY.rawValue]
        age         <- map[ImageFaceEnum.Age.rawValue]
        gender      <- map[ImageFaceEnum.Gender.rawValue]
    }
}

![screen shot 2015-10-30 at 8 44 11 am](https://cloud.githubusercontent.com/assets/2422521/10847243/104070be-7ee3-11e5-8a1a-023d1d6a58b8.png)

**Comment by tristanhimmelman** [comment]
Sorry this is not currently a supported type. Perhaps you will need to create a custom transform to handle it.

**Comment by vherrin** [comment]
Thanks for the reply!

Yes you are correct.  I was able to use a custom transformation that worked perfectly

Below is the snippet of code that worked for me 

```swift
    /// Transforms AnyObject to Int
    public static let anyObjectToInt = TransformOf<Int, AnyObject>(fromJSON: { (value: AnyObject?) -> Int? in
        // transform value from AnyObject? to Int?
        if let x = value {
            return Int(x as! String)
        }
        return nil
        }, toJSON: { (value: Int?) -> AnyObject? in
            // transform value from Double? to String?
            if let value = value {
                let any:AnyObject = value
                return any
            }
            return nil
    })
```
