### ISSUE TITLE
How to get the generic type?

### ISSUE THREAD

**Issue by hengchengfei** [Hearst-DD/ObjectMapper#271]
thank you!

<pre><code> let s = "{\"code\":200,\"data\":\"aa\"}"
 public func test&lt;T>(p1:T){
    if p1 is Mappable {
       let m = Mapper&lt;p1.self>().map(s)
        print(m)
    }else{
        //...
    }
 }</code></pre>

**Comment by tristanhimmelman** [comment]
I think you need to add `Mappable` to the function generic type definition. Something like this:
``` 
let s = "{\"code\":200,\"data\":\"aa\"}"
public func test<T: Mappable>(p1:T){
       let m = Mapper<T>().map(s)
       print(m)
 }
```

**Comment by hengchengfei** [comment]
I really appreciate.
