### ISSUE TITLE
init vs mapping?

### ISSUE THREAD

**Issue by ed-mejia** [Hearst-DD/ObjectMapper#272]
Hi when do you map using the init or the func mapping?

required init?(_ map: Map)
func mapping(map: Map)

In all the Readme samples, always use mapping, but using mapping does not allows me to use valueOrFail in order to do not return an invalid object.

so when do we need to use each other and what are the differences ?

**Comment by tristanhimmelman** [comment]
The majority of the time, and the way I designed the library to be used, is to put all your mappings within the mapping function.

If you are using immutable mappings (which again I will stress are experimental and don't support all functionality), you should put your mappings inside the init? function.
