### ISSUE TITLE
Mapping immutable properties

### ISSUE THREAD

**Issue by yomajkel** [Hearst-DD/ObjectMapper#275]
I try to map immutable properties according to documentation, but ObjectMapper doesn't seem to find correct key -> value in case where property is user defined struct. Furthermore the test crashes in the line where dummy memory should be returned instead (return pointer.memory). 

https://gist.github.com/yomajkel/5374b37b4e0339d4013c

In the gist test of Child mapping passes flawlessly. Testing of Parent mapping has always problem on the line 'child = map["child"].valueOrFail()'.

Is it me doing something wrong in the code?

**Comment by tristanhimmelman** [comment]
Hi @yomajkel, as mentioned in the docs, mapping immutable properties is an experimental feature so we  do not guarantee functionality or provide support for issues with this feature currently.

I have actually just removed it from the ReadMe as I don't recommend developers use this approach at the time being.

 If you want to continue using ObjectMapper, I recommend you stick to the regular mappings described in the ReadMe.

Tristan
