### ISSUE TITLE
How to manage polymorphic object

### ISSUE THREAD

**Issue by elpic** [Hearst-DD/ObjectMapper#276]
On the old version of ObjectMapper, we have a class func called newInstance. That method returns a Mappable object. 
I used to use that method to generate the corresponding instance of the type I want.

For example: 

```
{
  type: 'a'
}
```

This will generate an object of class A

```
{
  type: 'b'
}
```
This will generate an object of class B

A and B are the same API requests.

How can I do the same behavior with the new mapping protocol?

I will appreciate your response.
Thanks

**Comment by tristanhimmelman** [comment]
Hi @elpic, when I changed the protocol to `init?` I didn't realize that people were using the `newInstance` function as you described above. I am considering reverting to the old protocol, however it is a significant change that will affect many people so I am taking my time with the decision.

You can achieve polymorphic mapping in the current design, however, it requires a bit more code. Given the following JSON:
```JSON
{
    "object1" : {
        "type": "dog",
        "name": "joey"
     },
    "object2": {
        "type": "cat",
        "name": "fluffy" 
    }
}
``` 
You can map the objects based on the type flag as follows:
```
class Response: Mappable {

    init?(_ map: Map){}

    func mapping(map: Map){
    
        var object1JSON: Dictionary<String: AnyObject>?
        object1JSON <- map["object1"]
        if let type = object1JSON?["type"] where type == "dog" {
             let dog = Mapper<Dog>().map(object1JSON)
        } 
    }
}
```
Hope this helps!

**Comment by elpic** [comment]
Thanks

**Comment by elpic** [comment]
@tristanhimmelman any news on this?

**Comment by tristanhimmelman** [comment]
@elpic, unfortunately I haven't had the time to consider this any more. So for the time being I do not plan on changing this.
