### ISSUE TITLE
array of objects to alamofire put and post

### ISSUE THREAD

**Issue by mirzadelic** [Hearst-DD/ObjectMapper#278]
I have array of mappable objects:
```
var arr = [MappableObject]
```
now i need to use `Alamofire` and `.PUT` method to save that array on server.

How can i do that?

**Comment by tristanhimmelman** [comment]
@mirzadelic are you asking how to convert the array into a JSON string that you can submit to a server?

**Comment by mirzadelic** [comment]
Yes, and to send it to server with Alamofire.

**Comment by tristanhimmelman** [comment]
I just realized ObjectMapper doesn't have a method for generating JSON strings for arrays. I will add that shortly.

For now you can do the following:
```
var JSONString = "["
for object in array {
    JSONString += Mapper().toJSONString(object) + ","
}
JSONString += "]"
```

Now you can submit that JSONString to the server using Alamofire. If you have questions about Alamofire usage, please post those in the Alamofire Github issues.

**Comment by tristanhimmelman** [comment]
I actually just pushed an update that includes the new `toJSONString` function that takes an array of objects. If you use latest on master you will have those changes.
