### ISSUE TITLE
Unidirectional (To JSON) mapping with immutable model object

### ISSUE THREAD

**Issue by nmccann** [Hearst-DD/ObjectMapper#282]
Hi,
I recently ran into the following issue in my project: I have a request object that I need to convert to JSON, with the (self-imposed) limitations that the object should be immutable.

So far I've had no problem accomplishing this with response objects (From JSON) and ObjectMapper, but when trying to accomplish the same thing with request objects (ones that will only ever be mapped To JSON), I ran into the issue that ObjectMapper expects a `Mappable` object to support mapping from and to JSON. This means that properties have to be `var` so that they can be changed when mapping from JSON.

#42 showed me that it is possible to provide different mappings when mapping to JSON vs. from JSON, but that seems to assume that the properties will still be `vars`.

So far I've implemented the following workaround:

```
struct InviteRequest {
  let golferId: Int
  let customerId: Int
}

extension InviteRequest: Mappable {
  var mappingGolferId: Int {
    get {
      return golferId
    }
    
    set {}
  }
  
  var mappingCustomerId: Int {
    get {
      return customerId
    }
    
    set {}
  }
  
  init?(_ map: Map) {
    fatalError()
  }
  
  mutating func mapping(map: Map) {
    mappingGolferId    <- map["id"]
    mappingCustomerId  <- map["customerId"]
  }
}
```

This isn't ideal because it requires a lot of extra boilerplate code. The `init` method is particularly frustrating because `fatalError()` yields a warning that the method isn't called, while omitting it causes an error that the object's properties are not initialized.

Perhaps there is a better workaround for this, but it would be nice if ObjectMapper better supported the case where a model object is only being used for mapping to JSON - perhaps by providing separate protocols, or support for something like:

```
map["id"] = golferId
map["customerId"] = customerId
```

Thank you for your time,
Noah

**Comment by justbaum30** [comment]
@tristanhimmelman  The project I am working on is struggling with this same issue. We want to be able to map our immutable properties to a JSON but aren't able to. We're considering forking, but we would prefer not to do this. Especially if you have a potential solution or are considering making changes in the near future.

**Comment by nikita-leonov** [comment]
There are hidden section in README.md that was add before but was hidden afterward. Checked raw source of it for a `Mapping Immutable Properties`. I am actually curious why it was done like this? @tristanhimmelman

**Comment by nikita-leonov** [comment]
Ok, I just found that `valueOrFail` as mentioned in some other issues. Also causing crashes in my code, so I assume it is hidden from docs on purpose.

**Comment by tristanhimmelman** [comment]
@nikita-leonov I removed it from the README because the feature is still experimental and not well tested. There were a lot of reported issues with it so I decided to hide it until it is ready

**Comment by nmccann** [comment]
@nikita-leonov I've been using `valueOrFail` and related methods for a while and haven't add many issues. The only downside is that you have to manually map the objects. An example:

```
extension InviteResponse: Mappable {
  init?(_ map: Map) {
    let rawOthers: [[String: AnyObject]] = map["others"].valueOrFail()
    guard let mappedOthers = [InvitedPersonResponse](JSONArray: rawOthers) else {
      return nil
    }
    
    others = mappedOthers
    
    guard map.isValid else {
      return nil
    }
  }
  
  func mapping(map: Map) {
  }
}
```

Not sure if there is a better workaround.

**Comment by tristanhimmelman** [comment]
I've created an issue for discussing immutable types and how we may add support for them. Please continue the conversation here #383 if you have anything to add.
