### ISSUE TITLE
Is There Any Way Can Deal With: TypeOutter<TypeInner>? [Mapper<TypeOutter<TypeInner>>]

### ISSUE THREAD

**Issue by liuxue0905** [Hearst-DD/ObjectMapper#283]
I want use ObjectMapper in this scene:
let resultObject = Mapper&lt;Result&lt;DatasForGoodsList>>().map(jsonString)

Please tell me ObjectMapper can handle this~~~

**Comment by tristanhimmelman** [comment]
Hi there, you can do this by making your Result class look like the following and making sure your generic type also conforms to `Mappable`

```
class Result<T: Mappable>: Mappable {
	var result: T?
	
	required init?(_ map: Map){
		
	}
	
	func mapping(map: Map) {
		result <- map["result"]
	}
}
```
