### ISSUE TITLE
Adding own initialiser 

### ISSUE THREAD

**Issue by iandundas** [Hearst-DD/ObjectMapper#284]
Hi,

I'm just updating some code from 0.14 to 1.1,

Previously we would use the following to give us an instance of our `Mappable` object, which we could then set Optional properties on (prior to using it to generate JSON): 

    public class func newInstance() -> Mappable {
        return CheeseResource()
    }

I see the work on failable initialisers (`valueOrFail` etc) and it looks good, but (as is noted) is not ready for use yet.

So, in the meantime - since `Mappable` specifies an init taking a Map (`init?(_ map: Map)`), are we correct to mark our network resource class `final` and to just add `public required init() {}` as well, for our own use? 

Thanks

**Comment by tristanhimmelman** [comment]
Hi @iandundas , that's right you can just add your own `init()` for your own use. However, it does not need to be prefixed with `required` and I don't need to make the class `final` either (that is up to you).

**Comment by iandundas** [comment]
Strange - when I implement Mappable in a class I get: `Initialiser requirement 'init' can only be satisfied by a `required` initializer in non-final class 'CheeseResource'`

**Comment by iandundas** [comment]
(But doesn't matter much)

**Comment by tristanhimmelman** [comment]
Hmm that is strange. If you look at the ObjectMapperTests file you will see several examples where this isn't necessary.
