### ISSUE TITLE
Realm + ObjectMapper

### ISSUE THREAD

**Issue by yamifr07** [Hearst-DD/ObjectMapper#285]
I am getting data from my server. The response is:
{"languages":[{"language":"en","disabled":false}]}

When I do the request the code suddenly throws EXC_BAD_INSTRUCTION and it gets stuck in the error. If I remove inheritance Object from Language.swift it works ok

LanguageResponse.swift

    import ObjectMapper

    class LanguageResponse: Mappable {

        var languages: [Language]?
    
        required init?(_ map: Map){
        }

        override func mapping(map: Map) {
            super.mapping(map)
            languages <- map["languages"]
        }
    
    }

Language.swift

    import UIKit
    import RealmSwift
    import ObjectMapper

    class Language: Object, Mappable {
   
        dynamic var language: String = ""
    
        override static func primaryKey() -> String? {
            return "language"
        }
    
        required convenience init?(_ map: Map) {
            self.init()
        }
    
        func mapping(map: Map) {
            language <- map["language"]
        }
    
    }

**Comment by tristanhimmelman** [comment]
I'm not sure exactly what is going on but I don't think this should compile as is.

`LanguageResponse` has no super class so the mapping function shouldn't have a call to super in it and should not be mark as `override`. I've just tested this out with my suggested change and everything seems to work fine

**Comment by yamifr07** [comment]
Sorry, I put Realm instead of RealmSwift in my Pod file

**Comment by tristanhimmelman** [comment]
No problem
