### ISSUE TITLE
convert mappable object to [String: AnyObject]

### ISSUE THREAD

**Issue by mirzadelic** [Hearst-DD/ObjectMapper#286]
How can i convert mappable object with changed values to `[String: AnyObject]` ?

**Comment by tristanhimmelman** [comment]
You can use the following function: 
```
///Maps an object that conforms to Mappable to a JSON dictionary <String : AnyObject>
public func toJSON(var object: N) -> [String : AnyObject]
```
```
let dictionary = Mapper().toJSON(object)
```

**Comment by mirzadelic** [comment]
Where should i push this function code?

**Comment by mirzadelic** [comment]
Ohh, this is great. Thanks..

**Comment by tanujtak1986** [comment]
{"results":[{"gender":"female","name":{"title":"ms","first":"leana","last":"henry"},"location":{"street":"3060 rue paul-duvivier","city":"nîmes","state":"indre","postcode":94802},"email":"leana.henry@example.com","login":{"username":"bluefish422","password":"cameron","salt":"87Vty9Rx","md5":"50e4697bda5e14a5ab9cfa2b9ebcc920","sha1":"4bb1f967086e107b2d54ab819b12a093414fd55e","sha256":"fd93902b1bbe660a30ef39ccb07c3b42b88c35757a4f015da505596d7ce9cec7"},"dob":"1986-04-29 01:08:51","registered":"2012-04-05 10:41:51","phone":"03-14-56-37-67","cell":"06-92-24-98-22","id":{"name":"INSEE","value":"286362533442 76"},"picture":{"large":"https://randomuser.me/api/portraits/women/70.jpg","medium":"https://randomuser.me/api/portraits/med/women/70.jpg","thumbnail":"https://randomuser.me/api/portraits/thumb/women/70.jpg"},"nat":"FR"}],"info":{"seed":"68eb2a060c65a7b1","results":1,"page":1,"version":"1.1"}}



how to map nested dictionaries 
now i can't access the "name" dictionaries

**Comment by saifuzzafar** [comment]
{"results":[{"gender":"female","name":{"title":"ms","first":"leana","last":"henry"},"location":{"street":"3060 rue paul-duvivier","city":"nîmes","state":"indre","postcode":94802},"email":"leana.henry@example.com","login":{"username":"bluefish422","password":"cameron","salt":"87Vty9Rx","md5":"50e4697bda5e14a5ab9cfa2b9ebcc920","sha1":"4bb1f967086e107b2d54ab819b12a093414fd55e","sha256":"fd93902b1bbe660a30ef39ccb07c3b42b88c35757a4f015da505596d7ce9cec7"},"dob":"1986-04-29 01:08:51","registered":"2012-04-05 10:41:51","phone":"03-14-56-37-67","cell":"06-92-24-98-22","id":{"name":"INSEE","value":"286362533442 76"},"picture":{"large":"https://randomuser.me/api/portraits/women/70.jpg","medium":"https://randomuser.me/api/portraits/med/women/70.jpg","thumbnail":"https://randomuser.me/api/portraits/thumb/women/70.jpg"},"nat":"FR"}],"info":{"seed":"68eb2a060c65a7b1","results":1,"page":1,"version":"1.1"}}



how i create the mapper class for this response 
right no i can't access the name dictionary i.e nested dictionaries
