### ISSUE TITLE
Generic Objects: Result<[User]> (Result<Array<User>>) Can not work

### ISSUE THREAD

**Issue by liuxue0905** [Hearst-DD/ObjectMapper#287]
Generic Objects: 
Result&lt;[User]> 
Result&lt;Array&lt;User>>

**Comment by adamjweaver** [comment]
I'm also seeing this. Using an array of `Mappable` objects as the generic type parameter seems to yield a nil result.

**Comment by TJRoger** [comment]
I have also encountered this `nil` error

**Comment by tristanhimmelman** [comment]
Unfortunately, currently ObjectMapper doesn't support this type of generic argument. If you need to handle arrays, you will need to use the mapArray function.
