### ISSUE TITLE
valueOrFail always fails

### ISSUE THREAD

**Issue by ruben-samsonyan** [Hearst-DD/ObjectMapper#289]
I have Data model, and base class for all models, which implements Mappable:

```swift
class BaseModel: Mappable {    
    var id: String?
    
    required init?(_ map: Map){
        id = map["id"].valueOrFail()
    }
    
    func mapping(map: Map) {
        id <- map["id"]
    }
}
```

Then I have subclass like this:

```swift
class Channel: BaseModel {

    var name:       String?
    var order:      String?
    
    required init?(_ map: Map) {
        super.init(map)
        name = map["name"].valueOrFail()
        order = map["order"].valueOrFail()
        
        if !map.isValid {
            return nil
        }
    }

    override func mapping(map: Map) {
        super.mapping(map)

        name        <- map["name"]
        order       <- map["order"]
    }
}
```

When I'm mapping my json to object, my failable init is always return nil, because valueOrFail method always increments failedCount property of map by one. My json is valid, because when I remove implementation of init, my object maps successfully.

**Comment by anas10** [comment]
@ruben-samsonyan  Maybe you should say why you're closing this issue. It may not be obvious for everyone.
