### ISSUE TITLE
could not load any Objective-C class information

### ISSUE THREAD

**Issue by mpclarkson** [Hearst-DD/ObjectMapper#296]
Hi there

I'm getting the following warning when using this library in Swift 2.1:
```
warning: could not load any Objective-C class information. This will significantly reduce the quality of type information available.
```
followed by a crash on line 36 of `toJSON.swift`
```swift
let keyComponents = ArraySlice(key.characters.split { $0 == "." })
```
My model is very basic:
```swift
public struct OAuthToken: Mappable {

    var accessToken: String?   
    public init?(_ map: Map) {}
    
    mutating public func mapping(map: Map) {
        accessToken <- map["access_token"]
    }
}
```
Any ideas?

Great library by the way.

**Comment by tristanhimmelman** [comment]
Sorry but I have no idea what is happening here... is this still a problem for you?

**Comment by mpclarkson** [comment]
I'm afraid that I had to remove the library, as I couldn't find a work around.

**Comment by tristanhimmelman** [comment]
Sorry to hear that. I'm really not sure why you were experiencing the problem
