### ISSUE TITLE
NULL values on toJSON

### ISSUE THREAD

**Issue by mirzadelic** [Hearst-DD/ObjectMapper#298]
I have this model:
```
class Table: Mappable {
    var id: Int!
    var name: String!
    var order: Int!

    init(){}
    
    required init?(_ map: Map) {
        mapping(map)
    }

    func mapping(map: Map) {
        id <- map["id"]
        name <- map["name"]
        order <- map["order"]
    }
}
```

and now i need to create new table, with id `NULL` and send it with Alamofire.
Controller:
```
            let table = Table()
            table.id = nil
            table.name = textField.text
            table.order = self.results.count+1

            let dict = Mapper().toJSON(table)

            print(dict)
```

This prints me:
```
["order": 12, "name": asa]
```

And now i have error when send this data to server, it requires `id` field..

How can i deal with this?

**Comment by tobiasoleary** [comment]
Why can't you make type of 'id' 'Int?'?

**Comment by tobiasoleary** [comment]
Oh never mind. I see what you asking.

**Comment by tristanhimmelman** [comment]
At the moment, unfortunately ObjectMapper doesn't support inserting a value for nil objects. You will need to do this manually after the toJSON call. There is another open issue marked with "enhancement" that mentions this as well. The feature may be added in the future.

**Comment by mirzadelic** [comment]
How can i do that?

```
            let table = Table()
            table.id = nil
            table.name = textField.text
            table.order = self.results.count+1

            let dict = Mapper().toJSON(table)
            // what i need here?
```

**Comment by naeemshaikh90** [comment]
@tristanhimmelman can you mention that "enhancement" issue number?
