### ISSUE TITLE
Cast mapping?

### ISSUE THREAD

**Issue by BarakRL** [Hearst-DD/ObjectMapper#299]
Is there a way to cast while mapping?

I have a public protocol (ProtocolA) and a internal class that conforms to it (ClassA : ProtocolA).
now, in a second class (ClassB) I have a property that conforms to ProtocolA, but during the mapping I want to create an instance of ClassA, so I'm doing:

```
var myProperty: ProtocolA?

func mapping(map: Map) {
   var instance: ClassA?
   instance <- map["myProperty"]
   myProperty = instance
}
```

is there a way to do this more efficiently without the extra instance?

**Comment by tristanhimmelman** [comment]
Unfortunately I don't believe there is a more efficient way to write this. The Swift compiler seems requires this syntax to understand the code
