### ISSUE TITLE
Map [N] to JSON array

### ISSUE THREAD

**Issue by ldiqual** [Hearst-DD/ObjectMapper#30]
By looking at the source code, I can't find a way to map `[N] -> [[String: AnyObject]]`. Is there a way to do it with the current state of the code (without iterating directly)? If not, I might PR something.

**Comment by tristanhimmelman** [comment]
Hey there, you right, that was missing. I just pushed some code with a new function for you (func toJSONArray). I think this should do the job for you. Let me know if you have any issues. I will update the podspec by end of day. 

Cheers

**Comment by tristanhimmelman** [comment]
I just pushed it to Cocoapods. Everything should be good to go.
