### ISSUE TITLE
Transforms with parameters

### ISSUE THREAD

**Issue by esetnik** [Hearst-DD/ObjectMapper#300]
First off would like to say I'm loving ObjectMapper! Thanks for all the hard work.

I have a requirement to use `DateTransform()` with timestamps that include millsecond precision. I'd like to submit a PR so others can also take advantage of this behavior. Would you prefer a separate transform for this behavior or optional parameter (with default behavior of second precision) passed to `DateTransform()`?

**Comment by tristanhimmelman** [comment]
Hi @esetnik, I'm glad you like the library :).
I think an optional parameter would be fine in this situation. Thanks!
