### ISSUE TITLE
Delete orphaned objects

### ISSUE THREAD

**Issue by ogezue** [Hearst-DD/ObjectMapper#301]
I use Alamofire, ObjectMapper and Realm and save my fetched and mapped objets in realm.
Is it possible to delete orphaned objects automatically?

e.g. I fetch for a list of contacts. Now one contacts has been removed from the response and should be deleteted from Realm automatically. Is this something objectmapper can do?

**Comment by tristanhimmelman** [comment]
No at the moment there is no way to automatically delete the orphaned objects. You will have to process that and manually delete them
