### ISSUE TITLE
Sometimes the Int value "0" is converted to nil

### ISSUE THREAD

**Issue by popaaaandrei** [Hearst-DD/ObjectMapper#302]
Please be so kind and help me, I have an issue with a JSON conversion.
This is a part of a JSON that I expect to be converted to my model:

```
{
            amount = 5;
            color = "<null>";
            current = 0;
            duedate = "2015-11-20";
            focusactionID = 94;
            "manual_editing" = 1;
            name = "Drink Coffee x 5";
            percent = 0;
            "related_objective" = "<null>";
 }
```

This is the model: 
```
struct Action : Mappable {
    
    var focusactionID : String?
    var name : String?
    var current : Int?
    var amount : String?
    var percent : String?
    var duedate : String?
    var manual_editing : Bool?
    var related_objective : String?
    var color : String?
    
    init?(_ map: Map) {
        
    }
    
    mutating func mapping(map: Map) {

        amount              <- map["amount"]
        current             <- map["current"]
        focusactionID       <- map["focusactionID"]
        name                <- map["name"]
        percent             <- map["percent"]
        duedate             <- map["duedate"]
        manual_editing      <- map["manual_editing"]
        related_objective   <- map["related_objective"]
        color               <- map["color"]

    }
}
```

I know that the `amount` variable is a String which I am fine with that, it gets converted ok: `"5"` . My problem is the `current` variable for which I get the value of `nil`. Also, I cannot understand why `color` is `nil` instead of `"<null>"`

Thank you,
Andrei

**Comment by tristanhimmelman** [comment]
Sorry for the slow response... my initial guess is that there is a problem with the JSON as what you pasted above is not valid JSON.

Is this the actual server response that you are receiving?

**Comment by popaaaandrei** [comment]
Dear Tristan, 

Thank you for responding, you are too kind.
This is indeed what I am receiving from the server.


	Alamofire
	.request(router)
	.responseJSON(completionHandler: {
	                    response in
                    	print(response.result.value)
                    	...


This is the first part of the JSON. So do you think that this a malfunctioned response?

	{
	    focusactions =     (
	                {
	            amount = 5;
	            color = "#ff0077";
	            current = 0;
	            duedate = "2015-11-30";
	            focusactionID = 92;
	            "manual_editing" = 0;
	            name = "Leads x 5";
	            percent = 0;
	            "related_objective" = Prospecting;
	        },
	                {
	            amount = 2;
	            color = "#ff00e6";
	            current = 0;
	            duedate = "2015-11-30";
	            focusactionID = 93;
	            "manual_editing" = 0;
	            name = "Approach x 2";
	            percent = 0;
	            "related_objective" = Approach;
	        },
	                {
	            amount = 10;
	            color = "<null>";
	            current = 0;
	            duedate = "2015-11-30";
	            focusactionID = 97;
	            "manual_editing" = 1;
	            name = "Test ON x 10";
	            percent = 0;
	            "related_objective" = "<null>";
	        },
	                {
	            amount = 5;
	            color = "<null>";
	            current = 0;
	            duedate = "2015-12-04";
	            focusactionID = 94;
	            "manual_editing" = 1;
	            name = "Drink Coffee x 5";
	            percent = 0;
	            "related_objective" = "<null>";
	        }
	    );
	...
	}

Thank you!
Andrei

**Comment by tristanhimmelman** [comment]
Can you please post the output using this:
```
.responseString { response in
    print("Response String: \(response.result.value)")
}
```

**Comment by popaaaandrei** [comment]
Hmm... different... :(  Maybe I should try directly using this String response.
Still, I need to use SwiftyJSON for some custom validation.

	"focusactions": [
	    {
	      "focusactionID": "92",
	      "name": "Leads x 5",
	      "amount": "5",
	      "current": 0,
	      "percent": "0",
	      "duedate": "2015-11-30",
	      "manual_editing": false,
	      "related_objective": "Prospecting",
	      "color": "#ff0077"
	    },
	    {
	      "focusactionID": "93",
	      "name": "Approach x 2",
	      "amount": "2",
	      "current": 0,
	      "percent": "0",
	      "duedate": "2015-11-30",
	      "manual_editing": false,
	      "related_objective": "Approach",
	      "color": "#ff00e6"
	    },
	    {
	      "focusactionID": "97",
	      "name": "Test ON x 10",
	      "amount": "10",
	      "current": "0",
	      "percent": "0",
	      "duedate": "2015-11-30",
	      "manual_editing": true,
	      "related_objective": null,
	      "color": null
	    },
	    {
	      "focusactionID": "94",
	      "name": "Drink Coffee x 5",
	      "amount": "5",
	      "current": "0",
	      "percent": "0",
	      "duedate": "2015-12-04",
	      "manual_editing": true,
	      "related_objective": null,
	      "color": null
	    }
	  ]

**Comment by tristanhimmelman** [comment]
So what I notice is that sometimes the value for current is `"0"` and sometimes it is `0`. If it is surrounded by quotations, ObjectMapper will not be able to parse it as an Int?.

The same thing with the null value for color. Since it is `null` instead of `"null"` ObjectMapper cannot parse it as a String

**Comment by popaaaandrei** [comment]
Thank you so much for your response, I didn't see that! :8ball:
