### ISSUE TITLE
A Class(Not-Final Cannot-Change-SourceCode) Please Consider Supply some way to handle this

### ISSUE THREAD

**Issue by liuxue0905** [Hearst-DD/ObjectMapper#303]
AClass : Is a class in Some-framework library, It's not a final class, cannot modify source code
So, we cannot use extension to implement Mappable
Please Consider Supply some way to handle this

**Comment by tristanhimmelman** [comment]
I'm not sure I follow...

The `User` class is not part of the framework, it is only part of the tests for the framework. You do not need to include those in your project.

**Comment by liuxue0905** [comment]
I'm not said It's a class part of the "iOS" framework

**Comment by tristanhimmelman** [comment]
Closing this as solving #264 fix this as well.
