### ISSUE TITLE
About nested objects

### ISSUE THREAD

**Issue by hilen** [Hearst-DD/ObjectMapper#304]
If I get the following object from server like this:
```
"distance" : {
     "text" : "102 ft",
     "value" : 31
}   // It's a dictionary
```
I can get value by using `.` 

But if `distance` value is like this : 
```
"distance" : ( )  // It's an array
```

Does it work ?

**Comment by tristanhimmelman** [comment]
Nested keys also support keys like this `distance.0`, where 0 is the index within the array. Hope this helps

**Comment by hilen** [comment]
I mean if the `distance ` key has value ,the server response will be 
```
"distance" : {
     "text" : "102 ft",
     "value" : 31
}
```
But if its value is null or nil.The server response will be 
```
"distance" : ( )
```
My class mapper is `distance.text `, so how to control the same key ,but different value type ? Will it crash ?

**Comment by tristanhimmelman** [comment]
I believe the mapping will just be nil in this situation

**Comment by danielborges93** [comment]
And if I have this as a root element?
```json
{
    "type": "Some string",
    "data": [
        {
            "id": 1,
            "title": "Title1",
            "description": "Description1"
        },
        {
            "id": 2,
            "title": "Title2",
            "description": "Description2"
        }
    ]
}
```
I want only the array `data`, returning an array of:
```swift
class MyObject: Mappable {
    
    var id: Int!
    var title: String?
    var description: String?
    
    required init?(_ map: Map) {}
    
    func mapping(map: Map) {
        self.id          <- map["id"]
        self.title       <- map["title"]
        self.description <- map["description"]
    }
    
}
```
How do it? Thanks!

OBS: I am using `AlamofireObjectMapper`

**Comment by danielborges93** [comment]
Solved with this:
```swift
Alamofire.request(.GET, url, parameters: params)
    .responseArray("data") { (response: Response<[MyObject], NSError>) in

    }
```
Thanks :)
