### ISSUE TITLE
Mapping Progress

### ISSUE THREAD

**Issue by maksTheAwesome** [Hearst-DD/ObjectMapper#305]
Hi, 
At first, thank you for the mapper.

2-nd. I deal with large json objects to map. It takes 30-60 seconds to map them.

Please advise if there is any way for me to follow the progress of mapping?

**Comment by tristanhimmelman** [comment]
Hi @maksTheAwesome, unfortunately there is no functionality present to track progress. I cannot think of a simple way to incorporate that either. 

Glad you like the library :+1:
