### ISSUE TITLE
Updating objects replaces any Mappable children rather than updating them.

### ISSUE THREAD

**Issue by tapi** [Hearst-DD/ObjectMapper#306]
When using the `map(JSONString: String, toObject object: N) -> N` method to update an object with relationships to the `Mappable` entities those child objects are replaced rather than updated.
This is an issue when you rely on reference semantics to update an in memory store.

It looks as though this is because the methods
```
class func object<N: Mappable>(inout field: N, object: AnyObject?) 
class func optionalObject<N: Mappable>(inout field: N?, object: AnyObject?)
class func optionalObject<N: Mappable>(inout field: N!, object: AnyObject?)
```
methods in `FromJSON` all clobber the field property by calling `Mapper().map(object)` instead of `Mapper().map(object toObject:field)` (where appropriate)

I wrote up a test case demonstrating this issue https://gist.github.com/tapi/490f581fb9223d8832b6

It also appears to be related (tangentially) to the following two issues
https://github.com/Hearst-DD/ObjectMapper/issues/74
https://github.com/Hearst-DD/ObjectMapper/issues/230

**Comment by tristanhimmelman** [comment]
You're right, this is an issue that I never noticed. I'll think about how this could be addressed.

I have a work in progress branch which may address this issue in another fashion. The branch is called `class-clusters`. It provides the following extension to the Mappable protocol:
```
public protocol MappableCluster: Mappable {
	static func objectForMapping(map: Map) -> Mappable?
}
```

The objectForMapping function can be used to return an existing instance of an object to be used for mapping

**Comment by tristanhimmelman** [comment]
I should also note that I am considering simply replacing the `init?(_ map: Map)` requirement with the above function.

**Comment by tapi** [comment]
I was going to suggest adding an object source function. I was thinking about leaving the init and using it as a default implementation for `objectForMapping()`

Either way, if your adding it then that saves me from filing my last issue ;) needed something that allowed me to check a db

**Comment by tristanhimmelman** [comment]
I just merged a fix that handles updating children objects when mapping using the `toObject` function:
https://github.com/Hearst-DD/ObjectMapper/pull/310

This does fix does not handle arrays or dictionaries of child objects though.

**Comment by tapi** [comment]
Yeah, Not sure how you'd do it with collections, `objectForMapping()` will probably help there.

**Comment by tapi** [comment]
Dictionaries might still be okay as the keys for a value are likely sufficient to identify which object in a collection should be updated. Arrays, sets, etc that are no referenced collections are probably not something thats doable.

**Comment by tristanhimmelman** [comment]
Yep I think you're right about that

**Comment by tristanhimmelman** [comment]
I will be merging an update that handles sub dictionaries shortly. I will close this ticket up after that considering there is no safe way to handle Arrays and Sets

**Comment by tapi** [comment]
👌

**Comment by puttin** [comment]
+1 for renaming or object source
