### ISSUE TITLE
use struct for Map instead of final class

### ISSUE THREAD

**Issue by baydet** [Hearst-DD/ObjectMapper#308]
Hi there. 
Thanks for your library!

Did you think about switching to struct from final class for `Map` entity?
In my opinion `Map` should be immutable - in general it only stores JSON data and mapping direction. Moving to struct will help to avoid issues with mutability like that one:

```
let json = [
  "a" : "aa",
  "b" : "bb"
]
var a, b: String?
let map = Map(.FromJSON, json)

print(map.value())
// I expect to see value of json constant. Details in #307
a <- map["a"]
print(map.value())
// Why I see "a" here?
b <- map["b"]
print(map.value())
// Now I see "b" here. But I still expect to see value of json constant because I'm working with the same instance
```

What do you think about that?

**Comment by baydet** [comment]
Well, I've understood that in this case we have problems with toJSON mapping...

**Comment by tristanhimmelman** [comment]
I have also tried to do this, but unfortunately, given the current structure of the code, converting Map to a struct is not possible.

Like I mentioned in your pull request, perhaps exposing the JSONDictionary would solve your problem.

**Comment by baydet** [comment]
Did you think about declaring Map as protocol and create different implementations, conforming to Map, for toJSON(class) and fromJSON(struct)? 

For me it sounds like a good idea, because `fromJSON` mapping is good for structs, because it's just data. `toJSON` looks like a class because it has a lot of interactivity which requires saving a pointer to object. 

I've tried to replace class with struct roughly in my [fork](https://github.com/baydet/ObjectMapper/tree/refactor-map-to-struct). All `fromJSON` tests are passed.

**Comment by tristanhimmelman** [comment]
@baydet that is an interesting idea. I will put some more thought into it. Thanks :+1:

**Comment by baydet** [comment]
Hi, @tristanhimmelman!

I've put some thoughts in this direction. Could you have a look on it:
https://github.com/baydet/Pichi 

(Excuse me that it's not a PR but a different project that uses ObjectMapper's logic. It was hard for me to  modify ObjectMapper because in different look on core architecture)

In this project I have another look on some of ObjectMapper's concepts
- Map declared as protocol. This protocol declares operators `<->` which are doing almost the same that ObjectMapper's `<-` operators. And there are 2 implementation of this protocol:
 - `FromJSONMap` based on struct as wanted initially 
 - `ToJSONMap` based on class. 
- nested keys logic. String key is not nested by default. Nesting is provided by building tree of Map objects.
- `Mappable` protocol. I've removed `mapping` from it. In my version mapping could be declared in the independent function (for example: `func testRequestMapping<T:Map>(inout test: Test, map: T)`) It helps to decoupe model from mapping (#260, #264).

Note: It is just draft implementation of my vision of how ObjectMapper should look like. Because of that my version not includes all operators and transforms, class clusters etc.

What you think about all of this? Do you think it's a good way of ObjectMapper's evolution?
