### ISSUE TITLE
No operator overload for `<-` where T is mappable

### ISSUE THREAD

**Issue by tapi** [Hearst-DD/ObjectMapper#309]
This is useful in cases where the object relationship is not inline. 
This can happen for a number of reasons, we use it in cases where an object may show up in the response many times so we use a URI to reference that object and create a placeholder in our datastore. When we encounter the full payload we then update our placeholder.
Similar behaviour can be seen with links in [JSON API](http://jsonapi.org)

Id be happy to add this if you think its reasonable.

**Comment by tristanhimmelman** [comment]
Hey @tapi, I follow the example you are giving, but I'm not exactly sure what functionality you want to add. If you look here https://github.com/Hearst-DD/ObjectMapper/blob/master/ObjectMapper/Core/Operators.swift#L259 
there is an overload for `<-` where T is `Mappable`

**Comment by tapi** [comment]
Well crap, I completely missed the part that includes the transform.

**Comment by tristanhimmelman** [comment]
Actually... it does exist:
https://github.com/Hearst-DD/ObjectMapper/blob/master/ObjectMapper/Core/Operators.swift#L120

**Comment by tapi** [comment]
Except T does not conform to Mappable in that operator ;)

**Comment by tristanhimmelman** [comment]
Ahh I see. In that case, feel free to add and make a pull request :+1:

**Comment by tapi** [comment]
Interesting

`public func <- <T: Mappable, Transform: TransformType where Transform.Object == T>(inout left: T, right: (Map, Transform))`
and
`public func <- <T: Mappable, Transform: TransformType where Transform.Object == T>(inout left: T?, right: (Map, Transform))`
are both fine but

`public func <- <T: Mappable, Transform: TransformType where Transform.Object == T>(inout left: T!, right: (Map, Transform))`
segfaults the compiler

**Comment by tristanhimmelman** [comment]
Hmmm that is odd...

I just copy pasted those functions into the Operators file and was able to build the project without a problem.

**Comment by tapi** [comment]
What version of Xcode? Im running on 7.1.1

**Comment by tristanhimmelman** [comment]
I'm on the same version.

I do however get a seg fault with the following code due to the FromJSON line:
```
public func <- <T: Mappable, Transform: TransformType where Transform.Object == T>(inout left: T!, right: (Map, Transform)) {
	let (map, transform) = right
	if map.mappingType == MappingType.FromJSON {
		let value: T? = transform.transformFromJSON(map.currentValue)
		FromJSON.basicType(&left, object: value)
	} else {
		let value: Transform.JSON? = transform.transformToJSON(left)
		ToJSON.optionalBasicType(value, map: map)
	}
}
```
Replacing it with the following fixes the issue
```
FromJSON.optionalBasicType(&left, object: value)
```

**Comment by tapi** [comment]
huh, that seemed to do the trick. 
Its implicitly unwrapped so I wonder what kind of error that crash is obscuring.

**Comment by tapi** [comment]
There is a lot of boiler plate/repetition. It's kinda too bad non-optional values aren't automatically lifted into an `Optional<T>` type. That and the fact that `Optional<T>` and `ImplicitlyUnwrappedOptional<T>` are two different types.

**Comment by tapi** [comment]
Or maybe types *are* lifted automatically and something else is causing my compiler error when I try. Because the following totally works when I toss it in a playground.

```swift
infix operator <- { associativity left precedence 40 }

// Note we only implement the optional case
func <-<T: CustomStringConvertible>(lhs: T?, rhs: T?) -> String {
	return (lhs?.description ?? "") + (rhs?.description ?? "")
}

// Non-Optional
let one = "one"
let two = "two"

one <- two

// Optional
var three: String! = "three"
var four: String! = "four"

three <- four


// Implicitly Unwrapped Optional
var five: String! = "five"
var six: String! = "six"

five <- six

// Altogether now!
one <- two <- three <- four <- five <- six
```

**Comment by tapi** [comment]
Ahh, its because the `inout` keyword introduces side effects. When it lifts a non-optional value into an optional one it can't be sure that your not setting the lifted non-optional to `nil`.

Could still shed some weight in the operators file
Sorry for spamming you with a running commentary of my distractions @tristanhimmelman ;)

**Comment by tristanhimmelman** [comment]
I actually get some errors when I run the above code in a playground... here is the output:
```
Playground execution failed: /var/folders/4b/0j46cqdj5mbf_gt2qbdmvnl40000gn/T/./lldb/69414/playground91.swift:14:1: error: cannot convert value of type 'String' to expected argument type '_?'
one <- two
^~~
/var/folders/4b/0j46cqdj5mbf_gt2qbdmvnl40000gn/T/./lldb/69414/playground91.swift:30:1: error: cannot convert value of type 'String' to expected argument type '_?'
one <- two <- three <- four <- five <- six
^~~
```
Interestingly, the implicitly unwrapped optional does work in the custom operator.

However, if you bring the `inout` flag into the equation, the implicitly unwrapped optional will no longer work in the operator the custom operator.

**Comment by tristanhimmelman** [comment]
Ahh looks like you beat me to the bunch! lol

**Comment by tapi** [comment]
Crap yeah the  argument type error is because i forgot to add 
```swift
extension String: CustomStringConvertible {
	public var description: String { return self }
}
```

**Comment by tapi** [comment]
And with both defined it definitely uses the non optional overload which is not awesome.

**Comment by tapi** [comment]
So I'm looking at implementing `<-(lhs: Mappable, rhs:(Map, Transform)` for Dictionaries, Arrays & Sets.
It feels like theres some potential ambiguity. For example, for dictionaries, Does it take `map.currentValue` as is and expect a dictionary back? or does it assume `map.currentValue` is a dictionary of objects that the transform should run on.

**Comment by tristanhimmelman** [comment]
I'm not 100% sure I follow the question... but I think the answer is the later. ObjectMapper in general assumes that `map.currentValue` will be of the expected JSON format

**Comment by tapi** [comment]
Thats kind of what I thought. Just felt like maybe there was a use case it excluded.

**Comment by tristanhimmelman** [comment]
Closing this off as your PR is merged. Thanks again.

**Comment by tapi** [comment]
👍🏻
