### ISSUE TITLE
DateTransform using timestamp in miliseconds

### ISSUE THREAD

**Issue by borut-t** [Hearst-DD/ObjectMapper#315]
I have an issue using DateTransform becase iOS treats NSTimeInterval in seconds.
But I get timestamp from rest api in miliseconds.

What is the best way to achieve this? Subclassing DateTransform or is there anything else, maybe more elegant?

Thanks!

**Comment by baydet** [comment]
You can create your custom DateTransform kind of like that
```
class MilisecondDateTransform: TransformType {
    typealias Object = NSDate
    typealias JSON = Int

    init() {}

    func transformFromJSON(value: AnyObject?) -> NSDate? {
        if let timeInt = value as? Int {
            return NSDate(timeIntervalSince1970: NSTimeInterval(timeInt/1000))
        }
        return nil
    }

    func transformToJSON(value: NSDate?) -> Int? {
        if let date = value {
            return Int(date.timeIntervalSince1970 * 1000)
        }
        return nil
    }
}
```

**Comment by borut-t** [comment]
Yep, I've just done this.

**Comment by leondobnik** [comment]
Guys just one thing: the code displayed above has a bug for old devices. While 64bit devices can represent timestamp as Int, 32bit devices cannot and date is not parsed correctly (applies to iPhone5 and iPhone4) and other similar devices. So more secure code may be:

typealias JSON = Double

    func transformFromJSON(value: AnyObject?) -> NSDate? {
        if let timeInt = value as? Double {
            return NSDate(timeIntervalSince1970: NSTimeInterval(timeInt/1000.0))
        }
        return nil
    }

    func transformToJSON(value: NSDate?) -> Double? {
        if let date = value {
            return Double(date.timeIntervalSince1970 * 1000.0)
        }
        return nil
    }

**Comment by hajducak** [comment]
Hi guys, for switf 4 and Xvode 9.0 new version:

```
import ObjectMapper

class MilisecondDateTransform: TransformType {
    typealias Object = NSDate
    typealias JSON = Double
    
    init() {}
    
    func transformFromJSON(_ value: Any?) -> NSDate? {
        if let timeInt = value as? Double {
            return NSDate(timeIntervalSince1970: TimeInterval(timeInt/1000.0))
        }
        return nil
    }
    
    func transformToJSON(_ value: NSDate?) -> Double? {
        if let date = value {
            return Double(date.timeIntervalSince1970 * 1000.0)
        }
        return nil
    }
}
```
