### ISSUE TITLE
Collection of Enum Types

### ISSUE THREAD

**Issue by FrancisBaileyH** [Hearst-DD/ObjectMapper#320]
I have an array of Enum Types and I've attempted to create my own transform type however that appears to be for converting single values. In this case I'd like to convert an array of RawRepresentable types.

Currently you can do the following:

example.json

    [
       {
          "resource-type": [ "document", "media", "script"]
       }
    ]

Now if I had an array in Swift like so:

    var resourceType: [String]?

... in func mapping

    resourceType <- map["resourceType"]

It automatically converts it to a JSON array like the one in the example.json file. 

So, if I had an array of RawRepresentable types:

    var resourceType: [MyExampleEnum]?

Is it possible to have it replicate behaviour of an array of Strings, using EnumTransform or some other method?

**Comment by tristanhimmelman** [comment]
Yes, this behaviour should already be working. As long as your enum strings match the strings in the resource-type array. 
ex:
```
enum EnumType: String {
		case document = "document"
		case media = "media"
	}
```
Then you can map just as you do regularly using 
``` resourceType <- map["resource-type"]```

**Comment by FrancisBaileyH** [comment]
Hi @tristanhimmelman, thanks for the quick reply and excellent library. However, I'm running into an issue using that implementation. I can map an object to JSON, with  enum array type set to nil, no problem. In the JSON the value doesn't show up, as expected. However if I map from JSON to the object, then the array of enum types are set to an empty array as opposed to nil. Despite the values being mapped from not being present. 

I have an example project to show you what I mean:
https://github.com/FrancisBaileyH/ObjectMapperTestApp

I'm not sure if this is a bug or something that I'm doing wrong, but your help is appreciated either way.
