### ISSUE TITLE
Best way to copy an object to another?

### ISSUE THREAD

**Issue by allaire** [Hearst-DD/ObjectMapper#321]
Hi,

I'm creating an edit modal where I need a "scratch pad" instance, so if the user press cancel, all edit is dismissed.

Currently, I'm creating a copy of my passed ObjectMapper model like this:

`leaveRequest = Mapper<LeaveRequest>().map(Mapper().toJSON(leaveRequest))!`

Is there a better way to do an object copy?

Thanks!

**Comment by tristanhimmelman** [comment]
I think this approach is fine. Otherwise you can look into implementing `NSCopying`, however that will likely create a lot more boilerplate code. I can't speak to the performance NSCopying vs ObjectMapper though...

Cheers,
Tristan
