### ISSUE TITLE
Not support ' TransformOf< [T], [ Dictionary<String, AnyObject> ]> '

### ISSUE THREAD

**Issue by shiyizju** [Hearst-DD/ObjectMapper#322]
After debugging, I found in ToJson.swift, line 97: 

 " } else if let x = field as? Array< AnyObject > { " , 

this condition failed as AnyObject is not subtype of Dictionary<String, AnyObject>.

This may not be a issue, but it's not obvious enough, maybe we can add some hint like assertion in the code? :)

**Comment by tristanhimmelman** [comment]
Can you paste the model you are trying to map here to give me a better idea of the problem?

Thanks

**Comment by shiyizju** [comment]
I have a model which implement 'Mappable' protocol, while inside this mode, I have an array of objects whose type is, say A. which doesn't confirm to 'Mappable'. So I use 'TransformOf' to transform my array of A, to an array of Dictionary< String, AnyObject >.

The code in mapping func of the model looks like
       ....
       myArray <- ( map["myArray"], MyTransform< [A], [ [String: AnyObject] ] > )

The issue is that above code does't work, I have to change it to
       ....
       myArray <- ( map["myArray"], MyTransform< [A], [ AnyObject ] > )

Thanks.

**Comment by tristanhimmelman** [comment]
I've added a new case in the ToJSON file which should hopefully fix your problem. Please get the latest from master
