### ISSUE TITLE
Int and String Enum Types

### ISSUE THREAD

**Issue by hilen** [Hearst-DD/ObjectMapper#326]
Hi, if server response JSON is like this, the filed type return as String, not a Int.
```
{
   "gender_type":"1",
   "name":"Hilen"
}
```
But my model want the filed "gender_type" is Enum,  1 is female , 2 is male.
So how to control it except write a custom transformer?

**Comment by tristanhimmelman** [comment]
ObjectMapper should be able to handle this if you create an Enum like the following: 
```
enum Gender: String {
	case Female = "1"
	case Male = "2"
}
```
