### ISSUE TITLE
Decoupling json into multiple objects

### ISSUE THREAD

**Issue by piresbruno** [Hearst-DD/ObjectMapper#327]
Is it possible, from the same json object hierarchy, create map where one object is a property type in the other?
This is a simplistic approach to demonstrate my problem:

#### Json example
```
{
	"id" : "ewgerngortqerw_ret?$njbsd",
	"name" : "test_user",
	"email" : "xpto@xpto.com",
	"promotional_code" : "AHFJKLMNFDLKJ500",
	"promotional_value" : 350
} 
```
  
I want to map three properties of the json response into an User object, and the remaining two properties to a child User object property, called userPromotions, of type Promotion

```
class Promotion: Mappable {
    var value:String?
    var code:String?
    
    required init?(_ map:Map){}
    
    func mapping(map: Map) {
        value   <- map["promotional_value"]
        code    <- map["promotional_code"]
    }
}

class User: Mappable {
    var id:String?
    var name:String?
    var email:String?
    var userPromotions:Promotion?
    
    required init?(_ map:Map){}
    
    func mapping(map: Map) {
        id      <- map["id"]
        name    <- map["name"]
        email   <- map["email"]
        
        // how to handle this??
        userPromotions <- map["????"]
    }
}
```

Is this possible with ObjectMapper?

**Comment by tristanhimmelman** [comment]
You can do something like the following:
```
func mapping(map: Map){
    userPromotion = Promotion(map: map)
    userPromotion.mapping(map: map)
}
```

**Comment by piresbruno** [comment]
Thanks @tristanhimmelman.
Didn't saw that use case in the documentation, is it there?

**Comment by tristanhimmelman** [comment]
No it's not in the documentation at the moment...

**Comment by piresbruno** [comment]
Again, thanks for the help!

**Comment by tristanhimmelman** [comment]
No problem!

**Comment by piresbruno** [comment]
@tristanhimmelman regarding this issue, is this any way to serialize the User object with the userPromotions properties?
I've tried regular toJson() in the user object, but the userPromotions doesn't get serialized.

**Comment by tristanhimmelman** [comment]
Since what you are doing above is not the standard usage of ObjectMapper the toJSON doesn't work as it should.

You can probably get it to work by doing the following
```
func mapping(map: Map){
    if map.mappingType == .FromJSON {
        userPromotion = Promotion(map: map)
        userPromotion.mapping(map: map)
    } else {
        userPromotion <- map["promotion"]
    }
}
```
However this won't produce the same formate as the JSON you are receiving originally... it will add the userPromotion JSON as a sub object of the User JSON

**Comment by piresbruno** [comment]
Thanks for your help @tristanhimmelman
