### ISSUE TITLE
Expose Mapper.swift private JSON parsing utility methods

### ISSUE THREAD

**Issue by levieggert** [Hearst-DD/ObjectMapper#329]
Hey I was wondering if you could make the following methods Static in Mapper so we could access the JSON parsing utilities?

private func parseJSONDictionary(JSON: String) -> [String : AnyObject]? 
private func parseJSONDictionary(JSON: AnyObject?) -> [String : AnyObject]? 
private func parseJSONString(JSON: String) -> AnyObject?

I created an EntityMapper Class that handles creating new Mappable NSManagedObject's and would like to utilize your JSON parsing utils.

**Comment by tristanhimmelman** [comment]
I'm okay with making those functions public. Would you have the time to create a Pull Request with the change? (I'm crazy busy at the moment)

**Comment by levieggert** [comment]
Yep just created.
