### ISSUE TITLE
Consider providing a way to check if the key exists

### ISSUE THREAD

**Issue by grnbeagle** [Hearst-DD/ObjectMapper#333]
I want to throw this question out here and see if there's a way to do this right now, and if not, if this is a use case worth supporting.

Is it possible to check whether the key exists before assigning to the property?

```
// Current usage:
tracks <- map["tracks"]

// Proposed usage:
if map.hasKey("tracks") {
  tracks <- map["tracks"]
}
```

This is helpful if we don't want to overwrite properties of objects that are previously populated and stored in an object cache.

**Comment by raulagrait** [comment]
Agreed, this would be fantastic.

**Comment by levieggert** [comment]
Yeah that would be great.  I need to map values for keys that exist so I don't override any values with nil.

**Comment by tristanhimmelman** [comment]
You can actually already check for the existence of a key as follows:
```
if map["tracks"].currentValue != nil {

}
```

A `hasKey` function could make this a bit clearer though. I will consider adding it

**Comment by levieggert** [comment]
Ok great!

Is it possible to include a subscript that will only map if the key exists?

That way there is no need to add if conditionals.  

This may not be possible, I am unfamiliar with using subscripts. But, my thought would be something like this.

name <- map["name", mapFlag: Map.OnlyIfKeyExists]

Could include other flags for mapping.

**Comment by grnbeagle** [comment]
@levieggert: it turns out it's designed to map only if the key exists. However, a property of optional Mappable object array was not behaving that way, so the pull request above fixed that. 
Thanks for merging so promptly, @tristanhimmelman.

**Comment by levieggert** [comment]
Ok I see.  Thanks for the update!
