### ISSUE TITLE
How to save mappable object to nsuserdefault??

### ISSUE THREAD

**Issue by ArsalanReal** [Hearst-DD/ObjectMapper#334]
Please share any sample class, i want to save custom whole object to NSUserDefault.

**Comment by tristanhimmelman** [comment]
The easiest way I can think of would be to convert the object to a String using the toJSON function. Then save that String into the user defaults. When you retrieve the string you use ObjectMapper to convert it back to an object

**Comment by ArsalanReal** [comment]
Thanks a lot guru
