### ISSUE TITLE
Subclasses and json arrays

### ISSUE THREAD

**Issue by piresbruno** [Hearst-DD/ObjectMapper#335]
Hi,

Above i present a simplified version of my problem.

I have a base class, called Payment, from witch i create a few more subclasses.
In my api call, i get an array of payment types, witch i intend to map to the different subclasses, based on the payment type.

Given that using something like *Mapper<Payment>.mapArray(json)* will map all the objects on the array to the base class, i was wondering if ObjectMapper has this kind of scenario taken into consideration, and if t's possible to map a json array to multiple subclasses from the same base class.

```
public enum PaymentType{
    case
    Money,
    Electronic,
    PayPal
}

class Payment{
	var token:String?
	var type:PaymentType? = .Money
}

class PaymentElectronic: Payment{
	// card type [Visa, MasterCard, Amex]
	var card:CardType?
	var lastDigits:String?
}

class PaymentCorporate: Payment{
    var logoUrl:NSURL?
    var name:String?
}
```

```
{
  "payment_methods": [
    {
      "token": "clfdjhsdgwldfkgl&fd890gdfs8lk",
      "type": "corporate",
      "logo": "https:\/\/default.com\/assets\/img\/logo.png",
      "name": "CompanyName"
    },
    {
      "token": "clfdjhsdgwldfkgl&fd890gdfs8lk",
      "last_digits": "1111",
      "card_type": "visa",
      "type": "Electronic"
    }
  ]
}
```

**Comment by tristanhimmelman** [comment]
Hi there,

If you use the master version of ObjectMapper there is new functionality that supports class clusters (essentially the situation you are describing above). See the test class below for an example:
https://github.com/Hearst-DD/ObjectMapper/blob/master/ObjectMapperTests/ClassClusterTests.swift

Hope this helps

**Comment by piresbruno** [comment]
Thanks @tristanhimmelman, this is really what i need.
