### ISSUE TITLE
[Parse support] parse both String or Int for 1 variable 

### ISSUE THREAD

**Issue by hoangtuanfithou** [Hearst-DD/ObjectMapper#337]
@tristanhimmelman 
@anyone
Current I did:

```swift
class BaseModel: Mappable {
var created_at: Int?
}

func mapping(map: Map) {
  created_at <- (map["created_at"], TransformOf<Int, String>(fromJSON: { $0 == nil ? nil : Int($0!) }, toJSON: { $0.map { String($0) } }))
or  normal way :
  created_at <- map["created_at"]
}
```
server return : created_at ＝ 1430387340

How to do like this :
- server can return 
+ created_at ＝ 1430387340 (mean Int)
+ created_at ＝ "1430387340" (mean String)
But created_at still can parse well ?

Thanks

**Comment by tristanhimmelman** [comment]
I think this should work:
```
func mapping(map: Map) {
    created_at <- (map["created_at"], TransformOf<Int, String>(fromJSON: { $0 == nil ? nil : Int($0!) }, toJSON: { $0.map { String($0) } }))
    if created_at == nil {
        created_at <- map["created_at"]
    }
}
```

**Comment by hoangtuanfithou** [comment]
@tristanhimmelman: It is super simple that I do not think about. Thanks. I think it will work.
In the fact I tried to make a custom transform of ( your protocol Tranform type -> and it worked, but your suggestion is much simple)

- anyway, just small question: should I define TranformOf using let ( as constant ) for reuse later, because I have some others like create_at.
- and if i use TranformOf many where when parse , how much It will slow down, can you get :) (2x time or 3x time...) ( just not important question)
- thanks for your support.

**Comment by tristanhimmelman** [comment]
1. If you use the Transform many times, then it is not a bad idea to define it using let, however it shouldn't make a big difference either way.
2. There should be very little if any performance impact when using the TransformOf you included above. It could slow down depending on what you do in the Transform however.
3. Glad to help :)

**Comment by hoangtuanfithou** [comment]
Thanks, and have nice weekend.
Last question :
It is great we can avoid mapping function for every model that Mappable.
- If variable name is the same with json key. -> do have to write on mapping function a_name <- a_name
- Or the it can auto mapping with Camel style support ( like Jsonmodel or something ) aName <- a_name

Maybe it was mentioned by other people, on other issues, I just mention again:)

Thanks.

**Comment by tristanhimmelman** [comment]
Unfortunately ObjectMapper cannot support automatic mappings based on variable names due to it's compile time nature

**Comment by hoangtuanfithou** [comment]
>Unfortunately ObjectMapper cannot support automatic mappings based on variable names due to it's compile time nature
@tristanhimmelman yes, I think I read it somewhere before, (maybe others explain). But no problem. Still using it in my current project, and still loving it.
Thanks you and have nice Sat, nice Christmas soon.:beers: 
Bye bye.
