### ISSUE TITLE
Mapping from JSON to object with optional array of enumerations results in empty array value being set, instead of nil.

### ISSUE THREAD

**Issue by FrancisBaileyH** [Hearst-DD/ObjectMapper#339]
I can map an object to JSON with an optional array of enums type set to nil, no problem. In the JSON the value doesn't show up, as expected. However if I map from JSON, where the property to be converted is absent, then the array of enum types are set to an empty array as opposed to nil. Despite the values being mapped from, not being present.

I have an example project to show you what I mean:
https://github.com/FrancisBaileyH/ObjectMapperTestApp

I'm not sure if this is a bug or something that I'm doing wrong, but your help is appreciated either way.

**Comment by tristanhimmelman** [comment]
Hi @FrancisBaileyH, sorry for the slow response. I finally got a chance to test out your example project. It turns out that this issue has been fixed in subsequent releases of ObjectMapper. Please use anything after v1.1

**Comment by FrancisBaileyH** [comment]
Hi @tristanhimmelman thanks for the update!
