### ISSUE TITLE
Realm models that have a primary key seem to crash when mapped to JSON

### ISSUE THREAD

**Issue by bennichols** [Hearst-DD/ObjectMapper#340]
I'm trying to integrate my ObjectMapper codebase (which I love!) with Realm, and I'm having a really hard time getting it to work with even the most simple setup. I have a class that just has a string "id" that I'm telling Realm is the primary key. When I call Mapper().toJSONString() on it, I get a crash: "Terminating app due to uncaught exception 'RLMException', reason: 'Primary key can't be changed after an object is inserted.'" If I remove the primary key, the crash goes away and behaves as intended, but I don't see the point of using a database like Realm if I can't use primary keys.

```swift

class IronObject: Object, Mappable {
    dynamic var id: String? = ""

    override static func primaryKey() -> String? {
        return "id"
    }
    
    convenience init(id: String) {
        self.init()
        self.id = id
    }
    
    convenience required init?(_ map: Map) {
        self.init()
        mapping(map)
    }

    func mapping(map: Map) {
        id              <- map["id"]
    }
}

let i = IronObject(id: "12345")
let realm = try! Realm()
try! realm.write {
    realm.add(i)
    print(Mapper().toJSONString(i))
}
```

**Comment by tristanhimmelman** [comment]
I think you may need to put an if clause around the primary key so that it is only set once:
```
if id == nil {
    id <- map["id"]
}
```
The ObjectMapper operator `<-` has an `inout` flag on the left hand side variable. This is only necessary when mapping data from JSON. However since the `<-` operator is also used for writing JSON, Realm assumes that the values are being modified when `toJSONString` is called.

**Comment by bennichols** [comment]
Ok, that appears to work. Thanks Tristan!

**Comment by j2damax** [comment]
when checking below condition toJsonString omit the id in json string, any solution for that?

if id == nil {
    id <- map["id"]
}

**Comment by tristanhimmelman** [comment]
I think this might work:
```
if map.mappingType == .ToJSON || id == nil {
    id <- map["id"]
}
```

**Comment by j2damax** [comment]
Hi thanks for the reply, but when do this still same issue when trying to convert object into json, it says 'RLMException', reason: 'Primary key can't be changed after an object is inserted.'

What i need is when trying to convert ToJson id should be included in json string.

**Comment by tristanhimmelman** [comment]
I think you may need to store the primaryKey in another variable that is not used directly in the mapping.
```
id <- map["id"]
if primaryKey == nil {
    primaryKey = id
}
```

**Comment by ivanruizscm** [comment]
theres ir a better solution other than cheking if its not set?

**Comment by ivanruizscm** [comment]
Its weird, plus i need the primary key in the json

**Comment by ivanruizscm** [comment]
@tristanhimmelman

**Comment by tristanhimmelman** [comment]
@ivanruizscm, I have never really used Realm with ObjectMapper so I'm not sure if there is a better solution. Perhaps you can just map the primary key to a different variable and set the real primary key variable once during the first mapping?

**Comment by thacilima** [comment]
@ivanruizscm I also need the primary key in the json and I did like this:

```
if map.mappingType == .ToJSON {
    var id = self.id
    id <- map["id"]
}
else {
    id <- map["id"]
}
```

'id' is the realm object primary key. It worked!

**Comment by pvsilvestrin** [comment]
It works like a charm, thanks @thacilima

**Comment by vitovalov** [comment]
Thanks for the workarounds,
However on Swift 4 it gives me this compile error: 
`Binary operator '==' cannot be applied to operands of type 'MappingType' and '_'`
And I'm using pod branch *swift-4*
cc @thacilima

**Comment by rafaelkgobara** [comment]
@vitovalov 

For Swift 4, use:

if map.mappingType == .toJSON

**Comment by kkizlaitis** [comment]
For those also wondering, I have come up with a _slightly_ more elegant solution:

    switch map.mappingType {
        case .fromJSON:
            id <- map["id"]
        case .toJSON:
            id >>> map["id"]
    }
Here `id` is the _primaryKey_ in _Realm_.
