### ISSUE TITLE
Converting a Model to JSON String Not working

### ISSUE THREAD

**Issue by itsaboutcode** [Hearst-DD/ObjectMapper#341]
When I try to convert a model object to a JSON string:

     let JSONString = Mapper().toJSONString(user, prettyPrint: true)

I get the following error

    Cannot invoke 'toJSONString' with an argument list of type

**Comment by tristanhimmelman** [comment]
This should work if your user object implements the `Mappable` protocol. Please see the test classes in ObjectMapper if you need example code to help you out.

**Comment by itsaboutcode** [comment]
It don't work on following case

    let user = Mapper<User>().map(JSONString)
    let JSONString = Mapper().toJSONString(user, prettyPrint: true)

But it work if I do this.

    let user = Mapper<User>().map(JSONString)
    let theUser = User()
    theUser.name = user.name
    let JSONString = Mapper().toJSONString(user, prettyPrint: true)

**Comment by ikesyo** [comment]
This is because:

- `Mapper<User>().map(JSONString)` returns `User?`
- `Mapper().toJSONString` expects `User`, not `User?`
- So the following should work:

    ```swift
    let user = Mapper<User>().map(JSONString)
    if let user = user {
        let JSONString = Mapper().toJSONString(user, prettyPrint: true)
    }
    ```

**Comment by chanonly123** [comment]
let jsonString = Mapper().toJSONString(["id1", "id2", "id3"]) not working!
