### ISSUE TITLE
Allow public access to Mapper.toJSONString(object: AnyObject)

### ISSUE THREAD

**Issue by aventurella** [Hearst-DD/ObjectMapper#346]
currently located here (1.0.1):
https://github.com/Hearst-DD/ObjectMapper/blob/1.0.1/ObjectMapper/Core/Mapper.swift#L316

Is there any reason to keep this hidden? It's a nice encapsulation on `NSJSONSerialization`. In my use case I have a Realm Model. Since the toJSON on a Realm object is less than ideal, I just get a a dictionary back from the Realm Object. Anyway, I'm already using ObjectMapper, so once I have that dictionary back from the RealmObject I have to either

1. Write my own implementation of your function that is exposed to my application, effectively duplicating it
2. Follow the conversion all the way though: Realm -> Dictionary -> ObjectMapper Perform Mapping -> JSON which is silly to do.

**Comment by tristanhimmelman** [comment]
There is no reason to have it hidden other than keeping a simple interface. 

I've decided to go ahead and make the change you suggested. On master the `toJSONString` function is now `public static`

Thanks
