### ISSUE TITLE
Auto Create Objects based on given JSON

### ISSUE THREAD

**Issue by parthisubu** [Hearst-DD/ObjectMapper#351]
It would be super cool and a wonderful timesaver to have an utility that can convert a given JSON to objects and relevant mappers :) similar to http://www.jsonschema2pojo.org/ that does it for JAVA 

Thanks for all your work, appreciate it.

Parthi

**Comment by tristanhimmelman** [comment]
Cool idea. I don't think I will have time to build such a utility but I would welcome it if someone else built it.

**Comment by amolgupta** [comment]
I wrote a script for this and put some basic UI to it. see http://parse-amol.rhcloud.com/

If people find it useful, I can take up change requests and host properly.

**Comment by tristanhimmelman** [comment]
Very cool @amolgupta. I haven't had a chance to test it out yet but I think this could be a pretty useful utility.

**Comment by PhilCai1993** [comment]
how about this: https://gist.github.com/PhilCai1993/5821a168cd3ea11168f2 
Just look at the bottom line.

**Comment by karnakar** [comment]
Try JSONExport [https://github.com/Ahmed-Ali/JSONExport] which is available in different languages.

**Comment by Ashu** [comment]
Try [SwiftyJSONAccelerator](https://github.com/insanoid/SwiftyJSONAccelerator)

**Comment by amolgupta** [comment]
[https://github.com/Ahmed-Ali/JSONExport] is a neat tool. I have added Swift-3 support in my branch and opened a pull request[https://github.com/amolgupta/JSONExport].

**Comment by tobiasoleary** [comment]
Maybe just add a link to JSONExport in the README?

**Comment by tristanhimmelman** [comment]
After some more thought, I don't think including model generation is in the scope of this project. 

But I do agree with @tobiasoleary. I am happy to accept PRs with links to model generating projects in the Readme.
