### ISSUE TITLE
 Non numeric value from json is failing for numeric model's property .

### ISSUE THREAD

**Issue by NiteshKumar-webonise** [Hearst-DD/ObjectMapper#352]
class User: Mappable {
    var userName: String = ""
    var identifier: String?
    var photoCount: Int = 0  // what if i get some string value from json which is not convertible to integer value.
    var age: Int?
--------------------
I am facing crash at 
let user = userMapper.map(userJSONString)!

It would be great if I can trace which is the key in json for which it's crashing.

**Comment by paradoxally** [comment]
Create your user like this instead:

`let user : User? = userMapper.map(userJSONString)`

You should never assume that JSON string will be valid, i.e. don't force it to create a `User` object. If it's not valid, `user` will be `nil`. 

A simple check like this will solve that issue (you can use `if` instead if you don't want to handle the case where user is `nil`):

```swift
guard let _ = user else {
     // handle invalid user here
}
```

`user` will be printed out, so you can see what failed. Alternatively, print out your userJSONString or set a breakpoint at that line and inspect the variables with the debugger.

Hope this helps.

**Comment by tristanhimmelman** [comment]
Thanks @paradoxally

**Comment by NiteshKumar-webonise** [comment]
Thanks for reply :)
I will take care of it.
but still if i get nil user how to check where is the problem, which property type we need to change as per json response ?
