### ISSUE TITLE
Unexpected output when accessing arrays

### ISSUE THREAD

**Issue by mamouneyya** [Hearst-DD/ObjectMapper#354]
Using this data source: http://ax.itunes.apple.com/WebObjects/MZStoreServices.woa/ws/RSS/topsongs/limit=30/json

I am trying to access im:image.0.label in song object, however I get the full im:image array instead.

**My code (simplified):**

    class Song: Root {
        // MARK: - Vars        
        var test: AnyObject?
        
        // MARK: - Methods
        required init?(_ map: Map) {
            super.init(map) 
            mapping(map)
        }
        
        override func mapping(map: Map) {
            super.mapping(map)
            test <- map["im:image.0.label"]
        }
    }

**Expected value for 'test' is something like:**
```
"http://is2.mzstatic.com/image/thumb/Music6/v4/49/05/0a/49050af2-82dd-1a7c-547d-c7fda91ba271/886445568219.jpg/55x55bb-85.jpg"
```

**However, current value:**
```
Printing description of [0].test:
        Optional((
            {
                attributes =         {
                    height = 55;
                };
                label = "http://is2.mzstatic.com/image/thumb/Music6/v4/49/05/0a/49050af2-82dd-1a7c-547d-c7fda91ba271/886445568219.jpg/55x55bb-85.jpg";
            },
            {
                attributes =         {
                    height = 60;
                };
                label = "http://is3.mzstatic.com/image/thumb/Music6/v4/49/05/0a/49050af2-82dd-1a7c-547d-c7fda91ba271/886445568219.jpg/60x60bb-85.jpg";
            },
            {
                attributes =         {
                    height = 170;
                };
                label = "http://is1.mzstatic.com/image/thumb/Music6/v4/49/05/0a/49050af2-82dd-1a7c-547d-c7fda91ba271/886445568219.jpg/170x170bb-85.jpg";
            }
        ))
```

**Comment by mamouneyya** [comment]
P.S. `im:image.0` also returns the full array. :confounded:

**Comment by tristanhimmelman** [comment]
Which version of ObjectMapper are you using? Please trying using the master version as it has fixes for this.

**Comment by mamouneyya** [comment]
You're awesome. :smiley: 

Just tried it, and I can confirm that it's really fixed. So, when will you be releasing the next version to CocoaPods, cause I really don't prefer to directly embed the library. :grin: 

Thanks man!

**Comment by tristanhimmelman** [comment]
No problem, glad I could help! 

I've been meaning to make a release for a while. I will try to get one out in the next few days

**Comment by tristanhimmelman** [comment]
I ended up making a new release just now. You can go ahead and use v 1.1 using cocoapods

**Comment by mamouneyya** [comment]
Awesome. Really thanks man!
