### ISSUE TITLE
Explain purpose of `init?(_ map: Map)` in README

### ISSUE THREAD

**Issue by raphaeloliveira** [Hearst-DD/ObjectMapper#357]
Hi, I'm struggling to understand what is the purpose of the method `init?(_ map: Map)` declared on `Mappable`. All examples on [README](https://github.com/Hearst-DD/ObjectMapper/blob/master/README.md) have an empty implementation. Can you please clarify?

**Comment by tristanhimmelman** [comment]
The init method is necessary so that ObjectMapper can create an instance of the object it is trying to map. It also allows you to do some validation before mapping. If a certain key that you need doesn't exist you can return `nil` from `init?(_ map: Map)` and the mapping will not happen.

**Comment by werediver** [comment]
This should definitely be noted in the documentation (`README.md`)!

**Comment by eoinoconnell** [comment]
Out of interest why is there an init and a mapping function? Can the failable initialiser not be used for both purposes?

**Comment by tristanhimmelman** [comment]
@eoinoconnell The mapping could technically occur within the init function, but if we took that approach we would lose the ability write JSON and to map JSON to an existing object.

**Comment by eoinoconnell** [comment]
OK cool, valid point. Thanks!

**Comment by tristanhimmelman** [comment]
The readme has now been updated with the information above
