### ISSUE TITLE
ObjectMapper + CoreData ????????

### ISSUE THREAD

**Issue by returnight** [Hearst-DD/ObjectMapper#359]
can not use ObjectMapper + CoreData ?????  like this 

class Model: NSManagedObject, Mappable {
    @NSManaged var name = ""

    required convenience init?(_ map: Map) {
        self.init()
    }

    func mapping(map: Map) {
        name <- map["name"]
    }
}

when I use above, crashed with -[app.Model name]: unrecognized selector sent to instance 0x7fa5c360ff40

**Comment by tristanhimmelman** [comment]
Sorry I do not use CoreData much so cannot be of much help with this... are you still having the problem?

**Comment by returnight** [comment]
YES, but i will use realm instead CoreData, because CoreData has no porpule framework with swift
