### ISSUE TITLE
Build failed on iPhone 5

### ISSUE THREAD

**Issue by Dohko** [Hearst-DD/ObjectMapper#36]
Hi,

I want to use ObjectMapper in my project but i have a build failed when i compile it on iPhone 5 (but it compiles on iPhone 5S and higher).

Here are the issue logs:
Swift compiler error
Use of undeclared type 'Mapper'
Swift compiler error
Use of undeclared type 'MapperProtocol'

Regards,
Dohko

**Comment by Dohko** [comment]
Hi,

It's fixed now. I forgot to add ObjectMapper into my dependencies.

Regards,
Dohko

**Comment by tristanhimmelman** [comment]
Glad you sorted it out!
