### ISSUE TITLE
Is there a way convert string into int?

### ISSUE THREAD

**Issue by cuzv** [Hearst-DD/ObjectMapper#360]
Here is the problem:
Sever response field declared to `Int`, which is should be like this:
```
{
 "id": 12345
}
```
But really response is:
```
{
 "id": "12345"
}
```
So, the converted object's property value will be incorrect.
Is there any way to solve this problem? Thanks.

**Comment by tristanhimmelman** [comment]
See the following:
https://github.com/Hearst-DD/ObjectMapper/issues/337
