### ISSUE TITLE
I got stuck with error handling with Alamofire

### ISSUE THREAD

**Issue by macbaszii** [Hearst-DD/ObjectMapper#361]
I have used this https://github.com/tristanhimmelman/AlamofireObjectMapper

```swift
    func signalForCreateTribe(form: TribeCreationForm) -> SignalProducer<Tribe, NSError> {
    return SignalProducer({ observer, disposable in
        let request = self.manager.request(Router.CreateTribe(form: form))
                .responseObject({ (response: Response<Tribe, NSError>) -> Void in
                    switch response.result {
                    case .Success(let tribe):
                        observer.sendNext(tribe)
                        observer.sendCompleted()
                    case .Failure(let error):
                        observer.sendFailed(error)
                    }
                })
        
            disposable.addDisposable({ () -> () in
                request.cancel()
            })
        })
    }
```

and when server sent me a 404 (anything not 200..<299)
'Success' case was called with I got empty object instead of 'Failure' with error from server

How can I get real error from server ?
Thanks in advance.

I have tried to call validate() before responseObject(), 
but it's return only error with status code not error object from my server.

**Comment by tristanhimmelman** [comment]
I think this issue may have to do with Alamofire more than ObjectMapper or AlamofireObjectMapper.

Did you test this with the regular Alamofire `.response` function?
