### ISSUE TITLE
Handling Realm List<T>

### ISSUE THREAD

**Issue by kbpontius** [Hearst-DD/ObjectMapper#362]
I'm trying to use the Realm List<T>, but I'm not sure syntactically how to accomplish this or if it's even possible. The object would be something that looks like this (from Realm's website: https://realm.io/docs/swift/latest/#models). Thank you in advance:

```
// Dog model
class Dog: Object {
    dynamic var name = ""
    dynamic var owner: Person? // Properties can be optional
}

// Person model
class Person: Object {
    dynamic var name = ""
    dynamic var birthdate = NSDate(timeIntervalSince1970: 1)
    let dogs = List<Dog>()
}
```

From the tests I'm running, which are very similar to the above code, it's not deserializing the JSON properly, into the different objects in the List<T>.

**Comment by tristanhimmelman** [comment]
Please see this issue https://github.com/Hearst-DD/ObjectMapper/issues/143
