### ISSUE TITLE
No support Realm List model?

### ISSUE THREAD

**Issue by Au12th0psav** [Hearst-DD/ObjectMapper#365]
I user Realm in my model，e.g. var totalList = List<MFTimelineCommentObject>() is error。What should I do?
public class MFTimelineContentObject: Object, Mappable {
    dynamic var totalCount = 0
   // Error
    var totalList = List<MFTimelineCommentObject>()
    
    public required convenience init?(_ map: Map) {
        self.init()
    }
    
    public func mapping(map: Map) {
        totalCount <- map["total"]
        totalList <- map["list"]
    }
}

public class MFTimelineCommentObject: Object, Mappable {
    dynamic var commentAt = ""
    dynamic var publisherID = ""
    dynamic var contentID = ""
    dynamic var content = ""
    dynamic var commentID = ""
    dynamic var replyerID = ""
    dynamic var replyToUserID = ""
    dynamic var replyToUserName = ""
    dynamic var userID = ""
    dynamic var userName = ""
    
    public required convenience init?(_ map: Map) {
        self.init()
    }
    
    public func mapping(map: Map) {
        commentAt <- map["add_time"]
        publisherID <- map["bus_id"]
        contentID <- map["con_id"]
        content <- map["content"]
        commentID <- map["id"]
        replyerID <- map["reply_id"]
        replyToUserID <- map["to_user_id"]
        replyToUserName <- map["to_user_name"]
        userID <- map["user_id"]
        userName <- map["user_name"]
    }
}

**Comment by tristanhimmelman** [comment]
Please see this issue #143

**Comment by Au12th0psav** [comment]
ths
