### ISSUE TITLE
Correct way to fail a mapping?

### ISSUE THREAD

**Issue by scottrhoyt** [Hearst-DD/ObjectMapper#367]
I have some objects that I would like to fail a mapping if certain keys are `nil`. For instance, if I try to map a server error response to a model object, I'd like to fail if `var id: String!` is `nil`. I thought this should be accomplishable by doing something like:

    init?(_ map: Map) {
      guard let _ = id else {
        return nil
      }
    }

Is this the intended way to accomplish this, because all my mappings fail. Is it instead something like:

    init?(_ map: Map) {
      guard let _ = map["id"].value else {
        return nil
      }
    }

or 

    init?(_ map: Map) {
      guard let _ = map.JSONDictionary["id"] else {
        return nil
      }
    }

**Comment by tristanhimmelman** [comment]
Either of the last two ways is fine. I would probably go with `map["id"].value()` though

**Comment by scottrhoyt** [comment]
For posterity's sake, I wound up using `map["id"].currentValue` to test.

**Comment by kubajakowski** [comment]
How about failing after mapping? I.e having enum property that cannot be mapped properly?
Do I need to do something like:
```
init?(_ map: Map)
{
    guard let typeString = map["Type"].currentValue as? String,
          let _ = SomeEnum(rawValue: typeString) else {
                return nil
          }
}
```
