### ISSUE TITLE
Support for nil values in array of optionals (ex. [String?])

### ISSUE THREAD

**Issue by zellb** [Hearst-DD/ObjectMapper#368]
Currently if I try to map a JSON in array of optionals the object is always empty, even if JSON array does not return any null field. Example : on my mappable struct I declare a field as follow :

 `var strings : [String?]?`

This object is always nil for all json cases below

`{"strings":["someString",null]}`
`{"strings":["someString"]}`
`{"strings":[]}`
 
Is there a way to map array of optionals to objects ?

**Comment by tristanhimmelman** [comment]
Unfortunately, at the moment ObjectMapper doesn't support mapping arrays of Optionals the way you are describing.

**Comment by PhilCai1993** [comment]
I think this kind of JSON is a little weird...

**Comment by lgrzywac** [comment]
I have to handle similar json arrays in my app. For an array of Ints = [null, 5, null, 10] index of an element does matter - I must get value '10' using array[3] instead of array[1]

**Comment by KevM** [comment]
Duplicate of #263 which has a workaround.

**Comment by tristanhimmelman** [comment]
Thanks @KevM, closing this.
