### ISSUE TITLE
Help needed: Mapping bool is always nil

### ISSUE THREAD

**Issue by AnnieNinaJoyceV** [Hearst-DD/ObjectMapper#370]
import ObjectMapper

    struct TreatmentResponse: Mappable {
    
    var id: String!
    var isActive: Bool!
    var isCompleted: Bool!
    
    init?(_ map: Map){
        
    }
    
    mutating func mapping(map: Map) {
        id <- map["id"]
        isActive <- map["isActive"]
        isCompleted <- map["isCompleted"]
    }
    }

isActive and isCompleted is always nil.
I have tried changing them to

    var isActive: Bool = false
    var isCompleted: Bool = false

In that case, it is not updating to the actual values from API call.
Please suggest a solution to get this fixed. Thanks!

**Comment by tristanhimmelman** [comment]
Can you please paste the JSON you are receiving from the API

**Comment by AnnieNinaJoyceV** [comment]
[
{
"id":"31",
"added_by":"451",
"treatment_Id":"1",
"medication_id":"0",
"name":"TR 1",
"name_slug":"TR-1",
"provider_id":"91",
"start_date":"01-19-2016",
"end_date":"01-23-2016",
"isActive":"true",
"isCompleted":"false",
"date_created":"2016-01-20 08:31:29",
"date_updated":"0000-00-00 00:00:00",
"modified_by":"0"
}
]

Sorry for the delay in response, here is the JSON.

**Comment by tristanhimmelman** [comment]
The reason your boolean values are not mapping correctly is because the JSON values are strings instead of booleans. A properly set boolean value in JSON is `true` not `"true"`
