### ISSUE TITLE
Foundation dependency

### ISSUE THREAD

**Issue by loretoparisi** [Hearst-DD/ObjectMapper#371]
Taken apart Cocoa dependecies like

```swift
import class Foundation.NSString;
import var Foundation.NSUTF8StringEncoding;
import class Foundation.NSJSONSerialization;
import struct Foundation.NSJSONReadingOptions;
import struct Foundation.NSJSONWritingOptions;
import class Foundation.NSData;
```
there is no other dependencies from Cocoa, so is it possible to leverage these ones in order to be pure Swift lang?

**Comment by tristanhimmelman** [comment]
I am open to using the above imports instead of importing all of Foundation.

Can you please create a pull request with the change?

**Comment by loretoparisi** [comment]
@tristanhimmelman so the idea actually was to make this Swift project to work in a non `Cocoa` environment, take a look at the discussion here: http://talk.remobjects.com/t/swift-libraries-with-silver/7853/11

I'm not sure if all these dependencies could be completely removed in order to have no Cocoa's `Foundation` or `Darwin` dependency, so a cross-platform compiler could generate multi platform binaries from this.
