### ISSUE TITLE
2 README improvement requests

### ISSUE THREAD

**Issue by getaaron** [Hearst-DD/ObjectMapper#372]
After reading the README, I'm left with two questions:

1. What is the point of `init?(_ map: Map)` in the `Mappable` protocol? It always appears empty in the code samples and there is no comment in `Mappable.swift`.
2. Does ObjectMapper also work with other types like `struct`? Or will it only work with a `class`?

If someone wants to answer those for me here I can open a PR to expand the README.

**Comment by tristanhimmelman** [comment]
1. The `init?(_ map: Map)` function is required to ensure that ObjectMapper can create new instances of your classes during mapping. It also allows developers to perform validation on the JSON prior to mapping. For example you may want to check if a certain key exists in the JSON. If it doesn't exist, you can cancel the mapping by returning nil.

2. Struct support is listed in the Features of ObjectMapper. It is also stated in the Basics section where there is an example of a struct mapping.

Hope this helps. I will add more information on the `init?` function in the README when I get a chance
