### ISSUE TITLE
Can't find module ObjectMapper

### ISSUE THREAD

**Issue by vicmosin** [Hearst-DD/ObjectMapper#373]
Tried to install it via cocoapods:

```
pod 'ObjectMapper', '~> 1.1'
```
then `pod update/install`, xCode restart -> nothing. xCode just can't recognize this module at 
`import ObjectMapper`

Any ideas?

**Comment by VLEIX** [comment]
In your podfile add

# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

:)

**Comment by achirkof** [comment]
Hi!
I have same issue. 
`/Users/andrey/Documents/workspace/smartworkout/smartworkout/Model/Workout+CoreDataClass.swift:11:8: Cannot load underlying module for 'ObjectMapper'`

Is it possible because I use `platform :ios, '9.0'` ? I can't use 8.0 because of dependency for another pods.

**Comment by achirkof** [comment]
Error disappear after machine restarted. Restart of Xcode didn't help.
