### ISSUE TITLE
Could not build the tvOS target (Missing Bitcode)

### ISSUE THREAD

**Issue by MugunthKumar** [Hearst-DD/ObjectMapper#374]
I added ObjectMapper using Carthage.
The command `carthage build --platform tvOS` doesn't work because the tvOS target doesn't have ENABLE_BITCODE defined

Other targets build fine.

**Comment by tristanhimmelman** [comment]
I am not experiencing this issue. Also, I do not see the "Enable Bitcode" flag in the tvOS target. Let me know if this is still a problem for you.
