### ISSUE TITLE
currentValue == nil by default?

### ISSUE THREAD

**Issue by zulkis** [Hearst-DD/ObjectMapper#375]
In order to support full power of <- operator we should set "currentValue = JSONDictionary" in the init method of Map.
So it will be possible to just map everything from the Map to the object which could support generics and other dynamic mapping based ob the Map subscription methods.

Something like that:
self.dataResponse <- map // current value == nil, but I am expecting to get JSONDictionary there. 

If there were some reasons why it should stay nil - could you clarify?

**Comment by zulkis** [comment]
I want to achieve next behavior:
```
public protocol Fetchable : Mappable {
    func keyPathResponseValue() -> String // To map in the dataResponses
}

class FetcherResponse<T:Fetchable, Error> : Mappable {
    var error : Error?
    var dataResponse : T?
    
    internal required init?(_ map: Map) {
        
    }
    
    internal func mapping(map: Map) {
        if let _ = map["exception"].currentValue as? String {
            error = Error(map)
        } else {
            self.dataResponse <- map
        }
    }
}
```

So idea about that to just map the map to the object. But I don't have an access to the JSONDictionary and I cannot map it straightforward because currentValue is nil by default

**Comment by zulkis** [comment]
I just realized that currentValue resets every time we trying to get valueForKey through subscription.
Why implementation was made this way not the other?

**Comment by tristanhimmelman** [comment]
Closing this as I accepted your PR #379
