### ISSUE TITLE
"Must call a designated initializer of the superclass 'Navigator'" error has occurred.

### ISSUE THREAD

**Issue by nashirox** [Hearst-DD/ObjectMapper#378]
I'm using ObjectMapper with Realm with these version.

- ObjectMapper 1.1.1
- Realm 0.97.0
- Swift 2.1.1
- Xcode 7.2

But when added new class with Realm + ObjectMapper, an error has occured.
below line is error message.

`Must call a designated initializer of the superclass 'Navigator'`

and thisi is new class i added.

```
import RealmSwift
import ObjectMapper

class Navigator: Object, Mappable {
    
    dynamic var id : Int              = 0
    dynamic var name : String         = ""
    dynamic var imageURL : String     = ""
    dynamic var coverImageURL : String = ""
    dynamic var totalPlayCount : Int  = 0
    dynamic var totalFavCount : Int   = 0
    dynamic var createdAt : NSDate    = NSDate()
    dynamic var updatedAt : NSDate    = NSDate()
    
    var guides : [Guide] {        
        return linkingObjects(Guide.self, forProperty: "navigator")
    }
    
    override class func primaryKey() -> String {
        return "id"
    }
    
    override static func indexedProperties() -> [String] {
        return ["name", "imageURL", "totalPlayCount", "totalFavCount"]
    }

    // Mark: - ObjectMapper

    required convenience init?(_ map: Map) {
        self.init()
    }

    func mapping(map: Map) {
        id             <- map["id"]
        name           <- map["name"]
        imageURL       <- map["avatar_url"]
        coverImageURL  <- map["cover_url"]
        totalPlayCount <- map["listen_count"]
        totalFavCount  <- map["favorite_count"]
        createdAt      <- (map["created_at"], ISO8601DateTransform())
        updatedAt      <- (map["updated_at"], ISO8601DateTransform())
    }
}
```

this class works correctly.

```
import RealmSwift
import ObjectMapper

class Guide: Object, Mappable {
    
    dynamic var id : Int                = 0
    dynamic var title : String          = ""
    dynamic var spotName : String       = ""
    dynamic var placeId : String        = ""
    dynamic var explanation : String    = ""
    dynamic var category : String       = ""
    dynamic var totalPlayCount : Int    = 0
    dynamic var totalFavCount : Int     = 0
    dynamic var latitude : Double       = 0.0
    dynamic var longitude : Double      = 0.0
    dynamic var createdAt : NSDate      = NSDate()
    dynamic var updatedAt : NSDate      = NSDate()
    
    dynamic var navigator: Navigator?
    var relatedGuides = List<Guide>()
    
    override class func primaryKey() -> String {
        return "id"
    }
    
    // インデックス設定
    override static func indexedProperties() -> [String] {
        return ["name", "category", "firstImageUrl", "totalPlayCount"]
    }
    
    //  override static func ignoredProperties() -> [String] {
    //    return []
    //  }

    // Mark: - ObjectMapper
    
    required convenience init?(_ map: Map) {
        self.init()
    }
    
    func mapping(map: Map) {
        id             <- map["id"]
        title          <- map["name"]
        spotName       <- map["spot.name"]
        explanation    <- map["description"]
        category       <- map["category.name"]
        totalPlayCount <- map["listen_count"]
        totalFavCount  <- map["favorite_count"]
        latitude       <- map["geometry.latitude"]
        longitude      <- map["geometry.longitude"]
        createdAt      <- (map["created_at"], ISO8601DateTransform())
        updatedAt      <- (map["updated_at"], ISO8601DateTransform())
    }
}
```

so i'm confused what to do next.
someone please give me advices.

**Comment by tristanhimmelman** [comment]
Hi there, I just tested this code and I am not getting any errors. Are you still having this problem?

**Comment by Andr3y-** [comment]
I have exactly the same problem:
`import ObjectMapper
import RealmSwift

class WRUser: Object, Mappable {
    
    var ID: Int = 0
    var email: String = ""
    
    // MARK: - Init
    
    required convenience init?(_ map: Map) {
        self.init()
    }
    
    func mapping(map: Map) {
        ID <- map["user.id"]
        email <- map["user.email"]
    }
    
//    // CustomStringConvertible
//    override var description: String {
//        return "ID: \(ID), email: \(email)"
//    }
}`

Actually **building** a project gives an error: **Must call a designated initializer of the superclass "WRUser"**

Any thoughts?

**Comment by dotmartyr** [comment]
This happens because the ObjectMapper initializer that we override is a convenience initializer, which differs from a designated initializer, which it states in the error.

However, I am here because I am having the same issue. I want to subclass one of my objects which is Mappable, but because I cannot override the convenience init, it will not compile.

Is there any way around this ? I really would like to avoid having two classes which are nearly identical and both subclass Mappable and chain them one layer further instead.

**Comment by kylebegeman** [comment]
Having same issue with a subclass of another mappable object. This issue says closed but there does not appear to be a solution?

**Comment by adipurnama** [comment]
Hi,
I also having same error when subclassing mappable object.
The working solution for me is by adding init method (same as parent class)

So, in above case :

```
class WRUserSubclass: WRUser {

    required convenience init?(_ map: Map) {
        self.init()
    }

    func mapping(map: Map) {
        // extended mapping here
    }
}
```

Hope this help
