### ISSUE TITLE
fails to map JSON array of objects

### ISSUE THREAD

**Issue by aler** [Hearst-DD/ObjectMapper#380]
It seems that mapper cannot handle array of object like this one

`let jsonString = "[{\"Points\":[[-122.218,47.7041],[-122.2202,47.704],[-122.2255,47.7007]]}]"`

Mapper parse func fails to convert it to dict and returns ni

```
	/// Convert a JSON Object into a Dictionary<String, AnyObject> using NSJSONSerialization
	public static func parseJSONDictionary(JSON: AnyObject?) -> [String : AnyObject]? {
		if let JSONDict = JSON as? [String : AnyObject] {
			return JSONDict
		}

		return nil
	}
```

My temp solution looks like this, but I am not sure if it a best one.

```
       /// Convert a JSON Object into a Dictionary<String, AnyObject> using NSJSONSerialization
	public static func parseJSONDictionary(JSON: AnyObject?) -> [String : AnyObject]? {
		switch JSON {
		case let dict as [String: AnyObject]:
			return dict
		case let arr as [[String: AnyObject]]:
			return arr.count != 0 ? arr[0] : [:]
		default:
			return nil
		}
	}
```

**Comment by tristanhimmelman** [comment]
Are you using the following function for mapping `Mapper<Type>().mapArray()`?

**Comment by aler** [comment]
I am using `Mapper<Type>().map(jsonStr)` I have a common func that parse api responses from a backend. Some api calls returns JSON object and some JSON array and that func has no idea what to expect.

Is there any solution for such problem?

**Comment by tristanhimmelman** [comment]
Since you the type you are receiving is an Array you need to use the `mapArray` function. You will need to add some logic that handles responses with top level arrays differently.
