### ISSUE TITLE
Dynamic Attribute mapping

### ISSUE THREAD

**Issue by DeTakaki** [Hearst-DD/ObjectMapper#381]
Hello, I've been having a issue with dynamic attribute mapping. my JSON follows this model:

```
{
    "2016-02-01": [
        {
            "id": 86,
            "name": "Café Diário Com Patricia Palumbo",
            "url": "https://beta.radiovozes.com/programas/cafe-diario-com-patricia-palumbo",
        },
        {
            "id": 87,
            "name": "Rádio Vozes",
            "url": "https://beta.radiovozes.com/programas/radio-vozes",
           
        }
    ],
    "2016-02-02": [
        {
            "id": 95,
            "name": "Café Diário Com Patricia Palumbo",
            "url": "https://beta.radiovozes.com/programas/cafe-diario-com-patricia-palumbo",
        }
    ]
}
```
I even took a look at #139 ,but didn't succeed to do the same. Can you please help me?

this is my model:

   
  ```
  class Schedule: Mappable{
        var id: Int?
        var name: String?
        var url: String?
        
        //MARK: Mappable
        required init?(_ map: Map) {}
        
       func mapping(map: Map) {
            id <- map["id"]
            name <- map["name"]
            url <- map["url"]
        }
    }
```

Thanks in advance!

**Comment by tristanhimmelman** [comment]
Since your JSON is in the form of Dictionary<String, Schedule> you should use probably be using  the following function to perform your mapping:
`Mapper<Schedule>().mapDictionary(JSONString)` 

Hope this helps.

**Comment by khunshan** [comment]
I dont know how this solution will solve the array in json.

**Comment by tristanhimmelman** [comment]
@khunshan , you're right, I didnt notice the arrays. In that case you would probably need to make a model that represents the whole JSON.
This model could have a dictionary of arrays in it like this:
```
var schedules: Dictionary<String, Array<Schedule>> 
```
