### ISSUE TITLE
Way to copy objects.

### ISSUE THREAD

**Issue by RishabhTayal** [Hearst-DD/ObjectMapper#385]
How can we implement the NSCopying protocol?

**Comment by cwalo** [comment]
Just had to do this myself. Here's a sample class. Note the additional `init()` method.

`import Foundation
import ObjectMapper

class SomeClass: NSObject, NSCopying, Mappable {
    var firstName: String?
    var lastName: String?
    
    required init?(_ map: Map){
        
    }
    
    func mapping(map: Map) {
        firstName <- map["first_name"]
        lastName <- map["last_name"]
    }
    
    init(firstName: String?, lastName: String?) {
        self.firstName = firstName
        self.lastName = lastName
    }
    
    func copyWithZone(zone: NSZone) -> AnyObject {
        let copy = SomeClass(firstName: firstName, lastName: lastName)
        return copy
    }
}`

**Comment by tristanhimmelman** [comment]
Thanks @cwalo
