### ISSUE TITLE
target 'ObjectMapper-tvOS' has bitcode disabled

### ISSUE THREAD

**Issue by honghaoz** [Hearst-DD/ObjectMapper#386]
I used `ObjectMapper` as a dependency, when i run Travis CI, it's failed with this error:
```
ObjectMapper / ObjectMapper-tvOS (Debug)
      ✗ Check dependencies (207 ms)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Check dependencies
target 'ObjectMapper-tvOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'watchos' platform
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      1 errored, 0 warning (230 ms)
```

Not sure should we enable bit code?

**Comment by Tombio** [comment]
I think it should be enabled for all targets by default. In fact Apple requires bitcode to be enabled for WatchOS and tvOS apps [as stated here].(https://developer.apple.com/library/prerelease/ios/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html)

Having bitcode enabled for all targets is open for debate, but it does enable Apple to optimize binaries without need to upload new archive. In my opinion there are more upsides than downsides having bitcode enabled by default.

**Comment by tristanhimmelman** [comment]
As far as I can tell, the ENABLE_BITCODE flag is only available on the iOS target. I cannot find the option to enable it for the tvOS or watchOS targets

**Comment by tristanhimmelman** [comment]
In the link that @Tombio posted it states: 

> Note: For iOS apps, bitcode is the default, but optional. For watchOS and tvOS apps, bitcode is required. If you provide bitcode, all apps and frameworks in the app bundle (all targets in the project) need to include bitcode.

From this, I'm assuming that bitcode is enabled by default in the target (hence why I can't find the setting)

**Comment by honghaoz** [comment]
Actually, by default, ENABLE_BITCODE is not enabled for tvOS and watchOS.

If you go to project build settings:
<img width="917" alt="screen shot 2016-02-15 at 11 37 33 pm" src="https://cloud.githubusercontent.com/assets/3926785/13067369/3864010a-d43d-11e5-8cd0-e16aaa5fd169.png">

Switch `Enable Bitcode` to `NO` and then `YES`, this will add a flag to tvOS and watchOS targets:
<img width="878" alt="screen shot 2016-02-15 at 11 37 44 pm" src="https://cloud.githubusercontent.com/assets/3926785/13067378/55f6cf4a-d43d-11e5-9e49-ba5f189e8848.png">

This is git diff after my changes:
<img width="661" alt="screen shot 2016-02-15 at 11 39 48 pm" src="https://cloud.githubusercontent.com/assets/3926785/13067387/75cea752-d43d-11e5-8738-04b208b23e73.png">

I was able to resolve those test failures on my other projects. Any thoughts?

**Comment by honghaoz** [comment]
Btw, using [Alamofire](https://github.com/Alamofire/Alamofire) as a subproject has no problems with `BITCODE`, you can verify their target settings

**Comment by MugunthKumar** [comment]
I too have this problem.
https://github.com/Hearst-DD/ObjectMapper/issues/374

I have another machine running Xcode 7.2.1 on the developer seed of El Capitan and I see no problems there. I'm pretty sure this is a compiler issue.

**Comment by tristanhimmelman** [comment]
Thanks @honghaoz. I've enabled bitcode for watchOS and tvOS using your solution. I just released v1.1.4 with the fix.

**Comment by honghaoz** [comment]
great, thanks!

**Comment by MugunthKumar** [comment]
I solved the Bitcode issue by updating Carthage to 0.11. Seems like if ENABLE_BITCODE is missing (because Xcode treats bitcode mandatory for tvOS and watchOS), Carthage wasn't passing the bitcode flag as a compiler arg.

0.9.1 is the version where this fix was implemented I guess
https://github.com/Carthage/Carthage/releases/tag/0.9.1
