### ISSUE TITLE
Conversion issue to Int? in inconsistent JSON

### ISSUE THREAD

**Issue by popaaaandrei** [Hearst-DD/ObjectMapper#388]
Hello, 

Me again with JSON inconsistencies :)

1) This time I have these Int values in the JSON:
`"premium": 1000`, `"premium": 506`, ...
2) They are mapped to `var premium : Int?`
3) Sometimes I receive `"premium": 9999999999.99`
4) In this case I expect the conversion to fail and give me `nil`. Instead I get a number like `1410065407`

Somehow the program continued to run on iPhone 6 but crashed constantly on iPhone 5.

Please share your thoughts. _I think we must take these inconsistencies into account more seriously because lots of backends are poorly coded ... :(_

Andrei

**Comment by tristanhimmelman** [comment]
Hi @popaaaandrei,

I'm pretty sure the reason the mappings are failing for the above large values is that those values are larger than the maximum Int value. You should probably be mapping those values into Int64 or NSNumber. Please note that I have not really tested ObjectMapper with Int64... it should work, but it's possible that it doesn't behave as expected...

For reference, here is the max Int value: `2147483647`

**Comment by popaaaandrei** [comment]
I was reading that Int is always Int32 or Int64 depending on the device. Is there some way that we can protect against `integer overflow` ?

- Int8 -128 |||| 127
- Int16 -32,768 |||| 32,767
- Int32 -2,147,483,648 |||| 2,147,483,647
- Int64 -9,223,372,036,854,775,808 |||| 9,223,372,036,854,775,807
- UInt8 0 255
- UInt16 0 65,535
- UInt32 0 4,294,967,295
- UInt64 0 18,446,744,073,709,551,615

Thank you!

**Comment by tristanhimmelman** [comment]
As far as I know, there is no easy way to protect against integer overflow. 

I think it's probably best to just use a type that will be certain to work for all cases and all devices (ie Int64)
