### ISSUE TITLE
Is it possible to map value(maybe string or int)  to int

### ISSUE THREAD

**Issue by PhilCai1993** [Hearst-DD/ObjectMapper#389]
JSON may be as follows:
```
{
    "id":123,
    "name":"XXX"
}

{
    "id":"123",
    "name":"XXX"
}
```
If one day server changes "id" from Number to String for some reason. But actually type of "id" is not determined. Once it has changed, I have to update my Model Class.
```
class Model: Mappable {
    var id: Int
    var name: String
    ......
}
update to:
class Model: Mappable {
    var id: String
    var name: String
    ......
}

```
Is there a way to get the Model correctly whatever the server sends me? I want "id" as Int even if it is a String in JSON, but without changing the implementation of Class?
Thanks!

**Comment by tristanhimmelman** [comment]
You should be able to build a Transform that handles this. This example below converts a String to an NSURL.
```
public class URLTransform: TransformType {
	public typealias Object = NSURL
	public typealias JSON = String

	public init() {}

	public func transformFromJSON(value: AnyObject?) -> NSURL? {
		if let URLString = value as? String {
			return NSURL(string: URLString)
		}
		return nil
	}

	public func transformToJSON(value: NSURL?) -> String? {
		if let URL = value {
			return URL.absoluteString
		}
		return nil
	}
}
```

In the `transformFromJSON` function you could check the type of the input value and convert it to an Int appropriately depending on its type.

**Comment by PhilCai1993** [comment]
Thanks a lot
