### ISSUE TITLE
[RFC] Rename MapperProtocol to something

### ISSUE THREAD

**Issue by ikesyo** [Hearst-DD/ObjectMapper#39]
The name `MapperProtocol` is long a little bit, and also Swift protocols are mainly named with suffix like `Type` (e.g. `SequenceType`) or `able` (e.g. `Equatable`, `Hashable`, and so on).

How do you think about renaming it to something like `MapperType` or `Mappable`?

**Comment by tristanhimmelman** [comment]
Yeah I've been thinking about this too. I like ```Mappable```. I will go ahead and refactor it. Thanks for the input.

**Comment by ikesyo** [comment]
:+1: for `Mappable` too.

**Comment by tristanhimmelman** [comment]
All done! Created a new release and also pushed it to Cocoapods
