### ISSUE TITLE
Generic Objects is not casting into Model

### ISSUE THREAD

**Issue by srthakkar** [Hearst-DD/ObjectMapper#390]

**Comment by srthakkar** [comment]
Here is My class...

class LoginModel: Mappable {
    
    
    var FirstName: String?
    var LastName: String?
    
    required init?(_ map: Map) {
        
    }
    
    
    func mapping(map: Map) {
        FirstName    <- map["FirstName"]
        LastName         <- map["LastName"]
    }
    
}



class User<T: Mappable>: Mappable {
    var IsSuccess: Bool?
    var Code: String?
    var Message: String?
    var Data: T?
    
    required init?(_ map: Map) {
       
        
       //print( Mirror(reflecting: Data).subjectType)
        
        print( Mirror(reflecting: LoginModel.self).subjectType)
    }
    
    // Mappable
    func mapping(map: Map) {
        IsSuccess    <- map["IsSuccess"]
        Code         <- map["Code"]
        Message      <- map["Message"]
        Data       <- map["Data",nested: false]
        
    }
}


and I am calling this...
et user1 = Mapper<User<LoginModel>>().map(datastring)


I am not getting Data as LoginModel class but getting undefined property.

My JsonString is following.
"{\"Code\":\"200\",\"IsSuccess\":true,\"Message\":\"User authenticated successfully.\",\"Data\":{\"UserID\":\"56b49e720a351d29b0daaee4\",\"Email\":\"nisarg@mailinator.com\",\"Token\":\"4b075a7b-0d41-40ed-ac97-d125032f54e2\",\"FirstName\":\"Nisarg\",\"LastName\":\"Shah\",\"IsPhoneVerified\":true,\"MobileNumber\":\"9510861645\"}}"

**Comment by tristanhimmelman** [comment]
Here is an example from the ObjectMapper tests to guide you:

```
class Response<T: Mappable>: Mappable {
	var result: T?
	
	required init?(_ map: Map){
		
	}
	
	func mapping(map: Map) {
		result <- map["result"]
	}
}

class Status: Mappable {
	var status: Int?
	
	required init?(_ map: Map){
		
	}

	func mapping(map: Map) {
		status <- map["code"]
	}
}
```
```
let response = Mapper<Response<Status>>().map(JSONString)
```

In your example above, the Data variable needs to conform to `Mappable`. This is declared in the class definition as you see in the Response class. Then when you are mapping the object you need to declare the type T that is being mapped.
