### ISSUE TITLE
Cannot invoke 'toJSONString' with an argument list of type '(User, prettyPrint: Bool)'

### ISSUE THREAD

**Issue by denisbetsi** [Hearst-DD/ObjectMapper#395]
**Podfile:**
```
platform :ios, '9.2'
use_frameworks!
target "ObjectMapperTest" do
	pod 'ObjectMapper', '~> 1.1'
end
```

Created an empty project in XCode, added the above pod file and ran Pod install. Everything installed properlly. Opened workspace . Put in a sample code from the How to documentation

**Code:**
```
import ObjectMapper

public protocol Mappable {
    init?(_ map: Map)
   mutating func mapping(map: Map)
}

`class User: Mappable {
    var username: String?
    var age: Int?
    required init?(_ map: Map) {}
    
    func mapping(map: Map) {
        username    <- map["username"]
        age         <- map["age"]
    }
    init(){
    }
}

```

Tried using it
```
        var user:User = User();
        let JSONString = Mapper().toJSONString(user, prettyPrint: true)
```

the let JSONString line has the error
_Cannot invoke 'toJSONString' with an argument list of type '(User, prettyPrint: Bool)'_

I created empty project and started fresh because I had same error while trying to use this in another project. Figured perhaps I messed something up there that would cause this error.

**Comment by denisbetsi** [comment]
One more thing to add, doesn't work going from String to Object either.

**Error:**
Type 'User' does not conform to protocol 'Mappable'

**Code:**
```

        var jsonString:String = "{\"username\":\"myusername\",age:23}"
        
        let objuser = Mapper<User>().map(jsonString)

```

**Comment by tristanhimmelman** [comment]
You are not supposed to include the following in your code:
```
public protocol Mappable {
    init?(_ map: Map)
   mutating func mapping(map: Map)
}
```

Other than that, I believe your code is fine.

**Comment by galvezz** [comment]
That worked for me! Thanks!
