### ISSUE TITLE
Is it possible to have a "merge" function

### ISSUE THREAD

**Issue by PhilCai1993** [Hearst-DD/ObjectMapper#396]
Like in Mantle there are methods like ``mergeValuesForKeysFromModel:`` and ``mergeValueForKey: fromModel``.
Is it possible for ObjectMapper to support that since during ``mapping`` we have typed all the keys, and we can use a set to record them?
It may be not easy but is it possible?

**Comment by tristanhimmelman** [comment]
Unfortunately due to the structure of the code, I do not think this is possible.

**Comment by mariovillamizar** [comment]
I have found a temporary solution. You can create an extension of Dictionary: 

`
extension Dictionary {
    mutating func merge(with: Dictionary){
        for (k, v) in dict {
            updateValue(v, forKey: k)
        }
    }
}
`
Then you can use your objects as JSONs to merge them, for example:

`
var user1 = User()
user1.name = "Mario"

var user2 = User()
user2.name = "Pedro"
user2.email = "pedro@test.com"
        
var user1JSON = user1.toJSON()
var user2JSON = user2.toJSON()
user1JSON.merge(with: user2JSON)

print(user1JSON)
// Result = ["name": "Pedro", "email": "pedro@test.com"]
`
