### ISSUE TITLE
ObjectMapper + Firebase?

### ISSUE THREAD

**Issue by Dodig** [Hearst-DD/ObjectMapper#398]
Hi
How I can use ObjectMapper with Firebase?
Do you have any tutorials or samples?

**Comment by tristanhimmelman** [comment]
Sorry I have never used or heard of Firebase so I do not have any samples to tutorials for you.

**Comment by Dodig** [comment]
@tristanhimmelman if you don't know Firebase you can check this: [Firebase features](https://www.firebase.com/features.html#features-database) :wink:

**Comment by fractalzombie** [comment]
I'm interesting the same thing.

**Comment by TofPlay** [comment]
Found it! 😀
## Example with an Array of users
### Json 
Import this Json at `https://<your db>.firebaseio.com/Users`
Replace `<your db>` by your database
```
{
  "Users": [
    {
      "firstName": "Paul",
      "lastName": "Dumont"
    },
    {
      "firstName": "Jacque",
      "lastName": "Zero"
    },
    {
      "firstName": "Marc",
      "lastName": "Longshot"
    }
  ]
}
```
### ObjectMapper class
```swift
import Foundation
import ObjectMapper

class User: Mappable {

  var firstName:String? = nil
  var lastName:String? = nil

  required init?(_ pMap: Map){
  }

  func mapping(pMap: Map) {
    self.firstName  <- pMap["firstName"]
    self.lastName   <- pMap["lastName"]
  }
}
```
### View Controller
Replace `<your db>` by your database name
```swift
override internal func viewDidLoad() {
    super.viewDidLoad()

    let lUsers = Firebase(url: "https://<your db>.firebaseio.com/Users")
    
    lUsers.observeEventType(.Value) {
      (pSnapshot:FDataSnapshot!) -> Void in

      if let lJsonArray = pSnapshot.value as? [[String : AnyObject]] {
        let lUsers = Mapper<User>().mapArray(lJsonArray)
        print("\(lUsers)")
      }
    }
}
```
### Debug view
![image](https://cloud.githubusercontent.com/assets/1082222/13575848/354b8f98-e48b-11e5-95b7-cd8fbd2f87ba.png)

**Comment by Dodig** [comment]
Thanks :smile:

**Comment by omarzl** [comment]
Maybe this is helpful to someone, I ended up creating a mix of many resources on the Internet.
This is the base class:

`import UIKit
import Firebase

class FIRDataObject: NSObject {
    
    var snapshot: FIRDataSnapshot!
    var key: String { return snapshot.key }
    var ref: FIRDatabaseReference { return snapshot.ref }
    
    required init(_ snapshot: FIRDataSnapshot) {
        super.init()
        self.snapshot = snapshot
        for child in snapshot.children {
            if respondsToSelector(Selector(child.key)) {
                setValue(child.value, forKey: child.key)
            }
        }
        load()
    }

    func load(){
        
        // retrieve the properties via the class_copyPropertyList function
        var count: UInt32 = 0;
        let myClass: AnyClass = self.classForCoder;
        let properties = class_copyPropertyList(myClass, &count)
        
        // iterate each objc_property_t struct
        for i:UInt32 in 0..<count{
            let property = properties[Int(i)]
            
            // retrieve the property name by calling property_getName function
            let cname = property_getName(property)

            // covert the c string into a Swift string
            if let name = String.fromCString(cname){
                if let value=snapshot.value!.valueForKey(name){
                    self.setValue(value, forKey: name)
                }
            }
        }
        // release objc_property_t structs
        free(properties);
    }
    
    func save(){
        var dicc=[String:AnyObject]()
        
        // retrieve the properties via the class_copyPropertyList function
        var count: UInt32 = 0;
        let myClass: AnyClass = self.classForCoder;
        let properties = class_copyPropertyList(myClass, &count)
        
        // iterate each objc_property_t struct
        for i:UInt32 in 0..<count{
            let property = properties[Int(i)]
            
            // retrieve the property name by calling property_getName function
            let cname = property_getName(property)
            
            // covert the c string into a Swift string
            if let name = String.fromCString(cname){
                
                let value=self.valueForKey(name)
                dicc[name]=value
            }
        }
        ref.setValue(dicc)
        
        // release objc_property_t structs
        free(properties);
    }
}

protocol FIRDatabaseReferenceable {
    var ref: FIRDatabaseReference { get }
}

extension FIRDatabaseReferenceable {
    var ref: FIRDatabaseReference {
        return FIRDatabase.database().reference()
    }
}`

you only need to inherit from it:

`class User: FIRDataObject {
    
    var name=""
    var username=""
    var amigos=[String:Bool]()
    
}`

and an example of use:

`            ref.child("users").child(user.uid).observeSingleEventOfType(.Value, withBlock: { (snapshot) in
                let user=User(snapshot)
                user.username="Demo"
                user.amigos[user.key]=true
                user.save()
            })`

**Comment by callam** [comment]
@omarzl nice code you got there

**Comment by Jasonchan91** [comment]
nice sharing

**Comment by choioi** [comment]
Very thanks !

**Comment by piv199** [comment]
@omarzl great way to deal with mapping

**Comment by Ankish** [comment]
Is there any way we can convert firebase snapshot object to raw json ? Then it could be easy to convert to this. Anythoughts ?
