### ISSUE TITLE
iOS 7 support

### ISSUE THREAD

**Issue by Dohko** [Hearst-DD/ObjectMapper#40]
Hi,

Thank you very much for this framework, i love it.

I just have a request. Can you add an iOS 7 support, please?

iOS 8 adoption is too slow (only 69%) https://developer.apple.com/support/appstore/

Regards,
Dohko

**Comment by ikesyo** [comment]
AFAIK, the library itself supoorts iOS 7 (not using iOS 8 API). But Dynamic Framework (and also CocoaPods support) is only supported at iOS 8 and later.

So if you'd like to use this library in iOS 7, you can use by using git submodule and add source files directory to your app project.

**Comment by ikesyo** [comment]
See also #23.

**Comment by tristanhimmelman** [comment]
@ikesyo is correct. ObjectMapper does work on iOS 7 but unfortunately iOS 7 does not support including dynamic frameworks in a project (It will run with a warning but Apple will reject it if you submit that way). @ikesyo suggestion of using git submodule and adding the files to you app directly is probably your best bet.

**Comment by stephenyao** [comment]
Added source files directly to project and now it's running on iOs7. Hope there will be a way in the future to resolve this
