### ISSUE TITLE
A question about "where"

### ISSUE THREAD

**Issue by PhilCai1993** [Hearst-DD/ObjectMapper#401]
In ToJSON.swift, what does it mean by this:
```
if let x = field as? AnyObject where false 
    || x is AAA 
    || x is BBB
... {}
```
I don't understand the "where false".
Could you please tell me what does it mean?
Thanks.
😄

**Comment by tristanhimmelman** [comment]
It is actually not necessary at all. This code came from a pull request and I believe the `where false` is mainly there so that all the conditions line up nicely below. We could consider removing it as it serves no other purpose, but I don't think it does much harm either.

**Comment by PhilCai1993** [comment]
Thanks, I was just confused.
