### ISSUE TITLE
Cannot have empty init implementation on struct

### ISSUE THREAD

**Issue by nicpro85** [Hearst-DD/ObjectMapper#404]
I am forced to fill the init method with values how can I not?
```
struct Plate: Mappable {
    var id      :String
    var number  :String
    var country :String
    var state   :String
    var active  :Bool
    
    init?(_ map: Map) {
        id      = ""
        number  = ""
        country = ""
        state   = ""
        active  = false
    }
}
```

**Comment by tristanhimmelman** [comment]
Since you're variables are not optional, they need to be given a default value. You could write your model as follows to avoid filling the init function:
```
struct Plate: Mappable {
    var id = ""
    var number = ""
    var country = ""
    var state = ""
    var active = false

    init?(_ map: Map) {
    }
}
```

**Comment by jbmaxwell** [comment]
I don't understand this implementation; why would we set default values when the init is passed the Map as an argument? Wouldn't it make sense to just get the objects from map?
