### ISSUE TITLE
Trying to convert to json with mapper using the type Mappable directly doesn't work

### ISSUE THREAD

**Issue by majorgilles** [Hearst-DD/ObjectMapper#405]
Hello,

I'm trying to be as generic as possible with my network requests but cannot figure out why the following is not working:

`
private func postAuthInfo(url: NSURL, payload: Mappable) {

    let payload = Mapper().toJSONString(obj) 
    
    Alamofire.request(.POST, url, parameters: payload, encoding: .JSON).responseString(completionHandler: {
        response in
        if response.result.isSuccess {
            TokenManager().saveToken(response.result.value!)
        }
        else {
            NSNotificationCenter
                .defaultCenter()
                .postNotificationName(ERROR_TO_DISPLAY_IN_ALERT, object: "Error posting request \(response.result.description)")
        }
    })
}
`

I intended to pass my instances of model objects implementing Mappable to that function, convert it to json and process it in the network request.
The error I get is:  "cannot invoke 'toJSONString' with an argument list of type '(Mappable)'

Invoking my concrete Mappable implementation (e.g. User) works without any problem.

**Comment by tristanhimmelman** [comment]
I believe this should work if you change your function definition to the following:
```private func postAuthInfo<T: Mappable>(url: NSURL, payload: T) ```

**Comment by majorgilles** [comment]
Ok, thanks a lot, will try asap

**Comment by tristanhimmelman** [comment]
Closing this for now, you can reopen if you are still having issues.
