### ISSUE TITLE
crash when mapping with transforms

### ISSUE THREAD

**Issue by jonasman** [Hearst-DD/ObjectMapper#407]
i have this code in the mapping function:
`expiresIn	<- (map["expires_in"], TransformOf<NSTimeInterval, Int>(fromJSON: { NSTimeInterval($0! / 1000) }, toJSON: { Int($0!) * 1000 }))`

The issue is that the json is not mapping to this object. It is an error case. And thus the values are all nil. even if the Transform should give me non optionals!
The crash happens because $0 is nil in fromJSON closure

**Comment by jonasman** [comment]
One way i thought is to check for the valid data in the init. but that makes no sense?

**Comment by jonasman** [comment]
i think the problem is that ` TransformOf<ObjectType, JSONType>` is changing the generic types to optionals and that makes the problem of validation! 
The protocol TransformType forces the use of optionals. i guess this shouldn't be forced, but instead be taken from the generic types.

**Comment by tristanhimmelman** [comment]
Is this still a problem for you?

I think the issue may be that you are using the forced unwrapping operator `!` on optional objects which may be nil. If would be better to use the `if let` syntax to avoid this.

**Comment by jonasman** [comment]
But why converting the generics to optionals?

**Comment by tristanhimmelman** [comment]
They are converted to optional objects of the generic type. This is necessary because ObjectMapper needs to be able to handle `nil` values within JSON objects.
