### ISSUE TITLE
What about a more strict behaviour of map() when implicitly unwrapped optionals are missing?

### ISSUE THREAD

**Issue by pixelogik** [Hearst-DD/ObjectMapper#409]
We really need entity parsing to fail if properties - that are not supposed to be optional - are missing in the API responses (JSON). For this we use implicitly unwrapped optionals, so that the constructor does not need to have them initialized. If however the JSON does not provide parseable values, we get nil values and either we have to check for that when we use them or the app crashes. 

To make this happen we forked the project and added a strict parameter to Mapper, that is default false, which results in the current behaviour of map().

If that parameter is true however, the map() method returns nil if an implicitly unwrapped optional cant be parsed from the JSON. I made sure all tests are green. I added a test for the new strict option in Mapper. 

If you are interested in this please check it out at: 
https://github.com/youandthegang/ObjectMapper

Would be happy to have a conversation about this. We have not added anything yet for the toJSON case though.

**Comment by tristanhimmelman** [comment]
That's an interesting addition. ObjectMapper already includes a way to validate your JSON before mapping. In the failable initializer you can return nil if you are missing data that you need to perform the mapping. 
```
required init?(_ map: Map) {
    // check if fields you need exist
    return nil
}
```

**Comment by pixelogik** [comment]
Hey, thanks! 
I try to understand the patterns here. This means if I have N fields that need to be there, I need N checks in the initializer and the N <- in the mapping() method right? 

In our projects the JSON responses of APIs have two kind of fields: Optional and non-optional. And most fields are non-optional. That's why for us having this implicitly in there is really helpful, reduces the code of model classes about 40-50%. I just wonder, why the implicitly unwrapped optional should ever be allowed to be nil in the returned objects. Does this not force the user code to always check against nil? What if the API changes or has issues? In that case the app would crash if no nil checks are done. And if nil checks are mandatory, then everything could be optional. Am I missing something? 

Thanks for the framework btw, it is freaking awesome! :D

**Comment by rwichmann** [comment]
+1

**Comment by pixelogik** [comment]
Ok I looked more into this and realized that this is not possible. 

When you support non-optional properties, you have to have a default-value mechanism so that all properties get a value assigned in the constructor, which potentially also means that you have to specify the fromJSON mapping on the constructor and the toJSON mapping in an additional function. We do this in our APILayer framework. 

OR

You only support optionals, which gives you the freedom to NOT initialize properties in the constructor, thus enabling the one function that defines both toJSON and fromJSON mappings (like ObjectMapper is doing it).

There is unfortunately currently no perfect solution because in Swift all non-optional properties need to be defined in the constructor - which is what we expect and like of course. Even working with exceptions in the constructor does not help, the non-optional properties still need to be defined before the throw. So without default values being assigned this does not work either. 

We will go with our existing model in APILayer because to us non-optionals are more important than the toJSON mapping. Most of our entities are not send back to the API so if we need that we just add a serialisation method to the entity, something like toDict().
