### ISSUE TITLE
Backslashes in JSON

### ISSUE THREAD

**Issue by pkasson** [Hearst-DD/ObjectMapper#410]
Just started using the library - does work great for my needs, but all the strings are escaped/have back slashes in them.  Have not tried to parse this with other languages just yet, but seems wrong.  Online JSON validators are complaining and after removing them, validate fine.

Is there an option when generating to avoid the backslashes

**Comment by tristanhimmelman** [comment]
The JSON string generation is handled by NSJSONSerialization which is within the foundation framework. 

You can get a Dictionary<String, AnyObject> representation of your data using the `map` function. From here you could write your own JSON string generator, or perhaps find another one online
