### ISSUE TITLE
How to validate for json response and correct object has created.

### ISSUE THREAD

**Issue by jazz-mobility** [Hearst-DD/ObjectMapper#412]
Hi,

I am looking for a method or error handler to check if the correct object is created or not.
So for example, I have assigned Car json response to a Customer object, i want to validate the Customer object if it is created or not, in my Mapper is always returning me the Customer object with nil values.

let autoSuggestions = Mapper<SPAutoSuggestionResponseModel>().map(String(data: response.data!, encoding: NSUTF8StringEncoding))

This is the code I am using to get the autoSuggestions from response, In case of error or exception in server i get different error json. But even then autoSuggestions object is not nil, it got initalized and i can not validate it with 
if autoSuggestions == nil

Looking for a quick solution. Thanks in Advance :)

**Comment by tristanhimmelman** [comment]
See the example here https://github.com/Hearst-DD/ObjectMapper#mappable-protocol

Prior to mapping when the `init?` function is executed, you can make sure the JSON response has the correct data necessary for mapping, if it does not, return nil.
