### ISSUE TITLE
nested folder structure with parent

### ISSUE THREAD

**Issue by vigyanhoon** [Hearst-DD/ObjectMapper#414]
Hi,

I am trying to parse a nested folder structure using ObjectMapper. I can do this well. But the problem is that I want to add a parent property on every node, which I have no clue about.

Can anyone please guide me on that?

class FileModel: Mappable {
    
    var identifier : String?
    var path : String?
    var name : String?
    var type : String?
    var downloadLink : String?
    var children : [FileModel]?
    var parent : FileModel? //added this property for setting explicitly
    
    required init?(_ map: Map){
        // this doesn't work
        if children != nil {
            for child in children!{
                child.parent = self
            }
        }
    }

    func mapping(map: Map) {
        identifier          <- map["identifier"]
        path                <- map["path"]
        name                <- map["name"]
        type                <- map["type"]
        downloadLink        <- map["downloadLink"]
        children            <- map["children"]
    }
}

Thank you.

**Comment by tristanhimmelman** [comment]
Hey there,
Sorry for the slow response. 

You need to move the following code: 
```
if children != nil {
    for child in children!{
        child.parent = self
    }
}
```
to the mapping function after the children assignment. I think this should do the trick

**Comment by bargar** [comment]
@tristanhimmelman big thanks for this tip!
