### ISSUE TITLE
Testing mappings question

### ISSUE THREAD

**Issue by ehuynh** [Hearst-DD/ObjectMapper#415]
Hi,
I was wondering how we can test the Mappings in the test target. I'm creating a framework (lets call it framework **foo**) that contains an API to call some remote API. And I've added the `ObjectMapper` framework to framework foo in the _Link Binary with Libraries_ section in the _Build Phases_. 

In my test target for framework foo. I'm trying to import `ObjectMapper` to test my mappings by
```
let response = Mapper<SomeResponseClass>().map(JSONString)
```
 but I get the message 
```
Library not loaded: @rpath/ObjectMapper.framework/ObjectMapper
```
when i try to run the tests. 

Is there something wrong with my approach? 

Cheers

**Comment by dac09** [comment]
Hi @ehuynh did you manage to resolve this issue? I'm seeing the same problem

**Comment by ehuynh** [comment]
yeah turns out i just forgot to import the framework in my test target
