### ISSUE TITLE
iOS7... crash when mapping with transforms

### ISSUE THREAD

**Issue by Kofktu** [Hearst-DD/ObjectMapper#418]
i have this code in the mapping function:

let transform = TransformOf<NSData, NSData>(fromJSON: { (value: NSData?) -> NSData? in
        if let value = value {
            return NSKeyedUnarchiver.unarchiveObjectWithData(value) as? NSData
        }
        return nil
        },
        toJSON: { (value: NSData?) -> NSData? in
            return value
        }
    )

The crash happens 
stack trace...

swift_initClassMetadata_UniversalStrategy
type metadata accessor for TransformOf<NSData, NSData>
.....
.....

**Comment by piresbruno** [comment]
+1

**Comment by piresbruno** [comment]
@Kofktu witch version of Xcode are you running?
I can reproduce the issue running Xcode 7.3, Swift 2.2 and an iPhone 4 running iOS 7.1.2

**Comment by piresbruno** [comment]
I believe this is a Swift 2.2 compatibility issue with iOS 7, just tested with an version of Object mapper that i know for a fact was running well, and i got the same crash with XCode 7.3

**Comment by Kofktu** [comment]
@piresbruno i got the same crash with XCode 7.3

**Comment by piresbruno** [comment]
@Kofktu just did a full rollback to Xcode 7.3 / Swift 2.1 in my project, updated ObjectMapper to v1.1.5 and have no problems with iOS 7 anymore

**Comment by piresbruno** [comment]
@tristanhimmelman is ObjectMapper dropping iOS 7 compatibility?
With the latest release, it's still crashing when executing transformations in devices running iOS 7 and Swift 2.2 / Xcode 7.3

**Comment by tristanhimmelman** [comment]
@piresbruno ObjectMapper has not officially supported iOS 7 since iOS 9 was released. I do not plan on investigating iOS 7 bugs, however if you find a solution to the problem, I am happy to accept pull requests with fixes.

**Comment by piresbruno** [comment]
Was going to take a few hours to check if i could fix the compatibility issue with iOS 7.1, and it seems @tristanhimmelman @Kofktu, that is was automagically fixed in Xcode 7.3.1

**Comment by tristanhimmelman** [comment]
@piresbruno Thanks for looking into this. Closing this off
