### ISSUE TITLE
What are some useful operations to do in the map's init ?

### ISSUE THREAD

**Issue by LeonardBonfils** [Hearst-DD/ObjectMapper#421]
I understand how to do a basic implementation of this library after having used it for a project I'm working on. However, I don't quite understand the sort of operations one might do inside the map's initialization function ?

In the examples, the init is empty. I've kept my inits empty and ObjectMapper still works fine, but of course I want to know if there are ways to initialize the map in a different way ? or just in general, what might one want to include inside the map's init ?

**Comment by tristanhimmelman** [comment]
Hi @LeonardBonfils, please see #357 .

I plan to add more documentation about the init? function in the README but I have not had a chance yet.
