### ISSUE TITLE
get the origin key name

### ISSUE THREAD

**Issue by mrchenhao** [Hearst-DD/ObjectMapper#423]
if I user 
```
self.desc <- map["description"]
```

How can I can the remote key `description ` if I only know the key `desc`

**Comment by tristanhimmelman** [comment]
Sorry but I do not follow your question. Are you still having this problem?

**Comment by mrchenhao** [comment]
yes , I still have this problem , I use 
```
self.desc <- map["description"]
```
in the map method

when I use NSManagedObject `changedValue`, I get the dict 
```
{
'desc':'xxxxxxx'
}

```

but I should use the origin key `description ` to tell the server  like this

```
{
'description':'xxxxxxx'
}


```

this is my problem,can you understand what I meaning, O(∩_∩)O

**Comment by tristanhimmelman** [comment]
If you use `toJSONString` on your object it will create a JSON string using "description" as the key. You could send that to the server. Otherwise I think you may need to replicate the naming convention from the server in your models
