### ISSUE TITLE
Mistake - Expected declaration

### ISSUE THREAD

**Issue by zionix357** [Hearst-DD/ObjectMapper#424]
<img width="1137" alt="captura de tela 2016-03-30 as 19 16 56" src="https://cloud.githubusercontent.com/assets/5609018/14159487/7a465a1e-f6ac-11e5-8c6e-43e037b5d18c.png">

Does anyone know what can it be?

**Comment by tristanhimmelman** [comment]
The last release of ObjectMapper requires Xcode 7.3. 

So you can either update Xcode, or use the previous version of ObjectMapper
