### ISSUE TITLE
Error Domain=NSCocoaErrorDomain Code=3840 "Badly formed object around character 25." UserInfo={NSDebugDescription=Badly formed object around character 25.}

### ISSUE THREAD

**Issue by NALAWALAMURTUZA** [Hearst-DD/ObjectMapper#425]
How i convert my object class to string. when i a used toJSON its convert into dictionary .but i want to convert my object Class  to Json Formate
  
toJSON
 "[\"reminderDateTime\": 2016-04-01T18:07:07 +0530, \"alarmId\": 800428, \"recurrenceOption\": EVERY WEEK]"
but i want in this formate
 {"reminderDateTime": "2016-04-01T18:07:07 +0530", "alarmId": 800428, "recurrenceOption": "EVERY WEEK"}
Please guide me ....

**Comment by tristanhimmelman** [comment]
Have you tried using the `toJSONString` function?

**Comment by NALAWALAMURTUZA** [comment]
Thank For Reply....

**Comment by veeranjain04** [comment]
I am facing this issue despite of using `toJSONString` function
