### ISSUE TITLE
Uniquing conventions for core data

### ISSUE THREAD

**Issue by waltermvp** [Hearst-DD/ObjectMapper#430]
Is there a "recommended" way to structure the mapping to work nicely with core data? Im struggling with how I would approach maintaining unique objects (with identifiers) in Core Data.

**Comment by tristanhimmelman** [comment]
Take a look at the MappableCluster protocol and the associated tests to get an idea how it's used. This protocol will allow you to return an existing object to use for mapping. I have not personally used ObjectMapper with CoreData but I believe this approach is what you are looking for

**Comment by waltermvp** [comment]
@tristanhimmelman thanks for the quick reply will take a look

**Comment by waltermvp** [comment]
@tristanhimmelman seems like this protocol is used to support inheritance with mapping subclasses. If you take a look at `	static func objectForMapping(map: Map) -> Mappable?` it sues a switch statement to branch between types not sure this would work since I can't switch with a identifier attribute. 

Is my understanding correct?

**Comment by tristanhimmelman** [comment]
Yes, this protocol was designed to support inheritance, however, it can also be used to return a cached model to perform mapping on, instead of creating a new instance

**Comment by waltermvp** [comment]
So I would modify 	`static func objectForMapping(map: Map) -> Mappable?` to return a unique model with a unique id?

**Comment by waltermvp** [comment]
Soemthing like this?
```swift


	static func objectForMapping(map: Map) -> Mappable? {
		if let identifier: String = map["id"].value() {
			//Fetch uniqe model from core data here?
			return uniqueManagedObject
		}
		return nil
	}

```

**Comment by tristanhimmelman** [comment]
Yep, exactly. I think that should do the trick

**Comment by waltermvp** [comment]
@tristanhimmelman awesome thanks. i'll close this issue for now and reopen if anything.

**Comment by tristanhimmelman** [comment]
and note, if you need to subclass that object, you will need to switch the `static` keyword with `class`.

**Comment by waltermvp** [comment]
@tristanhimmelman not sure if you get this question often, would you accept a PR that has a core data example for the demo project?

**Comment by tristanhimmelman** [comment]
@waltermvp I'd be happy to accept a PR with a core data example :+1:. I'm assuming you mean including it as a new test as there isn't a demo project

**Comment by waltermvp** [comment]
@tristanhimmelman good to know, expect one this weekend

**Comment by maksTheAwesome** [comment]
Thank you, Tristan for directing me here. I tried adding the following to the NSManagedObject subclasses but objects are still getting duplicated.

```
extension Country: Mappable, MappableCluster {
    
    func mapping(map: Map) {
        name <- map["name"]
        code <- map["code"]
        continent <- map["continent"]
        filename <- map["filename"]
    }
    
    static func objectForMapping(map: Map) -> Mappable? {
        if let name: String = map["name"].value() {
            return Country.country(name, context: CoreDataStack.sharedInstance.managedObjectContext)
        }
        return nil
    }
}
```

It looks like I'm not using it write.

**Comment by maksTheAwesome** [comment]
Thank you. worked for me too.
