### ISSUE TITLE
func mapping(map: Map) called twice -> causes related NSManagedObject's duplicate

### ISSUE THREAD

**Issue by maksTheAwesome** [Hearst-DD/ObjectMapper#433]
Hey guys,

Love your component. It helps me with the project a lot.

Today I've noticed that function `func mapping(map: Map)` is called twice when mapping one object while Mapper<T>().map(response) is called only once. My object has relationships with another object that is being mapped also `country <- map["location.country"]`. And because of that it causes duplication of the property object in the database.
Example:

```
class User: NSManagedObject {
 required init?(_ map: Map) {
        let ctx = CoreDataStack.sharedInstance.managedObjectContext
        let entity = NSEntityDescription.entityForName(User.entityName(), inManagedObjectContext: ctx)
        super.init(entity: entity!, insertIntoManagedObjectContext: ctx)
        mapping(map)
    }
    
    override init(entity: NSEntityDescription, insertIntoManagedObjectContext context: NSManagedObjectContext?) {
        super.init(entity: entity, insertIntoManagedObjectContext: context)
    }

func mapping(map: Map) {
        identifier <- map["_id"]
        name <- map["profile.firstname"]
        lastName <- map["profile.lastname"]
        country <- map["location.country"] //also a subclass of NSManagedObjec
    }
}
```

Where country is also a subclass of NSManagedObject and when mapping called twice country's init method is also called twice which causes a country object to be duplicated in the persistent store

I tried to do something like this:

```
class CountryTransform<T:AnyObject where T:Mappable> : TransformType {
    typealias Object = Country
    typealias JSON = [String : AnyObject]
    
    func transformFromJSON(value: AnyObject) -> Object? {
        if let countryDict = value as? [String : AnyObject] {
            let result = Country.createOrUpdateCountryWithData(countryDict, context: CoreDataStack.sharedInstance.managedObjectContext)
            return result
        }
        return nil
    }
    
    func transformToJSON(value: Country?) -> JSON? {
        return value?.toJSON()
    }
}
```
But I get a compiler error that CountryTransform does not conform the TransformType protocol. Can you guys please help me with it. Also I believe if objects will stop being mapped twice it would increase the component efficiency.

**Comment by tristanhimmelman** [comment]
Hi there, I believe the reason that mapping is called twice is because you include a call to mapping within the `init?` function. You should remove that call as it is handled by the library. Hope this helps

**Comment by maksTheAwesome** [comment]
O-o-oh! That's so obvious! I should stop coding at night. Thank you, Tristan!

**Comment by maksTheAwesome** [comment]
Sorry for bothering again. 
I noticed that the problem with duplication property object in the database is not entirely fixed. The user object does not get mapped twice now but I map it again with the next app launch to check the profile updates. I've created a separate function `createOrUpdateUserWithData` so the user object does not get duplicated but it's dependant property objects are getting duplicated.

I tried to create a transform class to avoid duplication:

```
class CountryTransform<T:AnyObject where T:Mappable> : TransformType {
    typealias Object = Country
    typealias JSON = [String : AnyObject]
    
    func transformFromJSON(value: AnyObject) -> Object? {
        if let countryDict = value as? [String : AnyObject] {
            let result = Country.createOrUpdateCountryWithData(countryDict, context: CoreDataStack.sharedInstance.managedObjectContext)
            return result
        }
        return nil
    }
    
    func transformToJSON(value: Country?) -> JSON? {
        return value?.toJSON()
    }
}
```

But compiles is not agree with me on matter that CountryTransform class conforms protocol `TransformType`.
