### ISSUE TITLE
Priority for map() function?

### ISSUE THREAD

**Issue by daffodilistic** [Hearst-DD/ObjectMapper#434]
Hi,

I was wondering, if let's say I declared the following in the mapping() function:
```swift
	// Our web API doesn't return the field properly ("Name" instead of "FullName")
	// So hence we're declaring this twice
	// This should work?
	fullName        <- map["Name"]
	fullName        <- map["FullName"]
```
And these are my two web API endpoints:
http://www.example.com/GetUserData
(For the user to view their own data)
```json
{ "FullName" : "John Doe" }
```
http://www.example.com/GetUserProfile
(For other users to view this user)
```json
{ "Name" : "John Doe" }
```

1) Is it "safe" to declare it "twice" this way?
2) Would map["FullName"] have "priority" when calling http://www.example.com/GetUserData, as there is no "FullName" field?

**Comment by tristanhimmelman** [comment]
Hi there, yes it is safe to do what you are doing and the last mapping will always have priority.

This is not really an ideal implementation though. For that reason, I am working on a new feature. This feature will allow developers to create a mapping context object that will be passed around during mapping in the `Map` object. This object will store whatever information you want, so you could use it to decide how to perform your mapping. This work is currently in a branch (mappable) which I am hoping to merge soon. See documentation: 
https://github.com/Hearst-DD/ObjectMapper/tree/mappable#mapping-context

**Comment by daffodilistic** [comment]
Hello,

I gave the latest version a whirl, and it's working fine on my project, resulting in cleaner code. Seems pretty nifty. 😃
