### ISSUE TITLE
Duplicated object

### ISSUE THREAD

**Issue by maksTheAwesome** [Hearst-DD/ObjectMapper#436]
Hey guys,

I've met the following issue:
I have the following class `class User: NSManagedObject` that has property of class `class Country: NSManagedObject`. Also I have a list of about 244 countries in database. In the following case I get a duplicated object:
1. User object has country property = `USA`
2. We change user's country to `Great Britain`
3. Fetch user profile from server where user's country model is still `USA` (we did not make a server request to update user's profile so it is fine) and update profile model `ParsingService<User>().updateWith(self, with: userDict)` and local user model again has `USA` as a country property
4. Issue: `updateWith` method appear to change `Great Britain` local model to be identical to `USA` and database would have two objects with `USA` name.

**Comment by maksTheAwesome** [comment]
Is there any way to make ObjectMapper make a new connection if such object already exist?

**Comment by tristanhimmelman** [comment]
Hey there, check this issue out #430 

You can use the MappableCluster protocol to fetch an existing model during mapping.
