### ISSUE TITLE
Subclassing another mappable class throwing initializer error (still)

### ISSUE THREAD

**Issue by kylebegeman** [Hearst-DD/ObjectMapper#437]
I have a class conforming to Mappable and have subclassed to onto another class. Unfortunately, I am still getting the error about using the designated initializer. 

I am simply trying to match the same functionality as in the documentation for ObjectMapper in regards to subclassing.

![screen shot 2016-04-13 at 10 36 43 am](https://cloud.githubusercontent.com/assets/1012880/14503219/ee501d7a-0163-11e6-8f05-f2ca488a1a51.png)

Currently using Xcode 7.3 and Swift 2.1. 

Have tried multiple options both online and my own tinkering with no luck. Any insight would be great, thanks.

**Comment by hwpo** [comment]
I have got the same problem,and no andswer too

**Comment by tristanhimmelman** [comment]
Please see documentation for proper subclass definition https://github.com/Hearst-DD/ObjectMapper#subclasses
