### ISSUE TITLE
Mapping unnamed arrays

### ISSUE THREAD

**Issue by funky-monkey** [Hearst-DD/ObjectMapper#439]
Hi Tristan, 

I'm running into a problem with mapping of unnnamed arrays in JSON. How would you go about this?
`[
  {
    "id": 1,
    "name": "Tag 1",
    "slug": "tag-one"
  },
  {
    "id": 2,
    "name": "Tag 2",
    "slug": "tag-two"
  }
]`

I cant figure out how to model this in ObjectMapper. Any ideas?

Best, 
Sidney

**Comment by tristanhimmelman** [comment]
Hi there, you should be able to handle this as follows:
```
class Item: Mappable {
	var id: Int?
	var name: String?
	
	init?(_ map: Map) {
		
	}
	
	func mapping(map: Map) {
		id <- map["id"]
		name <- map["name"]
	}
}
```
Then using the Item class, you can do
```
if let items = Mapper<Item>().mapArray(JSON){

}
```

**Comment by tristanhimmelman** [comment]
Oops didnt realize you had already closed this...

**Comment by catach** [comment]
Hi @tristanhimmelman !

I think I've a real unnamed array :) 

How should I map a variable array like `["1", "2", "3"]`? Do I need to create a Mappable class to embed the String? If so, what's the field name?

**Comment by tristanhimmelman** [comment]
@catach Is this the complete response or a sub object? If it is a sub object, I would just map it as a `Array<String>`

**Comment by catach** [comment]
@tristanhimmelman it's the complete response 😄 and you're completely right. I used `responseJSON` from Alamofire and just assigned the result to my String array, as you said. Sometimes we get too obsessed on "serialize all the things" hehehe. Thanks 👍
