### ISSUE TITLE
Really need help Objecting mapping enums

### ISSUE THREAD

**Issue by patchthecode** [Hearst-DD/ObjectMapper#441]
Hey guys. Thanks for the awesome library.

I am really stuck on how i should go about converting a JSON response to an enum.
Could you provide an example on this?

**Comment by kaandedeoglu** [comment]
[https://github.com/Hearst-DD/ObjectMapper/blob/master/ObjectMapperTests/CustomTransformTests.swift#L196](url)

There's an example in the tests.

**Comment by patchthecode** [comment]
Thank you!.
Closing this.

**Comment by danielrees18** [comment]
For the future traveler, above is a dead link. Here is an [updated one](https://github.com/Hearst-DD/ObjectMapper/blob/master/Tests/ObjectMapperTests/CustomTransformTests.swift#L242)

The skinny of it is that you must pass an `EnumTransform<T>` to your map
`mimeType <- (map["mime_type"], EnumTransform<MimeType>())`
