### ISSUE TITLE
Question: Combining values

### ISSUE THREAD

**Issue by patchthecode** [Hearst-DD/ObjectMapper#442]
Is there a way to combine values?

Let's say i have a JSON with two keys and values in it

```
Json = 
{ 
   key1: "value 1"
   key2: "value 2"
   key3: "value 3"

}
```

And what if i want to turn it into a class/Structure like this:
```
struct MyStruct: Mappaple {
   var twoCombinedVals: twoCombinedValues?
   var val3: String? 

    init?(_ map: Map) {}
    mutating func mapping(map: Map) {
        twoCombinedVals <- map
        val3 <- map["key3"]
    }

}

struct twoCombinedValues: Mappaple {
   var val1: String?
   var val2: String?
   
    init?(_ map: Map) {}
            
    mutating func mapping(map: Map) {
       val1 <- map["key1"]
       val2 <- map["key2"]
     }
}
```

What is the correct way to combine two values?

**Comment by patchthecode** [comment]
The `MyStruct` structure var called `twoCombinedVals` which is a struct of the combination of 2 json values on the same level. Is there a way to combine those?

**Comment by patchthecode** [comment]
Of maybe i should say.
Is there a way to pass the `map` unto a value like i did above?

`twoCombinedVals <- map`

I want `map` here to refer to the same map "level" and not a subLevel

**Comment by patchthecode** [comment]
This is what i have done in the mean time, but i would still need help to tell me how it should really be done.

I have modified the following private method to allow this let `map[""]` return the current map:

```swift
/// Fetch value from JSON dictionary, loop through keyPathComponents until we reach the desired object
private func valueFor(keyPathComponents: ArraySlice<String>, dictionary: [String: AnyObject]) -> AnyObject? {
	// Implement it as a tail recursive function.
	if keyPathComponents.isEmpty {
		return nil
	}
	
	if let keyPath = keyPathComponents.first {
        let object: AnyObject?
        // MODIFIED TEXT STARTS HERE
        if keyPath == "" {
            object = dictionary
        } else {
             object = dictionary[keyPath]
        }
	 // MODIFIED TEXT END HERE
        if object is NSNull {
			return nil
		} else if let dict = object as? [String : AnyObject] where keyPathComponents.count > 1 {
			let tail = keyPathComponents.dropFirst()
			return valueFor(tail, dictionary: dict)
		} else if let array = object as? [AnyObject] where keyPathComponents.count > 1 {
			let tail = keyPathComponents.dropFirst()
			return valueFor(tail, dictionary: array)
		} else {
			return object
		}
	}
	
	return nil
}
```

**Comment by tristanhimmelman** [comment]
map.JSONDictionary also returns the current Dictionary<String, AnyObject>. 

ObjectMapper doesn't have any built in functionality for combining two keys. I would map the two values to two temporary variables and then combining them manually.

**Comment by namanhams** [comment]
You can do this : 
`
func mapping(map: Map) {
        twoCombinedVals.val1 <- map["key1"]
        twoCombinedVals.val2 <- map["key2"]
        val3 <- map["key3"]
    }
`

**Comment by namanhams** [comment]
Sorry i don't know how to format the code here

**Comment by buscarini** [comment]
I have more or less the same problem, but with an associated enum. I can use map.JSON to parse what I need, but then I can't serialize the JSON back. Is there any way to do that?
