### ISSUE TITLE
Compile Time Error Occur When i add object mapper to my project 

### ISSUE THREAD

**Issue by ankushdhawan** [Hearst-DD/ObjectMapper#443]
public protocol TransformType {
	associatedtype Object                       // Show Error:Expected Declarartion
	associatedtype JSON

	func transformFromJSON(value: AnyObject?) -> Object? //Use of undeclared type 
	func transformToJSON(value: Object?) -> JSON? //Use of undeclared type object
}

I do not know what is issue and how it resolve. I am using alamophire and realm in my project

**Comment by tristanhimmelman** [comment]
The latest version of ObjectMapper requires Xcode 7.3. Either update xcode or add the previous release of ObjectMapper to your project.
