### ISSUE TITLE
No idea how to map specific JSON

### ISSUE THREAD

**Issue by tomaszwojcik** [Hearst-DD/ObjectMapper#444]
I'm implementing an iOS app for existing project and got stuck on parsing a JSON containing list of events, where key for each event is a "timestamp": [ array of events during that date ].

It looks like this:
List of places with ids, containing list of events, where the keys are dates.

```
[
   {
      "place_id":1,
      "events":[
         {
            "1460604671":[
               {
                  "event_name":"some name",
                  "other_event_field":1
               }
            ],
            "2460604671":[
               {
                  "event_name":"some name",
                  "other_event_field":1
               }
            ]
         }
      ]
   }
]          
```

Is it possible to map that structure with ObjectMapper?

**Comment by patchthecode** [comment]
yes. it is

**Comment by tomaszwojcik** [comment]
I would like to get a list of Places that contains a list of all events, something like this:

PlaceList -> array of places
Place -> place_id, array of events
Event -> date (from the timestamp that is problematic for me), event_name, other_event_field

Thanks for the quick response.

**Comment by patchthecode** [comment]
What i mean is, can you show what you want the structure that you want the JSON be mapped to look like?
```
struct MyEventPlacesStruct {
   ????
}
```

**Comment by tomaszwojcik** [comment]
Sure.

```
struct PlaceEvents {
    var placeId: Int
    var events: [Event]
}

struct Event {
    var date: NSDate
    var name: String
    var otherField: String // for the sake of this example. I can handle all other fields except the date thing in the json format
}
```

Any my API should return [PlaceEvents] (for multiple places).

**Comment by tristanhimmelman** [comment]
ObjectMapper provides several different functions which you can use for mapping. I think the following is probably what you are looking for:
```
public func mapDictionaryOfArrays(JSONDictionary: [String : [[String : AnyObject]]]) -> [String : [N]]?
```

Also available:
```
public func map(JSON: AnyObject?) -> N?
public func mapArray(JSONArray: [[String : AnyObject]]) -> [N]?
public func mapDictionary(JSONDictionary: [String : [String : AnyObject]]) -> [String : N]?
```

**Comment by patchthecode** [comment]
@tristanhimmelman hi, is there any documentation giving an example of how those methods are used?

**Comment by tristanhimmelman** [comment]
Unfortunately, not at the moment. Given a JSON string, you should be able use the functions just like you use `Mapper<T>.map(JSON)`. So in your case, it would look something like:
```
let JSONString = "..."
if let dictionary = Mapper<Person>().mapDictionaryOfArrays(JSONString){
			
}
```
