### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Leverin** [Hearst-DD/ObjectMapper#447]
Thank you for an overall great lib! I appreciate the effort you put into making this.

Today I ran Apple's leak detector tool Instruments and discovered this:

![nscfstring](https://cloud.githubusercontent.com/assets/5451399/14854100/9135dec8-0c8e-11e6-84cb-2bf988ae6304.png)

I'm afraid I don't have much else to contribute with. Do you have any theories on what causes this and/or how to fix it?

Tested on/with
iOS: 9.2.1 (13D15)
Xcode version: 7.3 (7D175)
Device: iPad Air 2 (A1566)

**Comment by namanhams** [comment]
Can you post the line of code that you use ObjectMapper to parse ?

**Comment by tristanhimmelman** [comment]
Due to inactivity I am closing this issue. Please comment if you are still seeing this leak and have more info to help debug.
