### ISSUE TITLE
Request for Documentation: `init?(_ map: Map)` implementation

### ISSUE THREAD

**Issue by SimplGy** [Hearst-DD/ObjectMapper#448]
I'm not sure what to put in the `required init?(_ map: Map)` method. In all the examples in the readme it's blank except for the subclass.

I'd like to have some properties (eg: `id`) be required, and fail the init if they do not--can I use the init implementation to enforce required properties? Is it for something else?

I'm just not seeing how the init connects with the mapping function I guess. I can't really call init, the Mappable library does that for me?

Sorry I'm not sure how exactly to phrase this question. I can't tell what piece of the puzzle I'm missing. Probably lots of them :)

Here's what I have so far:
```swift
class StarWarsPerson: Mappable, CustomStringConvertible {
  
  var id:   String
  var name: String?
  var hairColor: String?
  var eyeColor: String?
  
  var description: String { return "[\(id)] \(name)" }
  
  // MARK ObjectMapper
  required init?(_ map: Map) {} // (!) Variable self.id used before being initialized, since it's not optional
  func mapping(map: Map) {
    id        <- map["url"]
    name      <- map["name"]
    hairColor <- map["hair_color"]
    eyeColor  <- map["eye_color"]
  }
}
```

**Comment by JamesZeinzu** [comment]
+1, looks like at the moment you cant have non optional properties, or at least I cant figure out how to have them as optional. The examples all have optional or explicitly unwrapped(var id: String!) properties. If someone more experienced could shed some light on this it would be appreciated :)

**Comment by tristanhimmelman** [comment]
Here is the documentation for `init?(_ map: Map)`
https://github.com/Hearst-DD/ObjectMapper#mappable-protocol

Non optional properties are only supported by ObjectMapper if they are initialized prior to serialization. This can happen when they are declared or within `init?`

**Comment by SimplGy** [comment]
Oh, so is this:

    if map["name"].value() == nil {
        return nil
    }

Sort of the "manual" version of this syntax?

    name <- map["name"]

Meaning I could implement non optional properties in this way?

```swift
class StarWarsPerson: Mappable, CustomStringConvertible {
  
  var id:   String
  var name: String
  var hairColor: String?
  var eyeColor: String?
  
  var description: String { return "[\(id)] \(name)" }
  
  // If a star wars person doesn't have a name and id in the JSON, fail the initialization of the object.
  required init?(_ map: Map) {
    if let id = map["id"].value() {
      self.id = id
    } else { return nil }
    if let name = map["name"].value() {
      self.name = name
    } else { return nil }
  }

  // ...The rest can map optionally
  func mapping(map: Map) {
    hairColor <- map["hair_color"]
    eyeColor  <- map["eye_color"]
  }
}
```

**Comment by tristanhimmelman** [comment]
Yes you can do that. The value() function will only work for basic types (String, Bool, Int etc) though. 

You should know that when creating JSON, ObjectMapper only uses the `mapping` function. This means that in your example above, your name and id properties would not get written to the JSON output. You can always include the mapping twice if you need the none optional variables and the toJSON functionality
