### ISSUE TITLE
Difficult to react to an inability to parse

### ISSUE THREAD

**Issue by SimplGy** [Hearst-DD/ObjectMapper#449]
Sorry to take up your time again, hopefully this is useful to you.

There are models I work with that have substantially similar content, but the apis have minor differences. For these, I'd like to be able to do something like:

```swift
  func mapping(map: Map) {
    id = <- map["place_id"] ?? map["id"] // Either location for id
    name = <- map["name"] ?? map["name.0"] // Either position for name
  }
```

This doesn't work of course, as the `<-` function mutates an `inout` param: `public func <- <T>(inout left: T, right: Map)`, so instead I do:

```swift
  func mapping(map: Map) {
    placeId       <- map["place_id"]  // if from google places api
    waitressId    <- map["id"]        // if from Waitress api
    name          <- map["name"]      // if from google places api
    if name == nil {
      name        <- map["name.0"]    // if from Waitress api
    }
  }
```

Another approach would be to use a custom transform like `nameFromEitherLocation`. Maybe this is the idiomatic way for this library?

I guess there are two questions:

1. What is the recommended way to detect a failure to parse (to log warnings, to take corrective action, etc)?
1. Is there a good reason not to redesign `<-` as something like `prefix operator <- {}`, `public func <- <T>(right: Map) -> T?`. (or even just `func <T>setMapping(map: Map) -> T?`) (The only reason I wonder is a return value lets us test against a successful and unsuccessful parse. Maybe theres an issue with enforcing symmetrical-ity with this approach?

**Comment by SimplGy** [comment]
Noting this is similar in part to https://github.com/Hearst-DD/ObjectMapper/issues/260, feel free to close if it raises no new questions.

**Comment by tristanhimmelman** [comment]
Hey there, sorry for such a delayed response to this.

The best approach to using one model class with two different APIs is to use the MapContext functionality within ObjectMapper https://github.com/Hearst-DD/ObjectMapper#mapping-context

This will allow you to define a MapContext object is passed around during mapping. You can define which API is being used within the MapContext and switch based on the info within your mapping function.

Hope this helps!
