### ISSUE TITLE
Carry a context when mapping

### ISSUE THREAD

**Issue by jsgoupil** [Hearst-DD/ObjectMapper#451]
I am trying to transform some Object that gets its value from another service. The knowledge of that service is done at mapping time. Even though I use a CustomTransform, it is really complicated to go get that service for handling the data.

Your `Map` and `Mapper` class are final, and everything converges with the `toJSON`

The only solution I have right now is this ugly subclassing where I do

```
class Parent {
    var myService: ABService?
    public func toSpecialJSONString(withService: ABService) -> String {
        self.myService = withService
        let data = self.toJSONString()!
        self.myService = nil
        return data
    }
}
```

```
class A : Parent {
    var value: Custom!

    override public func mapping(map: Map) {
        value              <- (map["value"], IdTransform(service: myService))
    }
}
``` 

I think it would be beneficial to carry some kind of context, or having a way to new up `Map` with a subclass, or start with my own `Mapper(withService: myService)`

**Comment by tristanhimmelman** [comment]
Hi @jsgoupil, I agree that this could be a useful addition. 

I have added this functionality on a branch I am working on https://github.com/Hearst-DD/ObjectMapper/tree/mappable

Hopefully I can merge it into master soon.

**Comment by jsgoupil** [comment]
@tristanhimmelman That looks great! Awesome 👍

**Comment by tristanhimmelman** [comment]
This has now been merged into master. Closing this. Thanks for the idea @jsgoupil
