### ISSUE TITLE
Mapping in array of nsdictionary to mappable class using object mapper

### ISSUE THREAD

**Issue by Raghvendra7** [Hearst-DD/ObjectMapper#452]
Hi everyone ,
i m using almofire object mapper to parse json and save it to coredata .its working fine but in some case i have to store parameter which i send to post request api into coredata model which i create with mappable protocol the parameter which i send is array of [String:NSobject ] so i have to map it into my coredatamodel class using mapping protocol but since param array is not have same protocol it not allowing it.

**Comment by tristanhimmelman** [comment]
Sorry but I understand your question... are you still having this issue?
