### ISSUE TITLE
ObjectMapper for Xcode 7.2

### ISSUE THREAD

**Issue by karnakar** [Hearst-DD/ObjectMapper#454]
Installed latest pod version, but there are errors after installation, what version can i use to work on Xcode 7.2

**Comment by ofirdagan** [comment]
+1

**Comment by tristanhimmelman** [comment]
Hey there,
You should be able to use any version prior to 1.2
https://github.com/Hearst-DD/ObjectMapper/releases

**Comment by ofirdagan** [comment]
I upgraded my xcode and it solved the issue.
