### ISSUE TITLE
Adjustable behaviour when JSON containing nil

### ISSUE THREAD

**Issue by LakhV** [Hearst-DD/ObjectMapper#457]
Hey.
Version 1.2.0 broke my app due to new feature "JSON containing nil objects is no longer ignored". The thing is that my object properties are initialised by default values before mapping hence are not nil always. Now I have to go through the all mapping functions to check whether JSON value is nil or not for each property.
I reverted back to 1.1.5 and looking forward to having an option in the framework to configure the behaviour whether to ignore nil or not. Thanks.

**Comment by at-daonv** [comment]
I think there are many users still need `null` value instead `nil`.

**Comment by zendobk** [comment]
I have a workaround with `Map.isKeyPresent` flag, hope this help.

**Comment by tristanhimmelman** [comment]
I have added an option in the `Map` subscript to ignore nil values on this branch:
https://github.com/Hearst-DD/ObjectMapper/tree/ignore-nil-option

So your mapping would look something like:
```
name <- map["name", ignoreNil: true]
```

What do you all think of this solution?

**Comment by namanhams** [comment]
I think that looks very clean. Awesome !

**Comment by tristanhimmelman** [comment]
Great. When I have a chance, I will add some tests and merge into master.

**Comment by LakhV** [comment]
Is it possible to have global option in the framework or on Mapper level?

**Comment by tristanhimmelman** [comment]
@LakhV potentially we could do that. I will think about it some more

**Comment by tarangpatel** [comment]
When will the ignore-nil-option available in master ? I need this feature but cant get it to work. Any work around until its available ? Thanks

**Comment by tristanhimmelman** [comment]
@tarangpatel, I haven't had a chance to properly test the branch. I need to add unit tests before safely merging back to master. 

For the mean time I recommend you use the branch directly.

**Comment by tristanhimmelman** [comment]
The ignoreNil flag has been merged into master.

**Comment by tarangpatel** [comment]
Awesome. thank you.

**Comment by tarangpatel** [comment]
I tried to pod update but the pod is not showing latest changes. 
Any idea ?

**Comment by tristanhimmelman** [comment]
The code is in master, but I haven't created a new release yet.

**Comment by tarangpatel** [comment]
oh ok. I will have to wait for the new release then.

**Comment by RebecaMartin** [comment]
Morning!
I just need this ignoreNil but It doesn't work for me and I don't know why.

I have a date, and the mapper shows:
startDate <- (map["started_date", ignoreNil: true], ISO8601ServerDateTransform())
However this field is not included on JSON :(
I tried to modified ISO8601ServerDateTransform(), but no results.
Could you help me? Thanks!
