### ISSUE TITLE
DateTransform crashing

### ISSUE THREAD

**Issue by opnsystems** [Hearst-DD/ObjectMapper#46]
With the following on Xcode 6.1 and SWIFT I'm getting a crash on the following function in Transforms/DateTransform.swift:

override public func transformToJSON(value: ObjectType?) -> JSONType? {
        if let date = value as? NSDate {
            return (Double(date.timeIntervalSince1970) as JSONType)  // crashes here <------
        }
        return nil
    }

The class triggering the error is:

class Test: Mappable {
    var dob: NSDate?
    required init() {}
    func map<N>(mapper: Mapper<N>)
    {
        dob <= (mapper["dob"], DateTransform<NSDate, Int>())
    }
}

It is invoked as:

var t = Test()
t.dob = NSDate()
let js = Mapper().toJSONString(t, prettyPrint: true)
println(js)

**Comment by tristanhimmelman** [comment]
I believe you have a bug in the date mapping line. It should look like this:
```
dob <= (mapper["dob"], DateTransform<NSDate, Double>())
```
