### ISSUE TITLE
DateTransform is Not working Properly

### ISSUE THREAD

**Issue by gmansata6290** [Hearst-DD/ObjectMapper#460]
I have tried to use DateTransform from JSON to Objects. but date is not getting converted properly.
"Fri May 13 2016 18:30:05 GMT+0800 (SGT)" i m receiving date from server. but not able to convert to NSDate. Can somebody help me out in this?

**Comment by namanhams** [comment]
May be you can post some code here ?

**Comment by gmansata6290** [comment]
Below is  my Model Class

import UIKit
import ObjectMapper
class Model: NSObject, Mappable
{
    var posted_on : NSDate!
    override init()
    {
        super.init()
    }
    convenience required init?(_ map: Map) 
    {
        self.init()
    }

    func mapping(map: Map)
    {
        let dateFormatter = NSDateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        dateFormatter.timeZone = NSTimeZone(name: "UTC")
        posted_on <- (map["posted_on"], DateFormatterTransform(dateFormatter: dateFormatter))
    }
}

while gettting the response from the server end 
let allModel =  Mapper\<Model\>().map(responseJSON.rawString()!)

i am using SwiftyJSON for JSON response and from JSON converting to raw string. and then mapping from raw string to my Model

all the other data is getting mapped with my model but posted_on coming as nil

**Comment by namanhams** [comment]
It's clearly the date format returned from your server is not "yyyy-MM-dd"

**Comment by gmansata6290** [comment]
In the sample I have shown you that way. But I tried all other format also using the above technique. But It was not working as expected. even I tried below also.

 var dateFormatter = NSDateFormatter()
 dateFormatter.locale = NSLocale(localeIdentifier: "en_US_POSIX")
 dateFormatter.timeZone = NSTimeZone(abbreviation: "GMT")
 dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSS" etc.

**Comment by namanhams** [comment]
@gmansata6290 : what formats have you tried ? Clearly "yyyy-MM-dd" will not parse "Fri May 13 2016"

**Comment by gmansata6290** [comment]
@namanhams: I was more playing around with "yyyy-MM-dd'T'HH:mm:ss.SSZ" and I also used ISO8601Datetransform but it didnt work for me. I not so expert in this. Is it possible for you to guide me how can I parse (Fri May 13 2016 18:30:05 GMT+0800 (SGT)) date format?

**Comment by namanhams** [comment]
@gmansata6290 : you need to refer to this http://waracle.net/iphone-nsdateformatter-date-formatting-table/

In your case, Fri is EEE, May is MMM, 13 is dd, 2016 is YYYY, and so on
So the format string should be : "EEE MMM dd YYYY ....." 

My suggestion for you, is to create a test function, try with a simple string first (Eg, "Fri May 13 2016 18:30:05", try until your date formatter works correctly, and then slowly make the string more complicated

**Comment by gmansata6290** [comment]
@namanhams : Thank you so much for your support. I will surely work on the guidelines that you have provided.
