### ISSUE TITLE
Subclassing and Realm

### ISSUE THREAD

**Issue by jpmcglone** [Hearst-DD/ObjectMapper#462]
I have this class

```swift
import ObjectMapper
import RealmSwift

class Base: Object, Mappable {
    dynamic var id: String?
    dynamic var objectType: String?
    dynamic var createdAt: String? // TODO: make sure this gets converted to an NSDate!
    
    required convenience init?(_ map: Map) {
        self.init()
    }
    
    func mapping(map: Map) {
        id <- map["id"]
        createdAt <- map["created_at"]
        objectType <- map["_class"]
    }
}
```

and then I subclass it here:

```swift
import ObjectMapper
import RealmSwift

class User: Base {
    dynamic var username: String?
    dynamic var bio: String?
    
    override func mapping(map: Map) {
        super.mapping(map)
        username <- map["username"]
        bio <- map["bio"]
    }
}
```

And it won't build. Some reason, I'm getting this error:
`<unknown>:0: error: must call a designated initializer of the superclass 'Base'`

<unknown> worries me >_<

Is there something I'm missing??

**Comment by jpmcglone** [comment]
Ok, so I figured out that every subclass (we have many) needs to have these `required`s

```swift
    // MARK: - Requireds
    required init() { super.init() }
    required init?(_ map: Map) { super.init() }
    required init(value: AnyObject, schema: RLMSchema) { super.init(value: value, schema: schema) }
    required init(realm: RLMRealm, schema: RLMObjectSchema) { super.init(realm: realm, schema: schema) }
```

I get this is probably more a swift question now, and not a realm or objectmapper question, but can someone explain to me why I need to do this in every subclass? Or is there a way to get it from super?  Calling only super.init on everything makes little sense

**Comment by jpsim** [comment]
This shouldn't be necessary if you remove the `required` from the `required convenience init?(_ map: Map)` declaration.

**Comment by jpmcglone** [comment]
Thanks! I will try this. If it works, you just made the code look 1000x cleaner.

**Comment by jpmcglone** [comment]
Well damn.  `Initializer requirement 'init' can only be satisfied by a `required` initializer in non-final class 'Base'`

**Comment by jpmcglone** [comment]
Unrelated: it's nice to meet a fellow JP.

**Comment by liuxuleidota** [comment]
does any subclass should add Initializer
`required convenience init?(_ map: Map) {
        self.init()
    }
`
if not,  i got a build error: 
`must call a designated initializer of the superclass`

**Comment by robbiet480** [comment]
Any updates on this? Hitting the same error that @jpmcglone was getting about Initializer requirement...

**Comment by maasim94** [comment]
I have exact same error following help me to solve it, i'm not sure if it is correct way but it solves my problem
basically i don't call super.init in child class
//Base class

class CookJson:Object, Mappable {
    dynamic var cookID:Int = 0
    dynamic var cuts_id:Int = 0
    dynamic var doneness:String = ""
    dynamic var duration:String = ""
    dynamic var tempreature:String = ""
    override class func primaryKey() -> String {
        return "cookID"
    }
    required convenience init?(_ map: Map) {
        self.init()
    }
    func mapping(map: Map) {
        cookID <- map["id"]
        cuts_id <- map["cuts_id"]
        doneness <- map["doneness"]
        duration <- map["duration"]
        tempreature <- map["tempreature"]    
    }
}
//Child class
class CookbyWeightJson:CookJson {
    dynamic var high_weight:String = ""
    dynamic var low_weight:String = ""
    required convenience init?(_ map: Map) {
        self.init()
    }
    override func mapping(map: Map) {
        super.mapping(map)
        high_weight <- (map["high_weight"])
        low_weight <- map["low_weight"]
    }
}

**Comment by robbiet480** [comment]
@maasim94 Just tried your code and got this error:

```
<unknown>:0: error: must call a designated initializer of the superclass 'Entity'
/Users/robbiet480/Repos/HomeAssistant/HomeAssistant/Entity.swift:77:26: note: convenience initializer is declared here
    required convenience init?(_ map: Map) {
```

**Comment by chrixrux** [comment]
Any updates on this topic? I'm getting the same error as @robbiet480

**Comment by geodesicer** [comment]
I use the following in my base class (called RBase), and in addition this solves AFAIK the update problem in writing a JSON from within a Realm write:

class RBase: Object, Mappable {
    
    dynamic var filename = ""
    dynamic var id = NSUUID().UUIDString
    dynamic var idz = "" {
        didSet {
            idz = id
        }
    }
    dynamic var rType: String = ""
    
    internal override init(value: AnyObject)
    {
        super.init(value: value)
        rType = String(self.dynamicType)
    }
    
    required init() {
        super.init()
        rType = String(self.dynamicType)
    }
    
    required init?(_ map: Map) {
        if let theType = map.JSONDictionary["rType"] {
            if let theString = theType as? String {
                if theString == String(self.dynamicType) {
                    super.init()
                    return
                }
            }
        }
        
        return nil
    }
    
    required init(value: AnyObject, schema: RLMSchema) {
        super.init(value: value, schema: schema)
        rType = String(self.dynamicType)
    }
    
    required init(realm: RLMRealm, schema: RLMObjectSchema) {
        super.init(realm: realm, schema: schema)
        rType = String(self.dynamicType)
    }
    
    override class func primaryKey() -> String? {
        return "id"
    }

    func mapping(map: Map) {
        filename <- map["filename"]
        rType <- map["rType"]
        idz <- map["id"]
        idz <- map["idz"]
    }
}

**Comment by MadeByDouglas** [comment]
Anyone find a clean solution to this?

**Comment by jpmcglone** [comment]
We're still just adding the required inits unfortunately. At least I can make it a copy paste solution that goes at the bottom (or top) of the file.  /shrug

**Comment by MadeByDouglas** [comment]
ok, looks like ill do that too then, cant find a better alternative

**Comment by tristanhimmelman** [comment]
I have just released v1.5.0. This update now allows ObjectMapper to be implemented purely within an extension. Using the updated `StaticMappable` protocol, you will only need to implement the following two functions:
```
mutating func mapping(map: Map)
static func objectForMapping(map: Map) -> BaseMappable?
```

This should make working with Realm significantly easier. Hope this helps!

**Comment by jpmcglone** [comment]
I'll try it some time this week @tristanhimmelman

**Comment by robbiet480** [comment]
Can the 1.5.0 changes be merged into the Swift 3 branch?

**Comment by tristanhimmelman** [comment]
@robbiet480 they already have been :)

**Comment by robbiet480** [comment]
Whoops, didn't notice, just saw the merge commit. Thanks @tristanhimmelman! I plan to test this out at some point today and will report back.

**Comment by robbiet480** [comment]
@tristanhimmelman Looks like this change may have broken AlamofireObjectMapper. 
<img width="892" alt="screen shot 2016-09-07 at 4 41 21 pm" src="https://cloud.githubusercontent.com/assets/18516/18332259/0a27d266-751a-11e6-95ea-f20ea758c5a1.png">

If you are going to go fix that, I'd suggest that https://github.com/tristanhimmelman/AlamofireObjectMapper/pull/137 gets merged beforehand to fix the Alamofire class renaming that occurred in the last few days.

**Comment by tristanhimmelman** [comment]
@robbiet480 I have updated AlamofireObjectMapper to work with the latest Alamofire using Xcode 8 GM. Let me know if you are still having problems

**Comment by robbiet480** [comment]
@tristanhimmelman Had to make another change to get it working, see https://github.com/tristanhimmelman/AlamofireObjectMapper/pull/143

**Comment by robbiet480** [comment]
With that change this issue appears to be fixed for me!

**Comment by robbiet480** [comment]
@tristanhimmelman I still need to keep the required inits in. Otherwise I get fixable errors that they are missing. So it appears StaticMappable didn't change anything :(

**Comment by tristanhimmelman** [comment]
@robbiet480 StaticMappable and Realm are working fine for me. See the model I am testing for AlamofireObjectMapper
```
class Forecast: Object, StaticMappable {
    dynamic var day = ""
    dynamic var temperature: Int = 0
    dynamic var conditions = ""
    
    class func objectForMapping(_ map: Map) -> BaseMappable? {
        return Forecast()
    }
    
    func mapping(_ map: Map) {
        day <- map["day"]
        temperature <- map["temperature"]
        conditions <- map["conditions"]
    }
}
```

I'm not sure why you are getting errors wrt the initializers. Perhaps you can post your class so we can help you out.

**Comment by robbiet480** [comment]
@tristanhimmelman I got it working! It's because I had a custom `init` function I wrote in my base Entity class. Once I removed that everything worked. Thanks!

**Comment by tristanhimmelman** [comment]
Closing this ticket as the issues should be resolved by using the updated `StaticMappable` protocol

**Comment by mitchtreece** [comment]
@tristanhimmelman Still trying to get this working with Realm. I'm using StaticMappable like this:

```swift
class Parent: Object, StaticMappable {

    dynamic var uid: String = ""
    
    static func objectForMapping(map: Map) -> BaseMappable? {
        return Parent()
    }

    func mapping(map: Map) {
        uid <- map["uid"]
    }

}

class Child: Parent {

    dynamic var name: String = ""

    override func mapping(map: Map) {
        super.mapping(map: map)
        name <- map["name"]
    }

}
```

Everything compiles fine, but mapping these objects fails. After some stepping around, I found that when calling map(), this code in **Mappable.swift** cannot grab the object. It just returns nil.

```swift
...

if var object = klass.objectForMapping(map: map) as? N {
    object.mapping(map: map)
    return object
}
```

Any ideas?

**Comment by robbiet480** [comment]
```swift
static func objectForMapping(map: Map) -> BaseMappable? {
    return Parent()
}
```

My understanding is that `objectForMapping` should be inspecting the incoming `map` and determining what child class the object should be and then returning that class.

**Comment by mitchtreece** [comment]
@robbiet480 Is that the only way? What if the JSON I'm getting is generic (no "type" property).

**Comment by tristanhimmelman** [comment]
@mitchtreece the other solution is to override the objectForMapping function in `Child`:
```
	override class func objectForMapping(map: Map) -> BaseMappable? {
		return Child()
	}
```

Note you will have to change `static` to `class`

**Comment by mitchtreece** [comment]
@tristanhimmelman Wow I can't believed I missed that. That's exactly what I needed. Thank you 😄

**Comment by vincentSuwenliang** [comment]
```
class RegisteredService: Object, StaticMappable {
    dynamic var service_id: Int = 0
    dynamic var client_id: Int = 0
    dynamic var expiry_date: Date?

    class func objectForMapping(map: Map) -> BaseMappable? {
        return TableShared_Time()
    }

    func mapping(map: Map) {

        service_id <- map["service_id"]
        client_id <- map["client_id"]
        expiry_date <- (map["expiry_date"], YMDDateTransform())
        
    }
    
}


class TableShared_Time: Object, Mappable {
    dynamic var creation_time: Date?
    dynamic var last_update_time: Date?
    dynamic var visible: Bool = true
    
    required convenience init?(map: Map) {
        self.init()
    }
    
    func mapping(map: Map) {
        creation_time <- (map["creation_time"], YMDTimeDateTransform())
        last_update_time <- (map["last_update_time"], YMDTimeDateTransform())
        visible <- (map["visible"], BoolTransform())
    }
    
}

```

<img width="427" alt="screen shot 2017-07-03 at 7 04 18 pm" src="https://user-images.githubusercontent.com/26848805/27790293-790051a6-6022-11e7-82b2-d684235deb6f.png">

hi, could you please help me to find out the solution of this error? Use StaticMapple solved the init problem, but can not access the son's property when get response
