### ISSUE TITLE
Is it possible to get more detail message when serialization fails?

### ISSUE THREAD

**Issue by AlexEdunov** [Hearst-DD/ObjectMapper#464]
I got the error: "The operation couldn’t be completed. ObjectMapper failed to serialize response."
I'm working on quite complicated objects. Is it possible to get more detail error message, e.g. which property couldn't be mapped?

**Comment by tristanhimmelman** [comment]
This is something I am thinking about improving as I update the project. Unfortunately for the time being the error messages are not as good as they could be.
