### ISSUE TITLE
sort array in mapping function

### ISSUE THREAD

**Issue by anddygon** [Hearst-DD/ObjectMapper#465]
struct SWProduct: Mappable {
    
    var images = [Image]()
    
    init?(_ map: Map) {
        
    }
    
    mutating func mapping(map: Map) {
        images <- (map["images"], SortTransform())
    }
    
}

extension SWProduct {
    
    struct Image {
        var id = -1
        var url = ""
    }
    
}

How can i sort images by id when mapping? Thank advance

**Comment by tristanhimmelman** [comment]
Unfortunately, ObjectMapper has no functionality to sort arrays during mapping at the moment. 

I do not think that a Transform will work for this scenario because Transforms are performed on each element of an array instead of the whole array at once.
