### ISSUE TITLE
Mapping with Core Data Contexts

### ISSUE THREAD

**Issue by mcblakeb** [Hearst-DD/ObjectMapper#467]
I was wondering if it was possible to map core data objects in a NSManagedObjectContext (not always the default context). Here is an example of what I would like to do: 

            MagicalRecord.saveWithBlock({ (ctx: NSManagedObjectContext) in
                for (_, subJson) in response.data!["Result"] {
                    let tmp = Mapper<ReportTemplate>().map(subJson.dictionaryObject, ctx: ctx)
                    print(tmp)
                }
            })

However, to pass a context into the map function like the example here, I have to modify the protocol. Is there a way to open this up to extension? Or perhaps an approach I haven't thought of?

**Comment by tristanhimmelman** [comment]
See https://github.com/Hearst-DD/ObjectMapper#mapping-context

There is a new feature that allows you to pass an object around during mapping

**Comment by mcblakeb** [comment]
Excellent, that's exactly what I needed. The updated and working code looks as follows: 

```
class MapManagedObjectContext : MapContext {
    var ctx: NSManagedObjectContext
    
    init(context ctx: NSManagedObjectContext) {
        self.ctx = ctx
    }
}
```

```
    required init?(_ map: Map) {
        var context: MapManagedObjectContext?
        if let _context = map.context as? MapManagedObjectContext  {
            context = _context
        } else {
            context = MapManagedObjectContext(context: NSManagedObjectContext.MR_defaultContext())
        }
        // This will throw an exception if context is null, that's ok, it should.
        let entity = NSEntityDescription.entityForName("ReportTemplate", inManagedObjectContext: context!.ctx)
        super.init(entity: entity!, insertIntoManagedObjectContext: context!.ctx)
        mapping(map)
    }
```

And finally: 

```
                for (_, subJson) in response.data!["Result"] {    
                    let ctx = MapManagedObjectContext(context: context)
                    let tmp = Mapper<ReportTemplate>(context: ctx).map(subJson.dictionaryObject)
                    print(tmp)
                }
```
