### ISSUE TITLE
Making mapping generic

### ISSUE THREAD

**Issue by tarangpatel** [Hearst-DD/ObjectMapper#469]
In my application i have JSON response like follow: 
`
{
   "HasError": false,
   "ErrorMessage": "",
"SuccessMessage": "Login success",
"data": { <Dict> }
}
`
Here Dict can be any response object. How can i create mappable response object ?

My assumption is something like this:

```
class ResponseModel: BaseModel {
  var hasError: Bool?
  var errorMessage: String?
  var successMessage: String?
  var data: ResponseData?
  
  required init?(_ map: Map) {
    super.init(map)
  }
  
  override func mapping(map: Map) {
    super.mapping(map)
    
    hasError <- map["HasError"]
    errorMessage <- map["ErrorMessage"]
    successMessage <- map["SuccessMessage"]
    data <- map["data"]
  }
}
```

Where ResponseData is:
```
class ResponseData<T: Mappable>: Mappable {
  var responseData: T?

  required init?(_ map: Map){
  }
  
  func mapping(map: Map) {
    responseData <- map["data"]
  }
}
```

**Comment by tristanhimmelman** [comment]
You can use the following function in the Mappable protocol:
`static func objectForMapping(map: Map) -> Mappable?`

Simply return a different a subclass of ResponseData the matches the given JSON response.
You can inspect map object as follows:
```
static func objectForMapping(map: Map) -> Mappable? {
    if map["type"].value() == "something" {
        return Subclass(map)
    }
    if map.JSONDictionary["type"] == "something" {
        return Subclass(map)
    }
    return nil
}
```

Or you can follow this example: https://github.com/Hearst-DD/ObjectMapper#generic-objects

**Comment by sregg** [comment]
@tristanhimmelman can you use nested objects in `objectForMapping`?
like:
`map["parent.child"].value()`
