### ISSUE TITLE
Removal of toType affects subclassing

### ISSUE THREAD

**Issue by nmccann** [Hearst-DD/ObjectMapper#47]
Hi, in the process of updating my code to accommodate the changes introduced by [this commit](https://github.com/Hearst-DD/ObjectMapper/commit/f377a94e4a0a038500ce49c7a6e71c5ee30a418c), (which removed `toType`), I noticed that my mapping no longer behaves as expected. Specifically, I get the following compiler error when trying to override the `map` method in a subclass that uses generics: `Method does not override any method from its superclass`.

Here is a simplified example of my use case:

```
class Base: Mappable {
    required init() {}
    
    func map<N>(mapper: Mapper<N>) {
        
    }
}

class Sub<T>: Base {
    required init() {
        super.init()
    }
    
    override func map<N>(mapper: Mapper<N>) { //Compiler error
        
    }
}
```

Removing `override` gets rid of the error, but the method on the subclass is never called. Adding a generic to the base class (making it `Base<T>`) seems to fix the problem, but defeats the purpose of my base class (it allows me to pass around instances of the subclass without knowing their generic type).

Do you know of a possible workaround for this? Please let me know if additional info is needed.

Thanks,
Noah

**Comment by tristanhimmelman** [comment]
Hey Noah,

Thanks for pointing out this issue. I was able to reproduce it. The problem is caused by the generic type within the Mappable protocol (something I was never that fond of having).

I just pushed some changes which remove the generic type within the Mappable protocol. This should remove the problem you are having.

Cheers,
Tristan

**Comment by tristanhimmelman** [comment]
By the way, I have included a Test in the ObjectMapperTests.swift file to make sure this functionality doesn't break in the future

**Comment by nmccann** [comment]
Awesome, thank you for the quick response and excellent mapping library :)
