### ISSUE TITLE
(Possible Bug) ObjectMapper is returning an object when should return nil in Swift

### ISSUE THREAD

**Issue by ccarlassare** [Hearst-DD/ObjectMapper#470]
Sorry for troubling, but there is an important issue.

Being short, I have a User object. making some tests, my service returned a JSON with format: {response: "OK"}.

Of course that is not a user, however, passing

Mapper<User>().map(json)

it returned a user with default values, for example, "name" was "", "age" was 0, and so.

Shouldnt it return nil as that JSOSN does not match a user? Or am I wrong?

Thanks in advance!!! Regards!

**Comment by PhilCai1993** [comment]
Mapper<User>().map(json)

**Comment by tristanhimmelman** [comment]
This is not a bug. ObjectMapper does not validate whether an object was is fully mapped or not mapped at all. It simply tries to map any of the defined mappings in the `mapping` function. 

Perhaps in the future we can add some extra validation.
