### ISSUE TITLE
Using AlamoFire/ObjectMapper with Realm Foreign Keys

### ISSUE THREAD

**Issue by dwas** [Hearst-DD/ObjectMapper#471]
Suppose you have two related realm classes you want to map:

Dog.swift
```
class Dog: Object, Mappable {
    dynamic var id: String?
    dynamic var name: String?
    dynamic var owner: Person?

    required convenience init?(_ map: Map) {
        self.init()
    }

    func mapping(map: Map) {
        id <- map["id"]
        name <- map["name"]
        owner <- map["owner]
    }
}
```

Person.swift
```
class Person: Object, Mappable {
    dynamic var id: String?
    dynamic var name: String?

    required convenience init?(_ map: Map) {
        self.init()
    }

    func mapping(map: Map) {
        id <- map["id"]
        name <- map["name"]
    }
}
```

Suppose also that there is already a person in the system, and you request dogs.

How should the dog response come in with a person reference; I don't want the entire person record to be overwritten. For example, if the dog response looks like this:

GET: /dogs
```
[
    {
        "id": "12345"
        "name": "Rex"
        "person": {"id": 12}
    }
]
```

... the person object should still have a name in storage, even though the otherwise empty person object is provided with an id. Is there another way to map a reference? 

Note: I am about to test this, but wanted to find the answer in the documentation. If this answer is in the documentation, I missed it.

**Comment by tristanhimmelman** [comment]
You should implement the following function: https://github.com/Hearst-DD/ObjectMapper#static-func-objectformappingmap-map---mappable

In the function you can query realm for an existing object to use in your mapping. 

Hope this helps
