### ISSUE TITLE
Injecting the managedObjectContext or the CoreDataStack in the init method called by Mapper

### ISSUE THREAD

**Issue by estebancs** [Hearst-DD/ObjectMapper#472]
I'm trying to create a Unit Test to test the mapping of my CoreData object, and I am following the solution here [#68](https://github.com/Hearst-DD/ObjectMapper/issues/68#issuecomment-105831195 ) but I want to try to inject to the Model object the CoreDataStack or the managedObjectContext because I don't like the idea of having a static function or a singleton to retrieve the coreDataStack Object inside the Model class.

Is there anyway to this? To override the init method being called by Mapper `Mapper<User>().map(data)` so I can inject an object in the init?

**Comment by tristanhimmelman** [comment]
The current solution is to use the static `objectForMapping` function. 

Along with that you can create your own MapContext object which will be passed around during mapping. You can store your coreDataStack in there and you won't need a singleton to access it. See:
https://github.com/Hearst-DD/ObjectMapper#mapping-context
