### ISSUE TITLE
Serializing and storing non-mapped properties

### ISSUE THREAD

**Issue by ssnielsen** [Hearst-DD/ObjectMapper#473]
As a measure against making PUT requests that removes/resets user data, I'd like to store non-mapped properties when mapping from JSON to objects and use that info when mapping from objects to JSON.

Imagine the following class:
```
public class Entry: Mappable {
    var id: Int?
    var text: Int?

    public func mapping(map: Map) {
        id <- map["id"]
        text <- map["text"]
    }
}
```

This works well while my REST endpoint follows the same model.
But when the endpoint's model is updated with an additional field - let's say ``title`` - the new field is set to null when I make a PUT request with the JSON from the mapped object that I mapped from JSON from a GET request. I.e. I lose the info.

Of course this could be fixed by updating my mapping and push an app update - and that will often be the case. But as a secondary measure I'd like to save the non-mapped properties such that they can be used to re-create the JSON.

I've played around with writing a base model class as followed:
```
public class BaseModel: Mappable {
    var allProps = [String:AnyObject]()
    
    public required init?(_ map: Map) { }
    
    public func mapping(map: Map) {
        switch map.mappingType {
        case .FromJSON:
            for (key, value) in map.JSONDictionary {
                allProps[key] = value
            }
        case .ToJSON:
            for (key, value) in allProps {
                map.JSONDictionary[key] = value
            }
        }
    }
}
```
But as the the setter on the ``JSONDictionary`` property in the ``Map`` class is inaccessible, this won't do the trick.

Besides forking this (great) library, is there any way of achieving this?

**Comment by tristanhimmelman** [comment]
Unfortunately ObjectMapper doesn't provide any functionality like this. Good luck finding a solution. 

I would maybe recommend versioning your API when new keys are added to the models.
