### ISSUE TITLE
ObjectMapper and Realm's List types

### ISSUE THREAD

**Issue by arden** [Hearst-DD/ObjectMapper#475]
Realm To-Many Relationships types is List. and ObjectMapper is Array OR Set.
ObjectMapper could support RealmSwift List types?

**Comment by gbmksquare** [comment]
I have the same problem.
Currently I'm trying the following workaround. I wonder if you have any other ideas until the problem is fixed?

```Swift
class MyObject: Object, Mappable {
    let tags = List<Tag>()

    required convenience init?(_ map: Map) { self.init() }

    func mapping(map: Map) {
        var tags: [Tag]?
        tags <- map["tags"]
        if let tags = tags {
            for tag in tags {
                self.tags.append(tag)
            }
        }
    }
}
```

**Comment by eikebartels** [comment]
same for me

**Comment by pawin** [comment]
You can use `ArrayTransform`
`items <- (map["items"],ArrayTransform<Item>())`

**Comment by akovalov** [comment]
There is reference to simple extension that can be used https://github.com/Hearst-DD/ObjectMapper#objectmapper--realm

**Comment by eikebartels** [comment]
I guess this issue should be closed. @pawin s solution works perfectly

**Comment by danilValeev** [comment]
I've created an operator which properly fixes this issue. Please, check https://gist.github.com/danilValeev/ef29630b61eed510ca135034c444a98a
With this operator you don't need any additional code or transforms.
`list <- map["name"]`
