### ISSUE TITLE
Filter Fields

### ISSUE THREAD

**Issue by uditbatra** [Hearst-DD/ObjectMapper#478]
Hi,

I want to filter fields.
How to filter.

class BabyNames: Mappable {
    
    var id: Int?
    var name: String?
    var desc: String?
    var gender: String?

    required init?(_ map: Map) {
        
    }
    
    // Mappable
    func mapping(map: Map) {
        id    <- map["id"]
        name         <- map["name"]
        desc      <- map["desc"]
        gender       <- map["gender"]
    }
}

Filter Gender == M

Please help!!!!!!!!!!!!!!

**Comment by brunov0id** [comment]
Hey, you couldn't give other example ?
