### ISSUE TITLE
Mapping array of Mappable Objects

### ISSUE THREAD

**Issue by fcruzsbtv** [Hearst-DD/ObjectMapper#481]
I have a JSON array like this:

`[
{
    "id" : 1,
    "field" : "somevalue"
},
{
    "id" : 2,
    "field" : "somevalue"
}
]`

I find no way to map it to an array of mappable objects, when I try 

`let result = Mapper<[MyObject]>().map(json)`

I get the following error: Type Array<MyObject> does not conform protocol Mappable

**Comment by fcruzsbtv** [comment]
Nevermind I just find out you have a mapArray function, my bad :)

**Comment by lzhlewis2015** [comment]
@fcruzsbtv  what is your function to map it to an array of mappable objects?
