### ISSUE TITLE
Array mapping validity if received a non array object (singular object)

### ISSUE THREAD

**Issue by nissaba** [Hearst-DD/ObjectMapper#482]
Hi. Sorry for the title.. 
Basically, I have this service here that will send a single object instead of an array of 1 object when it only needs to send 1 instead of multiples. 

so for 1 object we get 

{
   "message":"One message"
}

or we getthis JSon for the same request returning multiples results

{
 "message":[
         "Messge 1", "Message 2", "message N"
]
}

It would be useful if mapper would check for the mapping in a way where if the receiving object that is being mapped is an array say for example `var messages: [String]?` and that `messages <- map["messages"]` would work for both JSon response. 

for example a struct such as 

```
Struct MyStruct: Mappeble
{
 var someVar: SomeType?
 var someOtherVar: SomeOtherType?
 var messages: [String]?

... init and so one

 func mapping(map: Map)
 {
   someVar <- map["someVar"]
   someVar <- map["someOtherVar"]
  messages <- map["messages"]
 }
}
```

and this would work for both JSon example I gave above.

**Comment by tristanhimmelman** [comment]
Hi there,

You could try the following:
```
Struct MyStruct: Mappeble {
    var messages: Message?
    var message: [Message]?

... init and so one

    func mapping(map: Map) {
        message <- map["messages"]
        messages <- map["messages"]
    }
}
```

With this set up only `message` or `messages` should be assigned a value during mapping based on the response you get.
