### ISSUE TITLE
Why to create a new Mapper(context: context)?

### ISSUE THREAD

**Issue by cp3hnu** [Hearst-DD/ObjectMapper#483]
Hi,
ObjectMapper is a very good job. I have a question when I study your source code. Why to create a new `Mapper(context: context)`? rather than call directly `map(value, toObject: object)`?
```
public func mapDictionary(JSONDictionary: [String : [String : AnyObject]], toDictionary dictionary: [String : N]) -> [String : N] {
		var mutableDictionary = dictionary
        for (key, value) in JSONDictionary {
            if let object = dictionary[key] {
				Mapper(context: context).map(value, toObject: object)
            } else {
				mutableDictionary[key] = Mapper(context: context).map(value)
            }
        }
        
        return mutableDictionary
    }

```

**Comment by tristanhimmelman** [comment]
I think you are right, this is not necessary. Would you like to create a Pull Request for the fix? If not I will update this myself. Thanks for pointing this out 👍

**Comment by cp3hnu** [comment]
Thank you for your attention. This is a small question, there is no need to create a Pull Request. You can fix it in next version.

**Comment by tristanhimmelman** [comment]
This change will be merged into master shortly
