### ISSUE TITLE
Generic Objects which is Array 

### ISSUE THREAD

**Issue by lizhihui0215** [Hearst-DD/ObjectMapper#484]
```
class ResponseObject<T: Mappable> : Mappable{
    var errorCode: String?
    
    var errorName: String?
    
    var status: String?
    
    var results: T?
    
    required init?(_ map: Map){
        
    }
    
    func mapping(map: Map) {
        errorCode <- map["errorCode"];
        errorName <- map["errorName"];
        status <- map["status"];
        results <- map["results"]
        
        
        
        //        if results is Array {
//            var a = results as! Array
//            a <- map["results"]
//        }
    }
}

```
sorry my poor english

this is a network response object, which has some common fields but the "results" is a Generic type .
when the T which maybe is "Array" 
this will give me error below 
Type 'Array' does not conform to protocol 'Mappable'

**Comment by lizhihui0215** [comment]
Any one help me please

**Comment by lizhihui0215** [comment]
class ResponseObject<T> : Mappable{
    var errorCode: String?

    var errorName: String?

    var status: String?

    var results: T?

    required init?(_ map: Map){

    }

    func mapping(map: Map) {
        errorCode <- map["errorCode"];
        errorName <- map["errorName"];
        status <- map["status"];
        results <- map["results"]



        //        if results is Array {
//            var a = results as! Array
//            a <- map["results"]
//        }
    }
}

I‘am try to change the “T：Mappable” to “T”. But if the T really is a Mappable this given me the result nil ，I hope the “objectmapper” can let us define the “T” not the “T：Mappable” and inside the “objectmapper” if the T not as “Array” or can mappable Object which given the error should be nice.
is there any one agree me？

**Comment by tristanhimmelman** [comment]
Unfortunately ObjectMapper cannot handle generic Arrays at this point.

You will probably need two response objects to satisfy this situation. One with `var results: T?` and one with `var results: [T]?`

The generic type must conform to `Mappable` to be used by ObjectMapper
