### ISSUE TITLE
Mapping an array of Strings using a Model class

### ISSUE THREAD

**Issue by sasojadrovski** [Hearst-DD/ObjectMapper#487]
Hey guys,

Thank you for developing this awesome framework!

I have come across an issue with mapping an array of strings, and I need your help... 
I am not sure whether this is possible, so any feedback will be greatly appreciated.

Lets say we have a response the comes in the following form:
```
[
  "Item1",
  "Item2"
]
```
I would like to have a model class that will conform to the Mappable protocol and in which I will be able to store the values that are returned in this array. Is this even possible?
The documentation states about a method called `mapArray`, but it says that in only works if the array is composed of JSON dictionaries (in this case it is not, there are only strings in the array).

I am using Alamofire for fetching the data from the server and the app is written in Swift.

Thanks in advance!

**Comment by tristanhimmelman** [comment]
Hi there,

In this situation I would recommend accessing the data directly from the Alamofire response. You should be able to simply cast it to `[String]`.

Alternatively, you may be able to subclass `String` and make the subclass `Mappable`, however I think that is more work than necessary for the your situation
