### ISSUE TITLE
More compact syntax that's also more readable imo

### ISSUE THREAD

**Issue by Evertt** [Hearst-DD/ObjectMapper#488]
How about turning this syntax:

```swift
id <- (map["id"], TransformOf<Int, String>(fromJSON: { Int($0!) }, toJSON: { $0.map { String($0) } }))
```

into this:

```swift
id <- (map["id"], transform(from: { Int($0) }, to: { String($0) }))
```

Which would be possible by adding this function to `ObjectMapper/Transforms/TransformOf.swift`:

```swift
public func transform<Object, JSON>(from from: JSON -> Object, to: Object -> JSON) -> TransformOf<Object, JSON> {
    return TransformOf<Object, JSON>(fromJSON: { $0.map { from($0) } }, toJSON: { $0.map { to($to) } }))
}
```

### edit

Or maybe it can be a bit more clear if we'd change the argument names like so:

```swift
id <- (map["id"], transform(left: { Int($0) }, right: { String($0) }))
```

Because then it's easy to remember "okay the left side, which is `id`, contains an Int, and the right side, which is `map["id"]`, contains a string".

**Comment by tristanhimmelman** [comment]
Thanks for your suggestions 👍 . I like the idea of having a convenience function to simplify syntax and usage.

I think I will go with the following to maintain consistency and clarity:
```
transform(fromJSON: { Int($0) }, toJSON: { String($0)})
```

**Comment by tristanhimmelman** [comment]
I am actually having some issues with the above implementation. Not all my tests are succeeding. I do not have time to look into this more carefully, but I would welcome a pull request if you have the time.

Thanks
