### ISSUE TITLE
Class does not conform the protocol 'Mappable' when trying to map object

### ISSUE THREAD

**Issue by redamimouni** [Hearst-DD/ObjectMapper#489]
I would like to map a JSON that I am receiving, but I am getting a message saying that:
Type 'ObjectResponse' does not conform to protocol 'Mappable'.
I created a protocol separately named Mapper.swift, contains:

public protocol Mappable {
    mutating func mapping(map: Map)
    static func objectForMapping(map: Map) -> Mappable?
}

My model named ObjectResponse.swift:

import UIKit
import ObjectMapper

class ObjectResponse: Mappable {

    var r_city: City!
    var r_cod: String!
    var r_cnt: String!
    var r_message: Float!
    var r_list: NSArray!
    
    class func newInstance(map: Map) -> Mappable? {
        return ObjectResponse()
    }
    
    func mapping(map: Map) {
        r_city    <- map["city"]
        r_cod     <- map["cod"]
        r_message <- map["message"]
        r_cnt     <- map["cnt"]
        r_list    <- map["list"]
    }
}

And I'm trying to map using:

let obj = Mapper<ObjectResponse>().map(data)

**Comment by tristanhimmelman** [comment]
You do not need to create the Mappable protocol, it exists already in ObjectMapper. You just need to implement the functions it defines. Please see the Read me or one of the many examples in the ObjectMapperTests directory

public protocol Mappable {
mutating func mapping(map: Map)
static func objectForMapping(map: Map) -> Mappable?
}
