### ISSUE TITLE
Build error in new Xcode 8 beta

### ISSUE THREAD

**Issue by RishabhTayal** [Hearst-DD/ObjectMapper#490]
Getting build error in the beta version of Xcode 8.

![screenshot 2016-06-15 14 19 24](https://cloud.githubusercontent.com/assets/2100166/16094113/43b005b0-3304-11e6-999d-062edea8e2c3.png)

**Comment by batschz** [comment]
I have a working branch over [here](https://github.com/e-Sixt/ObjectMapper)
You can use it in your Podfile like that: 
`pod 'ObjectMapper', :git=> 'git@github.com:e-Sixt/ObjectMapper.git', :branch => 'master'`

I strongly recommend to not use that in production environment...

**Comment by tristanhimmelman** [comment]
Please use the swift-3 branch if you are using xcode 8 beta

**Comment by RishabhTayal** [comment]
Thanks. Here is the branch link for reference: [swift-3](https://github.com/Hearst-DD/ObjectMapper/tree/swift-3)

**Comment by deepp** [comment]
Hi, I am having the same issue with version 1.1.5 ,so i tried using swift-3 branch but as it does not exist ,which version should be used?

**Comment by devxoul** [comment]
@deepp, `swift-3` branch is now merged into `master`. Use `2.0.0` instead.

**Comment by deepp** [comment]
after updating version to 2.0.0 , i got this error while updating pod files.

[!] Unable to satisfy the following requirements:

- `ObjectMapper (= 2.0.0)` required by `Podfile`
- `ObjectMapper (~> 1.0)` required by `AlamofireObjectMapper (4.0.0-beta)`

**Comment by devxoul** [comment]
@deepp `AlamofireObjectMapper 4.0.0` has `ObjectMapper ~> 2.0` dependency. Try using `4.0.0` instead `4.0.0-beta`.
