### ISSUE TITLE
Not serializing Int32

### ISSUE THREAD

**Issue by bithavoc** [Hearst-DD/ObjectMapper#492]
Is there any particular reason why it fails to serialize a field of type `Int32`?

**Comment by tristanhimmelman** [comment]
`Int32` is not supported by default. You need to create a Transform for this type. See this transform that pulled from the Test classes for int64Value

```
(map["int64Value"], TransformOf<Int64, NSNumber>(fromJSON: { $0?.longLongValue }, toJSON: { $0.map { NSNumber(longLong: $0) } }))
```
