### ISSUE TITLE
breaking change from 1.1.5 to 1.3.0 when transforming nil value

### ISSUE THREAD

**Issue by xiaodao** [Hearst-DD/ObjectMapper#493]
We have a code snippet like this:

```
let productTransform = TransformOf<String, String>(
      fromJSON: {(value: String?) -> String? in
        guard let value = nameFromSource else {
          return "standard"
        }
        return value
      },
      toJSON: { _ -> String? in
        return nil
      }
    )

product <- (map["productDepth"], productTransform)
```

We want to set product = "standard" when the json has no "productDepth".

This code snippet when using version 1.1.5, but after we upgraded to 1.3.0, the `productTransform` function is not executed when the json has no "productDepth".

Is here any workaround for this, or what shall we do to fix that?

Thanks.

**Comment by JakeLin** [comment]
I have tried 1.2.0, and it is also an issue as well. The change might be made in 1.2.0.

**Comment by JakeLin** [comment]
We found out where this change is https://github.com/Hearst-DD/ObjectMapper/commit/f72ad154d1f11b2833d4d3e35de68f41e7056d19#diff-5a346d3647f9e826c80411d006520d56R59

We only call `Mapper().map(map.currentValue, toObject: field)` when the `map.currentValue != nil`. Could you please advise how to fit our requirements? How can we apply a default value when the value is `nil`? Thanks.

**Comment by tristanhimmelman** [comment]
You can use the `ignoreNil` flag on individual mappings to get around this issue.
`name <- map["name", ignoreNil: true]`

Unfortunately there is no global setting to change this for all mappings at the moment.
