### ISSUE TITLE
[WiP] Proper 'swift_3.0' branch

### ISSUE THREAD

**Issue by Bersaelor** [Hearst-DD/ObjectMapper#495]
I believe there should be a proper Swift 3 branch of ObjectMapper, so people can build beta versions of their apps using the beta toolchain in preparation for the iOS 10 release. Install would then go like so:

```
pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git', :branch => 'swift_3.0'
```

which then would be merged once Swift 3.0 is live.

@batschz already provided a possible start [here](https://github.com/e-Sixt/ObjectMapper).

Furthermore we should make sure the new branch is in line with the 'Grand Renaming' in Swift 3 and the [Swift API Guidelines](https://swift.org/documentation/api-design-guidelines/). Which means we should not just fix warnings Xcode presents us with but also review our method names to be in line with the new naming scheme.

**Comment by tristanhimmelman** [comment]
I have just created a fresh brand (swift-3) which can be used until swift 3.0 is fully supported. I haven't done any work on it yet as I am a bit strapped for time at the moment. I welcome you all to make PRs on it

**Comment by puneetgoyal08** [comment]
swift-3 branch is not compiling as of now

**Comment by Bersaelor** [comment]
@puneetgoyal08 As @tristanhimmelman said earlier, it's just an empty branch.
Let's give @batschz some time to make a PR for his changes.

**Comment by puneetgoyal08** [comment]
oh cool, I am also liking this library, I will try to contribute as well.

**Comment by tristanhimmelman** [comment]
I have merged the first PR into the swift-3 branch. Everything seems to be functioning properly. Please post here if there are any issues.

**Comment by itman85** [comment]
i got this error when built objectmapper swift-3 branch:

> /Pods/ObjectMapper/ObjectMapper/Core/Operators.swift:723:75: Expected '>' to complete generic parameter list

**Comment by tristanhimmelman** [comment]
The swift-3 branch is now up to date with Xcode beta 4.

**Comment by carobeta** [comment]
Branch has been updated for beta 6?

**Comment by staticdreams** [comment]
@carobeta doesn't look like it. There are some major breaking changes and it wont compile with the new beta :(

**Comment by EvilClay** [comment]
I have created a pull request for the beta 6 swift 3.. until it gets pulled, you can use "EvilClay/ObjectMapper" "swift-3"

**Comment by tristanhimmelman** [comment]
The swift 3 branch has now been merged into master
