### ISSUE TITLE
Init? Validation does not work properly.

### ISSUE THREAD

**Issue by victtavares** [Hearst-DD/ObjectMapper#498]
I'm experiencing a weird bug when using the ` required init?(_ map: Map)` function to validate my JSON.

I have a JSON object that contains a "Email" string field (And others, that I'm ignoring for now). This field is always nil on the init function accessing it by the `value()` function. However, on the `mapping` function it works fine (It's not nil).

Here is the full code that I'm using now:

```
class LoginResponse: Mappable {
    var email: String!
    
    required init?(_ map: Map) {
        
        if map["Email"].value()  == nil {
            print("Email is nil")
        }
    }
    
    func mapping(map: Map) {
        print(map["Email"].value()!)
        email <- map["Email"]
    }   
}
```

It prints the following:

<img width="916" alt="screen shot 2016-06-24 at 8 12 44 pm" src="https://cloud.githubusercontent.com/assets/2566465/16352894/0fba5b6a-3a49-11e6-83aa-62bc8c240bac.png">

A part of the JSON that I'm decoding:

![screen shot 2016-06-24 at 8 21 19 pm](https://cloud.githubusercontent.com/assets/2566465/16352912/4d1649ce-3a49-11e6-93fe-0374ee265f42.png)

---------------------------- EDIT1 ---------------------------- 

The function  `map.JSONDictionary["Email"]` works perfectly.

**Comment by lambreto** [comment]
I have experienced the same problem
This works:
```swift
let temp: String? = map["Email"].value()
if temp == nil {
  return nil
}
```

this also:
```swift
guard let _: String = map["Email"].value() else {
  return nil
}
```

The rule is to explicitly specify the type you want `value()` function to return.
Maybe it is related to the Swift version. I'm using the current latest version of Xcode 7.3.1 with Swift version 2.2

Please fix it or update your documentation

**Comment by tristanhimmelman** [comment]
@lambreto is correct, you need to specify the type being returned from `.value()`. I will update the docs
