### ISSUE TITLE
Possible to call `Mapper` from Objective C?

### ISSUE THREAD

**Issue by chrismanderson** [Hearst-DD/ObjectMapper#499]
I'm looking to initialize classes conforming to Mappable from Objective C, but I can't figure out how to initialize these classes with JSON from Objective C. E.g. I can't access the `Mapper` class in Objective C, and thus can't call something like `[Mapper map:JSONString]`.

Any ideas, or is creating Mappable objects from Objective C just not supported?

**Comment by tristanhimmelman** [comment]
ObjectMapper does not officially support Objective C. It may work but I cannot guarantee any functionality as it is not something I have tested. Good luck

**Comment by simran-lbbd** [comment]
@chrismanderson were you able to find a workaround for this?
