### ISSUE TITLE
how to set Singleton user model

### ISSUE THREAD

**Issue by SeongBrave** [Hearst-DD/ObjectMapper#500]
when login and i get a Singleton  User model ,so how  to set

**Comment by SeongBrave** [comment]
大神们咨询个问题， swift 登陆成功后返回user 对象，你们是用单例模式保存了还是经过传参数呢， 我是用 的ObjectMapper 解析直接实例化user对象，现在不知道怎么用单例模式，请大神们指点下吧

**Comment by tristanhimmelman** [comment]
Sorry I do not understand your question
