### ISSUE TITLE
No control over deserialisation errors when mapping Array<T: Mappable>, Dictionary<String, T: Mappable>, etc.

### ISSUE THREAD

**Issue by svetlyo** [Hearst-DD/ObjectMapper#502]
Let's say we have the following:
```swift
class User: Mappable { ... }

class Service: Mappable {
    var users: [User]?
    . . .

    func mapping(map: Map) {
        users <- map["users"]
        . . .
    )
}
```

If we have some validation in the `User`'s `init?` and it failed for some of the elements this goes unnoticed by `Service` - the `flatMap` used in `mapArray` silently skips the users that fail to map properly to `User` objects. If the value for the "users" key is a JSON array the `users <- map["users"]` mapping always succeeds even if some (or all!) elements failed to deserialise and `Service` has no way of checking for that.

**Comment by tristanhimmelman** [comment]
Unfortunately at the moment there is no error messaging available. This is a feature that I hope to add in the future.
