### ISSUE TITLE
Mapping Nested Array 

### ISSUE THREAD

**Issue by EkambaramE** [Hearst-DD/ObjectMapper#506]
{
	_id: "575a94f4dd4fac56abc4f002",
	hall_name: "hall2",
	row: "4",
	column: "4",
	seat: {
		seats_available: [
			"1_1",
			"1_2",
			"1_3",
			"3_3",
			"3_4",
			"4_4"
		],
		seats_disable: [
			"2_1",
			"2_2",
			"1_4",
			"4_1",
			"4_2"
		],
		blank_area: [
			"3_1",
			"3_2",
			"2_3",
			"2_4",
			"4_3"
		]
	},
	time: [
		"fullday",
		"half_a_day"
	]
}

I'm trying to read "time", "seats_disable" , "seats_available" but its doesn't work :

class Example: Object, Mappable {
    
    dynamic var _id = ""
    dynamic var hall_name = ""
    dynamic var row = ""
    dynamic var column = ""
    
    var time = List<Time>()
    
    override static func primaryKey() -> String? {
        return "_id"
    }
    
    required convenience init?(_ map : Map) {
        self.init()
    }
    
    func mapping(map: Map) {
        
        time <- (map["time"], ListTransform<Time>())

        _id <- map["_id"]
        hall_name <- map["hall_name"]
        row <- map["row"]
        column <- map["column"]
        
    }
    
}

class Time : Object, Mappable {
   
    dynamic var dayTime = ""
    
    required convenience init?(_ map: Map) {
        self.init()
    }
    
    func mapping(map: Map) {
    }
}

**Comment by tristanhimmelman** [comment]
In the Example class above you have not defined any mappings for time, seat_disable or seat_available.

Something like this should work
```
var seatsDisable: Array<String>?

seatsDisable <- map["seats.seats_disable"]
```
