### ISSUE TITLE
SwiftPM support

### ISSUE THREAD

**Issue by TofPlay** [Hearst-DD/ObjectMapper#507]
Hi,
With [Swift 3](https://swift.org/blog/swift-3-0-release-process/) it would also be nice to add support for [SwiftPM](https://swift.org/package-manager/)

Articles about **SwiftPM**:
- [Package.swift — The Manifest File](https://github.com/apple/swift-package-manager/blob/master/Documentation/Package.swift.md)
- [Developing Packages](https://github.com/apple/swift-package-manager/blob/master/Documentation/DevelopingPackages.md)
- [System Modules](https://github.com/apple/swift-package-manager/blob/master/Documentation/SystemModules.md)
- [Swift Package Manager Community Proposal](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageManagerCommunityProposal.md)
 
On your `README.md` add [![SwiftPM Compatible](https://img.shields.io/badge/SwiftPM-Compatible-brightgreen.svg)](https://swift.org/package-manager/)  on top and add section for the installation with SwiftPM.

**Comment by jonasman** [comment]
+1

**Comment by jonasman** [comment]
btw where did you get that badge from?

**Comment by jonasman** [comment]
to support SPM we need to:

- [ ] Change folder structure and add all files under `Sources/`
- [ ] Create `Package.swift` describing the module

**Comment by tobiasoleary** [comment]
Is there a guide on the best way to support SwiftPM, Cocoapods, and Carthage in the same branch?

**Comment by tobiasoleary** [comment]
I couldn't find one on Google.

**Comment by jonasman** [comment]
one of my libs supports cocoapods and SPM: https://github.com/jonasman/MulticastDelegate
The sources folder needs to contain all the files, unless you want to make many modules.
The cocoapods just points there

**Comment by tristanhimmelman** [comment]
Swift PM support has just been merged into master. I will create a release in the coming days.
