### ISSUE TITLE
parse NSNumber response always nil 

### ISSUE THREAD

**Issue by ahmedtahaaroua** [Hearst-DD/ObjectMapper#508]
It's not same as #73

json : 
["expression_literal_id": 1, "value": yes, "id": 1]

mapper

class Answer: NSManagedObject ,Mappable {
    @NSManaged var id: NSNumber?

 override init(entity: NSEntityDescription, insertIntoManagedObjectContext context: NSManagedObjectContext?) {
        let appDelegate =
            UIApplication.sharedApplication().delegate as! AppDelegate
        
        let managedContext = appDelegate.managedObjectContext
        super.init(entity: entity, insertIntoManagedObjectContext: managedContext)
    }
    
    required init?(_ map: Map) {
        let appDelegate =
            UIApplication.sharedApplication().delegate as! AppDelegate
        
        let managedContext = appDelegate.managedObjectContext

       
        let entity = NSEntityDescription.entityForName("Answer", inManagedObjectContext: managedContext)
        super.init(entity: entity!, insertIntoManagedObjectContext: managedContext)
        
        mapping(map)
    }
    
    func mapping(map: Map) {

               id <- map["id"]
 
    }

}
id is always nil

**Comment by tristanhimmelman** [comment]
NSNumbers are not explicitly supported by ObjectMapper but I believe they should map correctly. I'm not sure why this is not working for you. 

Closing this for now, if you are still having this problem feel free to elaborate.
