### ISSUE TITLE
How could I map this JSON structure?

### ISSUE THREAD

**Issue by mariovillamizar** [Hearst-DD/ObjectMapper#509]
How could I map this JSON structure:
{
  "-JxlacPofIQNahrwLlCe" : {
     "name" : "Design Room",
     "online" : false
  },
  "-JxlacSA6rY_urmvr_nU" : {
     "name" : "Development Room",
     "online" : true
  },
  "-Jxlac34PgHGS045Ce" : {
     "name" : "Test Room",
     "online" : true
  },
  ...
}

Suppose that I'm monitoring some devices, which are in the JSON structure. Each device have an identifier, i.e: -Jxlac34PgHGS045Ce. I need to map those devices with its identifier.
I need something like this:

device.objectId = "-Jxlac34PgHGS045Ce"
device.name =  "Test Room"
device.online = true.

Thanks and sorry for my English.

**Comment by lujing666208** [comment]
You can easily create your own custom transforms by adopting and implementing the methods in the TransformType protocol:
```
public protocol TransformType {
    typealias Object
    typealias JSON

    func transformFromJSON(value: AnyObject?) -> Object?
    func transformToJSON(value: Object?) -> JSON?
}
```

**Comment by mariovillamizar** [comment]
@lujing666208 can you explain me a little more?

**Comment by zendobk** [comment]
Hope this help. Sorry about the syntax because I write this with SublimeText.
```
class Device: Mappable {
    func mapping(map: Map) {
        name <- map["name"]
        online <- map["online"]
    }
}

class DeviceListTransform: TransformType {
    typealias Object = [Device]
    typealias JSON = [String: [String: AnyObject]]

    func transformFromJSON(value: AnyObject?) -> Object? {
        guard let json = value as? JSON else { return nil }
        var devices: Object = []
        for key in json.allKeys {
            let device = Device()
            device.id = key
            let info = json[key]
            Mapper<Device>().map(info, toObject: device)
            devices.append(device)
        }
        return devices
    }

    func transformToJSON(value: Object?) -> JSON? {
        // TODO
        return nil
    }
}
```
Implement in other mapping:
```
class User: Mappable {
    func mapping(map: Map) {
        devices <- (map["devices"], DeviceListTransform())
    }
}
```
or get the devices only:
```
let devices = DeviceListTransform().transformFromJSON(json)
```
