### ISSUE TITLE
Sorted keys for json object

### ISSUE THREAD

**Issue by Romixery** [Hearst-DD/ObjectMapper#512]
Hi all
Excuse me for bad English. All JSON library i seen, generate json from object, sorted by keys. For example, Jackson library for java generate json objected default sorted by key names. This is important when i want create Base64 from json object. The priority of keys, impact the base64 string and for exmaple if you want to create key from this string, we get different key for same json object, because base64 string is different !!!
Please set option for sorting keys in json object or generate json by key names by default for compatibility with other libraries.
For example:
`{
	"BKey" : "VALUE 1",
	"CKey" : "VALUE 2",
	"AKey" : "VALUE 3"
}`

Must be in this format:
`{
	"AKey" : "VALUE 3",
	"BKey" : "VALUE 1",
	"CKey" : "VALUE 2"
}`
Thanks.

**Comment by tristanhimmelman** [comment]
I have no plans to add sorting during mapping at this time. Dictionaries are not sorted in swift so you would need to add a new OrderedDictionary type for this to work.

**Comment by SerggioC** [comment]
Actually this is easy to do. 

> I have no plans to add sorting during mapping at this time. Dictionaries are not sorted in swift so you would need to add a new OrderedDictionary type for this to work.

It can be done easily, just enable this option to outside:
https://developer.apple.com/documentation/foundation/jsonserialization/writingoptions/2888322-sortedkeys

I had to change the ObjecMapper source code to enable this option because hashing a json would never return the same value.
