### ISSUE TITLE
Hot can I Parse JSON with dynamic array 

### ISSUE THREAD

**Issue by GuyKahlon** [Hearst-DD/ObjectMapper#513]
I'm trying to parse the following JSON (for http://www.coindesk.com/api/):

  {  "time": {"updated":"Jul 12, 2016 12:59:00 UTC","updatedISO":"2016-07-12T12:59:00+00:00","updateduk":"Jul 12, 2016 at 13:59 BST"},
     "disclaimer" :"This data was produced from the CoinDesk Bitcoin Price Index (USD). Non-USD currency data converted using hourly conversion rate from openexchangerates.org",
    "bpi": { "USD": { "code":"USD","symbol":"$","rate":"654.1700","description":"United States Dollar","rate_float":654.17 },
             "GBP": { "code":"GBP","symbol":"£","rate":"497.6095","description":"British Pound Sterling","rate_float":497.6095 },
             "EUR": { "code":"EUR","symbol":"€","rate":"589.8978","description":"Euro","rate_float":589.8978 }
            }
  }

The "bpi" can be with dynamic currencies, it depends on the user selection. 

I'm trying to do something like this:
```swift 
import Foundation
import ObjectMapper

struct Currecncy: Mappable {
  
  var code: String?
  var symbol: String?
  var rate: String?
  var description: String?
  
  // MARK: - Mappable
  init?(_ map: Map) {
    
  }
  
  mutating func mapping(map: Map) {
    code          <- map["code"]
    symbol        <- map["symbol"]
    rate          <- map["rate"]
    description   <- map["description"]
  }
}

struct Rate: Mappable {
 
  var date: String?
  var disclaimer: String?
  var currecncies: [Currecncy]?
  
  // MARK: - Mappable
  init?(_ map: Map) {
    
  }
  
  mutating func mapping(map: Map) {
    date        <- map["time.updated"]
    disclaimer  <- map["disclaimer"]
    currecncies <- map["bpi"]
  }
}
 
```
Thanks,
Guy

**Comment by tristanhimmelman** [comment]
You can use the following funciton to help with this:
https://github.com/Hearst-DD/ObjectMapper#static-func-objectformappingmap-map---mappable

See `ClassClusterTests.swift` for an example of how it is implemented

**Comment by GuyKahlon** [comment]
@tristanhimmelman Hey, I've tried this solution, it doesn't work.
Can you provide, please 🤒,  a specific example for the JSON above? 

Thanks, 
Guy

**Comment by tristanhimmelman** [comment]
You will need to inspect the JSON to detect which type of class you are parsing in the `objectForMapping` function.

**Comment by GuyKahlon** [comment]
I don't think it's the same problem.
Here the data is the same.
Just the prefix is changed dynamically.

"bpi": { 
"USD": { "code":"USD","symbol":"$","rate":"654.1700","description":"United States Dollar","rate_float":654.17 },
"GBP": { "code":"GBP","symbol":"£","rate":"497.6095","description":"British Pound Sterling","rate_float":497.6095 },
"EUR": { "code":"EUR","symbol":"€","rate":"589.8978","description":"Euro","rate_float":589.8978 }
}

Anyway, For people finding this issue, I solved it like this:


```Swift
import Foundation
import ObjectMapper

struct Currecncy: Mappable {
  
  var code: String?
  var symbol: String?
  var rate: String?
  var description: String?
  
  // MARK: - Mappable
  init?(_ map: Map) {
    
  }
  
  mutating func mapping(map: Map) {
    code          <- map["code"]
    symbol        <- map["symbol"]
    rate          <- map["rate"]
    description   <- map["description"]
  }
}

struct Rate: Mappable {
 
  var date: String?
  var disclaimer: String?
  var currecncies: [String: Currecncy]?
  
  
  init?(_ map: Map) {
    
  }
  
  mutating func mapping(map: Map) {
    date        <- map["time.updated"]
    disclaimer  <- map["disclaimer"]
    currecncies <- map["bpi"]
  }
}
```

@tristanhimmelman thanks for your quick response.
