### ISSUE TITLE
Circular structures

### ISSUE THREAD

**Issue by juangamnik** [Hearst-DD/ObjectMapper#514]
Can you handle circular instance graphs? I.e. `inst1->inst2->inst1`. Frameworks like JSOG (from the Java world) handle these by adding an `@id` reference to the JSON data and each object gets an id-attribute. The deserializer then restores the dereferentiated instance graph. Just want to check before starting to use the framework. `NSCoding` does this in a similar way with `XMLID` when serializing to XML.

**Comment by tristanhimmelman** [comment]
This is not supported out of the box, however, you can build a custom transform that returns an object from a local cache based on an ID. 

Issue #309 is where this functionality was added. Hopefully this helps.
