### ISSUE TITLE
Keep order of elements as in the JSON

### ISSUE THREAD

**Issue by o15a3d4l11s2** [Hearst-DD/ObjectMapper#516]
Having the following JSON response:
```json
{
   "users":[
      {
         "id":3,
         "name":"Zzz"
      },
      {
         "id":10,
         "name":"Kkk"
      },
      {
         "id":2,
         "name":"Aaa"
      }
   ]
}
```

is there a way to keep the order of the elements exactly like in the response?
In the database I would like to put a new property "order", but I do not know how to populate it from the response.

**Comment by tristanhimmelman** [comment]
I believe the order of arrays should be maintained when mapping. So you should be able to loop through your elements and assign an order value after the mapping is completed (this could be at the end of the `mapping` function).

**Comment by o15a3d4l11s2** [comment]
Are there any options if I have the response like
```
[
   {
      "id":3,
      "name":"Zzz"
   },
   {
      "id":10,
      "name":"Kkk"
   },
   {
      "id":2,
      "name":"Aaa"
   }
]
```
