### ISSUE TITLE
Is it safe to create an NSDateFormatter inside of the mapping function? Will it be called many times if it is trying to map an array?

### ISSUE THREAD

**Issue by patchthecode** [Hearst-DD/ObjectMapper#518]
Is it safe to create an NSDateFormatter inside of the mapping function? Will it be called many times if it is trying to map an array?

**Comment by tristanhimmelman** [comment]
The `mapping` function is called once per mapped object. I will leave it up to you whether you think this is safe or not, however IMO NSDateFormatter objects are light weight enough to be created on the fly
