### ISSUE TITLE
How to map object (Object Mapper)?

### ISSUE THREAD

**Issue by tijana258** [Hearst-DD/ObjectMapper#520]
This is my code:

`import Foundation
import Alamofire
import ObjectMapper

class User: Mappable{

    
    private var _userID: Int;
    private var _username: String!;
    private var _languageID: Int;
    private var _organizationID: Int;
    private var _password: String!;
    
    var userID: Int{
        
        return _userID
    }
    
    var username: String{
        
        return _username
    }
    var languageID: Int{
        
        return _languageID
    }
    var organizationID: Int{
        
        return _organizationID
    }
    var password: String{
        
        return _password
    }
    
    init(username: String, password: String){
        
        _username = username
        _password = password
        
    }
    
    required init?(_ map: Map) {
       
    }
    
    func mapping(map: Map) {
        userID <- map["USER_ID"]
        username <- map["USERNAME"]
        languageID <- map["LANGUAGE_ID"]
        organizationID <- map["ORGANIZATION_ID"]
        password <- map["PASSWORD"]
    }
    
    let JSONString = Mapper().toJSONString(User, prettyPrint: true)

}`

and i really can't understand why it doesn't work.

It says it has error at first line ("does not conform to protocol"), even if  i import ObjectMapper on the beginning of the file.

I am also using cocoapods.

It also has error in func maping("Use of unresolved identifier mapper").

It is obvious that I'm making a big mistake, but i don't understand what is happening. If could someone explain me how it works i would be really appreciate.

**Comment by josejuanqm** [comment]
Unrelated (maybe) but that should cause an error at mapping function because you are setting the getters, those variables are get only. you need to use the "_" prefixed variables

**Comment by tristanhimmelman** [comment]
Thanks for the answer @josejuanqm. Closing this
