### ISSUE TITLE
Bad Access when non optional field doesn't come with json

### ISSUE THREAD

**Issue by abdbarjoud** [Hearst-DD/ObjectMapper#523]
i have this class
import Foundation
import ObjectMapper

class OSListing: Mappable {
    
    let id: Int
    let title:String
    let memberId:Int
    let memberUserName:String
    let memberName:String
    let memberAvatar:String

    required init?(_ map: Map) {
        
        id = map["id"].valueOrFail()
        title = map["title"].valueOrFail()
        
        memberId = map["memberId"].valueOrFail()
        memberUserName = map["memberUserName"].valueOrFail()
        memberName = map["memberName"].valueOr("")
        memberAvatar = map["memberAvatar"].valueOr("")
        if !map.isValid {
            return nil
        }
    }
  
     func mapping(map: Map) {
    }
}

when Json object doesn't contain the key "memberUserName", it give me the EXEC_BAD_ACCESS
in file Map.swift , function valueOrFail, line return pointer.memory, instead of normal fail

**Comment by zendobk** [comment]
- Did you try using `<-` operator?
- After that, moving all binding to the `mapping` func, excect `id`.

**Comment by abdbarjoud** [comment]
<- operator doesn't give me the ability to set default value, which i need it

**Comment by zendobk** [comment]
Can you change `let` to `var` and set a default value for them?

**Comment by abdbarjoud** [comment]
in this case won't the value being overwritten with nil if it the JSON has null value for it ?

**Comment by zendobk** [comment]
Please check [this release](https://github.com/Hearst-DD/ObjectMapper/releases/tag/1.2.0).
The attribute will be set to `nil` if JSON value is `null`.
