### ISSUE TITLE
What is the difference between AlamofireObjectMapper and this ObjectMapper?

### ISSUE THREAD

**Issue by rlam3** [Hearst-DD/ObjectMapper#524]
What is the difference between AlamofireObjectMapper and this ObjectMapper?

**Comment by tristanhimmelman** [comment]
ObjectMapper is a library that handles conversion of JSON to model classes. 

Alamofire is an HTTP Request library

AlamofireObjectMapper is an extension for Alamofire that uses ObjectMapper to automatically map requests that return JSON in models.
