### ISSUE TITLE
Realm + ObjectMapper + PrimaryKey

### ISSUE THREAD

**Issue by piv199** [Hearst-DD/ObjectMapper#526]
I have a class

```
class Dog: Object, Mappable {
   dynamic var code = NSUUID.UUIDString
   dynamic var name = ""

   required init?(_ map: Map) {
   
    }

    mutating fun mapping(map: Map) {
         code <- map["code"]
         name <- map["name"]
    }

    //required by Object inits

    override func primaryKey() -> String? { return "code" }
}
```

I created this class in my application and now I want send it to server

```
var dog = Dog()
try! Realm().beginWrite()
let json = dog.toJSONString(pretyprint: false)
try! Realm().endWrite()
```

And it crashes thus saying I cannot modify primaryKey - its because of <- operator its inout. What could be done to solve this situation?

**Comment by tristanhimmelman** [comment]
There are many conversations about ObjectMapper + Realm in the closed issues which I believe will answer your question. 

Good luck

**Comment by dipkasyap** [comment]
@tristanhimmelman  Too rude :(
