### ISSUE TITLE
Need Swift 2.3 and 3.0 supports

### ISSUE THREAD

**Issue by Stjng** [Hearst-DD/ObjectMapper#528]
After upgrade to Xcode 8. I cannot use this plugin anymore. Please update to support Swift 2.3. Thanks!

**Comment by itman85** [comment]
I using Xcode 8, whenever i install pod again, it asks me convert objectmapper to current swift 3.0 syntax.

**Comment by tristanhimmelman** [comment]
You need to use the swift-3 branch if you are using Xcode 8.

**Comment by zendobk** [comment]
@Stjng poor you, kaka
