### ISSUE TITLE
Nesting on object level

### ISSUE THREAD

**Issue by kubajakowski** [Hearst-DD/ObjectMapper#534]
Is it possible to map flat structure and nest it on object level?
Having a JSON like this:
```
{
	"name": "John",
	"age": 29,
	"street": "Loop st",
	"city": "Some"
}
```

I would like to map User object and have nested address property:

```
let user = Mapper<User>().map(JSON)

struct User
{
	var name: String!
	var age: Int!
	var address: Address!

	mutating func mapping(map: Map)
    {
    	name <- map["name"]
    	age <- map["age"]
    	address <- map //here I would like to pass full map, without key because structure is flat
    }

}

struct Address
{
	var street: String!
	var city: String!

	mutating func mapping(map: Map)
    {
    	street <- map["street"]
    	city <- map["city"]
    }
}
```

Is it possible somehow?

**Comment by tristanhimmelman** [comment]
ObjectMapper does not provide this exact functionality.

But you could achieve this by mapping street and address to local variables within the mapping function and then using them to create the Address object within the mapping function.

Hope this helps

**Comment by kubajakowski** [comment]
@tristanhimmelman that's interesting - never thought about it in this way. I think it really should be in readme.md (I mean mapping to local variable)
Thanks, and btw - great job!

**Comment by dinaraja** [comment]
@tristanhimmelman Thanks for an idea.

But, it is a valid scenario. We can have one root key to parse both child and parent object. If we manually create the object, won't that defeat the actual purpose of ObjectMapper?

If there is any plan to implement this feature, please direct me to see that. Thanks.
