### ISSUE TITLE
Expose Map currentKey  as public property.

### ISSUE THREAD

**Issue by shshalom** [Hearst-DD/ObjectMapper#535]

**Comment by tristanhimmelman** [comment]
Please provide a reason for your request

**Comment by shshalom** [comment]
I wanted to create a merge functionality and in my case i needed the current key so I could test against it.

**Comment by tristanhimmelman** [comment]
Oh ok. Feel free to create a pull request with your functionality. You can change the visibility of the currentKey variable within your Pull Request

**Comment by shshalom** [comment]
I still trying to figuring out how to do this.

The way I'm doing it right now (without actually relaying on ObjectMapper existing functionality),
is by having a Dictionary extension:  

```swift
extension Dictionary  {
    
    public func merge(dictionary: Dictionary) -> Dictionary {
        
        var result = Dictionary()
        
        self.forEach {(key,value) -> Void in
            _ = result.updateValue(value, forKey: key)
        }
        
        dictionary.forEach { (key, value) -> Void in
            if value is Dictionary, let v1 = result[key] where v1 is Dictionary {
                let dicValue = (v1 as! Dictionary).merge(value as! Dictionary) as! Value
                _ = result.updateValue(dicValue, forKey: key)
            }else{
                _ = result.updateValue(value, forKey: key)
            }
        }
        
        return result
    }
}
```
and then creating an extension for Mappable:

```swift
extension Mappable {
    mutating func merge<T:Mappable>(object:T) {
        let json = self.toJSON().merge(object.toJSON())
        mapping(Map(mappingType:.FromJSON, JSONDictionary: json))
    }
} 
```
There's must be a way to create the merge functionality without going back and forth,  Mappable object -> JSON and merged JSON to Map object..

Your thoughts?
