### ISSUE TITLE
objectForMapping not called

### ISSUE THREAD

**Issue by maksTheAwesome** [Hearst-DD/ObjectMapper#546]
Hello guys.

I've updated pods (ObjectMapper (1.4.0)) a moment ago and had found out that `func objectForMapping(map: Map)` not called anymore when I call `ParsingService<NSManagedObjectInheritant>().parseObject(Object)`.

It causes objects being duplicated. Please advise if I should use other function now.

UPD: Installed version 1.3. It works fine.

**Comment by jpstern** [comment]
objectForMapping(map: Map) was moved into 
protocol StaticMappable: Mappable {
...
}

Replace Mappable with StaticMappable wherever you need to use objectForMapping

**Comment by tristanhimmelman** [comment]
Thanks @jpstern

**Comment by jakecraige** [comment]
I also ran into this recently and it took some time to debug. 

I would have much preferred this to come with a version 2.0 ObjectMapper since this was a breaking change. Is there a particular reason it wasn't?

**Comment by tristanhimmelman** [comment]
@jakecraige my mistake, this change definitely warranted a major version number change.
