### ISSUE TITLE
Saved realm object is not getting convert into the JSON

### ISSUE THREAD

**Issue by kamarshad** [Hearst-DD/ObjectMapper#548]
Hello @tristanhimmelman 
Thanks for writing such elegant library for JSON Object mapping 👍 .
I am facing a weird issue with the JSON mapping. Actually, I am not able to convert the saved realm object(see the else statement) into the JSON but unwritten(object those going to write into the disk) realm object is easily getting convert into the JSON(see the If block statement). 
I am also using the AlamofireObjectMapper, which automatically converts JSON response data into swift objects using ObjectMapper.

        func fetchContacts()   {
        Alamofire.request(.GET, url).responseArray { (response: Response<[Contact], NSError>) in
     
        //Persist the response and converting the realm object into the JSON successfully.

            if let contactsArray = response.result.value {
                let contactsDictionaryArray: NSMutableArray = []
                dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), {
                    autoreleasepool {
                        for contact in contactsArray {
                            // Get the default Realm
                            let realm = try! Realm()
                            try! realm.write {
                                print("contact ", contact);
                                //That deserialization has to be done after the write block
                                let contactParam = Mapper().toJSON(contact);
                                print("JSONString ", contactParam);
                                contactsDictionaryArray.addObject(contactParam)
                                realm.add(contact)
                            }
                        }
                    }
                })
            }
           //Incase if no data or request could not processed check the saved data and convert it into the JSON
            else{
                let contactsDictionaryArray: NSMutableArray = []
                dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), {
                autoreleasepool {
                // Get the default Realm
                let defaultRealm = try! Realm()
                let savedContacts:Results =   defaultRealm.objects(Contact.self)
                for contact in savedContacts {
                try! defaultRealm.write {
                    //That deserialization has to be done after the write block
                    print("contact  ", contact);
                    //Actuall problem is here below method returns the blank JSON only even contact object having proper values in it.    
                    let contactParam = Mapper().toJSON(contact);
                    print("JSONString ", contactParam);
                    contactsDictionaryArray.addObject(contactParam)
                    }
                    }
                   }
                   })
                  }
                  }
               }
 
I am not able to find out the reason behind this weird issue. Any suggestion is highly appreciated.
Thanks!

**Comment by tristanhimmelman** [comment]
Hi there, are you still having this issue? Unfortunately I have not worked with Realm and ObjectMapper together very much so I don't have much insight into what the issue might be

**Comment by kamarshad** [comment]
No right now I am not working on it. But for my curiosity will continue it after 1-2 days and will share  the information If I find the same issue again. Thanks for your gentle reply @tristanhimmelman

**Comment by tristanhimmelman** [comment]
@kamarshad I am closing this for the time being. If you ware still having the problem, you can post here and I will reopen the issue. Thanks
