### ISSUE TITLE
Do not overwriting null (no exist) values

### ISSUE THREAD

**Issue by eikebartels** [Hearst-DD/ObjectMapper#555]
The following scenario. (using Realm) 

I'm parsing an object i.e. 

```
{
 id=10
 name= "awesome"
 description = "awesome description"
}
```

at a later state I want to override the object with the following 

```
{
 id=10
 name= "awesome 2"
}
```

I would like to keep the `description` value and only override `name` 

What would be the solution to do this?

**Comment by A1iAshoor** [comment]
+1 same question

**Comment by eikebartels** [comment]
I just checked the implementation and from the current implementation it seems there is no way to avoid this. 

`<-` implementation 
```
public func <- <T>(inout left: T?, right: Map) {
		FromJSON.optionalBasicType(&left, object: right.value())
}
```
2nd step 

```
class func optionalBasicType<FieldType>(inout field: FieldType?, object: FieldType?) {
		field = object
}
```

I guess to solve this issue we have to implement something. 

@Hearst-DD any suggestion for this?

**Comment by eikebartels** [comment]
Ok what about we are creating an enum 

```
public enum MappingOverwriteType {
    case Overwrite
    case OverwriteIfNotNil
    case NotOverwrite
}
```

And a new `operator` function i.e. 

```
/// Optional object of basic type
public func <- <T>(inout left: T?, right: (Map , MappingOverwriteType)) {
    switch right.0.mappingType {
    case .FromJSON where right.0.isKeyPresent:
        FromJSON.optionalBasicType(&left, object: right.0.value(), override: right.1)
    case .ToJSON:
        ToJSON.optionalBasicType(left, map: right.0)
    default: ()
    }
}
```

And extending the "writing" functions? i.e. 
```
class func optionalBasicType<FieldType>(inout field: FieldType?, object: FieldType?, override:MappingOverwriteType = .Overwrite) {
        
        switch override {
        case .Overwrite:
            field = object
            break
        case .OverwriteIfNotNil:
            if let object = object {
            field = object
            }
            break
        case .NotOverwrite:
            guard let field = field else {
                return
            }
        }
	}
```

I'm happy to do that but I would like to hear your thought before I do it.

**Comment by eikebartels** [comment]
@A1iAshoor  

To have a easy quick and dirty solution you could write a helper function like this 


```
    func mapIt (inout object:String?, key:String, map:Map) {
        if let _ = map[key].currentValue {
            object <- map[key]
        }
    }
```

Example:
`var name:String? `
 `mapIt(&name, key: "nameStr", map: map)`

**Comment by tristanhimmelman** [comment]
Hey guys, unless something is broken, absent JSON keys should not be nullifying your objects during mapping. See the `isKeyPresent` flag:
```
case .fromJSON where right.isKeyPresent:
		FromJSON.basicType(&left, object: right.value())
```
If the key is not present mapping should not be happening.

There is a test for this in `NullableKeysFromJSONTests.swift` in the function `func testMapperAbsentValues()`

Are you using the latest version of ObjectMapper?

**Comment by eikebartels** [comment]
Hey @tristanhimmelman 

thanks for pointing this out. 
Then it seems there is an issue. The vales get overwritten from the relations. 

ie

Product 
```
{
 id=10
 name= "awesome Product"
 description = "awesome Product description"
}
```
Look 
```
{
 id=88
 name= "awesome Look"
 description = "awesome Look description"
 products [
  {id = 10} /// at this stage all values get overwritten 
]
}
```

**Comment by eikebartels** [comment]
Ok I had another deeper look into this and `right.isKeyPresent` works correct. 
This issue comes not from ObjectMapper. The problem is realm. 

Sorry for the trouble!

**Comment by tristanhimmelman** [comment]
@eikebartels Arrays are not supported when mapping on to an object. This is because it is not safe to assume that an element is the same based on its position in an array.

If the products were stored in a dictionary instead this would not be a problem because ObjectMapper knows how each key in the dictionary maps to the JSON

**Comment by tristanhimmelman** [comment]
@eikebartels glad you found the root of the issue!

**Comment by A1iAshoor** [comment]
@eikebartels what should be a clean solution now?

**Comment by eikebartels** [comment]
@A1iAshoor  I don't have one yet... Its tricky. especially if you have relations

**Comment by A1iAshoor** [comment]
@eikebartels the way I finally fixed it is by using this method in mapping function:

```
func mapping(map: Map) {
    param = self.getValue(id: id) ?? <default-value>
}

func getValue(id: Int) -> Bool? {
    return Realm.object(ofType: Theater.self, forPrimaryKey: id)?.param
}
```

still not convinced, and as you concluded this is not ObjectMapper issue but Realm.
