### ISSUE TITLE
Mapping context - Cannot convert value of type 'X' to expected argument type 'Map'

### ISSUE THREAD

**Issue by gsabran** [Hearst-DD/ObjectMapper#558]
I'd like to use the mapping context to pass objects that have already been parsed, but it seems there's a type mismatch because I'm getting the error `Cannot convert value of type 'User' to expected argument type 'Map'`

I've a `User` class that impelements the `Mappable` protocol:
```swift
public class User: Mappable {
  ...
}
```

and a class `Item`:

```swift
struct UserContext: MapContext {
  let user: User
}

public class Item: Mappable {
  public var id: String
  public var owner: User

  public init(
    id: String,
    owner: User
    ) {
    self.id = id
    self.owner = owner
  }

  required public init?(_ map: Map) {}

  public func mapping(_ map: Map) {
    id <- map[FieldNames.id]

    if let context = map.context as? UserContext {
      // use context to make decisions about mapping
      let user = context.user
      owner <- user
    } else {
      let user = Mapper<User>().map(map["owner"])
      owner <- user
    }
  }
}
```

The lines `owner <- user` fails, even though the variable `user` is of type `User`, as is the attribute `owner`. It seems that Swift is excepting `owner` to receive a variable of type `Map`

**Comment by tristanhimmelman** [comment]
The `<-` is meant to be used with a variable on the left and a `Map` object on the right. 

`owner <- user` is not a valid usage of the operator.

**Comment by gsabran** [comment]
I see, nice. Thanks
