### ISSUE TITLE
[Question] Dictionary key transformation

### ISSUE THREAD

**Issue by matuslittva** [Hearst-DD/ObjectMapper#563]
Is there any way to transform dictionary key ? I need to transform JSON from [String: AnyObject] to [NSDate: AnyObject]

**Comment by tristanhimmelman** [comment]
You should be able to create a custom transform to achieve this. Or alternatively you can do some post processing after you map to `[String: AnyObject]`.

See the following transform as a starting place: https://github.com/Hearst-DD/ObjectMapper/blob/master/ObjectMapper/Transforms/DictionaryTransform.swift

Hope this helps
