### ISSUE TITLE
Error: cannot invoke initializer for type 'XPNews' with no arguments

### ISSUE THREAD

**Issue by xiaopn166** [Hearst-DD/ObjectMapper#564]
My code : 

`
import Foundation
import ObjectMapper

class XPNews: Mappable {
    var newsId:String?
    var newsTypeStr:String?
    var newsThumb:String?
    var newsTitle:String?
    var newsTime:NSDate?
    
    required init?(_ map: Map) {

    }
    
    func mapping(map: Map) { 
        newsId <- map["newsId"]
        newsTypeStr <- map["newsId"]
        newsThumb <- map["newsId"]
        newsTitle <- map["newsTitle"]
        newsTime <- (map["newsTime"],DateTransform())
    }
}

`

Use:
I wan't to write a demo and test it , like: 
`
let model:XPNews = XPNews() //This place is compile error 

model.newsId = "1"
model.newsTypeStr = "TestType"
` 
Error Info :" cannot invoke initializer for type 'XPNews' with no arguments"

**Comment by happiehappie** [comment]
May I ask what's the reason for closing this?

**Comment by ManWithBear** [comment]
Cauz it's not framework issue.
Error saying: "Your object don't have initializer without parameters, so object can't be created in this way"
