### ISSUE TITLE
Get compile error when run on XCode 8: Generic parameter 'N' could not be inferred

### ISSUE THREAD

**Issue by Huy-Vu** [Hearst-DD/ObjectMapper#571]
I have this compile error when trying to run in XCode 8 GM

```
class Data: Mappable {
.....
}

class PostData {
...
    func transferData (data:Data) {
    ...
   var dataDict: Dictionary<String, AnyObject> = Mapper().toJSON(data) // error: Generic parameter 'N' could not be inferred
   ....
   }
}
```

Any one have the same issue ? Any fix or work around will be appreciated!
Thank you,

**Comment by juliengdt** [comment]
You miss the name parameter to .toJson() function. Or make it optional with "_".

Swift 3.0 refactoring stuff

BTW, wait for 1.5 version, seems to be released soon

**Comment by csersurya** [comment]
try data.toJSON()

**Comment by tristanhimmelman** [comment]
toJSON returns a `Dictionary<String, Any>` not `AnyObject`. Try either of the following
```
var dataDict: Dictionary<String, Any> = Mapper().toJSON(data)
var dataDict = Mapper().toJSON(data)
```
