### ISSUE TITLE
Version 3 not added to cocoapods repo

### ISSUE THREAD

**Issue by borut-t** [Hearst-DD/ObjectMapper#573]
You should push update to the cocoapods repo, swift 3.0 public release is here.

**Comment by juliengdt** [comment]
+1 need to update the repo version for cocoapod.

FYI, the Moya/ObjectMapper dependency is waiting for it (no pressure :D )

**Comment by tristanhimmelman** [comment]
I'm working on it. I attempted to push last night when I made the release, however the `pod trunk` utility was throwing errors when building the project. Hopefully I can resolve this asap

**Comment by tristanhimmelman** [comment]
Problem solved. Had to include a `.swift-version` file for cocoapods to function correctly

For reference: https://github.com/CocoaPods/CocoaPods/pull/5841

Let me know if you have any issues

**Comment by juliengdt** [comment]
clap clap !! 👏
