### ISSUE TITLE
Want to use the ObjectMapper for Swift 2.2 using Git submodule

### ISSUE THREAD

**Issue by kamarshad** [Hearst-DD/ObjectMapper#574]
Hello Hearst-DD

I want to use this library for swift 2.2 and like to integrate it using the submodule. Any help would be highly appreciated

**Comment by tristanhimmelman** [comment]
Hi there, you will need to use v.1.3.0 or earlier for swift 2.2. With regards to including the project as a submodule, you should be able to do this like you would with any other submodule.

Hope this helps.

**Comment by kamarshad** [comment]
Thanks @tristanhimmelman 👍
