### ISSUE TITLE
how to custom transform the string value to NSNumber using objectMapper Swift ?

### ISSUE THREAD

**Issue by sundarsan** [Hearst-DD/ObjectMapper#576]
I am implementing objectMapper in CoreData Model Classes.And also please find the below code for your reference 

        Direction   <- ( map["Direction"] , TransformOf < NSNumber , String >(fromJSON: { $0 == nil ? nil : NSNumber(integer:Int($0!)) }, toJSON: { $0.map { String($0) } }) )

**Comment by tristanhimmelman** [comment]
Your attached example looks like it should work. 

Please look through some of the Test classes to see more examples of transform.
