### ISSUE TITLE
Swift 3 Error 

### ISSUE THREAD

**Issue by alexsanderkhitev** [Hearst-DD/ObjectMapper#577]
I made migration to Swift 3, I use this framework and I get this framework from the specific swift-3 branch. But I get Xcode error “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

My pod file 
pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git', :branch => 'swift-3'

I saw it in the terminal window Installing ObjectMapper 1.4.0 (was 1.4.0) then I opened the swift-3 branch popspec and I saw incorrect version for this branch. I think error because of it.

https://monosnap.com/file/JooapeSwo8b1lvvwGbuuuqDTYDUriF

How can I fix it?

**Comment by tristanhimmelman** [comment]
Please use v2.0.0. I have already merged the swift-3 branch back into master.

Let me know if you are still having issues when you use that
