### ISSUE TITLE
Swift 3.0 Errors

### ISSUE THREAD

**Issue by dylankbuckley** [Hearst-DD/ObjectMapper#579]
See below buildtime errors. Why is this happening?

<img width="329" alt="screen shot 2016-09-15 at 15 30 53" src="https://cloud.githubusercontent.com/assets/8408005/18553767/a34fd7aa-7b59-11e6-875a-42e8267d0b9f.png">

**Comment by tristanhimmelman** [comment]
Are you using Xcode 8?

I would need a bit more information to understand your problem. The 2.0.0 release is running well for me with no compilation issues

**Comment by michelalbers** [comment]
I get lots of errors as well :( 

XCode Version:

![Xcode Version 8](https://abload.de/img/bildschirmfoto2016-09qdyqc.png)

Errors:

![Errors](https://abload.de/img/bildschirmfoto2016-095wl8i.png)

... and a lot more :'(

**Comment by eciftcioglu** [comment]
I had the same problem.I found out my pod was outdated and it was pulling the wrong version of objectmapper. Updating pods and installing worked for me.

**Comment by nicorsm** [comment]
I'm experiencing the same issue with Xcode 8.0 (8A218a). Tried to update and reinstall pods but with no result. Xcode reports 235 compile-time errors, same type as @michelalbers . Using cocoapods 1.0.1

**Comment by tristanhimmelman** [comment]
Have you tried cleaning out the derived data folder? Option + Shift + CMD + K

**Comment by nicorsm** [comment]
Yes. Now I installed v1.4.0 and it works fine.

**Comment by Ssrana** [comment]
@tristanhimmelman I'm using v1.5.0 I'm getting the same multiple errors as asked above. I've cleaned the derived data folder and also cleaned project the tried building, no luck. Any suggestions?
