### ISSUE TITLE
pod specification to install ObjectMapper for Swift 3

### ISSUE THREAD

**Issue by jperera84** [Hearst-DD/ObjectMapper#581]
Hello,
Sorry I know this is not an issue but I can't find a way to install the ObjectMapper version that run with swift 3.
Could anybody help me please?
Thanks

**Comment by cristiansimioni** [comment]
You should use the 2.0.0 version.

`pod 'ObjectMapper', '~> 2.0.0'`

**Comment by jperera84** [comment]
Thanks @cristiansimioni I appreciate your help, I installed but I got the following error when I compile the project:
/Users/jperera/Documents/GitRepository/MySecurityAccount/MySecurityAccount/Contact.swift:10:8: Module file was created by an older version of the compiler; rebuild 'ObjectMapper' and try again: /Users/jperera/Library/Developer/Xcode/DerivedData/MySecurityAccount-cgpdohozsvhpevhjubironbdencq/Build/Products/Debug-iphonesimulator/ObjectMapper.framework/Modules/ObjectMapper.swiftmodule/x86_64.swiftmodule

Any idea of this?

**Comment by cristiansimioni** [comment]
I was facing something similar this week. I solved it following the steps below:

1) On Xcode, navigate to Product and hit Clean
2) Close Xcode
3) Open a console and delete DerivedData folder
    `cd ~/Library/Developer/Xcode/`
    `rm -rf DerivedData/`
4) Open Xcode and try again.

**Comment by snehasen1990** [comment]
Same issue trying clean build .....but no luck
