### ISSUE TITLE
Problem with Xcode8 and ObjectMapper

### ISSUE THREAD

**Issue by diogorborges** [Hearst-DD/ObjectMapper#586]
When I updated my Xcode to 8 and swift3 I got this following error below:

`framework module ObjectMapper {
  umbrella header "ObjectMapper-umbrella.h"

  export *
  module * { export * }
}

module ObjectMapper.Swift {
    header "ObjectMapper-Swift.h" **_ #// Header 'ObjectMapper-Swift.h' not found_**
}`

**Comment by devxoul** [comment]
@diogorborges, how did you setup ObjectMapper in you project?

**Comment by tristanhimmelman** [comment]
I am closing this issue until further reply.
