### ISSUE TITLE
Considerations when source JSON changes version

### ISSUE THREAD

**Issue by efc** [Hearst-DD/ObjectMapper#588]
I just ran into a situation where I had to change my model from an old version that stored an identifier as a `String` to a new version that stored an identifier as an `Int`. I could derive the `Int` from the old strings easily enough, but I could not find a way to use ObjectMapper to gracefully facilitate this repair when reading in serializations of the old model.

Here is a stripped down example:
```swift
class Gizmo: Mappable {
    
    var version: Int
    var id: Int?
    
    internal func mapping(map: Map) {
        version <- map["v"]
        id <- map["id"]
    }

    required init?(map: Map) { }

    func reset(fromJson json: String) {
        guard let newGizmo = Mapper<Gizmo>().map(JSONString: json) else {
            return
        }
        if newGizmo.id != nil {
            self.version = newGizmo.version
            self.id = newGizmo.id
        }
    }
}
```

Unfortunately, this approach does not let me intervene to correct the JSON when mapping a new Gizmo from JSON that represented the old version. Even if I have my old version JSON marked as version 1 and my new version marked as version 2, I cannot make a correction to the JSON to be used to map the `newGizmo` object before it fails to map the id because of the mismatched expectations.

In general I wonder how I can make ObjectMapper resilient when facing changing versions of the JSON serialization of the objects I wish to map?

For example, before the call to `map` in the `reset` function above, I'd like to check the incoming version number and adjust the remainder of the JSON accordingly. But ObjectMapper provides no way to read in that JSON in a generic way (without serializing objects), massage it, and then pass it along to the `map` function. Or better yet, is there a way to use the `map` function itself (currently empty) to facilitate this kind of versioning? Can `MapContext` be of some help?

I imagine I could use Freddy or other Swift JSON frameworks to accomplish this. But the need to check a version (or some other flag) in JSON and then adjust to accommodate older versions of serializations seems to be pretty basic. Is there something in ObjectMapper I am missing that facilitates this kind of check and repair?

**Comment by efc** [comment]
In hunting around a bit more I am pretty convinced that `MapContext` was created to help with situations like this, but I am just not clear on how to apply it, the example is pretty sparse. In particular, I am not sure how to make the mapping asymmetric, in that I want to be able to read all old versions (making adjustments to bring their data up to date) but I only want to write out the most recent version.

**Comment by tristanhimmelman** [comment]
Hi @efc , sorry for the slow response.

ObjectMapper is not officially set up to handle this type of scenario. You could potentially store the model version number within the MapContext and use that version number within the `mapping` function. See the below example. Hope this helps

```
mapping(map: Map){
    guard let (map.context as? Context)?.version else {
        return
    }

    if version == 1 {
         // v1 mappings
    } else {

    }
}
```

```
	struct Context: MapContext {
		let version: Int
		
		init(version: Int){
			self.version = version
		}
	}
```
