### ISSUE TITLE
Swift 3 - Float mapping issue

### ISSUE THREAD

**Issue by Sianay** [Hearst-DD/ObjectMapper#591]
Since swift 3, ObjectMapper seems to not map float type correctly anymore

For example I have this dictionnary : 
`let dict: [String:Any]  = ["manager":1, "self_assessment":0, "average":0, "total_answers":1]`

and this object : 

```
class AnswerOverview: Object, Mappable {
    dynamic var manager: Float = 0
    dynamic var selfAssessment: Float = 0
    dynamic var average: Float = 0
    dynamic var totalAnswers: Int = 0
}
```

when i tried to map it : 
`let answerOverview = Mapper<AnswerOverview>().map(JSON: dict)`

my float values are still empty ( all equal to 0)

I have unit test for this and it was passing before with swift 2.2

**Comment by tristanhimmelman** [comment]
Hi @Sianay, We have unit tests for float in ObjectMapper and they are passing as in Swift 3.0

I'm not sure what the problem is in your case? What do you mean by the float values are empty? They are mapped to 0?

**Comment by Sianay** [comment]
Yes there are mapped to 0 instead of 1 in this case

**Comment by Sianay** [comment]
I think in your unit test you assume that they are passed as float to float and this is working. 
However in my dict these numbers are of the type `Any` and i want them to become ` Float`  

if I wrote my dict this way : 
`let dict: [String:Any] = ["manager":1  as Float , "self_assessment":0 as Float, "average":0 as Float, "total_answers":1]`

then the values will be map correctly (manager = 1 ) but I can't force the type when i parse from real json

**Comment by tristanhimmelman** [comment]
`{"float" : 0}`

I am able to map the above to a var of type Float. 

Maybe you can post your class so that I can have a better idea what is going on?

**Comment by Sianay** [comment]
here a screenshot of unit test : 
![capture d ecran 2016-09-26 a 18 16 40](https://cloud.githubusercontent.com/assets/1273735/18842513/85727458-8415-11e6-91da-f950a7b30326.png)

my class

```
class AnswerOverview: Object, Mappable {
    
    dynamic var question: Question?

    dynamic var manager: Float = 0
    dynamic var selfAssessment: Float = 0
    dynamic var average: Float = 0

    dynamic var totalAnswers: Int = 0
    dynamic var totalComments: Int = 0
    
    dynamic var hiddenStrength: Bool = false
    dynamic var blindSpot: Bool = false

    var answerPreviews: List<AnswerPreview> = List<AnswerPreview>()
     var scrolledPage = 0
    
    override static func ignoredProperties() -> [String] {
        return ["scrolledPage"]
    }
    
    required convenience init?(map: Map) {
        self.init()
    }
    
    func mapping(map: Map) {
        question <- map[Constants.JSONKey.question]
        manager <-  map[Constants.JSONKey.manager]
        selfAssessment <- map[Constants.JSONKey.selfAssessment]
        average <- map[Constants.JSONKey.average]
        totalAnswers <- map[Constants.JSONKey.totalAnswers]
        totalComments <- map[Constants.JSONKey.totalComments]
        hiddenStrength <- map[Constants.JSONKey.hiddenStrength]
        blindSpot <- map[Constants.JSONKey.blindSpot]
        answerPreviews <- (map[Constants.JSONKey.answerPreviews], RealmListTransform<AnswerPreview>())
    }
    
```

**Comment by Sianay** [comment]
Ok so if it can help you this is working with JSONString but not with a dict 

![capture d ecran 2016-09-26 a 18 27 48](https://cloud.githubusercontent.com/assets/1273735/18842926/0a3247f8-8417-11e6-9a7f-fa6d6130e956.png)

**Comment by tristanhimmelman** [comment]
I was able to reproduce your issue. It seems that Swift 3 is not able cast a value of type `Any` to a `Float`. 
```
let anyVal: Any = 11
let float = anyVal as? Float // This results in nil
```

I'm not sure how I will address this yet, but thanks for bringing it up.

**Comment by CaptainMack** [comment]
I might be having same problem using Double and Int. For some reason, mapping JSON to these types fail - String maps correctly.

**Comment by hardeep** [comment]
I'm having this issue on swift 2.2 (ObjectMapper "1.4.0") as well.

My current solution is to use `map["someKey"].currentValue?.floatValue`

**Comment by hardeep** [comment]
@tristanhimmelman I wonder if this has anything to do with your issue. http://stackoverflow.com/questions/32554357/is-float-double-int-an-anyobject

**Comment by tristanhimmelman** [comment]
Oddly I am no longer able to reproduce this issue on v2.1.0. See my test below:

```
	func testMappingFloatFromJSON(){
		let value: Float = 11
		let JSON: [String: Any] = ["float": 11 as Float, "floatOpt": value, "floatImp" : value]
		
		let mappedObject = BasicTypes(JSON: JSON)
		
		XCTAssertNotNil(mappedObject)
		XCTAssertEqual(mappedObject?.float, value)
		XCTAssertEqual(mappedObject?.floatOptional, value)
		XCTAssertEqual(mappedObject?.floatImplicityUnwrapped, value)
	}
```

**Comment by devxoul** [comment]
@tristanhimmelman, this problem occurs with enum.

Try adding this line to `testNestedKeys()` function in **`NestedKeyTests.swift`**.

`XCTAssertEqual(value.floatEnum, FloatEnum.b)` // this will fail because `value.floatEnum` is `nil`.

**Comment by jsgoupil** [comment]
I have found the same problem and opened the bug right here:

https://github.com/Hearst-DD/ObjectMapper/issues/636

**Comment by sallyahmed** [comment]
+ 1 here !

**Comment by CoreOne23** [comment]
Is everybody getting Int mapping correctly? I got some issues on Int(not all Int , but some) mapping along with float .

**Comment by j2damax** [comment]
Use CGFloat instead of Float

**Comment by FerdiKT** [comment]
I have same problem on İOS 11 (same version of app with no problem on ios 10). I used Double instead of Float and it's working now.

**Comment by conqueror** [comment]
If I have a `Double?` and I receive a value without decimals in the JSON such as `4`, ObjectMapper does not map it.
In case I receive a value with decimals like `4.00` then ObjectMapper maps it properly.

**Comment by oleghnidets** [comment]
Have the same issue as @conqueror. @tristanhimmelman any updates on that?

**Comment by SebastianCrow** [comment]
Personally, I'm using a custom transformer like that to have it mapped correctly:
```
TransformOf<Float, NSNumber>(
	fromJSON: { (value: NSNumber?) -> Float? in
		return value?.floatValue
	},
	toJSON: {
		if let float = $0 {
			return float as NSNumber
		}
		return nil
	}
)
```
However, it would be nice if float mapping would work out of the box

**Comment by Adrift001** [comment]
same problem too.
![2018-06-17 10 46 34](https://user-images.githubusercontent.com/8119320/41509049-70e67ed4-7280-11e8-95b3-f2d9d267f0de.png)

![2018-06-17 10 46 44](https://user-images.githubusercontent.com/8119320/41509053-8a8c6592-7280-11e8-886b-dad383c63129.png)

**Comment by Adrift001** [comment]
#959 solved
