### ISSUE TITLE
ObjectMapper 1.5.0 is not available from Cocoapods

### ISSUE THREAD

**Issue by MaximeChaillou** [Hearst-DD/ObjectMapper#593]
Hello,

I'm working on a Swift 2.3 project, so i can't update ObjectMapper to 2.x.x. But the last version I can get from Cocoapods, is the 1.4.0. Can you update your podspecs please ?

Thank you

**Comment by tristanhimmelman** [comment]
Hey there, sorry about that, I just pushed 1.5.0 to cocoapods.
