### ISSUE TITLE
Swift Code not up to date

### ISSUE THREAD

**Issue by Montrazul** [Hearst-DD/ObjectMapper#596]
I added the 2.0.0 Version (Is this the newest version. The Readme file says add 1.3 but that cant be correct) and when I do pod install and build my project I get:

`ObjectMapper will not be code signed because its settings dont specify a development team. "Use Legacy Swift Language Version" (SWIFT_VERSION) is required to be configured correctly for targets which use Swift.`

How can I solve that?

**Comment by tristanhimmelman** [comment]
Hi @Montrazul, when you run `pod install` are you seeing v 2.0.0 of ObjectMapper getting installed? You may need to run `pod update` if you are upgrading versions.

I cannot reproduce what you are describing. v2.0.0 of ObjectMapper is using Swift 3.0

**Comment by Montrazul** [comment]
I did `pod update` before and version 2.0.0 is getting installed. Im on XCode 8 with Swift 3.0
