### ISSUE TITLE
Cocoapods , ObjectMapper ~> 2.0 spec is not available.

### ISSUE THREAD

**Issue by shantanubharadwaj** [Hearst-DD/ObjectMapper#599]
Using cocoapods to install objectmapper ~> 2.0 , gives the following error:
[!] Unable to satisfy the following requirements:

- `ObjectMapper (~> 2.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `ObjectMapper (~> 2.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by kamarshad** [comment]
I am facing the same error while installing the ObjectMapper pod. Have you @shantanubharadwaj  fixed this issue? 

Any help will be much appreciated!

**Comment by kamarshad** [comment]
By the dependency can be resolved If we mention the pod like it `pod 'ObjectMapper'`.
