### ISSUE TITLE
Mapping bool toJSON returns false instead of 0

### ISSUE THREAD

**Issue by RickPasveer** [Hearst-DD/ObjectMapper#607]
When converting an object to json the bool value is returned as false instead of 0

using: Mapper()<Report>().toJSON(report)
Objectmapper v 2.0

**Comment by tristanhimmelman** [comment]
`false` and 0 are both valid JSON. Object mapper uses the former when mapping bools

**Comment by tristanhimmelman** [comment]
You could potentially use a custom transform if you need `0` and `1` in your JSON
