### ISSUE TITLE
Cannot apply Mappable Protocol to NSManagedObject Subclass 

### ISSUE THREAD

**Issue by ReaddyEddy** [Hearst-DD/ObjectMapper#61]
I'm seeing a very obscure build error with objects inheriting from NSManaged object, the code below is extracted form a sample project based on the MasterDetail template. ObjectMapper is installed via 0.36.0.beta.2 Cocoapods with the _Event and Event classes generated with mogenerator 1.28 --v2 --swift. It makes no difference whether the protocol is applied to the derived Human readable class or the Machine Readable class inherited form NSManagedObject.    
This builds OK:  
import Foundation
import ObjectMapper
class Lump:  Mappable {
    var timeStamp : NSDate?
    required init() {}
    func mapping(map : Map) {
            timeStamp <= (map["timeStamp"],DateTransform())
    }
}

This does not:

import ObjectMapper
@objc(Event)
class Event: _Event, Mappable {
  func mapping(map : Map) {
        timeStamp <= (map["timeStamp"],DateTransform())
    }
}

The error message is 
CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
.. snip ..
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

**Comment by tristanhimmelman** [comment]
Hi there,
Unfortunately I'm not sure what is going on here. I haven't tried using ObjectMapper with any classes that are visible to Objective-C code.

One thing I do notice in the above code is that the Event class doesn't include the initializer. Hope this helps..

**Comment by ReaddyEddy** [comment]
Hi
The initialiser is provided by the base class. I suspect myself that the problem is one of using Cocoapods with the frameworks option but I'm yet to confirm that.
Thanks for the speedy response 
Ed

**Comment by hopiaw** [comment]
Any news with that issue?

Thanks

**Comment by ReaddyEddy** [comment]
Seems as though not using CocoaPods suse_frameworks directive allows a build I’ve yet to exercise the mapper though
HTH 
Ed

**Comment by andrebraga** [comment]
I have been easily able to use ObjectMapper with Core Data. https://github.com/Hearst-DD/ObjectMapper/issues/195 for details.
