### ISSUE TITLE
Mappable issue as generic type

### ISSUE THREAD

**Issue by bdrelling** [Hearst-DD/ObjectMapper#611]
If I have a class like this:

```
class MyClass<T>: Mappable where T : Mappable {
    var data: T?
}
```

And I want to deserialize with ObjectMapper, knowing that `data` must be `Mappable` to conform to the above, it won't work if `T` is a simple type like a `String` or `Float`, even though they are able to be unmapped.

If I remove `where T : Mappable`, I can deserialize simple types now (that don't conform to the protocol), but other `Mappable` classes I have can't be deserialized if set as `T`.

Any suggestions on how to work around this? Right now, we do things like the example below, but it's clutter for every type and I'm wondering if there's a better way to do it.

```
class MyClassWithFloat: Mappable {
    var data: Float?
}
```

**Comment by devxoul** [comment]
Could you give us a compilable code to test deserializing?

**Comment by bdrelling** [comment]
I mean, in the documentation there is already an example of how it should work: https://github.com/Hearst-DD/ObjectMapper#generic-objects

You could not, in this case, do `Result<Float>`. You'd have to make a separate class for each type you wanted entirely.

If you just copy the first snippet I wrote and try to do `MyClass<Float>`, it won't even compile. That's what I'm trying to explain.

So in what instance could we have a generic type that allows all types that are actually mappable from ObjectMapper but do not explicitly conform to the `Mappable` protocol?

**Comment by devxoul** [comment]
@bdrelling, I mean the test code. What is the result do you exactly want to see?

**Comment by tristanhimmelman** [comment]
I am closing this until further reply

**Comment by luosky** [comment]
I think what he expected is to write code like `Mapper<Float>().map(json[keyPath])`. But Float doesn't conform to Mappable, so he has to wrap Float in a custom type like MyClassWithFloat
