### ISSUE TITLE
 Initializer 'init' has different argument names from those required by protocol 'Mappable' ('init(map:)')

### ISSUE THREAD

**Issue by mathieudebrito** [Hearst-DD/ObjectMapper#613]
Hi guys !

I just switched to Swift 3 and ObjectMapper 2.0.0 and I'm facing this issue : 

```Swift
import Foundation
import ObjectMapper

@objc class MyClass: NSObject, Mappable {
    
    var myString: String!
    
    override init(){
    }
    
    required init?(_ map: Map){
        
    }
    
    func mapping(map: Map) {
        myString               <- map["myString"]
    }
}
```

And I'm getting the `Initializer 'init' has different argument names from those required by protocol 'Mappable' ('init(map:)')`, with `Fix it : delete _` for the required init

What can I do ?

Thanks and BTW,, thanks for this awesome lib !

**Comment by devxoul** [comment]
Replace `required init?(_ map: Map)` to `required init?(map: Map)`.

```diff
- required init?(_ map: Map)
+ required init?(map: Map)
```

**Comment by tristanhimmelman** [comment]
Thanks @devxoul, really appreciate your assistance!

**Comment by devxoul** [comment]
@tristanhimmelman No problem! I really love this project 👍
