### ISSUE TITLE
Installing through pods

### ISSUE THREAD

**Issue by mahmoudnaja** [Hearst-DD/ObjectMapper#614]
Hi, Please help  when updated to swift 3.When I install it through pods and open the project it always sees it as an old swift version how can I install the latest version compatible with swift 3 through pods.
Thanks in advance.

**Comment by devxoul** [comment]
@mahmoudnaja, how did you setup your `Podfile`?

**Comment by mahmoudnaja** [comment]
Hi here is my podfile.

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.1’
use_frameworks!
target “App” do
pod 'ObjectMapper', '~> 2.0'
end

**Comment by devxoul** [comment]
Did you mean that your ObjectMapper 1.x is installed?

**Comment by mahmoudnaja** [comment]
Yes it installs version 1.x

**Comment by devxoul** [comment]
@mahmoudnaja have you tried `$ pod update`? If it doesn't work, try:

```console
$ pod repo update
$ pod install
```

**Comment by mahmoudnaja** [comment]
Will try the above and will let you know if it works

**Comment by mahmoudnaja** [comment]
Thanks the above worked
