### ISSUE TITLE
parse integer response always nil (e.g status = 200) the result is always becomes nil .. any help ? thanks

### ISSUE THREAD

**Issue by rjjohnpatrickcruz** [Hearst-DD/ObjectMapper#62]
parsing response integer response and the result is always "nil"
example: (status = 200)
result = nil (when I parse the result)

**Comment by tristanhimmelman** [comment]
Please provide some more info so we can help. Your code and the JSON string you are trying to parse would help

**Comment by rjjohnpatrickcruz** [comment]
Hey,

here is the sample json string im trying to parse 
{
    "completed_in" = "0.0919";
    message = "Login Successful";
    profile =     {
        "current_coordinates" = "<null>";
        email = "juan@delacruz.com";
        fname = Juan;
        id = 83;
        lname = "Dela Cruz";
        mname = Gitna;
        "mobile_no" = 09090909090;
        photo = "<null>";
    };
    "security_key" = "4DB585AD-F0D2-28AB-68A7-5F4C43A55051";
    status = 1;
}

**Comment by tristanhimmelman** [comment]
Hi, you're models look properly formed but your JSON is not. You can test if JSON is properly formed using online tools like: http://jsonformatter.curiousconcept.com/

I've reformatted your JSON properly below. 
```
{
"completed_in" : 0.0919,
"message" : "Login Successful",
"profile" : {
    "current_coordinates" : "",
    "email" : "juan@delacruz.com",
    "fname" : "Juan",
    "id" : 83,
    "lname" : "Dela Cruz",
    "mname" : "Gitna",
    "mobile_no" : "09090909090",
    "photo" : ""
},
"security_key" : "4DB585AD-F0D2-28AB-68A7-5F4C43A55051",
"status" : 1
}
```
The other issue I see is that you need to pass in a type when you are creating a Mapper object.
```
Mapper<User>().map(string: JSONString)
```

Hope this helps

**Comment by rjjohnpatrickcruz** [comment]
Hi thanks , i think i see the issue.. im using alamofire to request the json and the json response is not a valid json format .. 
thanks!
