### ISSUE TITLE
Generic type mapping in swift 3

### ISSUE THREAD

**Issue by borut-t** [Hearst-DD/ObjectMapper#620]
I have an issue mapping data for generics in swift 3:

```Swift
var object : T? = nil
object = Mapper<T.self>().map(data, toObject: object)
```

This is working example in swift 2.2, but fails in swift 3.

Could you direct me to proper solution?

**Comment by devxoul** [comment]
@borut-t, what do you mean 'fail'?

**Comment by borut-t** [comment]
@devxoul 
![screen shot 2016-10-11 at 11 41 31](https://cloud.githubusercontent.com/assets/677166/19265949/b6b60172-8fa7-11e6-97aa-aa6ee9e1869e.png)

**Comment by devxoul** [comment]
@borut-t Have you tried this?

```diff
- object = Mapper<T.self>().map(data, toObject: object)
+ object = Mapper<T>().map(data, toObject: object)
```

**Comment by borut-t** [comment]
@devxoul 
![screen shot 2016-10-11 at 11 45 12](https://cloud.githubusercontent.com/assets/677166/19266081/3a886e86-8fa8-11e6-9b93-78424a30b6a6.png)

**Comment by devxoul** [comment]
@borut-t Could you please provide me how `T` is declared?

**Comment by borut-t** [comment]
@devxoul 

`class MyClass<T: Object> : Operation where T: Mappable {}`

**Comment by tristanhimmelman** [comment]
@borut-t, in the swift 3.0 version of ObjectMapper, the data parameter requires a name.
```
object = Mapper<T.self>().map(JSON: data, toObject: object)
object = Mapper<T.self>().map(JSONString: data, toObject: object)
```

**Comment by borut-t** [comment]
@tristanhimmelman, actually this is the correct syntax:

`object = Mapper<T>().map(JSONString: data, toObject: object)`

Thanks!

**Comment by M0TRIX** [comment]
try class MyClass<T: mappable>

**Comment by BharathGithubUser** [comment]
struct BasicMappableResponse<T: Mappable> : Mappable {
...
}
This worked for me
