### ISSUE TITLE
help

### ISSUE THREAD

**Issue by zhanghongdou** [Hearst-DD/ObjectMapper#622]
Why I've inherited the Mapper Model using the runtime obj. It is time to get the name of the class of classForCoder method, obj. ClassForCoder the return value is nil,

**Comment by devxoul** [comment]
@zhanghongdou, please provide us how to reproduce the bug and what you expected.

**Comment by zhanghongdou** [comment]
![2016-10-12 11 19 10](https://cloud.githubusercontent.com/assets/16813719/19296394/ba47b576-906d-11e6-973a-e497fa2d9ed9.png)
Obj is here I enclosed the inheritance in the model mapper, I meant to get obj‘s class by runtime , and then get all the attributes, but in the use of obj. ClassForCoder, returns nil

**Comment by zhanghongdou** [comment]
![2016-10-12 11 22 06](https://cloud.githubusercontent.com/assets/16813719/19296447/2467bc8a-906e-11e6-8664-a6973d825dea.png)
This is the obj’s class

**Comment by zhanghongdou** [comment]
My English is not very good, hope you can understand me, thank you

**Comment by devxoul** [comment]
@zhanghongdou Thank you for providing me a detail :smile:

1. `class_copyPropertyList` only works with Objective-C compatible properties.
2. `Double?` cannot be used in Objective-C. (But `Double` can be used in Objective-C)
3. Use `NSNumber?` to do what you want.

**Comment by zhanghongdou** [comment]
Thank you, I'll try it according to your opinion

**Comment by zhanghongdou** [comment]
![2016-10-12 11 44 00](https://cloud.githubusercontent.com/assets/16813719/19296786/36ff18a4-9071-11e6-9650-af699dd84f39.png)
When my Model  just like this picture, I use the method ：  
var outCount: UInt32 = 0
Let the properties = class_copyPropertyList (obj. ClassForCoder, & outCount)
 is able to obtain the model of a class, at the same time can get all his property, but if my model is inherited from the Mapper can't achieve what I want

**Comment by devxoul** [comment]
@zhanghongdou have you tried this?

```swift
class InvestRecordListModel: NSObject, Mappable {
  ...
}
```

**Comment by zhanghongdou** [comment]
No, not yet. Let me try

**Comment by zhanghongdou** [comment]
I'm sorry, just a little thing, I tried once is available
According to the following way：
class InvestRecordListModel: NSObject, Mappable {
  ...
}

**Comment by zhanghongdou** [comment]
Thank you for your help, should be the cause of my side, I again carefully look for the reason, thanks again

**Comment by devxoul** [comment]
@zhanghongdou Sounds great! Could you please close this issue? :tada:

**Comment by zhanghongdou** [comment]
Try my best to solve it, ha ha
