### ISSUE TITLE
Add support to change Separator character 

### ISSUE THREAD

**Issue by brentpi** [Hearst-DD/ObjectMapper#624]
By default in ObjectMapper, the Separator character used to navigate to sub-objects is ".", and the user is required to disable nesting if their object contains keys with a ".".

Potentially abstract the Separator character to a variable, so the user can change it to "|" or something less likely in their use case.

**Comment by devxoul** [comment]
@brentpi, you can use `property <- map["my.key", nested: false]` instead.

**Comment by brentpi** [comment]
My original data source is a bunch of OS X System Profiler Plist files that I'm reading into a dictionary.  The format for SPStorageDataType is something like the following, so you can see why I requested this:

_items.0."com.apple.corestorage.lv"."com.apple.corestorage.lv.encrypted"

So, for my use case, changing the '.' to a '/' or a '|' would be helpful, as I would like to maintain nesting, but ignore the "com.apple.corestorage.lv" keys as "nested" keys.

**Comment by devxoul** [comment]
@brentpi That makes sense. How about this approach? It allows to pass `delimiter` parameter to `map[]` subscription.

```swift
property <- map["_items -> 0 -> com.apple.corestorage.lv -> com.apple.corestorage.lv.encrypted", delimiter: " -> "]
```

**Comment by brentpi** [comment]
Yeah, that sounds like a better option perhaps.

**Comment by devxoul** [comment]
@brentpi, #629 is for you :tada:
