### ISSUE TITLE
Xcode 8, Swift 3

### ISSUE THREAD

**Issue by danipralea** [Hearst-DD/ObjectMapper#625]
Hello!
I am getting the following error:
![screenshot 2016-10-12 14 52 49](https://cloud.githubusercontent.com/assets/768893/19309101/9bee058a-908b-11e6-9319-36671235866d.png)

I also set `Use Legacy Swift Language Version` to `YES` but it still doesn't work
Project was integrated via Cocoapods

Maybe you can add a swift version file indicator, as per http://stackoverflow.com/a/39618219/743923 ?

**Comment by tristanhimmelman** [comment]
@danipralea we do have the `swift-version` file in the project. 

Which version of ObjectMapper are you using?

**Comment by devxoul** [comment]
@tristanhimmelman `.swift-version` file is for linting podspec. We need `s.pod_target_xcconfig` in podspec which is added in https://github.com/Hearst-DD/ObjectMapper/commit/e7408cab845c4204752ff20e2cce1d48cac962bc . So @danipralea, you have two options:

1. Use ObjectMapper 2.1.0
2. Add this script at the end of the `Podfile`:

    ```ruby
    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '3.0'
        end
      end
    end
    ```

**Comment by danipralea** [comment]
yeah, I ended up using 2.1.0
I had the 1.1 version somehow (I copy pasted the pod from an old project).

Thank you very much for your help!
