### ISSUE TITLE
Mapping dictionary with no name on key?

### ISSUE THREAD

**Issue by Dbigshooter** [Hearst-DD/ObjectMapper#626]
Hi there,

I'm facing a problem, which I can't seem to figure out. I have a JSON dictionary similar to this:

{"1": [{"id":11,"sId":2,"dateTime":"2016-10-05T04:00:00.000Z"},
{"id":12,"sId":3,"dateTime":"2016-10-05T04:00:00.000Z"}]}

So a dictionary containing an arrays. The problem seems to be, the key has no name, so I can't figure out how to map it?

**Comment by devxoul** [comment]
Can you provide expected output with that json?

**Comment by Dbigshooter** [comment]
Apologies for not making that clear. I want the above JSON into a corresponding dictionary of this [Int : [MyObject]].

**Comment by devxoul** [comment]
@Dbigshooter try:

```swift
class MyObject: Mappable {
  var id: Int!
  var sId: Int!
  var dateTime: Int!

  func mapping(map: Map) {
    id <- map["id"]
    sId <- map["sId"]
    dateTime <- (map["dateTime", DateTransform()])
  }
}

func myObjectsFromJSON(dict: [String: [String: Any]]) -> [Int: MyObject] {
  var objects: [Int: MyObject] = [:]
  for (key, value) in dict {
    guard let key = Int(key) else { continue }
    guard let object = MyObject(JSON: value) else { continue }
    objects[key] = object
  }
  print(objects)
}
```

**Comment by tristanhimmelman** [comment]
@devxoul 👍 

Alternatively, you can create a container object. 
```
class Container: Mappable {
  var objects: [MyObject]?

  init?(map: Map){}

  func mapping(map: Map) {
    objects <- map["1"]
  }
}
```

```
let container = Container(JSON: JSON)
```

Hope this helps

**Comment by Dbigshooter** [comment]
Oh, will this due the trick? 

```
func mapping(map: Map) {
    objects <- map["1"]
  }
```

The key in the dictionary is id's I need, not just incremental.

**Comment by tristanhimmelman** [comment]
Using JSONLint.com the updated JSON is not valid. But what it looks like is a dictionary of arrays: `[String: [MyObject]]`

So in the Container example I posted above, you can change the type of objects to `[String: [MyObject]]` and that should do it.

**Comment by Dbigshooter** [comment]
I'm just trying to understand it properly, please bare with me. I need the every key in the dictionary to be mapped to a list of MyObject, but I can't get a hold of it since it will vary, so the example you posted earlier with hardcoded "1" it it wouldn't work. Am I missing something? Am I making any sense? 

 I've tried this:

```
var objectDict = [String : [MyObject]]

func mapping(map: Map) {
    objects <- map
  }
```

However that didn't work at all.

**Comment by tristanhimmelman** [comment]
Ahh sorry I missed that.

What you want to do in this case is use :
`public func mapDictionary(JSON: [String: [String: Any]]) -> [String: N]?`

So the call should look like:
```
let dictionary = Mapper<MyObject>().mapDictionary(JSON: JSON)
```

**Comment by Dbigshooter** [comment]
Let me show you my entire call using Alamofire:

```
Alamofire.request(url, method: .get, parameters: params, headers: headers()).responseJSON {
            response in
            if let ms = Mapper<MeasurementsTransfer>().mapDictionary(JSON: response.result.value as! [String : [String : Any]]) {
                    print(ms)
                    completionHandler(ms, nil)
                } else {
                    print("Failed")
                    completionHandler(nil, false)
                }
        }
```

<img width="1098" alt="crash" src="https://cloud.githubusercontent.com/assets/6803648/19353524/f2327920-9163-11e6-9381-c2fd97cee086.png">

**Comment by tristanhimmelman** [comment]
Sorry, the type i posted is not correct based on your JSON. I missed an extra set of square brackets. It should be this I believe: `[String: [[String: Any]]]`

So in this case you should be able to use:
```
public func mapDictionaryOfArrays(JSON: [String: [[String: Any]]]) -> [String: [N]]?
```

If this doesn't work, I would loop through your dictionary, and call `mapArray` on each object.

**Comment by Dbigshooter** [comment]
Hmm, isn't this `[String: [[String: Any]]]` an dictionary of and array of dictionaries? What is need is basically something like this: 

`if let user = Mapper<MeasurementsTransfer>().mapDictionaryOfArrays(JSON: response.result.value as! [String : [Measurement]]) {`

My MeasurementsTransfer contains the dictionary itself and the Measurement is the objects in the array.

**Comment by tristanhimmelman** [comment]
The only mistake I see above is `response.result.value as! [String : [Measurement]]`

You cannot cast to Measurement. You should cast to:
`response.result.value as? [String : [[String: AnyObject]]]`

On a side note, I would avoid using `as!` to cast. This isn't a safe operation.

**Comment by Dbigshooter** [comment]
But how am I able to cast an array to a dict? The compiler doesn't complain, but it doesn't work.

**Comment by tristanhimmelman** [comment]
Based on the JSON you posted above, the response is in the form of a Dictionary of Arrays, so you should be able to cast it properly.

If the response is actually an array, then casting it wont work.

**Comment by Dbigshooter** [comment]
The JSON I get back is [String: [Measurement]], if I mistyped anything I apologize.

**Comment by tristanhimmelman** [comment]
I'm not sure what else I can do to help.

Perhaps you can post a complete sample of the JSON string as received from Alamofire?

**Comment by Dbigshooter** [comment]
Sure, like this:

`{
  "2443": [
    {
      "id": 354299,
      “sId": 2443,
    },
    {
      "id": 354300,
      “sId": 2443
    }
],
"2448": [
    {
      "id": 354312,
      "fieldId": 2448
    }],
}`

**Comment by devxoul** [comment]
```swift
import UIKit

let dict: [String: [String: Any]] = [
  "1": [
    "id": 1,
    "sId": 2,
    "dateTime": "2016-10-05T04:00:00.000Z",
  ],
]

class MyObject: Mappable {
  var id: Int!
  var sId: Int?
  var fieldId: Int?

  func mapping(map: Map) {
    id <- map["id"]
    sId <- map["sId"]
    fieldId <- map["fieldId"]
  }
}

func myObjects(from json: [String: [[String: Any]]]) -> [Int: [MyObject]] {
  var objects: [Int: MyObject] = [:]
  for (key, array) in dict {
    guard let key = Int(key),
      let objects = Mapper<MyObject>().mapArray(JSONArray: array)
    else { continue }
    objects[key] = objects
  }
  return objects
}

let objects = myObjects(from: json)
print(objects)
```

This code will convert your JSON dictionary into:

```swift
[
  "2443": [
    MyObject(id: 354299, sId: 2443)
    MyObject(id: 354300, sId: 2443)
  ],
  "2448": [
    MyObject(id: 354312, fieldId: 2448)
  ]
]
```

**Comment by Dbigshooter** [comment]
I want my JSON mapped into object, does this do that as well?

**Comment by devxoul** [comment]
@Dbigshooter Please give use your entire model classes.

**Comment by Dbigshooter** [comment]
@devxoul Sure, my models are as the following:

The real model class:

```
class Measurement : EVObject, Mappable {
    var id : Int = 0
    var sId : Int = 0
    
    required init?(map: Map) {
        super.init()
        mapping(map: map)
    }
    
    required init() {
        //super.init()
    }
    
    func mapping(map: Map) {
        id <- map["id"]
        sId <- map["sId"]
    }

```

The mapping model:

```
class MeasurementsTransfer: EVObject, Mappable {
    
    var measurement : [String : [Measurement]] = [:]
    
    required init?(map: Map) {
        
    }
    
    required init() {
        //super.init()
    }
    
    func mapping(map: Map) {
        measurement <- map
    }
}
```

**Comment by devxoul** [comment]
@Dbigshooter, which output would you expect?

1. `[Int: MeasurementsTransfer]`
2. `[MeasurementsTransfer]`
3. `MeasurementsTransfer `

**Comment by Dbigshooter** [comment]
2, since the MeasureTranfers object contains a dict of [String : [Measurement]].

**Comment by devxoul** [comment]
@Dbigshooter, I would wrap the dictionary:

**Before**

```json
{ 
  "2443": [{"id": 354299, "sId": 2443}, {"id": 354300, "sId": 2443}], 
  "2448": [{"id": 354312, "fieldId": 2448}, {"id": 354300, "sId": 3728}] 
}
```

**After**

```json
{
  "measurements": {
    "2443": [{"id": 354299, "sId": 2443}, {"id": 354300, "sId": 2443}], 
    "2448": [{"id": 354312, "fieldId": 2448}, {"id": 354300, "sId": 3728}] 
  }
}
```

... and map it to `MeasurementsTransfer`:

```swift
class MeasurementsTransfer: EVObject, Mappable {
  var measurements: [String : [Measurement]] = [:]

  func mapping(map: Map) {
      measurement <- map["measurements"]
  }
}

Alamofire.request(url, method: .get, parameters: params, headers: headers()).responseJSON { response in
  let measurementJSONs = response.result.value as! [String: [String: Any]]
  let measurementsTransferJSON = ["measurements": measurementJSONs]
  if let ms = Mapper<MeasurementsTransfer>().map(JSON: measurementsTransferJSON) {
      print(ms)
      completionHandler(ms, nil)
  } else {
      print("Failed")
      completionHandler(nil, false)
  }
}
```

**Comment by Dbigshooter** [comment]
@devxoul I can't alter the JSON on the backend, is has to stay that way :-/

**Comment by devxoul** [comment]
@Dbigshooter I didn't mean to change the JSON from the backend. Just wrap the dictionary in your Swift code.

```swift
let measurementsTransferJSON = ["measurements": measurementJSONs]
```

**Comment by Dbigshooter** [comment]
Hmm, I get this crash using your code:

<img width="1099" alt="ss" src="https://cloud.githubusercontent.com/assets/6803648/19435992/021aaef4-946e-11e6-88ac-6695c08be7fc.png">

**Comment by devxoul** [comment]
@Dbigshooter, when did you get that crash?

**Comment by Dbigshooter** [comment]
@devxoul It doesn't tell me, but debugging I can see it is one of these lines:

   ```
let measurementsTransferJSON = ["measurements": measurementJSONs]
   if let ms = Mapper<MeasurementsTransfer>().map(JSON: measurementsTransferJSON) {
```

**Comment by devxoul** [comment]
Try

```
let measurementJSONs = response.result.value as! [String: [String: Any]]
```

first, then adding second line, then adding third line.

**Comment by Dbigshooter** [comment]
@devxoul It seems it is this one:

        `let measurementJSONs = response.result.value as! [String: [String: Any]]`

It makes sense, since it is not a [String: [String : Any]] I get from the JSON, but [String : [Measuremt]]

**Comment by devxoul** [comment]
Then you can cast it or whatever you get from the server to dictionary :(

**Comment by Dbigshooter** [comment]
@devxoul This works better:

```
let measurementJSONs = ["measurements" : response.result.value]
            print(measurementJSONs)
            if let ms = Mapper<MeasurementsTransfer>().mapDictionary(JSON: measurementJSONs as! [String : [String : Any]]) {
                print(ms)
```

However, my dictionary looks funny:

```
["measurements": MeasurementsTransfer {
   hash = 0
   measurements = {
}
}
]

```

**Comment by devxoul** [comment]
Try

```diff
Mapper<MeasurementsTransfer>().mapDictionary(JSON: measurementJSONs as! [String : [String : Any]])
Mapper<MeasurementsTransfer>().map(JSON: measurementJSONs as! [String : [String : Any]])
```

**Comment by Dbigshooter** [comment]
Same result :-/

**Comment by Dbigshooter** [comment]
@devxoul My output before I map looks like this:

["measurements": {
    2396 =     (
                {
            id = "21313";
            sid = "43847";
        },
                {
            id = "21314";
            sid = "43841";
        }
    );
2397 =     (
                {
            id = "43237";
           sid = "37321";
        },
                {
            dateTime = "2016-10-05T04:00:00.000Z";
           id = "43231";
           sid = "37342";
        },
);

**Comment by tristanhimmelman** [comment]
The JSON you posted from the browser is not valid. If you plug it into JSONLint.com you will see the errors.

It includes `“` and `"`. The first type of quote cannot be used.

**Comment by Dbigshooter** [comment]
@tristanhimmelman Just my mistake, I alter the JSON a bit, but doesn't it seem that the JSON Alamofire outputs is invalid?

**Comment by rjndra** [comment]
I faced similar issue but taken some approach to get my desired result.
Here is json file:
[https://gist.github.com/rjndra/af568b276443b16204e61dfcb1ac2257](url)

And the mappable Object is:
`struct Category: Mappable {
    var id:String?
    var title: String?
    var image:String?
    var children:Dictionary<String,Category>?
    
    init?(map: Map) { }
    
    mutating func mapping(map: Map) {
        id <- map["id"]
        title <- map["title"]
        image <- map["image"]
        children <- map["children"]
    }
}`

Finally the implementation:
`import SwiftyJSON
import Alamofire
import ObjectMapper



class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        
        let url = "apiurl"
        
        let request = Alamofire.SessionManager.default.request(url, method: .get, parameters: nil, encoding: URLEncoding.default, headers: nil)
        
        request.responseJSON { (response) in
            if let value = response.result.value {
                
                var returnData:[(key:String,value:Category?)] = []
                if let val = value as? Dictionary<String,Any> {
                    print(val)
                    
                    let data = val.map({ (value) -> (key: String, value:Category?) in
                        if let newValue:Category = JSON(value.value).map() {
                            return (key:value.key,value: newValue)
                        }
                        return (key: value.key, value: nil)
                    })
                    returnData = data
                }
                print(returnData) //here you get tuples of your dictionary so save this tuple anywhere
            }
        }
        
// Now json from local directory for same json mentioned.
/*
        if let filePath = Bundle.main.url(forResource: "response", withExtension: "json") {
            
            let data = try? Data(contentsOf: filePath)
            let json = JSON(data!)
            
            var returnData:[(key:String,value:Category?)] = []
            if let val = json.rawValue as? Dictionary<String,Any> {
                print(val)
                
                let data = val.map({ (value) -> (key: String, value:Category?) in
                    if let newValue:Category = JSON(value.value).map() {
                        return (key:value.key,value: newValue)
                    }
                    return (key: value.key, value: nil)
                })
                returnData = data
            }
            print(returnData)
        }
*/
        
    }
}`

One more extension:
`extension JSON {
    func map<T: Mappable>() -> [T]? {
        let json = self.array
        let mapped: [T]? = json?.flatMap({$0.map()})
        return mapped
    }
    
    func map<T: Mappable>() -> T? {
        let obj: T? = Mapper<T>().map(JSONObject: self.object)
        return obj
    }
}`
