### ISSUE TITLE
BaseMappable and ImmutableMappable

### ISSUE THREAD

**Issue by azeff** [Hearst-DD/ObjectMapper#627]
Hi

Recently `ImmutableMappable` was introduced as a beta api. I've liked the idea and started converting structs from `Mappable`. During the process I've faced some unexpected bugs. My initial reaction was - "How is this even possible? That should have been caught by compiler."

But lets forget for a moment about new stuff related to `ImmutableMappable`.
It appears that `Mapper`'s API is written against `BaseMappable` protocol. **But** actually it does not work the way it declares it works. All `map*` methods evetually call `map(JSONObject:)` that tries to cast to `Mappable.Type` or `StaticMappable.Type` and returns `nil` if can't.

Here is sample that illustrates the problem.

```
struct Car: BaseMappable {
  var vin: String

  mutating func mapping(map: Map) {
    vin <- map["vin"]
  }

}
var carJson = ["vin": "a vin value"]
let mapper = Mapper<Car>()
mapper.map(JSONObject: carJson) // <== nil
```

That propagates up to mapping operators.

```
struct Wheel: BaseMappable {
  var type: String = ""

  mutating func mapping(map: Map) {
    type <- map["type"]
  }
}
struct Cart: Mappable {
  var wheels: [Wheel] = []

  init?(map: Map) { }

  mutating func mapping(map: Map) {
    wheels <- map["wheels"]
  }
}
var cartJson: [String: Any] = ["wheels": [["type": "rear"], ["type": "rear"], ["type": "front"], ["type": "front"]]]
let cartMapper = Mapper<Cart>()
let cart = cartMapper.map(JSONObject: cartJson)!
cart.wheels // <-- empty array
```

I know that `BaseMappable` should not be implemented directly, but my problems with adopting `ImmutableMappble` were that I accidentally ended up with the same scenarios by calling not `right` methods.
Now, after digging into this, I know what situations should be avoided and when to pay more attention to stuff I'm doing. Still feel that API should not allow me to do such things.

What do you think?

**Comment by tristanhimmelman** [comment]
You bring up a good point. The introduction of `BaseMappable` provided a lot of flexibility to `ObjectMapper` with the trade off of a looser API. You are probably not the only one having these issues. At the very least, we should make the documentation clearly state that you should not implement `BaseMappable`. 

I will put some thought into how we can make the API stricter without a lot of code duplication. If you have any suggestions they would be great to hear. Perhaps we can take the approach that @devxoul used when creating `ImmutableMappable` as an extension to `Mapper`.

**Comment by tristanhimmelman** [comment]
For the time being, I have included an assert in the `map` function that will stop developers from taking this approach. 

Ideally we would have a compile time warning, but I think this is better than nothing.
