### ISSUE TITLE
Guidance needed: how to pass a Mappable to a function that can map to it as a generic?

### ISSUE THREAD

**Issue by aehlke** [Hearst-DD/ObjectMapper#63]
I've tried a bunch of things which compile but don't result in what I expect, in mysterious ways. This is more of a general Swift question but should be a common use case of this lib, so I'm asking it here.

My use case: I have an API client method that takes the "model" type to de-serialize to as a parameter. I need to instantiate this Mappable model type inside the function, to return the de-serialized object.

Anyone have a way to get this working? It seems so simple...

**Comment by tristanhimmelman** [comment]
Hi there, something like this should work for you (this is using the Alamofire HTTP library): 
```
func getPath<T: Mappable>(URL: NSURL, parameters: [String: AnyObject]?, completion: ((T!, NSError!) -> Void)!) {
		
	Alamofire.request(.GET, URL, parameters: parameters)
		.responseJSON { (request: NSURLRequest, response: NSHTTPURLResponse?, data: AnyObject?, error: NSError?) in
			if error == nil {
				if let JSON = data as? [String : AnyObject]{
					let parsedObject = Mapper<T>().map(JSON)
					completion(parsedObject, nil)					}
				} else {
					completion(nil, error)
				}
			}
}
```

**Comment by aehlke** [comment]
What I've tried is close to that, but I'm not using completion callbacks (I'm using ReactiveCocoa signals). So the type is specified by passing the class in to the function, rather than in the completion signature.

This is what my method looks like: `func request<M: Mappable where M: APIObject>(token: T, method: Moya.Method, parameters: [String: AnyObject], model: M.Type, forKey key: String? = nil, showAuthOnAuthError: Bool = true) -> RACSignal {` I have to use `M.Type` in order to pass in a class. `APIObject` is what my models inherit from, it is itself a Mappable.

Inside the function when I try to instantiate `Mapper<M>()` and set a breakpoint, the debugger shows no value for that, but if I do e.g. `Mapper<Deck>()` where Deck is an actual Mappable class, it shows the instantiated mapper... Not sure what I'm missing.

EDIT: This appears to be some kind of bug in the debugger, it's actually working as intended AFAICT. Thanks for your answer - showed me that it must be something else wrong with my approach.

**Comment by tristanhimmelman** [comment]
Great, glad you got it working
