### ISSUE TITLE
Mapping dates

### ISSUE THREAD

**Issue by Dbigshooter** [Hearst-DD/ObjectMapper#631]
Hi there,

I'm trying to map a NSDate, like this: 

```
...
var date : NSDate?
...
func mapping(map: Map) {
        date <- (map["date"], DateTransform())
    }
```

But it fails and I'm left with: 

`Binary operator '<-' cannot be applied to operands of type 'NSDate?' and '(map, DateTransform)'`

**Comment by devxoul** [comment]
@Dbigshooter, if you're using Swift 3, you should use `Date` instead of `NSDate`.

**Comment by Dbigshooter** [comment]
@devxoul Just changed it, nothing new. Still leaves <null> in my objects.

**Comment by devxoul** [comment]
@Dbigshooter please provide us the JSON dictionary

**Comment by Dbigshooter** [comment]
Got this solved, using Date() instead of NSDate did it, thanks!
