### ISSUE TITLE
Pod only contains license and readme

### ISSUE THREAD

**Issue by RickPasveer** [Hearst-DD/ObjectMapper#633]
The pods project of ObjectMapper is empty after pod update
it only contains the readme and license file.

i've tried a couple of things:
- pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git'
- pod 'ObjectMapper'
- pod install

podfile:
```
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'BGDD Universal Swift' do

pod 'HockeySDK'
pod 'GooglePlaces'
pod 'Alamofire'
pod 'SwiftDate', '~> 4.0'
pod 'CircleProgressView'
pod 'IBAnimatable'
pod 'ObjectMapper', '~> 2.1'
pod 'SwiftyJSON'
pod 'RealmSwift'

end
```

**Comment by RickPasveer** [comment]
in pod spec:
`s.source_files = 'ObjectMapper/**/*.swift'`
should be:
` s.source_files = 'Sources/**/*.swift'`

**Comment by tristanhimmelman** [comment]
Thanks for the fix @RickPasveer , I have now merged it into master. 

I will make a release soon
