### ISSUE TITLE
NSDecimalNumberTransform should handle Int as well in Swift3

### ISSUE THREAD

**Issue by jsgoupil** [Hearst-DD/ObjectMapper#636]
The current NSDecimalNumberTransform has a behavior change with Swift 3 when using an Integer.

So if you do 

`let dict = ["Key", 1]`

Swift2
Optional&lt;AnyObject>
   Some : 1

Swift3
Optional&lt;Any>
   some : 1

So your current code with `as? Double` won't pick up the integer properly...
I would believe that an expected behavior in this case is to not get `nil` for this but 1.0...

This problem happens probably at more than one place in your code. I'll leave it up to you to decide if this is the behavior you want and if so, fix other places that might have this problem.

**Comment by kwosu87** [comment]
+1

**Comment by Jake000** [comment]
#777 should have resolved this. It now checks for NSNumber first which passes the check and pulls the decimal value out of it, so `nil` will no longer be returned but `1.0`.

**Comment by tristanhimmelman** [comment]
Closing this as it should be resolved. Let me know if it is still an issue and we can reopen this ticket
