### ISSUE TITLE
Library not loaded: @rpath/ObjectMapper.framework

### ISSUE THREAD

**Issue by trickpirata** [Hearst-DD/ObjectMapper#64]
Hi. I installed this framework using cocoa pods but I keep getting this thru crash report. Can't go pass through splash screen. Any ideas?

**Comment by tristanhimmelman** [comment]
I had a similar issue when using cocoapods beta on a project with multiple targets. It seems that cocoapods only properly configures the first target in the project and the others.

Have you used Cocoapods to add any other libraries in your project? or is this the first?

**Comment by trickpirata** [comment]
I've cocoapods before for projects coded in Obj-c. This is my first time using cocoapods for projects coded in Swift.

The odd thing is, even if I don't use cocoapods, I am still encountering this issue(When doing a manual import of this project as stated on your instructions).

**Comment by tristanhimmelman** [comment]
When you did the installation manually did you follow steps 4-7? I believe this is where you're problem might be coming from. Specifically the last step

**Comment by trickpirata** [comment]
Yes I did followed it carefully and repeatedly. I've read that this might be a certificate issue as referred to this link: https://www.airsignapp.com/ios-apps-using-swift-crash-when-signed-with-inhouse-certificate/

**Comment by trickpirata** [comment]
My certificate is new but I am still encountering errors. Any tips? :(
