### ISSUE TITLE
ObjectMapper failed to serialize response

### ISSUE THREAD

**Issue by zemadara** [Hearst-DD/ObjectMapper#646]
Hi, i do an Alamofire post request, before Swift 3.0 this request work well but then i have an error

-The request:
```swift
Alamofire.request(self.url, method: .post, parameters: contactJSON, encoding: JSONEncoding.default) 
.responseJSON() { response in 
switch response.result { 
case .success: 
let isAdd = response.result.value as! Bool if (isAdd) 
{ 
self.view.makeToast(GlobalClass.getString("contact_added"), duration: 3.0, position: .bottom) 
} 
case .failure(let error): print(error) } }
```

The error: Error Domain=com.alamofireobjectmapper.error Code=2 "ObjectMapper failed to serialize response." UserInfo={NSLocalizedFailureReason=ObjectMapper failed to serialize response.}
for more informations, the request return a boolean true or false.

**Comment by devxoul** [comment]
@zemadara, you can wrap the code with 3 backticks.

<pre>
```swift
Alamofire.request(self.url, method: post, .......) {
  .......
}
```
</pre>

**Comment by zemadara** [comment]
this error come to the url, with Swift 3.0 we are some new Optional() that appears when we get Int value
