### ISSUE TITLE
Is it possible to convert int to string?

### ISSUE THREAD

**Issue by tylerlong** [Hearst-DD/ObjectMapper#650]
I searched this repository and someone asked about convert string to int. I am asking for the opposite: convert int to string.

In JSON, the attribute is of int type, in the model I defined, the property is of string type. I did some tests and I always get nil value.

int to string conversion is fairly simple and direct:

``` swift
let i = 10
let s = "\(i)"
```

**Comment by devxoul** [comment]
@tylerlong, I'm using custom Transform.

```
/// Converts JSON to `String`.
///
/// - warning: It doesn't gaurantee the original type when convert `String` to JSON.
struct StringTransform: TransformType {

  func transformFromJSON(_ value: Any?) -> String? {
    return value.flatMap(String.init(describing:))
  }

	func transformToJSON(_ value: String?) -> Any? {
    return value
  }

}
```

Then

```swift
func mapping(map: Map) {
  stringValue <- (map["key"], StringTransform())
}
```
