### ISSUE TITLE
ConvertToJSONString with Realm

### ISSUE THREAD

**Issue by Phoxi** [Hearst-DD/ObjectMapper#652]
Is it possible to convert my object to JSONString after getting this item from Realm Database which i saved there earlier ? I am trying to achieve that but it just crush app.

**Comment by tristanhimmelman** [comment]
The `<_` operator requires the left hand side parameter to be of type `inout`. This is the reason that you are experiencing a crash as realm thinks we are modifying the object.

To work around this problem, you need to call toJSONString within a realm transaction block. Otherwise, we also have the following operator `>>>` that is used purely for defining mappings to JSON

**Comment by TopalSergey** [comment]
I think this can be helpful to people, that come to related thread. To avoid separating toJson and fromJson mapping, you can use functions, like this:
 ```
   func from<T>(_ obj: T) -> ((inout T) -> ())? {
        switch mappingType {
        case .toJSON:
            obj >>> self
            return nil

        case .fromJSON:
            return { (v: inout T) in
                v <- self
            }
        }
    }

    /// Optional object of basic type
    func from<T>(_ obj: T?) -> ((inout T?) -> ())? {
        switch mappingType {
        case .toJSON:
            obj >>> self
            return nil
            
        case .fromJSON:
            return { (v: inout T?) in
                v <- self
            }
        }
    }

    /// Object conforming to Mappable
    func from<T: BaseMappable>(_ obj: T) -> ((inout T) -> ())? {
        switch mappingType {
        case .toJSON:
            obj >>> self
            return nil
            
        case .fromJSON:
            return { (v: inout T) in
                v <- self
            }
        }
    }

    /// Optional Mappable objects
    func from<T: BaseMappable>(_ obj: T?) -> ((inout T?) -> ())? {
        switch mappingType {
        case .toJSON:
            obj >>> self
            return nil

        case .fromJSON:
            return { (v: inout T?) in
                v <- self
            }
        }
    }

```
and use it in mapping:
```
    override func mapping(map: Map) {
        map["id"].from(id)?(&id)
        map["name"].from(name)?(&name)
    }

```
Also, if you use operators to map Dictionaries, Arrays, operators with TransformType, you should write several similar functions.
