### ISSUE TITLE
Cocoapods integration in swift 2, iOS 9

### ISSUE THREAD

**Issue by nadeemkhoury** [Hearst-DD/ObjectMapper#653]
When I add  pod 'ObjectMapper', '~> 2.2' to my cocoapods file, I receive a lot of errors ?? what version should I add, or what should I do ?

**Comment by devxoul** [comment]
You should use 1.x for Swift 2

**Comment by nadeemkhoury** [comment]
Thank you so much, can you help where I can find old versions ?

**Comment by tristanhimmelman** [comment]
Here you go: https://github.com/Hearst-DD/ObjectMapper/releases

**Comment by nadeemkhoury** [comment]
Thank you much my friend.
