### ISSUE TITLE
Why do I need to initialize stored properties in init?() ? - Swift 3

### ISSUE THREAD

**Issue by rcholic** [Hearst-DD/ObjectMapper#654]
I have a model named `User` that implements the protocol `Mappable`. I have the `init(id: Int, name: String)` method defined as the initializer already, and I implemented the `init?(map: Map)` method as following:

```
init?(map: Map) {
    self.mapping(map: map)
}

mutating func mapping(map: Map) {
  // implemented, not shown here
}
```

If I do not initialized the stored properties in init?(map: Map), my XCode 8.1 shows error: self used before all stored properties are initialized; Return from initializer without initializing all stored properties.

So what should I do? should I re-initialize the stored properties in **init?()** ?

**Comment by ManWithBear** [comment]
1. Can you,please, provide full your code? 

> XCode 8.1 shows error: self used before all stored properties are initialized
You can't call object methods (mapping(_:) in your case) before all properties are initialized

**Comment by KoCMoHaBTa** [comment]
You must first initialize all of your stored properties before accessing them. This is required by the 2 step initialization process that is enforced by the compiler.
So your options are to either perform initialization in the init method or to have default values for all of your properties.
