### ISSUE TITLE
Binary operator '<-' cannot be applied to operands of type 'NSDate?' and '(Map, DateTransform)'

### ISSUE THREAD

**Issue by sakkeerhussain** [Hearst-DD/ObjectMapper#660]
I am getting this error on compile time itself. Attached screenshot with code and error message.

![screen shot 2016-11-05 at 1 12 34 pm](https://cloud.githubusercontent.com/assets/7835361/20028507/bf7fc084-a359-11e6-94cf-135769c1cb95.png)

**Comment by devxoul** [comment]
Possibly duplicated with #631. Use `Date`, not `NSDate`.

**Comment by sakkeerhussain** [comment]
This solved my issue, Thanks @devxoul.
