### ISSUE TITLE
using ObjectMapper framework without implementing func mapping

### ISSUE THREAD

**Issue by tazihosniomar** [Hearst-DD/ObjectMapper#662]
hi 
i wonder if there is a way to use ObjectMapper framework without implementing func mapping
because I have some objects that contains more than 200 properties.
thanks in advance

**Comment by ManWithBear** [comment]
If you dont want implement mapping functions, than you need to check some reflection mapping, like: https://github.com/evermeer/EVReflection
Or you some code-generators / macros. I common use macros in Vim, when I need to create mapping function for big object.
