### ISSUE TITLE
I translate document to Chinese, would you like to put a link into readme?

### ISSUE THREAD

**Issue by lacklock** [Hearst-DD/ObjectMapper#663]
ObjectMapper is popular in China. So I translate document to Chinese, would you like to put a link into readme? here is the link:  [ObjectMapper-CN-Guide](https://github.com/lacklock/ObjectMapper-CN-Guide)

**Comment by ManWithBear** [comment]
It will be better, if you make fork, add your translation md file, and send pull request.

**Comment by lacklock** [comment]
ok, i will do that tommorrow morning.

**Comment by lacklock** [comment]
but where should I put the md file?

**Comment by ManWithBear** [comment]
Beside README.md

**Comment by lacklock** [comment]
i have commit that PR.
