### ISSUE TITLE
required init?(map: Map) not called for NSManagedObject

### ISSUE THREAD

**Issue by maksTheAwesome** [Hearst-DD/ObjectMapper#665]
Hello Tristan,

I have a user model described below.

`class UserModel: NSManagedObject {
    required init?(map: Map) {
        let ctx = CoreDataStack.sharedInstance.managedObjectContext
        let entity = NSEntityDescription.entity(forEntityName: UserModel.entityName(), in: ctx)
        super.init(entity: entity!, insertInto: ctx)
    }
}`

`extension UserModel: Mappable, StaticMappable {
    
    func mapping(map: Map) {
        identifier <- map["data._id"]
        data <- map["data"]
    }
    
    static func objectForMapping(map: Map) -> BaseMappable? {
        if let identifier: String = map["data._id"].value() {
            if let userModel = UserModel.user(identifier, context: CoreDataStack.sharedInstance.managedObjectContext) {
                return userModel
            } else {
                return UserModel(map: map)
            }
        }
        return nil
    }
    
}`

I've noticed that required init?(map: Map) is not called when you have StaticMappable protocol implemented. Previously ObjectMapper called init method in case if objectForMapping(map: Map) was returning nil, and it does not now. Adding the following portion of code fixed problem, but still I think you should know.

` if let userModel = UserModel.user(identifier, context: CoreDataStack.sharedInstance.managedObjectContext) {
                return userModel
            } else {
                return UserModel(map: map)
            }`

**Comment by ManWithBear** [comment]
You can find in README:

> ```StaticMappable``` is an alternative to ```Mappable```. It provides developers with a static function that is used by ObjectMapper for object initialization **instead of** ```init?(map: Map)```.

**Comment by maksTheAwesome** [comment]
I see now. It used to call init() in case if that method was returning nil. Thank you.
