### ISSUE TITLE
Post-Mapping Validation

### ISSUE THREAD

**Issue by KoCMoHaBTa** [Hearst-DD/ObjectMapper#671]
Right now, the suggested way to perform mapping validation is to do it prior mapping in the `init?(map: Map)` initializer, however there is no good way to perform post-mapping validation.

**The use case:**
It is more convenient to perform a validation after a successful mapping, because:
- it is easier to check if a required property has been mapped successfully.
- it is easier to perform validation on transformed properties, like dates, rather than raw strings.

**The issue:**
The current implementation of the [`Mapper`](https://github.com/Hearst-DD/ObjectMapper/blob/master/Sources/Mapper.swift#L103) initializes the `Mappable` object and then calls the `mapping(map: Map)` function of `BaseMappable` protocol.
Obviously the intention of this behavior is to perform mapping after initialization, however the current implementation limits the usage of the `init?(map: Map)` initializer to perform validation based only on the raw json dictionary provided on the map. 

Trying to use it for post mapping validation, requires calling the mapping function from the initializer, which leads to double mapping that impacts the performance.
Other workaround is to perform validation at the end of the mapping function, however this brings the issue that this logic will be called also for serialization. 
Trying to avoid this brings more unnecessary burden on the Mappable objects.

**Proposal:**
Introduce an optional validation function that should be called after the mapping and based on its result - the mapping should continue or stop executing.

**PR details**
https://github.com/Hearst-DD/ObjectMapper/pull/672

**Comment by devxoul** [comment]
@KoCMoHaBTa, thanks for your proposal. Could you provide us the example use case? I mean, why do we need a post validation. `Transform`s are well-tested, and we can write tests for models.

**Comment by KoCMoHaBTa** [comment]
@devxoul I have added more detailed tests with description about use cases - https://github.com/Hearst-DD/ObjectMapper/pull/672/files#diff-5388011c7e59ca170360e3acc81c4719

The primary use case is the validation of required properties, although it can be used for things like date validations.

**Comment by devxoul** [comment]
@KoCMoHaBTa, You could write a test of `PaymentCard` in the Test Target of your project. Isn't it enough? I'm not sure why these things should be validated in Application Target.

**Comment by KoCMoHaBTa** [comment]
@devxoul Sorry, I did not get the point, but let me clarify - this use case for validating dynamic data coming from a server. It could change any time and the application must be sure that it throws away invalid data upon mapping.

**Comment by ManWithBear** [comment]
I think, you trying to solve wrong problem. This is mapping framework with only 1 responsibility: mapping object from/to JSON.
Validation is not part of this process.
So my opinion: validation shouldn't be part of ObjectMapper.

**Comment by KoCMoHaBTa** [comment]
Well it is, right now, but only limited to prior mapping.
The main problem that i'm trying to solve is to guarantee that required properties of Mappable objects will not get into inconsistent state and the object should accept them only if they are correct.
IMO this should be done with validation after mapping, because trying to do it prior is inconvenient.
If you have better ideas - i'm open to suggestion.

**Comment by tristanhimmelman** [comment]
@KoCMoHaBTa I understand your need, but I would prefer to not extend the protocols anymore at this point. Keeping the project as simple as possible is very important.

Perhaps allowing `mapping` to throw an error would be an alternative approach. I will put a bit more thought into this idea as I really try to minimize altering the protocols.

**Comment by tristanhimmelman** [comment]
Closing this ticket as I do not plan to add post mapping validation at this time. Thank you for your suggestion @KoCMoHaBTa
