### ISSUE TITLE
Mapping Dynamic and JSON Objects Without Keys

### ISSUE THREAD

**Issue by mattwitkowicz** [Hearst-DD/ObjectMapper#673]
I have JSON that I need to map to objects that are as follows:

```
{
	"data": {
		"questions": {
			"20161111": {
				"58137e55e4b0319ec58bc312": {
					"groupName": "Test1",
					"questions": {
						"1": {
							"questionId": "1",
							"text": "Question 1"
						},
						"2": {
							"questionId": "2",
							"text": "Question 2"
						}
					}
				},
				"58137e55e4b0319ec58bc313": {
					"groupName": "Test2",
					"questions": {
						"1": {
							"questionId": "1",
							"text": "Question 1"
						},
						"2": {
							"questionId": "2",
							"text": "Question 2"
						}
					}
				}
			},
			"20161112": {
				"58137e55e4b0319ec58bc312": {
					"groupName": "Test1",
					"questions": {
						"1": {
							"questionId": "1",
							"text": "Question 1"
						},
						"2": {
							"questionId": "2",
							"text": "Question 2"
						}
					}
				},
				"58137e55e4b0319ec58bc313": {
					"groupName": "Test2",
					"questions": {
						"1": {
							"questionId": "1",
							"text": "Question 1"
						},
						"2": {
							"questionId": "2",
							"text": "Question 2"
						}
					}
				}
			}
		}
	}
}
```

Objects:
```
class Response: Mappable {
    var days: [String: Day]?

    required init?(map: Map) {

    }
    func mapping(map: Map) {
        days <- map["questions"]
    }
}
```

```
class Day: Mappable {

    var groups: [String: Group]?

    required init?(map: Map) {

    }

    func mapping(map: Map) {
        groups <- map[""]
    }

}
```

Thanks to [this issue](https://github.com/Hearst-DD/ObjectMapper/issues/397) I was able to map the objects under the 'questions' key to a [String: Day]? dictionary. 

Now I need to map the JSON objects under the mapped Day object (i.e. 20161112 key) but they are randomly generated ID's, so I'm not sure what to do.

**Comment by KoCMoHaBTa** [comment]
Well, you could do the same - the IDs are actually strings, so you could represents the other types as [String: Group] for example.

**Comment by tristanhimmelman** [comment]
Thanks @KoCMoHaBTa, thats what I would suggest as well.

**Comment by mvpscottjon** [comment]
Excuse me for asking the similiar problem,
use this case for asking:
`class Day: Mappable {

    var groups: [String: Group]?

    required init?(map: Map) {

    }

    func mapping(map: Map) {
        groups <- map[""]
    }

}`

in this code
` func mapping(map: Map) {
        groups <- map[""]
    }`

what's the map["?"]     <------------  //////what should  I fill in "?"

did I  fill "questions.value"? or what?

**Comment by KoCMoHaBTa** [comment]
The whole design can be done this way

`          

        class Response: Mappable {
            var days: [String: Day]?
            
            required init?(map: Map) {
                
            }
            func mapping(map: Map) {
                days <- map["data.questions"]
            }
        }
        
        class Day: Mappable {
            
            var groups: [String: Group]?
            
            required init?(map: Map) {
                
            }
            
            func mapping(map: Map) {

                groups = [:]
                map.JSON.forEach { (key, value) in
                    
                    groups?[key] = Mapper().map(JSONObject: value)
                }
            }
        }
        
        class Group: Mappable {
            var groupName: String?
            var questions: [String: Question]?
            
            required init?(map: Map) {
                
            }
            
            func mapping(map: Map) {
                groupName <- map["groupName"]
                questions <- map["questions"]
            }
        }
        
        class Question: Mappable {
            var questionId: String?
            var text: String?
            
            
            required init?(map: Map) {
                
            }
            func mapping(map: Map) {
                questionId <- map["questionId"]
                text <- map["text"]
            }
        }
        
        let result = Mapper<Response>().map(JSONString: json)`

**Comment by vimalp015** [comment]
public class Data {
    @SerializedName("questions")
    @Expose
    private Map<String, Group> result;

    //....
}
