### ISSUE TITLE
How to handle dictionary root objects

### ISSUE THREAD

**Issue by shining228** [Hearst-DD/ObjectMapper#676]
Hi, I'm try to make a map like below:
let cache = "{\"2\": {\"region_name\": \"name_1\",\"region_id\": \"2\",\"children\": {\"3\": {\"region_name\": \"name_2\",\"region_id\": \"3\"}}},\"39\": {\"region_name\": \"name_3\",\"region_id\": \"39\",\"children\": {\"40\": {\"region_name\": \"name_4\",\"region_id\": \"40\",\"children\": {\"42\": {\"region_name\": \"name_5\",\"region_id\": \"42\"}}}}}}"
let regionMap = RegionMap(JSONString: cache)

I've tried these models below, but not work, is there some sample code about this? thx!
class RegionInfo: Mappable {
    
    var regionId: String?
    var regionName: String?
    var children: [String: RegionInfo]?
    
    required init?(map: Map) {
        
    }
    
    func mapping(map: Map) {
        regionId <- map["region_id"]
        regionName <- map["region_name"]
        children <- map["children"]
    }
    
}

class RegionMap: Mappable {
    
    var dictionary: [String: RegionInfo] = [:]
    
    required init?(map: Map) {
        
    }
    
    func mapping(map: Map) {
        dictionary <- map
    }
    
}

**Comment by tristanhimmelman** [comment]
See Mapper.swift:

There is a mapDictionary function which should handle this situation. 

Hope this helps
