### ISSUE TITLE
The app crash when using generic class. 

### ISSUE THREAD

**Issue by sunny131984** [Hearst-DD/ObjectMapper#677]
Fist of all thanks for such impressive framework.
The framework works fine and convert json object to model into simulator only using generic class <T> pattern. But the same time if i am going to run the application on actual device it will crash on below line.
`let contentString = try NSString(contentsOfFile: resourceDBFolderPath!, encoding: NSUTF8StringEncoding)
            print(contentString)
            let anyObj: AnyObject? =  try NSJSONSerialization.JSONObjectWithData(contentString.dataUsingEncoding(NSUTF8StringEncoding)! , options: NSJSONReadingOptions(rawValue: 0))
            if NSJSONSerialization.isValidJSONObject(anyObj!)
            {
                
               // let rootObject:RootApp =  Mapper<RootApp<Template>>().map(anyObj)!
//               
                let result = Mapper<Result<Template>>().map(anyObj) // Crash here only on device
`

So could you please check it and i have create same generic class as mention so could please let me know is there any other way to use it for both debug and release version

**Comment by tristanhimmelman** [comment]
I'm not sure what is causing your specific crash but in this code snippet there are many unsafe `!` operations.

I do not have any issues with generics when running on my device at the moment. I am closing this until further response.
