### ISSUE TITLE
Mapping dictionary of dictionary to object

### ISSUE THREAD

**Issue by mikkelam** [Hearst-DD/ObjectMapper#678]
I have not been able to figure out how to map this JSON

```
{
    "market_estimates": {
        "2000": {
            "0": 12830, 
            "10000": 11041
        },
        "2001": {
            "0": 12830, 
            "10000": 11041
        }
    }
}
```

Into an object like this:

```
class MarketEstimate {
	var year: Int = 0
	var price: Int = 0
	var mileage: Int = 0
}
```

How do I perform this task?

**Comment by devxoul** [comment]
@mikkelam, do you want an array of `MarketEstimate`?

**Comment by mikkelam** [comment]
Yes, I am sorry i did not specify. Do you know how I could solve this?

**Comment by devxoul** [comment]
Is this what you want? I'm not sure where `price` and `mileage` come from.

```swift
[
  MarketEstimate(year: 2000, price: 12830, mileage: 11041),
  MarketEstimate(year: 2001, price: 12830, mileage: 11041),
]
```

**Comment by mikkelam** [comment]
Yes, exactly

**Comment by devxoul** [comment]
You have to manipulate that json. Try:

```swift
let dict: [String: Any] = [
  "market_estimates": [
    "2000": [
      "0": 12830,
      "10000": 11041
    ],
    "2001": [
      "0": 12830,
      "10000": 11041
    ]
  ]
]
let jsonArray = (dict["market_estimates"] as? [String: [String: Int]] ?? [:])
  .flatMap { yearString, mileageAndPrice in
    return mileageAndPrice.flatMap { mileageString, price -> [String: Int]? in
      guard let year = Int(yearString),
        let mileage = Int(mileageString)
      else { return nil }
      return [
        "year": year,
        "mileage": mileage,
        "price": price,
      ]
    }
  }
let estimates = Mapper<MarketEstimate>().mapArray(JSONArray: jsonArray)
print(estimates)
```

**Comment by jsslai** [comment]
Do you have any alternative solution which could work for every dictionary of dictionaries? I'm using [Firebase](https://firebase.google.com) where every array is stored as dictionaries like in @mikkelam 's example.

**Comment by jsslai** [comment]
I ended up writing a custom mapping method which tries to map array or dictionary to array. In dictionary case key is passed by using Context.

```swift
extension Map {
	func valueFromArrayOrDictionary<Element: ImmutableMappable >(_ key: String, nested: Bool? = nil, delimiter: String = ".", file: StaticString = #file, function: StaticString = #function, line: UInt = #line) throws -> [Element] {
		let currentValue = self.currentValue(for: key, nested: nested, delimiter: delimiter)
		
		guard let JSONObject = currentValue else {
			throw MapError(key: key, currentValue: currentValue, reason: "Found unexpected nil value", file: file, function: function, line: line)
		}
		
		return try Mapper<Element>().mapArrayOrDictionary(JSONObject: JSONObject)
	}
	
	fileprivate func currentValue(for key: String, nested: Bool? = nil, delimiter: String = ".") -> Any? {
		let isNested = nested ?? key.contains(delimiter)
		return self[key, nested: isNested, delimiter: delimiter].currentValue
	}
}

extension Mapper where N: ImmutableMappable {
	func mapArrayOrDictionary(JSONObject: Any) throws -> [N] {
		if let dictionaries = JSONObject as? [String: Any] {
			return try dictionaries.map { try N(JSONObject: $0.value, context: FirebaseContext(key: $0.key)) }
		} else if let collection = JSONObject as? [Any] {
			return try collection.map { try N(JSONObject: $0) }
		} else {
			throw MapError(key: nil, currentValue: JSONObject, reason: "Cannot cast to '[String: Any] or [Any]")
		}
	}
}
```

**Comment by altagir** [comment]
simple way:
```
class MarketEstimate {
	var price: Int!
	var mileage: Int!
}
class MarketEstimates {
   var market_estimates:Dictionary<String, MarketEstimate >!
}
```
then you would have get your structure in market_estimates["2000"], but without the year inside the struct...

**Comment by mikkelam** [comment]
@altagir The reason I did not use a dictionary is because it is not supported by Realm.

**Comment by ios4vn** [comment]
> I ended up writing a custom mapping method which tries to map array or dictionary to array. In dictionary case key is passed by using Context.
> 
> ```swift
> extension Map {
> 	func valueFromArrayOrDictionary<Element: ImmutableMappable >(_ key: String, nested: Bool? = nil, delimiter: String = ".", file: StaticString = #file, function: StaticString = #function, line: UInt = #line) throws -> [Element] {
> 		let currentValue = self.currentValue(for: key, nested: nested, delimiter: delimiter)
> 		
> 		guard let JSONObject = currentValue else {
> 			throw MapError(key: key, currentValue: currentValue, reason: "Found unexpected nil value", file: file, function: function, line: line)
> 		}
> 		
> 		return try Mapper<Element>().mapArrayOrDictionary(JSONObject: JSONObject)
> 	}
> 	
> 	fileprivate func currentValue(for key: String, nested: Bool? = nil, delimiter: String = ".") -> Any? {
> 		let isNested = nested ?? key.contains(delimiter)
> 		return self[key, nested: isNested, delimiter: delimiter].currentValue
> 	}
> }
> 
> extension Mapper where N: ImmutableMappable {
> 	func mapArrayOrDictionary(JSONObject: Any) throws -> [N] {
> 		if let dictionary = JSONObject as? [String: Any] {
> 			return try dictionary.map { try N(JSONObject: $0.value, context: FirebaseContext(key: $0.key)) }
> 		} else if let array = JSONObject as? [Any] {
> 			return try array.map { try N(JSONObject: $0) }
> 		} else {
> 			throw MapError(key: nil, currentValue: JSONObject, reason: "Cannot cast to '[String: Any] or [Any]")
> 		}
> 	}
> }
> ```

Could you give an example how to use this extension?
