### ISSUE TITLE
Issue with NSManagedObject class conforming to Mappable

### ISSUE THREAD

**Issue by hopiaw** [Hearst-DD/ObjectMapper#68]
Hi,

I'm trying to map directly JSON to a class model inheriting NSManagedObject. I created an extension that conform to Mappable and implement mapping.

At compile time, I got a Swift compiler error, usr/bin/swiftc failed to exit code 1.

It might be due to the init() method of the Mappable protocol. When reading the Mapper.swift class I found the following:

       /**
	* Maps a JSON dictionary to an existing object that conforms to Mappable.
	* Usefull for those pesky objects that have crappy designated initializers like NSManagedObject
	*/
	public func map(JSON: [String : AnyObject], var toObject object: N) -> N {
		let map = Map(mappingType: .fromJSON, JSONDictionary: JSON)
		object.mapping(map)
		return object
	}

which would be the function to use in order to set properties of the entity once created.

Could you post an example of an NSManagedObject class conforming to Mappable?

Thanks

**Comment by tristanhimmelman** [comment]
Hi, I have not actually used ObjectMapper with an NSManagedObject as of yet. However perhaps @brandonroth can provide insight, as he is the one who contributed the above function.

**Comment by funky-monkey** [comment]
YES! I'm having the same problem as well. 
Can there be done something about the required init in the Mappable protocol?

**Comment by tristanhimmelman** [comment]
The required init is necessary so that ObjectMapper can instantiate objects during the mapping process. I can't think of a way to remove it at the moment. I'll put some more thought into it.

**Comment by tristanhimmelman** [comment]
The latest release has an update to the Mappable protocol. It no longer requires default initializer function. This may resolve the issue you all have been having.

**Comment by funky-monkey** [comment]
Great stuff!
What i've seen so far, is that if i omit the init method, the compiler will complain. I think it is a failable initializer, not an optional initializer. But please prove me wrong ;-)

**Comment by bonebox** [comment]
It is still required in 0.9. Am I missing something?

**Comment by tristanhimmelman** [comment]
`init?` is part of Mappable but `init` is not anymore.

````
public protocol Mappable {
	init?(_ map: Map)
	mutating func mapping(map: Map)
}
```

**Comment by bonebox** [comment]
Since it still has to be declared, I get the compiler error:
```
'/Users/jeremy/Development/Allogy/frameworks/mForms/mForms/Element.swift:20:12: Initializer requirement 'init' can only be satisfied by a `required` initializer in non-final class 'Element'
```
And when I add `required`, it forces me to call the designated initializer for NSManagedObject.

**Comment by vincent-ch** [comment]
Hi @bonebox , I'm facing the same problem. How do you resolved it ?

**Comment by bonebox** [comment]
Hi @vincent-ch , I actually didn't resolve it.  I ended up going with a different library, called [Sync] (github.com/hyperoslo/Sync).  It is awesome if you're mapping into managed objects!

**Comment by bonebox** [comment]
Hi @vincent-ch , I actually didn't resolve it.  I ended up going with a different library, called [Sync](https://github.com/hyperoslo/Sync).  It is awesome if you're mapping into managed objects!

**Comment by vincent-ch** [comment]
Thanks for the hint. If anyone would be interested in this case, I don't know if this is the proper way to do it, but I resolved it this way: 

    class AbstractModel: NSManagedObject, Mappable {
     
        @NSManaged var uuid: String?
        @NSManaged var updatedAt: String?
        @NSManaged var createdAt: String?
     
        override init(entity: NSEntityDescription, insertIntoManagedObjectContext context: NSManagedObjectContext?) {
             super.init(entity: entity, insertIntoManagedObjectContext: DBUtils().getManagedObjectContext())
         }

        required init?(_ map: Map) {
            var ctx = NSManagedObjectContext.MR_defaultContext()
            var entity = NSEntityDescription.entityForName("AbstractModel", inManagedObjectContext: ctx)
            super.init(entity: entity!, insertIntoManagedObjectContext: ctx)
    
            mapping(map)
         }
    
        func mapping(map: Map) {
            uuid        <- map["uuid"]
            updatedAt   <- map["updatedAt"]
            createdAt   <- map["createdAt"]
    
         }
    }

**Comment by Wii2zO** [comment]
Hey,

I use the method of @vincent-ch to map my JSON and store the POJO to the database, I succeed with one class, but how do that with a member which is an Array of another object ?
ObjectMapper use a simple Array to do this and it works perfectly, but CoreData use "NSSet" for relationships with another table...
I don't know how to do...

**Comment by vincent-ch** [comment]
Hi @Wii2zO , I faced the same problem and solved it that way: I created a temp array (this will not be persisted) to let ObjectMapper do its magic and then initialized the NSSet with that array using   ```NSSet(array: elementsArray!)``` .

Hope this helps! (:

Here's a full exemple:
    
    @objc(Gallery)
    class Gallery: AbstractModel, Mappable {

    @NSManaged var title: String?
    @NSManaged var shootingDate: String?
    @NSManaged var elements: NSSet?
    
    private var elementsArray: [Image]?

    override init(entity: NSEntityDescription, insertIntoManagedObjectContext context: NSManagedObjectContext?) {
        super.init(entity: entity, insertIntoManagedObjectContext: DBUtils().getManagedObjectContext())
    }
    
    required init?(_ map: Map) {
        var ctx = DBUtils().getManagedObjectContext()
        var entity = NSEntityDescription.entityForName("Gallery", inManagedObjectContext: ctx)
        super.init(entity: entity!, insertIntoManagedObjectContext: ctx)
        
        mapping(map)
    }
    
    override func mapping(map: Map) {
        
        super.mapping(map)
        
        title           <- map["title"]
        shootingDate    <- map["shootingDate"]
        elementsArray   <- map["elements"]
        
        elements = NSSet(array: elementsArray!)
        elementsArray = nil
        
    }
    
}

**Comment by Wii2zO** [comment]
Thank you for your response !
It seems to work... !

**Comment by HRiffiod** [comment]
Hi there, I've been trying @vincent-ch 's code but I'm having some troubles mapping custom NSManaged classes. Here's an example of my class : 

import Foundation
import CoreData

class Credential: NSManagedObject, Mappable {

    @NSManaged var credentialArrivalDate: String?
    @NSManaged var credentialBarCode: String?
    @NSManaged var credentialComment: String?
    @NSManaged var credentialCountCheckIn: Int
    @NSManaged var credentialCountCheckOut: Int
    @NSManaged var credentialDepartureDate: String?
    @NSManaged var credentialId: String?
    @NSManaged var credentialIsArrived: Bool
    @NSManaged var credentialIsCheckedOut: Bool
    @NSManaged var credentialIsHost: Bool
    @NSManaged var credentialLastModificationDate: String?
    @NSManaged var credentialMemberControlled: String?
    @NSManaged var credentialNumberOfPeople: Int
    @NSManaged var credentialRSVP: Int
    @NSManaged var credentialTypeId: String?
    @NSManaged var credentialTypeName: String?
    @NSManaged var credentialZoneId: String?
    @NSManaged var credentialZoneName: String?
    @NSManaged var credentialHosts: Set<Host>?
    @NSManaged var credentialMember: Member
    @NSManaged var credentialExtensionFields: Set<ExtensionFields>?
    @NSManaged var credentialDeltaFirstCheckIn: String?
    @NSManaged var credentialDeltaFirstCheckOut: String?
    @NSManaged var credentialIsCheckedIn: Bool
}

I have a relationship to a Member NSManaged class, and to-many relationships to Host and ExtensionFields.

My goal is to build JSON data from the credential class (including the relationships). I did have some success with a custom parser ( see my post on stack-overflow : http://stackoverflow.com/questions/31672558/ios-swift-serialize-a-nsmanagedobject-to-json-with-relationships/31697576?noredirect=1#comment51347010_31697576)

BUT to conform to the json data that the web service needs, I need to map my class because the variables don't have the same names etc.

That said, I'm getting error (found nil while unwrapping) with @vincent-ch' s code (the difference being I use Set and not NSSet, could it be the problem here ?) 

Is there a way to map my JSON string just to change variables name or can ObjectMapper do the magic for me ?

Thanks for your help,


Hugo

**Comment by vincent-ch** [comment]
Hi @HRiffiod ,

I don't know if the difference between Set and NSSet could be the problem, but I always try to use only the types generated by XCode (from the .xcdatamodel file). Could you try with NSSet?

And could you gave us the code line where you get the error?

**Comment by HRiffiod** [comment]
Hi @vincent-ch ,

so I added this code to my class : 

 // temporary array tos allow mapping
    var credentialHostsArray: [Host]?
    var credentialExtensionFieldsArray: [ExtensionFields]?
    
    class func newInstance() -> Mappable {
        return Credential()
    }
    
    func mapping(map: Map) {
        
        credentialBarCode <- map["barCode"]
        credentialIsHost  <- map["isHost"]
        credentialTypeId  <- map["typeId"]
        credentialRSVP    <- map["RSVP"]
        credentialComment <- map["comments"]
        credentialZoneId  <- map["zoneId"]
        credentialMember  <- map["member"]
        credentialIsCheckedIn   <- map["isCheckIn"]
        credentialIsCheckedOut  <- map["isCheckOut"]
        credentialCountCheckIn  <- map["countCheckin"]
        credentialCountCheckOut <- map["countCheckout"]
        credentialMemberControlled  <- map["memberControlled"]
        credentialDeltaFirstCheckIn <- map["deltafirstCheckin"]
        credentialDeltaFirstCheckIn <- map["deltaFirstCheckout"]
        
        credentialHosts = Set(credentialHostsArray!)
        credentialHostsArray = nil
        
        credentialExtensionFields = Set(credentialExtensionFieldsArray!)
        credentialExtensionFieldsArray = nil
        
    }

and I'm getting the error on this line : credentialHosts = Set(credentialHostsArray!)

Which is not that surprising because my array is declared as optional and is never initialized/filled before this line is called. so my JSON string should contain something like "credentialHosts" : [] (just an empty array as long as I don't add Hosts in my app).

Maybe I'm misunderstanding some initialization part (I'm kinda new to Swift). Should I add some code to my Host class for example ? At this time it looks like this : 

import Foundation
import CoreData

class Host: NSManagedObject {

    @NSManaged var hostEmail: String
    @NSManaged var hostId: String
    @NSManaged var hostName: String
    @NSManaged var hostPhone: String
    @NSManaged var hostTitle: String
    @NSManaged var hostCredential: Credential

}

PS : I'd like to make sure that it does not come from an misunderstanding instead of NSSet because I'm trying to use as much as possible native types in my app...

**Comment by vincent-ch** [comment]
I think you're almost there. I would change your function that way (I guessed the WS parameters' names, maybe you have to change them):

    func mapping(map: Map) {

    credentialBarCode <- map["barCode"]
    credentialIsHost  <- map["isHost"]
    credentialTypeId  <- map["typeId"]
    credentialRSVP    <- map["RSVP"]
    credentialComment <- map["comments"]
    credentialZoneId  <- map["zoneId"]
    credentialMember  <- map["member"]
    credentialIsCheckedIn   <- map["isCheckIn"]
    credentialIsCheckedOut  <- map["isCheckOut"]
    credentialCountCheckIn  <- map["countCheckin"]
    credentialCountCheckOut <- map["countCheckout"]
    credentialMemberControlled  <- map["memberControlled"]
    credentialDeltaFirstCheckIn <- map["deltafirstCheckin"]
    credentialDeltaFirstCheckOut <- map["deltaFirstCheckout"]
    credentialHostsArray <- map["credentialHosts"]
    credentialExtensionFieldsArray <- map["credentialExtensionFields"]

    credentialHosts = Set(credentialHostsArray!)
    credentialHostsArray = nil

    credentialExtensionFields = Set(credentialExtensionFieldsArray!)
    credentialExtensionFieldsArray = nil

    }

ObjectMapper will do the mapping of Hosts and ExtensionFieldsArray for you. The (almost) only thing my code does is to save this mapping in a temporary array (i.e. credentialHostsArray) and then "convert it" into a NSSet/Set (i.e. credentialHosts).

**Comment by HRiffiod** [comment]
Thank you for your answer, I updated my code, unfortunately, same error : 
<img width="821" alt="capture d ecran 2015-08-05 a 10 46 34" src="https://cloud.githubusercontent.com/assets/9365076/9081762/73cca43a-3b5f-11e5-9d29-5141241c0607.png">

I have a View Controller with a bunch of textfields where I get user input values, set them in a Credential object and then I want the corresponding JSON string.

Let's say my User did not specify any Host, the credentialHosts array will then be nil, according to the declaration right ?

So where using forced unwrapping, it founds nil and crashes (I guess, not 100% sure).

So maybe my mistake is I should always : 

- Create a New Credential Entity (and insert it in my managed context)
- Retrieve the values from the text fields and set them to my new Credential
- Create a New Host Array (even if there is no Host, just to make an empty array an avoid crashing ?)
- Set it like this : newCredential.credentialHostsArray = hostArray
- Then map using Mapper().toJSONString ?

**Comment by vincent-ch** [comment]
Ok, I got it! Yes, my solution works only if the parameters are always set (mandatory fields). In your case your last answer sounds good, you could also check if the arrays are nil after the mapping and then set an empty array in that case. Let me know if your solution worked!

**Comment by HRiffiod** [comment]
So I tried creating empty arrays, if prevents from crashing, first step :)

However, event when hard-coding some value to a host, my Json output does not contain my Host array, any idea why it does not work ?

Here is the code : 

// create a host Array to avoid crashing if nil
        var hostsArray = [Host]()
        let newHost = NSEntityDescription.insertNewObjectForEntityForName("Host", inManagedObjectContext: self.managedObjectContext!) as! Host
        newHost.hostName = "testHostName"
        hostsArray.append(newHost)
        newCredential.credentialHostsArray = hostsArray
        
        // create a credentialExtensionFields Array to avoid crashing if nil
        var extensionFieldsArray = [ExtensionFields]()
        newCredential.credentialExtensionFieldsArray = extensionFieldsArray
        
        // create a request to fetch the credential
        let requestGuest = NSFetchRequest(entityName: "Credential")
        
        // set a predicate to retrieve the credential according to its Id
        requestGuest.predicate = NSPredicate(format: "credentialId = %@", newCredential.credentialId!)
        
        /**********/
        
        // execute request
        let testFetch = (managedObjectContext!.executeFetchRequest(requestGuest, error:nil) as! [Credential]).first!
        
        var jsonTestGuest = Mapper().toJSONString(testFetch, prettyPrint: true)
        println(jsonTestGuest!)


and here is the json output : 

{
  "memberControlled" : "Hugo",
  "RSVP" : 1,
  "comments" : "a comment",
  "isHost" : false,
  "countCheckout" : 0,
  "isCheckIn" : false,
  "countCheckin" : 0,
  "isCheckOut" : false
}

**Comment by vincent-ch** [comment]
My solution works for a mapping from JSON and you're working to JSON. 

But nevertheless, I don't understand why your hosts are empty, because you're filling the array used in the ObjectMapper's mapping process. If I understand the ObjectMapper's doc right, the ```<-``` operator works in both ways so it should work. If I have time I'll check further why it doesn't work. 

Did you try to debug your code and see what happens during the mapping process?

**Comment by f1nality** [comment]
Guys, what do you if you have multiple ManagedObjectContext? I don't see any options how to tell mapper which context is should create entites in..

**Comment by marcospolanco** [comment]
@vincent-ch, you might be the only person on Earth to get this working. I followed your example (thx!) yet my code crashes calling mapping(map) with EXC_BAD_ACCESS(code=1). Seen anything like this?

**Comment by vincent-ch** [comment]
Hi guys,

I'm sorry, I don't work on that mobile project anymore, so I'll do my best to help you without XCode.

@f1nality : I set the context with the following line ```var ctx = DBUtils().getManagedObjectContext()```. There you can define wich context you want to use. In my case, if I remembered well, the method just returns the default context.

@marcospolanco : the ```EXC_BAD_ACCESS``` happens typically when you didn't initialize an object. Here a link to help you debugging it: http://www.touch-code-magazine.com/how-to-debug-exc_bad_access/

**Comment by iroller** [comment]
@bonebox how do you convert objects to JSON when using Sync? Are you still using ObjectMapper for it? Can't get them both to work together

**Comment by bonebox** [comment]
Yep, that's it.

**Comment by jackalcooper** [comment]
What is the proper place to perform managedObjectContext.save() of the context? Or it is unnecessary?

**Comment by Steveybrown** [comment]
@f1nality I have this working with multi contexts, one way to achieve this is to use a [custom mapping context object](https://github.com/Hearst-DD/ObjectMapper#mapping-context). The custom mapping context object can hold an NSManagedObjectContext in which you want to save the object. To extract this NSManagedObjectContext from the init function we can do something like map.context.myManagedObjectContext. This still works cleanly with @vincent-ch solution.

**Comment by GABHISEKBUNTY** [comment]
@vincent-ch Hi I am working on a project that uses objectMapper for its use. Please kindly explain what exactly is being done by this 2 functions:

override init(entity: NSEntityDescription, insertIntoManagedObjectContext context: NSManagedObjectContext?) {
    super.init(entity: entity, insertIntoManagedObjectContext: DBUtils().getManagedObjectContext())
}

required init?(_ map: Map) {
    var ctx = DBUtils().getManagedObjectContext()
    var entity = NSEntityDescription.entityForName("Gallery", inManagedObjectContext: ctx)
    super.init(entity: entity!, insertIntoManagedObjectContext: ctx)

    mapping(map)
}

**Comment by tristanhimmelman** [comment]
@GABHISEKBUNTY look into the `StaticMappable` protocol. You should be able to integrate more easily using `StaticMappable` as it does not require overriding init

**Comment by GABHISEKBUNTY** [comment]
@tristanhimmelman Actually I just wanted to know what exactly is going on these 2 methods. A small quick explannation will be quite helpful.

**Comment by tristanhimmelman** [comment]
Ah then I will leave that to @vincent-ch as I am not familiar with his implementation

**Comment by GABHISEKBUNTY** [comment]
@tristanhimmelman But what exactly this implementation helps for?

**Comment by vincent-ch** [comment]
@GABHISEKBUNTY Hi, I'm sorry, I don't work on that mobile project anymore. I cannot remember how I come to this solution. And sorry for the late answer, I was on holidays.

The first one overrides the default constructor to call the super constructor including the default context (I get it with DBUtils().getManagedObjectContext()).

The second one get the entity "Gallery" from the default context (always by calling DBUtils().getManagedObjectContext()), call the super constructor and then call the mapping method.

I hope it will help, just ask if you need some more precise informations.

**Comment by calvinsug** [comment]
Hi, is this code still working on Swift3 on iOS 10 ? cause i cant use DButils, it says "Use of unresolved identifier 'DBUtils'"

is DBUtils come from another library ?

**Comment by vincent-ch** [comment]
@calvinsug Sorry, I know this part was a little bit confusing because the DBUtils was part of my project. If I remember well, this method simply returns the default context.

**Comment by calvinsug** [comment]
@vincent-ch ok, i got it now, anyway, i still can't get the mapping works

here's my sample attribute in Song model
`    @NSManaged var artists: Set<Artist>
    var tmpArtists: [Artist]?
`

and my function mapping

`    func mapping(map: Map) {
        tmpArtists <- map["artists"]        
        artists = Set(tmpArtists!)
        tmpArtists = nil
    }
`

my code will got error in this code:
`artists = Set(tmpArtists!)`

**Comment by nikhilaqburst** [comment]
@vincent-ch i used your code and its working perfectly. But when i relaunch the app all the save datas in core data db get disappeared. 

I used the same code
```
@objc(Gallery)
class Gallery: AbstractModel, Mappable {

@NSManaged var title: String?
@NSManaged var shootingDate: String?
@NSManaged var elements: NSSet?

private var elementsArray: [Image]?

override init(entity: NSEntityDescription, insertIntoManagedObjectContext context: NSManagedObjectContext?) {
    super.init(entity: entity, insertIntoManagedObjectContext: DBUtils().getManagedObjectContext())
}

required init?(_ map: Map) {
    var ctx = DBUtils().getManagedObjectContext()
    var entity = NSEntityDescription.entityForName("Gallery", inManagedObjectContext: ctx)
    super.init(entity: entity!, insertIntoManagedObjectContext: ctx)

    mapping(map)
}

override func mapping(map: Map) {

    super.mapping(map)

    title           <- map["title"]
    shootingDate    <- map["shootingDate"]
    elementsArray   <- map["elements"]

    elements = NSSet(array: elementsArray!)
    elementsArray = nil

}

}
```

Any  help will be appreciated.

**Comment by vincent-ch** [comment]
Hi @niks1990 ,
I'm sorry, I don't work on mobile projects anymore. I don't have any wise hint to suggest...

**Comment by haroldogtf** [comment]
@niks1990 could you solve your problem? I am facing the same! After relaunch I losing the data.

**Comment by billsea** [comment]
Calling mapping(map) in required_init resulted in duplicates. Here's what is working for me:
`import CoreData
import Foundation
import ObjectMapper

@objc(Room)
public class Room: NSManagedObject, Mappable {
  private var devicesArray: [Device]?

  override init(entity: NSEntityDescription, insertInto context: NSManagedObjectContext?) {
    super.init(entity: entity, insertInto: DataController.shared.persistentContainer.viewContext)
  }

  required public init?(map: Map) {
    let ctx = DataController.shared.persistentContainer.viewContext
    let entity = NSEntityDescription.entity(forEntityName: "Room", in: ctx)

    if let dataEntity = entity {
      super.init(entity: dataEntity, insertInto: ctx)
    } else {
      super.init()
    }
  }

  public func mapping(map: Map) {
    id <- map["id"]
    unit <- map["unit"]
    name <- map["name"]
    roomDescription <- map["roomDescription"]
    devicesArray <- map["devices"]

    if let devices = devicesArray {
      device = NSSet(array: devices)
    }
    
    devicesArray = nil
  }
}`

**Comment by ricardonho** [comment]
> @vincent-ch, you might be the only person on Earth to get this working. I followed your example (thx!) yet my code crashes calling mapping(map) with EXC_BAD_ACCESS(code=1). Seen anything like this?

So many years for this answer... but for me the mapping(map) crash happened when:

1 - the class prototype was missing @objc(class) declaration;
2 - the entity on .xcdatamodeld was with codegen different that "Manual/none", resulting in a colateral effect after super.init is called, an instance of the autogenerated core data class being allocated instead of my current class... bizarre.
