### ISSUE TITLE
Error: Return form initializer without initializing all stored properties (Is this only me :( 

### ISSUE THREAD

**Issue by AashishSapkota** [Hearst-DD/ObjectMapper#681]
<img width="1029" alt="screen shot 2016-11-25 at 9 51 45 am" src="https://cloud.githubusercontent.com/assets/6425249/20614319/44628a16-b2f5-11e6-81a8-bc80397fddf4.png">

**Comment by devxoul** [comment]
Property `status` and `msg` should have initial value.

**Comment by tristanhimmelman** [comment]
Thanks @devxoul

**Comment by AashishSapkota** [comment]
Oh thank you so much. 👍 I dint even thought abt that..
