### ISSUE TITLE
ImmutableMappable example needed.

### ISSUE THREAD

**Issue by jleach** [Hearst-DD/ObjectMapper#682]
I'm testing the immutable mapping and I can't get any custom immutable objects to map. For example, if I have and object (that's Mappable) with this property defined: `public var foos: [Foo]?` its not mapping any Foo objects.

```
    public func mapping(map: Map) {
        
        name <- map["name"]
        foos <- map["foos"]
    }
```

```
public class Foo {
    
    public let name: String
    
    public init(map: Map) throws {
        name = try map.value("name")
    }
}
```

The `name` variable is populated as expected but I get nothing in my `foo` variable. Perhaps I need iterate over map["foos"] and create the objects myself?

**Comment by devxoul** [comment]
Possibly duplicated with #668.
