### ISSUE TITLE
simplify

### ISSUE THREAD

**Issue by kristopher8** [Hearst-DD/ObjectMapper#685]
Look!
       name_first <- map["name_first"]
        height <- map["height"]
        weight <- map["weight"]
       ......more,

Is there a simplified way?
like runtime, like this 

        var count : UInt32 = 0
        let ivars = class_copyIvarList(self.classForCoder, &count)
        
        defer {
            free(ivars)
        }
        
        for i in 0..<count {
            
            let ivar = ivars?[Int(i)]
            let name = ivar_getName(ivar)
            let key = String(utf8String: name!)
            
            if let value = dic.object(forKey: key!) {
                setValue(value, forKey: key!)
            }
        }

**Comment by devxoul** [comment]
Possibly duplicated with #662 and #179

**Comment by tristanhimmelman** [comment]
Agreed, this is a duplicate. ObjectMapper has no plans to support mapping via reflection.

**Comment by kristopher8** [comment]
Why$B!$(Bif there are hundreds of thousands of attributes $B!$(Bthere is no shorthand way to map$B!)(B

Get Outlook for iOS<https://aka.ms/o0ukef>




On Tue, Nov 29, 2016 at 1:53 AM +0800, "Tristan Himmelman" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #685<https://github.com/Hearst-DD/ObjectMapper/issues/685>.

-
