### ISSUE TITLE
Send full map to custom transformer

### ISSUE THREAD

**Issue by depl0y** [Hearst-DD/ObjectMapper#686]
I can't seem to figure out how to send the full map to a Custom transformer I wrote. I have an object that uses the `mapping(map: Map)` method and it maps some keys to some properties.

But then I want to send the full map that was supplied to a Transformer, which picks a couple of values and stores it in an object.

```
public func mapping(map: Map) {
	self.id <- map["id"]
	self.name <- map["name"]
	self.temperature <- (map, TimedValuesTransformer())
}
```

This is the JSON I have:
```
{
    id: 0,
    name: "Outside",
    channel: 1,
    model: 0,
    te: 17.1,
    hu: 60,
    te+: 19.5,
    te+t: "19:49",
    te-: 8.5,
    te-t: "18:14",
    hu+: 76,
    hu+t: "18:14",
    hu-: 60,
    hu-t: "19:51",
    outside: "yes",
    favorite: "no"
}
```

Only this results in a Transformer not being called.

**Comment by tristanhimmelman** [comment]
You should not pass the map without setting its key. Otherwise, the map will keep the key value from the previous mapping. An alternative would be to initialize your transform with the map:
```
self.temperature <- (map["temperature"], TimedValuesTransformer(map: Map))
```
