### ISSUE TITLE
Run a few points in the ios8 and 9:00 machine error

### ISSUE THREAD

**Issue by kristopher8** [Hearst-DD/ObjectMapper#687]
dyld: Library not loaded: @rpath/ObjectMapper.framework/ObjectMapper
  Referenced from: /var/containers/Bundle/Application/008A9542-ADC8-4C62-9727-A2E7F422D6D6/AvayaStadium_Stage.app/AvayaStadium_Stage
  Reason: image not found
-------
Is there any solution?

**Comment by devxoul** [comment]
How did you setup ObjectMapper?

**Comment by kristopher8** [comment]
Select the ObjectMapper.xcodeproj in the Project Navigator and verify the deployment target matches that of my application target.
In the tab bar at the top of that window, open the "General" panel.
Click on the + button under the "Embedded Binaries" section

**Comment by tristanhimmelman** [comment]
Is this still a problem? If so please follow up. Closing this issue for now.
