### ISSUE TITLE
Map context forwarding

### ISSUE THREAD

**Issue by haritowa** [Hearst-DD/ObjectMapper#689]
Hello, why don't you forward mapping context in [map](https://github.com/Hearst-DD/ObjectMapper/blob/master/Sources/ImmutableMappable.swift#L90) method, or provide way to customize it?

**Comment by tristanhimmelman** [comment]
Hey @haritowa, good point. The MapContext should be forwarded for immutable mappings. 

If you have the time, a PR would be appreciated for this functionality.

Thanks!

**Comment by haritowa** [comment]
Should it be forwarded only for Immutable mappings? I believe any mappable type can benefit from Context forwarding

**Comment by tristanhimmelman** [comment]
I believe it is already forwarded for the other protocols

**Comment by haritowa** [comment]
Ok, just double-check, pr will be available in a couple of hours

**Comment by haritowa** [comment]
Create [PR](https://github.com/Hearst-DD/ObjectMapper/pull/695), but Travis check failed for strange reason. Maybe performance check failed, but i barely affect this.
