### ISSUE TITLE
Do dictionary properties have to have String keys?

### ISSUE THREAD

**Issue by jbmaxwell** [Hearst-DD/ObjectMapper#690]
I'm trying to map a dictionary of [Int : MyStruct], but it appears to fail (i.e., nothing is written to the JSON). MyStruct is Mappable, and it maps fine as a property of another class I'm storing. 
So, I'm wondering if my keys have to be String for ObjectMapper dictionaries (since all the examples use String keys)? If so, how would you recommend managing this?

[EDIT: It looks like I had a nested object that didn't implement Mappable... will fix that and see if it fixes things.]

**Comment by tristanhimmelman** [comment]
At the moment ObjectMapper only supports Strings as the keys for dictionaries
