### ISSUE TITLE
generic type mapping

### ISSUE THREAD

**Issue by frontier17** [Hearst-DD/ObjectMapper#696]
Hi,

I have a response model like;

class ResponseModel<T : Mappable>: Mappable {

    var data: T?
    var code: Int = 0

    required init?(map: Map) {}
    
    func mapping(map: Map) {
        data <- map["data"]
        code <- map["code"]
    }
}

If json not an array it works;
{"code":0,"data":{"id":"2","name":"XXX"}}

but if an array does not work;
{"code":0,"data":[{"id":"2","name":"XXX"},{"id":"3","name":"YYY"}]}

My mapping code;

let apiResponse = Mapper<ResponseModel<T>>().map(JSONObject: response.result.value)

**Comment by haritowa** [comment]
If son contains Array, shouldn't you use `let apiResponse = Mapper<Array<ResponseModel>>().map(JSONObject: response.result.value)`?

**Comment by liyanhuadev** [comment]
i thank, it should be 
`
class ResponseArrayModel<T>: Mappable {

var data: [T]?
var code: Int = 0
}
`

**Comment by liyanhuadev** [comment]
you need have two response model,one handler object, the other one handler array object

**Comment by frontier17** [comment]
yes I understand for array, but what will I do for just string? one more response model?

**Comment by liyanhuadev** [comment]
`
class Response<T>: Mappable {
    var data: T?
    
    required init?(map: Map) {
        
    }
    
    func mapping(map: Map) {
        data <- map["data"]
    }
}

`
mapping code:
`Mapper<Response<String>>().map(JSONObject: "your json")`

**Comment by nearspears** [comment]
what is your final solution ? i have the same problem

**Comment by KoCMoHaBTa** [comment]
You can have something like this:

```
public struct ResponseValue<P>: Mappable {
    
    public var payload: P?
    
    public mutating func mapping(map: Map) {
        
        self.payload <- map["payload"]
    }
}


public struct ResponseObject<P: Mappable>: Mappable {
    
    public var payload: P?
    
    public mutating func mapping(map: Map) {
        
        self.payload <- map["payload"]
    }
}

public struct ResponseArray<P>: Mappable {
    
    public var payload: [P]?
    
    public mutating func mapping(map: Map) {
        
        self.payload <- map["payload"]
    }
}
```

**Comment by tristanhimmelman** [comment]
Thanks @KoCMoHaBTa, that is the best approach at the moment.
