### ISSUE TITLE
map POJO to JSON string 

### ISSUE THREAD

**Issue by TahorSuiJurisBenYAH** [Hearst-DD/ObjectMapper#699]
Hello, please... is it possible to create a JSON string from a POJO class ?

tried JACKSON but no one seems to understand what I am talking about
tried GSON, same thing...

Hello, please:

How may I accomplish converting a POJO into a JSON (writeValue) -

Need to write an ObjectMapper with System.out.println test.

http://stackoverflow.com/questions/41142802/jsf-managed-bean-accessing-mysql-remote-database-how-to-create-json-array-to-f

Any suggestions greatly appreciated.

Jon

**Comment by tristanhimmelman** [comment]
This project is a Swift library. I believe you are referring to Java libraries. Closing this issue. I will reopen if you follow up.
