### ISSUE TITLE
[Question] Get all Keys of Map

### ISSUE THREAD

**Issue by gperdomor** [Hearst-DD/ObjectMapper#701]
Hi...

I have a question can i get all the keys of <code>map</code> inside <code>mapping(map: Map)</code> function.

I need do that because i have a mappable class with two fields, a <code>type</code> as <code>String</code> and <code>parameters</code> as a <code>Dictionary<String, Any></code> and i receive a Dictionary like this as server response:

<pre>
<code>
[
    type: some_type,
    param1: value1,
    param2: value2,
    ...
    paramN: valueN
]
</code>
</pre>

Any key different of <code>type</code> is a parameter, so i want iterate the map (I don't know how) and build a new dictionary with the other keys

**Comment by gperdomor** [comment]
I solved it, i can access to map.JSON xD

**Comment by haritowa** [comment]
If all your keys are the same type you can use [these](https://github.com/Hearst-DD/ObjectMapper/blob/master/Sources/ImmutableMappable.swift#L125) methods
