### ISSUE TITLE
How to support Dictionary type json string

### ISSUE THREAD

**Issue by bolee** [Hearst-DD/ObjectMapper#706]
The json string like this:
```
{
  "key1":"value1",
  "key2":"value2"
}
```
ObjectMapper is support?

**Comment by devxoul** [comment]
That's what ObjectMapper does.

**Comment by bolee** [comment]
@devxoul I had parsed it by `Mapper`, but I want `Mappale`, is it support?

**Comment by devxoul** [comment]
@bolee I could not understand what you mean

**Comment by tristanhimmelman** [comment]
Closing this until further clarification.
