### ISSUE TITLE
Why not tuck the transform(Int to String, vice versa)  into ObjectMapper?

### ISSUE THREAD

**Issue by EvilNOP** [Hearst-DD/ObjectMapper#707]
It would be more convenience.

**Comment by devxoul** [comment]
@EvilNOP could you provide me some example usage?

**Comment by EvilNOP** [comment]
let transform = TransformOf<Int, String>(fromJSON: { (value: String?) -> Int? in 
    // transform value from String? to Int?
    return Int(value!)
}, toJSON: { (value: Int?) -> String? in
    // transform value from Int? to String?
    if let value = value {
        return String(value)
    }
    return nil
})

id <- (map["id"], transform)

Int to String transform should be built in?

**Comment by tristanhimmelman** [comment]
I agree that it this could be convenient but I think it is generally safer for transformations to be explicitly defined by the developer.
