### ISSUE TITLE
Quickly implementation protocl

### ISSUE THREAD

**Issue by liyanhuadev** [Hearst-DD/ObjectMapper#709]
hi, i created a xcode plug-in for ObjectMapper generating mapping.
**[https://github.com/liyanhuadev/ObjectMapper-Plugin]**

>

**Comment by devxoul** [comment]
Wow it looks cool!

**Comment by tristanhimmelman** [comment]
@liyanhuadev looks cool 👍 . 

I added a link to your repo in the ObjectMapper README: https://github.com/Hearst-DD/ObjectMapper#projects-using-objectmapper
