### ISSUE TITLE
Nested objects are not converting.

### ISSUE THREAD

**Issue by santhoshs5** [Hearst-DD/ObjectMapper#712]
class UserInfo:Mappable
{
	var name:String?
	var identifier:String?
	var accountType:String?
	var devices:[UserDevice]?
	required init?(map: Map) {

    }
	
	 // Mappable
    func mapping(map: Map) {
        name    <- map["username"]
        identifier         <- map["identifier"]
        accountType       <- map["accountType"]
        devices  <- map["devices"]
    }
	
}

class UserDevice:Mappable
{
	var deviceName:String?
	var deviceType:String?
	var deviceIdentifier:String?
	
	required init?(map: Map) {

    }
	
	 // Mappable
    func mapping(map: Map) {
        deviceName    <- map["name"]
        deviceType         <- map["type"]
        deviceIdentifier       <- map["identifier"]
    }
	
}

Alamofire.request(request).responseString{response in 

let userInfo = UserInfo(JSONString:response)
}

This is my code my userdevices is coming nil always. Let me know what I am doing wrong.

**Comment by devxoul** [comment]
What was your json?

**Comment by santhoshs5** [comment]
{
    username = santhosh;
    "identifier" = "IDJSDJSJS";
    configstatus = SET;
    configtype = DEFAULT;
    "data_center" = "evs.idrive.com";
    devices =     {
        "Ankita\LKKKK" =         {
            identifier = LJJDFDD;
            name = "Ankita iPAD";
            type = iPad;
        };
         "ARUN\LKKKHJH" =         {
            identifier = LJJDFDFFD;
            name = "ARUN iPhone";
            type = ipHone;
        };

    accountStatus = 2;
    acctype = Test;
}

**Comment by devxoul** [comment]
`UserInfo.devices` is an array of `UserDevice` but the `devices` of JSON is not an array.

**Comment by tristanhimmelman** [comment]
Thanks @devxoul, that is correct. Closing this ticket.

**Comment by santhoshs5** [comment]
Thanks guys , How can I declare if i want to use the same object with Realm.
Realm does not support dictionaries



class UserInfo:Object,Mappable
{
var name:String?
var identifier:String?
var accountType:String?
var devices:[UserDevice]?
required init?(map: Map) {

}

 // Mappable
func mapping(map: Map) {
    name    <- map["username"]
    identifier         <- map["identifier"]
    accountType       <- map["accountType"]
    devices  <- map["devices"]
}
}

class UserDevice:Object,Mappable
{
var deviceName:String?
var deviceType:String?
var deviceIdentifier:String?

required init?(map: Map) {

}

 // Mappable
func mapping(map: Map) {
    deviceName    <- map["name"]
    deviceType         <- map["type"]
    deviceIdentifier       <- map["identifier"]
}
}
