### ISSUE TITLE
How can I use Mappable class with NSKeyedArchiver

### ISSUE THREAD

**Issue by oniikal3** [Hearst-DD/ObjectMapper#715]
I have class UserInformations that's Mappable but I need to save this class in to UserDefaults.
I have no idea. How to save this class in to UserDefaults. It can't inherit NSObject, NSCoding.

**Comment by tristanhimmelman** [comment]
You can turn the `UserInformations` object into a string and then save it in UserDefaults. When you retrieve it you will need to use ObjectMapper to generate your `UserInformations` object from the saved string
