### ISSUE TITLE
List of object(Generic) does no conform to protocol 'Mappable'

### ISSUE THREAD

**Issue by magolla** [Hearst-DD/ObjectMapper#718]
Hi!

(Sorry for my bad english)

i have this class:

```
class GenericResponse<T:Mappable>: ApiResponseParent {

    var data:T!

    
    required init?(map: Map) {
        super.init(map: map)
    }
    
    
     override func mapping(map: Map){
        
        super.mapping(map: map)
        data <- map["data"]
        
    }

}
```

and this:

```
class ApiResponseParent: Mappable{
    
    var status:Int!
    var errors:[String]!
    
    
    required init?(map: Map) {
        
    }
    
    
    func mapping(map: Map) {
        status <- map["status"]
        errors <- map["errors"]
    }
    
}
```

and this last one:

```
class ActivityLogDTO: Mappable {
    
    
    var id: Int!
    var creationDate:String!
    var log:String!
 
    
    required init(map: Map) {
        
    }
    
     init() {
        
    }
    
    
     func mapping(map: Map){
        id <- map["id"]
        creationDate <- map["creationDate"]
        log <- map["log"]

     
    }
    

}
```

I try this:

  ```
Alamofire.request(urlString, method: .get, parameters: nil, encoding: JSONEncoding.default, headers: headers).responseObject { (response: DataResponse<GenericResponse<[ActivityLogDTO]>>) in
            
            switch(response.result) {
            case .success(let value):
                
                print(value)
                self.stopActivityIndicator()
                break
                
            case .failure(let error):
                
                print(error)
                self.stopActivityIndicator()
                break
            }
            
        }
```

and get this error:

"Type '[ActivityLogDTO]' does not conform to protocol 'Mappable'"

here:

`"DataResponse<GenericResponse<[ActivityLogDTO]>>) in "`

Can i make ActivityLogDTO Array conform Mappable?

**Comment by tristanhimmelman** [comment]
I believe your object should be defined as follows: `DataResponse<GenericResponse<ActivityLogDTO>>`

You do not need the `[]` in the definition. Hope this helps

**Comment by magolla** [comment]
But i receive an array of ActivityLogDTO.

**Comment by tristanhimmelman** [comment]
Sorry I read too quickly. You will need to define a new class to handle arrays. Something like this:

```
GenericArrayResponse<T:Mappable> {

    var data: [T]!

....
```

**Comment by magolla** [comment]
Hi!

I try this but get this error:

<img width="1154" alt="screen shot 2017-01-10 at 10 01 36" src="https://cloud.githubusercontent.com/assets/17319680/21807145/0d38f322-d71c-11e6-918f-9e76c94eee62.png">



GenericArrayResponse class:

<img width="1122" alt="screen shot 2017-01-10 at 10 02 11" src="https://cloud.githubusercontent.com/assets/17319680/21807166/2dad9f36-d71c-11e6-975a-0bf14b2f8eb6.png">

**Comment by tristanhimmelman** [comment]
Please update to `DataResponse<GenericArrayResponse<ActivityLogDTO>>`

`T` is of type `ActivityLogDTO`, not `[ActivityLogDTO]`. The array is defined when you write
```
var date:[T]!
```

**Comment by magolla** [comment]
It's work! You are a genius!

Thanks you! :)
