### ISSUE TITLE
Version 2.2.2 breaks compatibility.

### ISSUE THREAD

**Issue by pbrewczynski** [Hearst-DD/ObjectMapper#722]
I'm using this library as dependency for other dependency (Carthage dependency manager)

Specifically AlamofireObjectMapper.

AlamofireObjectMapper have in it's Cartfile

`github "Hearst-DD/ObjectMapper" ~> 2.0
`

but the 2.2.2 version broke compatibility:

```
dyld: lazy symbol binding failed: Symbol not found: __TFC12ObjectMapper6MapperCfT7contextGSqPS_10MapContext___GS0_x_
  Referenced from: /Users/pbrewczynski/Library/Developer/CoreSimulator/Devices/C74C8B25-0D55-4F06-8D7E-4D29F0E188E2/data/Containers/Bundle/Application/2A5F1CF2-9177-4528-881C-A7737F3D8313/Network.app/Frameworks/AlamofireObjectMapper.framework/AlamofireObjectMapper
  Expected in: /Users/pbrewczynski/Library/Developer/CoreSimulator/Devices/C74C8B25-0D55-4F06-8D7E-4D29F0E188E2/data/Containers/Bundle/Application/2A5F1CF2-9177-4528-881C-A7737F3D8313/Network.app/Frameworks/ObjectMapper.framework/ObjectMapper

dyld: Symbol not found: __TFC12ObjectMapper6MapperCfT7contextGSqPS_10MapContext___GS0_x_
  Referenced from: /Users/pbrewczynski/Library/Developer/CoreSimulator/Devices/C74C8B25-0D55-4F06-8D7E-4D29F0E188E2/data/Containers/Bundle/Application/2A5F1CF2-9177-4528-881C-A7737F3D8313/Network.app/Frameworks/AlamofireObjectMapper.framework/AlamofireObjectMapper
  Expected in: /Users/pbrewczynski/Library/Developer/CoreSimulator/Devices/C74C8B25-0D55-4F06-8D7E-4D29F0E188E2/data/Containers/Bundle/Application/2A5F1CF2-9177-4528-881C-A7737F3D8313/Network.app/Frameworks/ObjectMapper.framework/ObjectMapper
```

When putting 

`github "Hearst-DD/ObjectMapper" == 2.2.1`

in my project everything works fine. 

I was trying to find api breaks in commits between 2.2.1 and 2.2.2 but so far for no avail. 

I'm also wondering why the signatures are so strange: "__TFC12ObjectMapper6MapperCfT7contextGSqPS_10MapContext___GS0_x_"

**Comment by hariseldon78** [comment]
i confirm the same problem with the same error messages. i'm using the last versions of Alamofire and AlamofireObjectMapper

**Comment by qgliu** [comment]
I also have issue with v2.2.2
The Xcode reported errors happens in AlamofireObjectMapper/ObjectMapperSerializer; particularly this line
            } else if let parsedObject = Mapper<T>(context: context).map(JSONObject: JSONToMap){
                return .success(parsedObject)
            }

**Comment by bidadh** [comment]
I confirm the same issue
github "Alamofire/Alamofire" "4.3.0"
github "Hearst-DD/ObjectMapper" "2.2.2"
github "tristanhimmelman/AlamofireObjectMapper" "4.0.1"

**Comment by falcon283** [comment]
Same identical issue here using ObjectMapper 2.2.2

**Comment by tristanhimmelman** [comment]
I've just released an update which should resolve this issue. Please let me know if the problem persists.

https://github.com/tristanhimmelman/AlamofireObjectMapper/releases/tag/4.0.2

**Comment by hariseldon78** [comment]
Yes, I still have the problem with the 2.2.3 release: 

```
dyld: lazy symbol binding failed: Symbol not found: __TFC12ObjectMapper6MapperCfT7contextGSqPS_10MapContext___GS0_x_
  Referenced from: /Users/robertoprevidi/Library/Developer/CoreSimulator/Devices/3AA91D00-8D2B-40C0-93AE-2C2BD6822BB3/data/Containers/Bundle/Application/E08687C3-4F6F-4428-8BBC-AAF411FD0F07/Municipium.app/Frameworks/AlamofireObjectMapper.framework/AlamofireObjectMapper
  Expected in: /Users/robertoprevidi/Library/Developer/CoreSimulator/Devices/3AA91D00-8D2B-40C0-93AE-2C2BD6822BB3/data/Containers/Bundle/Application/E08687C3-4F6F-4428-8BBC-AAF411FD0F07/Municipium.app/Frameworks/ObjectMapper.framework/ObjectMapper

dyld: Symbol not found: __TFC12ObjectMapper6MapperCfT7contextGSqPS_10MapContext___GS0_x_
  Referenced from: /Users/robertoprevidi/Library/Developer/CoreSimulator/Devices/3AA91D00-8D2B-40C0-93AE-2C2BD6822BB3/data/Containers/Bundle/Application/E08687C3-4F6F-4428-8BBC-AAF411FD0F07/Municipium.app/Frameworks/AlamofireObjectMapper.framework/AlamofireObjectMapper
  Expected in: /Users/robertoprevidi/Library/Developer/CoreSimulator/Devices/3AA91D00-8D2B-40C0-93AE-2C2BD6822BB3/data/Containers/Bundle/Application/E08687C3-4F6F-4428-8BBC-AAF411FD0F07/Municipium.app/Frameworks/ObjectMapper.framework/ObjectMapper
```
![acquisizione regione 3](https://cloud.githubusercontent.com/assets/133625/23004742/9689ee3a-f3f8-11e6-97d3-1c3472667527.png)

**Comment by tristanhimmelman** [comment]
@hariseldon78 please try deleting the carthage folder and running `carthage update`

**Comment by hariseldon78** [comment]
ok.. it will take all the night, i'll let you know tomorrow
Il giorno gio 16 feb 2017 alle 03:40 Tristan Himmelman <
notifications@github.com> ha scritto:

**Comment by hariseldon78** [comment]
@tristanhimmelman  yes, it works! thanks
