### ISSUE TITLE
Is json null value not supported?

### ISSUE THREAD

**Issue by rendion** [Hearst-DD/ObjectMapper#724]
So if my property is nil object mapper emits nothing.  null is a valid json value.  Is there a configuration of objectmapper that supports this?

**Comment by amirsaifi77** [comment]
Doesn't look like it currently. The solutions in #263 might help point you in the right direction for a solution specific to you.

**Comment by alum** [comment]
You can manually set the Mapper to include null values like so:

`let json = Mapper<T>(context: nil, shouldIncludeNilValues: true).toJSON(object)`

where T is your Mappable type.

**Comment by tristanhimmelman** [comment]
@alum is correct.
