### ISSUE TITLE
Array of Mappables to JSON string

### ISSUE THREAD

**Issue by PavelKorolev** [Hearst-DD/ObjectMapper#727]
Let's say I have `GithubUser` entity which conforms `Mappable` protocol. 

So I can create it's instance and convert it to json string.
**1.**
```swift
let user: Mappable = GithubUser()
if let jsonString = user.toJSONString() {
    print(jsonString)
}
```

But if I want to use `GithubUser` array then there is an issue.
**2.**
```swift
let users: [Mappable] = [GithubUser()]
if let jsonString = users.toJSONString() { // Using 'Mappable' as a concrete type conforming to protocol 'BaseMappable' is not supported
    print(jsonString)
}
```

Interesting that if I change `users` type to `[GithubUser]` instead of `[Mappable]` it works good.
**3.**
```swift
let users: [GithubUser] = [GithubUser()]
if let jsonString = users.toJSONString() {
    print(jsonString)
}
```

Is it expected behaviour or are there any workarounds to do it in second way? 
It is simplified example of what I want to do. Actually I want to create function exactly like [this one](https://github.com/gspd-mobi/rage-ios/blob/master/Rage/Dependencies/ObjectMapper/RageObjectMapper.swift#L9) but it should get array of Mappables as parameter. Is it possible?

**Comment by tristanhimmelman** [comment]
This is expected behaviour. See the extension definition that was used to add this functionality:
```
public extension Array where Element: BaseMappable
```

Only arrays where the Element conforms to `BaseMappable` match the extension. Arrays of `Mappable` or `BaseMappable` do not conform to it.

You should be able to create the function using a generic type that conforms to `Mappable`. For example:

```
func map<T: Mappable>(array: [T]) -> String {
	return array.toJSONString() ?? ""
}
```
