### ISSUE TITLE
Maintain order of attributes when encoding to JSON

### ISSUE THREAD

**Issue by SnitramDev** [Hearst-DD/ObjectMapper#728]
The GSON library for Android allows to keep order of attributes when encoding the object to JSON.
Is there anything that could be done to develop this feature for this library?

https://github.com/google/gson

**Comment by tristanhimmelman** [comment]
Unfortunately this is not a priority for me. JSON objects are un ordered by specification. If you need to maintain order I suggest including a order key in your model object.
