### ISSUE TITLE
How to get access to the JSONString in mapping

### ISSUE THREAD

**Issue by dmorrow** [Hearst-DD/ObjectMapper#730]
I would like to return the native JSON String to store in Realm, since Realm can't store collections of native objects.

Example JSON:
` { "root": { "id":1, "name":"name", "array":["a", "b", "c"] }}`

```
func mapping(map:Map) {
    id <- map["id]
    name <- map["name"]
    array <- map["array"].JSONString  // array = "[\"a\", \"b\", \"c\"]"
}
```

Is this possible?

**Comment by tristanhimmelman** [comment]
Unfortunately, ObjectMapper does not store the JSON string representation of objects during mapping. You could use ObjectMapper to generate the JSON string you wish to store after the property has been mapped.

```
array <- map["array"]
let JSONString = Mapper<Type>().toJSONString(array)
```
