### ISSUE TITLE
Proposal to change TransformType to static functions

### ISSUE THREAD

**Issue by Bogidon** [Hearst-DD/ObjectMapper#731]
It seems _slightly_ inefficient to create an entire instance of `TransformType` for each mapping (I use a singleton, but the examples advocate initialization). Since these classes should probably be stateless, what do y'all think about changing `TransformType` from:
```swift
public protocol TransformType {
	associatedtype Object
	associatedtype JSON

	func transformFromJSON(_ value: Any?) -> Object?
	func transformToJSON(_ value: Object?) -> JSON?
}

//  date    <- (map["date"], RubyDateTimeTransform())
```
to
```swift
public protocol TransformType {
	associatedtype Object
	associatedtype JSON

	static func transformFromJSON(_ value: Any?) -> Object?
	static func transformToJSON(_ value: Object?) -> JSON?
}

//  date    <- (map["date"], RubyDateTimeTransform.self)
```

There might be something clever that can be done to keep both versions around until a breaking change is deemed ok. I could put something together if there is a positive consensus.

**Comment by tristanhimmelman** [comment]
That's an interesting idea. I agree that it may not be _optimal_ to create a transform objects, however I doubt the performance impacts are large if at all noticeable. 

My bigger concern with this approach would be porting the existing Transforms. Many of then have an initializer that accepts parameters which are stored for usage during the transformation. See `URLTransform` for example.

**Comment by tristanhimmelman** [comment]
I have decided not to move forward with this idea. Thank you for the suggestion.
