### ISSUE TITLE
 Json object without name

### ISSUE THREAD

**Issue by tolgayildirim** [Hearst-DD/ObjectMapper#733]
[{
"Time": "2016-10-29T09:00:00",
"Values": [
10.4
]
}, {
"Time": "2016-10-29T09:30:00",
"Values": [
10.7
]
}]

How do I adapt JSON according to the ObjectMapper class I have shared above?

**Comment by JALsnipe** [comment]
That's an array of objects, not a single object.

**Comment by tolgayildirim** [comment]
Yes, this is a JsonArray. But I get an error when I try to access it. Luckily I found the solution. Thank you. See  http://stackoverflow.com/questions/32353026/ios-map-a-root-json-array-with-objectmapper-in-swift/32353501#32353501
