### ISSUE TITLE
Normalize Flattened Properties?

### ISSUE THREAD

**Issue by cody1024d** [Hearst-DD/ObjectMapper#739]
Unfortunately, I am receiving JSON in a flattened format, where it really doesn't make sense.  I don't have control over this, though, so need to make lemonade out of lemons, so to speak.

As an example, I am receiving an object like this:
```json
{
            "typeID": 1,
            "typeName": "Participant",
            "activityID": 87955
          }
```

However, I want to break typeId and typeName out into it's own object within my model, for example:

```swift
class TestModel: Mappable {
    var individualType : IndividualType?
}
```

What is the best way to implement the mapping function to support this?  I'm having trouble coming up with a transform, or something along those lines that would allow me to "combine" properties into their own object.  I would also need to be able to serialize it back out, as well.

The only way I can think of doing it, is implementing it like this, but there are still downsides:

```swift
private var _individualTypeId: Int?
private var _individualTypeName: String?

var individualType: IndividualType? {
        guard let id = _individualTypeId, let name = _individualTypeName else {
            return nil
        }
        return IndividualTypeFactory.build(id: id, name: name)
    }
...
func mapping(map: Map) {
        _individualTypeId <- map["typeId"]
        _individualTypeName <- map["typeName"]
}      
```

The downside here is that property is really no longer nillable, then, and when would I instantiate it?

This seems to be a duplicate of #713 , sorry about that.  Although I think it would be good to discuss a more clean way of doing this, than what was the only possible current solution

**Comment by devxoul** [comment]
I found a better solution! This key idea is to wrap `Map` with another `Map` and map it with a property. This is how I've done:

```swift
struct IndividualType: Mappable {
	var typeID: Int!
	var typeName: String!

	init?(map: Map) {
	}

	mutating func mapping(map: Map) {
		self.typeID <- map["typeID"]
		self.typeName <- map["typeName"]
	}
}

class TestModel: Mappable {
	var individualType : IndividualType?

	required init?(map: Map) {
	}

	func mapping(map: Map) {
		let individualTypeJSON: [String: Any] = ["individualType": map.JSON]
		let individualTypeMap = Map(mappingType: .fromJSON, JSON: individualTypeJSON)
		self.individualType <- individualTypeMap["individualType"]
	}
}


let json: [String: Any] = [
	"typeID": 1,
	"typeName": "Participant",
	"activityID": 87955
]
let model = TestModel(JSON: json)
print(model?.individualType)
```

**Comment by cody1024d** [comment]
@devxoul  Thanks for that!  In my case, I am further constrained because the property name for the typeId and the typeName are different depending on the end point (don't ask...that API contract was not my doing lol) so your proposed solution won't work as cleanly for me.  BUT, in the future that definitely seems to be the best option we have!

**Comment by oddysee** [comment]
@cody1024d Would sub-classing and mapping to the new names for `typeId` and `typeName` be an option? I'm the same boat as you and am considering how to handle these API endpoints, which return the same type, using different property names:
```
/api/qualifications : { typeId, typeName }

/api/candidate/qualifications: {candidateQualificationTypeId, candidateQualificationTypeName}
```

**Comment by cody1024d** [comment]
@oddysee That would definitely work as well.  I ended up doing something that's a bit uglier, but works for now, and isn't *too* bad.  This is what my model looks like right now:

```swift
....
    private var individualTypeId: Int?
    private var individualTypeName: String?
    
    var individualType: IndividualType? {
        get {
            guard let id = individualTypeId, let name = individualTypeName else {
                return nil
            }
            return IndividualTypeFactory.build(id: id, name: name)
        } set {
            individualTypeId = newValue?.id
            individualTypeName = newValue?.name
        }
    }
```

I kept them flattened, and private to facilitate deserialization/serialization, but then exposed a computed variable of the model that I actually wanted.  Again, it's not the greatest piece of code I've ever written, but it gets the job done lol
