### ISSUE TITLE
Add an external parameter name to Map.map(JSON: AnyObject?)

### ISSUE THREAD

**Issue by amberstar** [Hearst-DD/ObjectMapper#74]
Both of the API's below can accept String as valid input.  The only difference in the calls when passing in a String is whether you included the parameter name "string:".  Inadvertently calling the second API when you intend to call the first is easy to do and cause for hardship. I suggest adding an external parameter name to the second API to avoid this problem. 

```swift
/**	
        * Map a JSON string to an object that conforms to Mappable
	*/
	public func map(string JSONString: String) -> N? 
```

```swift
/**
	* Maps a JSON object to an existing Mappable object if it is a JSON dictionary, or returns the passed object as is
	*/
	public func map(JSON: AnyObject?, var toObject object: N) -> N 
```

Suggestion:

```swift
	public func map(object JSON: AnyObject?, var toObject object: N) -> N
```

**Comment by tristanhimmelman** [comment]
Hi there, 
Been thinking about this... you bring up a valid issue. 

I am considering just overloading the function instead. So we would end up with something like this:
```
public func map(JSONString: String) -> N? 

public func map(JSON: AnyObject?) -> N? 
```

**Comment by tristanhimmelman** [comment]
I went ahead and made the update I mentioned above in #96
