### ISSUE TITLE
Mapping an array to a single object in a single line?

### ISSUE THREAD

**Issue by JALsnipe** [Hearst-DD/ObjectMapper#740]
Consider a simple JSON document like this:

    {
        "keys" : ["abc", "def"]
    }

Is there a simple way to map just the first value of this array to a single property?  Something like this?

    class MyObj {
        var key: String?
        public required init?(map: Map) { }
        public func mapping(map: Map) {
            key <- map["keys"].first // looking for something to just grab the first value here
        }
    }

**Comment by tristanhimmelman** [comment]
You can do something like this:

```
var keys: Array<String>?
keys <- map["keys"]
key = keys.first
```

**Comment by JALsnipe** [comment]
I'm aware, I was just hoping there was a way to do this in a single line.  Thanks.

**Comment by tristanhimmelman** [comment]
Ah I see. In that case you could write a custom transform if you want. My recommendation would be the above though.
