### ISSUE TITLE
init?(JSONString:) and StaticMappable

### ISSUE THREAD

**Issue by kubatruhlar** [Hearst-DD/ObjectMapper#741]
Is there a way to generate an object with jsonString via it's `init?(JSONString:)` if that object conform to `StaticMappable` protocol in it's extension?

**Comment by tristanhimmelman** [comment]
Hi @kubatruhlar, this already works. I just tested it out to make sure. You can use it the same way as you would if your object conformed to `Mappable`

**Comment by kubatruhlar** [comment]
Consider this:

```
class Foo {
}
extension Foo: StaticMappable {
} 
```

`Foo(JSONString: "")` produces `Argument passed to call that takes no arguments`. Moving `StaticMappable` behind the class will fix this, but that is the point of StaticMappable (to be able to implement ObjectMapper in an extension)

**Comment by tristanhimmelman** [comment]
@kubatruhlar I see, I did not consider that use case. It seems to me that this is a Swift compiler limitation.
