### ISSUE TITLE
Question with nested JSON

### ISSUE THREAD

**Issue by oniikal3** [Hearst-DD/ObjectMapper#743]
Can I use something like
`x <- map["A"]["B"]`
I have tried It has not an error. but `X` return nil. 
I'm sure I have a data in `B` key

**Comment by devxoul** [comment]
You have to use `x <- map["A.B"]`. Check the document: https://github.com/Hearst-DD/ObjectMapper#easy-mapping-of-nested-objects

**Comment by oniikal3** [comment]
Really appreciate for quickest answer ever. That's work Thanks.
