### ISSUE TITLE
Model validation best practices without repeating entire unwrap?

### ISSUE THREAD

**Issue by freak4pc** [Hearst-DD/ObjectMapper#744]
Hey @tristanhimmelman and other contributors :)
I'm relatively new to ObjectMapper, have sort of been spiking on it today, and I do like it's straightforward syntax so far.

I'm aware of the fact there have already been [other issues](#671) related to validation here, but I'll extremely appreciate your thoughts on how would you _actually_ go about validating model structure before or after the mapping phase. 

If I need to build a gigantic "guard" in my `init?(map: Map)`, then wouldn't I already be able to use the values which would make the Mapper itself a bit obsolete? for example, if I have to write something like this for every data model I'm mapping, I could just as well map the data myself as I've already unwrapped most of the content, unless I'm mistaken on that assumption ? 

![image](https://cloud.githubusercontent.com/assets/605076/22864676/91a654e0-f15e-11e6-9aec-601d1e4a2837.png)

I understand and respect your wish to leave ObjectMapper as thin as possible, but do you have any thoughts on best practice along with ObjectMapper to actually validate the model and still try to keep it DRY (or at least _a bit_ less repetitive) ? 

Thanks for reading this!
Shai.

**Comment by devxoul** [comment]
How about using [ImmutableMappable](https://github.com/Hearst-DD/ObjectMapper#immutablemappable-protocol-beta)? ImmutableMappable raises exceptions when failed mapping.

**Comment by freak4pc** [comment]
@devxoul Hey! Good seeing you here :) 
A few issues with that. 

1. I'm losing the nice syntax (having to `map.value` everything if im not mistaken)
2. Sometimes an exception might be overkill, but perhaps i could just catch and handle the error which would also be fine. 

Is there any way to still get the arrow-styled syntax with that kind of approach ?

**Comment by devxoul** [comment]
@freak4pc 👋

1. If you'd like to keep using `<-` syntax, ImmutableMappable is not for you.
2. Errors can be handled as Optionals using `try?` so there would be just few changes.

But personally I would recommend you to try `ImmutableMappable` because there are some advantages. For example, it provides strict mapping validation and the mapping errors can be used as RxSwift sequence's error event.

**Comment by freak4pc** [comment]
Alright, ImmutableMappable seems like a good solution for now. I'll migrate my mappable's to it. Thanks @devxoul !

**Comment by cadizjavier** [comment]
@freak4pc Hey, what is you experience so far with ImmutableMappable to solve your original issue ?
I have a very similar scenario for what you described initially.
Any recommendations ?
Thanks in advance

**Comment by freak4pc** [comment]
Hey @cadizjavier 
Other work got in the way and eventually I didn't migrate to ObjectMapper, so haven't used this since.
