### ISSUE TITLE
ImmutableMappable Array Alamofire

### ISSUE THREAD

**Issue by LemonRuss** [Hearst-DD/ObjectMapper#745]
When trying to map object conforms to ImmutableMappable getting this assertion:

> Assertion failed: 'ImmutableMappable' type requires throwing version of function map(JSON:)  - use 'try' before map(JSON:):

Here is some code:
```
static func requestArray<ResultType: ImmutableMappable>(with request: URLRequestConvertible) -> Promise<[ResultType]> {
          return Promise { fulfill, reject in
      let requestDebug = Alamofire.request(request)
        .validate()
        .responseArray { (response: DataResponse<[ResultType]>) in
          switch response.result {
          case .success(let data):
            fulfill(data)
            
          case .failure(let error):
            reject(NetworkError.customError(title: error.localizedDescription,
                                            message: error.localizedDescription))
          }
      }
      debugPrint(requestDebug)
    }

Networking.requestArray(with: categoryRoute).then {
        (categories: [Category]) -> Void in
}
```

**Comment by devxoul** [comment]
Are you using Alamofire+ObjectMapper?

**Comment by LemonRuss** [comment]
Yes. It s all works with Mappable protocol. But not with Immutable

**Comment by devxoul** [comment]
Yeah. Alamofire+ObjectMapper currently does not support ImmutableMappable. But you could easily make an extension method on Alamofire to map ImmutableMappable.

**Comment by LemonRuss** [comment]
Okey, i'll work on it. Thank you for ur answer! If someone already done it - u r welcome)
