### ISSUE TITLE
Bug in documentation - JSONDictionary instead of JSON

### ISSUE THREAD

**Issue by SnitramDev** [Hearst-DD/ObjectMapper#747]
In the documentation, I think the "JSONDictionary" part should be changed to "JSON" only, correct? 
This is because the compiler indicates that the "Value of type map has no member JSONDictionary".

Please see below:

required init?(map: Map){
    // check if a required "name" property exists within the JSON.
    if map.JSONDictionary["name"] == nil {
        return nil
    }
}

Great library! Awesome job!

Thanks!

**Comment by devxoul** [comment]
Thanks for reporting :)
