### ISSUE TITLE
Cannot mapper with UInt type

### ISSUE THREAD

**Issue by oniikal3** [Hearst-DD/ObjectMapper#751]
I created struct and make var number: Uint = 0
After I map with json it always return 0 as default

Here is json.
let info = ["id":"12345678", "number":1]

**Comment by devxoul** [comment]
@oniikal3, thanks for reporting. I made a PR #752 to fix this issue. I would prefer you to make custom `Transform` to support `UInt` mapping at this time.

**Comment by devxoul** [comment]
@oniikal3, Try [2.2.4 release](https://github.com/Hearst-DD/ObjectMapper/releases/tag/2.2.4) :tada:
