### ISSUE TITLE
Mapping Int with ObjectMapper_Realm

### ISSUE THREAD

**Issue by NikKovIos** [Hearst-DD/ObjectMapper#753]
Using https://github.com/Jakenberg/ObjectMapper-Realm

JSON:  
{
   "id": 33,
   "email": "lalaley@gmail.com"
}

```
class UserProfile: Object, Mappable {
  var id = RealmOptional<Int>()
  dynamic var email: String? = nil

func mapping(map: Map) {
    id                <- map["id"]
    email             <- map["email"]
  }
}
```
Mapping of String value is OK, but mapping of Int resulting `null`.

There are no examples provided for this case!

**Comment by NikKovIos** [comment]
Found this https://gist.github.com/danilValeev/ef29630b61eed510ca135034c444a98a

**Comment by NikKovIos** [comment]
I've created the pod, maybe it would help https://github.com/NikKovIos/ObjectMapper-RealmSwift

**Comment by jbmaxwell** [comment]
I'm having a similar problem with UInt8. I have an object with two UInt8 properties, and two Double properties. The Doubles are mapped, but the UInt8s are nulled out. I noticed that, unlike macOS, Linux can't automatically identify UInt8 as Int (maybe a missing protocol?), so I tried adding "|| x is UInt8" to ToJSON.swift's basicType func, but that broke everything, nullifying all properties (which I don't really understand)...

**Comment by amirpervaiz086** [comment]
Hi @NikKovIos I read it from Realm doc you cant use RealmOptional and List as var and dynamic. But for json parsing and any mappable you used, it has to be var. can you explain it how did it work for you using var? any downside? thanks

**Comment by amirpervaiz086** [comment]
I saw in your github you also used double and Int as var Optional.
