### ISSUE TITLE
How can i have custom (Computed) property ?

### ISSUE THREAD

**Issue by santhoshs5** [Hearst-DD/ObjectMapper#755]
I am using Objectmapper and Realm for my project.

I have an object like following
class File
{
dynamic var name
dynamic var folder
dynamic var path // This is not coming from JSON // this should be combination of both name+folder
}

I thought of writing a computed property to achieve this but Realm does not support computed properities as primary key.

But I should use this as primary key. is there any way i can manipulate to add that value after coming from server response.

Note: I am usign AlamofireObjectMapper.

I am using following method which pareses server response and give me the model object.

        Alamofire.request(router).responseObject{ (response: DataResponse<T>) in
{
  let myModel = response.result.value // Parsed object
===== What can i do here to achieve my requirement=====
}

**Comment by devxoul** [comment]
Try: 

```swift
class File {
  dynamic var name: String = "" {
    didSet {
      self.path = self.name + self.folder
    }
  }
  dynamic var folder: String = "" {
    didSet {
      self.path = self.name + self.folder
    }
  }
  dynamic var path: String = ""
}
```
