### ISSUE TITLE
Auto transform Int <-> String or Build in transformer

### ISSUE THREAD

**Issue by iShawnWang** [Hearst-DD/ObjectMapper#757]
```
id <- (map["id"], TransformOf<Int, String>(fromJSON: { Int($0!) }, toJSON: { $0.map { String($0) } }))
```
- I hope the transform such as Int <-> String can be done automatic, the ObjectMapper can try to transform JSON String to Int if I declare a Int? property
- In Objective-C a lot library having this done for me, which make my life easier
- I am not sure if we can't do this in Swift , we can provide some build in transformer such as `StringToIntTransformer()`

Looking forward to this improvement !
# :D

**Comment by iShawnWang** [comment]
- I just found some build in transformer in [Tests/CustomTransformTests.swift](https://github.com/Hearst-DD/ObjectMapper/blob/master/Tests/ObjectMapperTests/CustomTransformTests.swift), this helps a lot
- But I still hope some basic transform can be done automatically, such as `String -> Int` , instead of `(map[ "xxx" ], StringToIntTransform())`

**Comment by tristanhimmelman** [comment]
I would be happy to accept a Pull Request with a simple `StringToIntTransform`.
