### ISSUE TITLE
What is the best way to parse nested arrays?

### ISSUE THREAD

**Issue by yuriy-tolstoguzov** [Hearst-DD/ObjectMapper#763]
I made example JSON below, but basically I want to have only root object parsed and deepest leafs that wrapped in array with some nesting. I don't really care about any values in between them, so I would like to avoid creating classes in my code for them. 

Please advice, what will be the best way to do that?

### Your JSON dictionary:

```json
{
  "errorCode": 200,
  "payload":
  {
    "containers": 
    [
      { 
        "container": { "usefulField1": "value1", "usefulField2": "value2" }      
      },
      {
        "container": { "usefulField1": "value1", "usefulField2": "value2" }
      },
      { 
        "container": { "usefulField1": "value1", "usefulField2": "value2" }
      },
    ],
  }
}
```

### Your model:

```swift
struct UsefulClass: Mappable {
  var usefulField1: String!
  var usefulField2: String!

  init(_ map: Map) {
    usefulField1 <- map["containers.container.usefulField1"]
    usefulField2 <- map["containers.container.usefulField2"]
  }
}

struct Response: Mappable {
  var usefulObjects: [UsefulClass]!
  var errorCode: Int

  init(_ map: Map) {
    usefulObjects <- map["payload"]
    errorCode <- map["errorCode"]
  }
}
```

### What you did:

```swift
let repo = Mapper<Response>().map(myJSONDictionary)
```

### What you expected:

I exepected something like:

```swift
Response(errorCode: 200, usefulObjects: [
  UsefulClass(usefulField1: "value1", usefulField1: "value2"),
  UsefulClass(usefulField1: "value1", usefulField1: "value2"),
  UsefulClass(usefulField1: "value1", usefulField1: "value2")
])
```

### What you got:

```swift
Response(errorCode: 200, containers: nil)
```

**Comment by devxoul** [comment]
@yuriy-tolstoguzov Thanks for correctly using our issue template!

Try:

```diff
struct UsefulClass: Mappable {
  var usefulField1: String!
  var usefulField2: String!

  init(_ map: Map) {
-    usefulField1 <- map["containers.container.usefulField1"]
-    usefulField2 <- map["containers.container.usefulField2"]
+    usefulField1 <- map["container.usefulField1"]
+    usefulField2 <- map["container.usefulField2"]
  }
}


struct Response: Mappable {
  var usefulObjects: [UsefulClass]!
  var errorCode: Int

  init(_ map: Map) {
-    usefulObjects <- map["payload"]
+    usefulObjects <- map["payload.containers"]
    errorCode <- map["errorCode"]
  }
}
```

**Comment by yuriy-tolstoguzov** [comment]
@devxoul Thanks for quick reply! As soon as I saw your answer I understood that I asked not what I meant to ask. Please clarify one more moment if possible.

I use `UsefulClass` model class in different responses and ideally would like to continue to do that. I have next code there:

```swift
struct UsefulClass: Mappable {
  var usefulField1: String!
  var usefulField2: String!

  init(_ map: Map) {
    usefulField1 <- map["usefulField1"]
    usefulField2 <- map["usefulField2"]
  }
}
```

In answer you suggested I need to have different mapping ("usefulField1" -> "container.usefulField1"). So if I change existing class, it won't work for responses implemented before; if I made another class for this new response, I will have some duplication of model classes.

I know NSDictionary/NSArray Objective-C KVC implementation allows to prepare values I need like that: `"payload.containers.container"`. An as result it returns simple array of `UsefulClass` as NSDictionary, but there are pure Swift way to do that and as I see ObjectMapper's Map implementation also does not support it.

What you could suggest me?

**Comment by devxoul** [comment]
@yuriy-tolstoguzov, So you mean that you'd like to make `UsefulClass` respond to both:

```swift
usefulField1 <- map["usefulField1"]
usefulField2 <- map["usefulField2"]
```

and

```swift
usefulField1 <- map["container.usefulField1"]
usefulField2 <- map["container.usefulField2"]
```
?

**Comment by yuriy-tolstoguzov** [comment]
That is one option :)
Another option as I see it is to prepare map that will be passed there so it will point on proper places.

**Comment by yuriy-tolstoguzov** [comment]
@devxoul Any ideas how I could implement something like that?

**Comment by devxoul** [comment]
Not sure but try something like:

```swift
if map["usefulField1"].currentValue != nil {
  usefulField1 <- map["usefulField1"]
} else if map["container.usefulField1"].currentValue != nil {
  usefulField1 <- map["container.usefulField1"]
}
```

**Comment by yuriy-tolstoguzov** [comment]
The bad part is that I have to do that for each field, because `map["usefulField1"].currentValue != nil` is not guarantee that you just need to use second set of mappings for each field.
It would be cool feature if it would be possible to separate mapping and model somehow.
Anyway, thanks for your help @devxoul. I think this issue is solved for me.
