### ISSUE TITLE
ObjectMapper and MessagePack

### ISSUE THREAD

**Issue by TofPlay** [Hearst-DD/ObjectMapper#768]
Json is great. But if we have a lot of data to exchange or small data very fast we can use something like [MessagePack](http://msgpack.org/)

From msgpack.org:
"**MessagePack: It's like JSON. but fast and small.**
MessagePack is an efficient binary serialization format. It lets you exchange data among multiple languages like JSON. But it's faster and smaller. Small integers are encoded into a single byte, and typical short strings require only one extra byte in addition to the strings themselves."

What is the best way to use MessagePack with ObjectMapper?
May be we can use [SwiftMsgPack](https://goo.gl/oIpKWQ)...

**Comment by tristanhimmelman** [comment]
MessagePack looks cool but I have no plans to add support at this time.
