### ISSUE TITLE
Can I get help in getting the key name

### ISSUE THREAD

**Issue by d-shenoy** [Hearst-DD/ObjectMapper#769]
### Your JSON dictionary:
<img width="412" alt="screen shot 2017-03-07 at 10 38 17 am" src="https://cloud.githubusercontent.com/assets/11788099/23663952/35261a2c-0322-11e7-93a1-127c71e56705.png">

As you can see in the screenshot, one of the keys is a Date in Posix format. I want to extract the date and store it. However seems like, I am able to extract only the values of the JSON, Is there a way to get the key names as well.?

I might be missing something basic.

**Comment by tristanhimmelman** [comment]
You can use a map the jobsByDate to a Dictionary type. That way you will have the key and the value. Note: dictionary keys only support strings at the moment in ObjectMapper so you will need to store the date as a String
