### ISSUE TITLE
Nested Mappable structs bug

### ISSUE THREAD

**Issue by Aranoledur** [Hearst-DD/ObjectMapper#770]
If a have two Mappable structs, and one nested to another, they are not mapped correctly if I do toObject. It took me a couple of hours to detect this bug in real project.

I have function:
```swift
public extension Mappable {

    func consumed(_ other: JSONType) -> Self {
        let mapper = Mapper<Self>()
        return mapper.map(JSON: other, toObject: self)
    }
}
```

And this structs and test:
```swift
struct A: Mappable {
    var name: String?

    init(name: String) {
        self.name = name
    }

    init?(map: Map) {

    }

    mutating func mapping(map: Map) {
        name        <- map["name"]
    }
}

struct B: Mappable {
    var a: A?

    init(name: String) {
        a = A(name: name)
    }

    init?(map: Map) {

    }

    mutating func mapping(map: Map) {
        a       <- map["a"]
    }
}

func consumeTest() {
    var b1: B = B(name: "QW") //has a with name "QW"
    let b2: B = B(name: "ER") //has a with name "ER"
    b1 = b1.consumed(b2.toJSON())
    print("b1 name \(b1.a?.name)") //name is still "QW"
}
```

This happens because operator <- doesn't do assignment for Mappable objects in toObject mode. I don't know if this behaviour is correct for framework. But looks weird and unexpected. I think this kind of functions `map(JSONObject: Any?, toObject object: N)` should be in extension where Mappable is a class.

**Comment by tristanhimmelman** [comment]
I've just merged a fix for this issue. Thanks for pointing it out 👍

**Comment by Aranoledur** [comment]
I've just looked at a fix. Didn't even think it was that simple! I now can make my entities structs again, thanks!
