### ISSUE TITLE
Argument labels '(JSONString:)' do not match any available overloads

### ISSUE THREAD

**Issue by jacinzhang** [Hearst-DD/ObjectMapper#772]
There is no `JSONString:` init func. and I cant't use like this

```swift
 let userAlias = WLYUser(JSONString: response.jsonResponse)
```

but  `Mapper<T: Mappable>.map(JSON:)` is OK.
```swift
 let user = Mapper<WLYUser>().map(JSON: response.jsonResponse as! [String : Any])
```

please update README.md file.

**Comment by tristanhimmelman** [comment]
There is a `JSONString` init function. I think what you are looking for is a the `JSON` init function however. You should be able to use it like this:
```
let user = WLYUser>(JSON: response.jsonResponse as! [String : Any])
```
