### ISSUE TITLE
Problem in mapping numberic strings

### ISSUE THREAD

**Issue by Romixery** [Hearst-DD/ObjectMapper#78]
Hi all.
I have this json:
    {
      "id": "2",
      "name": "alex",
      "city": "1"
    },
    {
      "id": "3",
      "name": "Lindy",
      "city": "1"
    },....

The type of "id" and "city" in my Mappable object is Int. But after mapping, id and city is 0. When i changed the type of this field to String, the result is OK and mapping is successful.

This is my bean:
<code>
import UiKit

class Region: Mappable {
    
    var id : Int = 0
    var name : String = ""
    var city : Int = 0
    
    init(){}    
    
    required init?(_ map : Map){
        mapping(map)
    }
    
    func mapping(map: Map) {
        id <- map["id"]
        name <- map["name"]
        city <- map["city"]
    }
}
</code>
How i solve this issue?

**Comment by ikesyo** [comment]
You can use custom transforms written in README. See also #73.

**Comment by tristanhimmelman** [comment]
As @ikesyo mentioned you can use a custom transform to achieve what you want. Something like this should work for you:
```
let transform = TransformOf<Int, String>(fromJSON: { (value: String?) -> Int? in
	return value?.toInt()
}, toJSON: { (value: Int?) -> String? in
	if let value = value {
		return String(value)
	}
	return nil
})

id <- (map["id"], transform)
```

or a more condensed version:
```
id <- (map["id"], TransformOf<Int, String>(fromJSON: { $0?.toInt() }, toJSON: { $0.map { String($0) } }))
```
