### ISSUE TITLE
Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1

### ISSUE THREAD

**Issue by t3ngf0ung** [Hearst-DD/ObjectMapper#783]
Seems like ObjectMapper is not Swift 3.1 ready. Is there any workaround for this issue? 

I'm currently using ObjectMapper 2.2.5 via Carthage.

**Comment by devxoul** [comment]
😂

<img width="1154" alt="screen shot 2017-03-28 at 4 55 23 pm" src="https://cloud.githubusercontent.com/assets/931655/24394553/5d09a4da-13d7-11e7-94c9-5163d1412c97.png">

**Comment by t3ngf0ung** [comment]
Yup thats what I get once updated to Xcode 8.3.

**Comment by t3ngf0ung** [comment]
Found the solution. Command below shall do the job. 

`carthage update ObjectMapper --platform ios --no-use-binaries`
