### ISSUE TITLE
Set up CI environment

### ISSUE THREAD

**Issue by ikesyo** [Hearst-DD/ObjectMapper#79]
Travis CI or CircleCI, which do you prefer?

**Comment by tristanhimmelman** [comment]
Let's go with Travis CI. I don't have any experience setting up CI with Travis so you can go ahead and take care of that if you want to. I've linked my Github to Travis so it should be ready to go once it is configured. Let me know if you need me to do anything. Thanks!

**Comment by ikesyo** [comment]
Thank you for preparing!

**Comment by tristanhimmelman** [comment]
:+1: :+1: not a problem
