### ISSUE TITLE
How to convert json array to the []

### ISSUE THREAD

**Issue by shuijinliuxi** [Hearst-DD/ObjectMapper#792]
### Your JSON dictionary:

```json
{
  "options":  [{
      {
      "type": "01",
      "name": ""
      "content":""
      }, 
      {
      "type": "02",
      "name": ""
      "content": ""
      }
]}
```

### Your model:

```swift
public enum TemplateType: String {
    case text = "01"
    case digital = "02"
}

struct ObjItem: Mappable {
  var types: [TemplateType]!
}
```

### What you expected:

I exepected something like:

How I can only convert the json `options.type` to the [TemplateType], just like :

```swift
let item = Mapper<ObjItem>().map(JSONObject: json)
```

The result I accpet is : item.type = [.text, .digital]

**Comment by tristanhimmelman** [comment]
Unfortunately, nested keys do not work for arrays. You will need to create a wrapper object around TemplateType like this:
```
struct Obj: Mappable {
  var type: TemplateType?
}
```
