### ISSUE TITLE
List of Dates

### ISSUE THREAD

**Issue by vonox7** [Hearst-DD/ObjectMapper#794]
How can ObjectMapper handle a List of Dates?

### Your JSON dictionary:

```json
[
	"2017-04-09T04:34:00Z",
	"2017-05-01T12:21:26Z",
	"2017-01-01T02:54:33Z"
]
```
(A valid JSON, see http://jsonlint.com/)

### Your model:

Not sure if ObjectMapper can wrap it into `[Date]`.

### What you did:

```swift
let dates = Mapper<Date>().mapArray(JSONString: string!)
```

### What you expected:

I expected to return a `[Date]`.

### What you got:

nil

**Comment by devxoul** [comment]
This is not ObjectMapper's responsibility. You don't need ObjectMapper for that.

```swift
let dates = yourJSONArray.flatMap { string -> Date? in
  let formatter = DateFormatter()
  formatter.dateFormat = ...
  return formatter.date(from: string)
}
```
