### ISSUE TITLE
Mapping json with dynamic structure

### ISSUE THREAD

**Issue by protspace** [Hearst-DD/ObjectMapper#798]
### Your JSON dictionary:

Response 1
```json
{
    "Data": "12345"
}
```

Response 2
```json
{
    "Data": {"deviceIdentifier":"123", "mobilePhoneNumber":"123", "version":"1.0.1"} 
}

```

```swift
final class ClientApplicationIdentifier:  Object, Mappable {
    
    var deviceIdentifier: String?
    var mobilePhoneNumber: String?
    var version: String?

    override static func primaryKey() -> String? {
        return "mobilePhoneNumber"
    }
    
    //Mappable
    required convenience init?(map:Map) {
        self.init()
    }
    
    
    override func mapping(map: Map) {
        deviceIdentifier    <- map["DeviceIdentifier"]
        mobilePhoneNumber <- map["MobilePhoneNumber"]
        version <- map["Version"]
    }
}
```

Thanks for the great Mapper. The library is very useful.
I didn't find solution fore my case when the structure of the Response object is different. In my case Data can be either String or Object. Is there a way to treat this case properly?

**Comment by devxoul** [comment]
You may want to make custom Transform. Check [Custom Transforms](https://github.com/Hearst-DD/ObjectMapper#custom-transforms) section in the README.

**Comment by tristanhimmelman** [comment]
As @devxoul suggested, you could use a custom transform and inspect the value and then act accordingly. ObjectMapper doesn't provide any other techniques for handling this situation. Good luck!
