### ISSUE TITLE
Error "__TIFE12ObjectMapperPS_12BaseMappablecFT4JSONGVs10DictionarySSP__7contextGSqPS_10MapContext___GSqx_A0_", referenced from:

### ISSUE THREAD

**Issue by vinamelody** [Hearst-DD/ObjectMapper#805]
Strange that ObjectMapper error happens in my test target. Previous unit tests build and run ok and while refactoring major code, I didn't update the unit tests for a while so I commented the tests. Then I recently updated to XCode Version 8.3.2 (8E2002).
And today wanting to rewrite the tests again, getting this errors:

<img width="925" alt="screenshot 2017-05-11 15 13 16" src="https://cloud.githubusercontent.com/assets/990511/25936930/4df40fba-365c-11e7-90eb-295cc6d00cbb.png">

Not much of information as nothing given when I double click. Tried google too but no similar issues seem to exists.

Thanks for your help

**Comment by vinamelody** [comment]
Update... the reason is an old block of code that creates an object from json string. error is gone after removing the code.

**Comment by ppamorim** [comment]
@vinamelody How to test the create of objects from json string? I need this...

**Comment by ppamorim** [comment]
@vinamelody Wrapping it into a function solved the problem. :)

**Comment by vinamelody** [comment]
@ppamorim I somehow just removed that line lol ... glad you found the solution!
