### ISSUE TITLE
Map never returns nil 

### ISSUE THREAD

**Issue by wassimseif** [Hearst-DD/ObjectMapper#807]
### Your JSON dictionary:

```json
{
	"token": "very secret token "
}
```

### Your model:

```swift
class Post :  Mappable{
    
    var body : String?
    var id : Int?
    var title : String?
    var userId : Int?
    
    func mapping(map: Map)
    {
        body <- map["body"]
        id <- map["id"]
        title <- map["title"]
        userId <- map["userId"]
        
    }
    
```

### What you did:
T is generic parameters conforming to `Mappable `
```swift
let object = Mapper<T>().map(JSON: jsonDictionary)'
```

### What you expected:

I exepected something like:

```swift
object = nil 
```

### What you got:

```swift
objectToEmit
<MyApp.Post: 0x6000000d5a80>
```
However all the values are nil. shouldn't all the object be nil

**Comment by tristanhimmelman** [comment]
The object will only be nil is the top level JSON dictionary is nil. ObjectMapper does not verify whether each mapping within an object succeeds or not. It simply processes all the mappings sequentially and returns the result.
