### ISSUE TITLE
Some suggestions for use in the development process

### ISSUE THREAD

**Issue by chenkefeng** [Hearst-DD/ObjectMapper#811]
Exmaple

```
let jsonString = "{\"name\":\"Test\", \"id\":10}"

struct User: Mappable {
     var id: String!
     var name: String!
}

/// 
```

At this point, the type of ID is String, and ID is Int in jsonString, so the conversion fails, and id = nil. The framework does provide the transformTo () method to solve, but can it be implicitly solved?

**Comment by devxoul** [comment]
Use Transform to convert Int to String. https://github.com/Hearst-DD/ObjectMapper#custom-transforms
