### ISSUE TITLE
Wrong int parsing

### ISSUE THREAD

**Issue by KLim1989** [Hearst-DD/ObjectMapper#812]
### MY JSON dictionary:

```json
 ▿ 12 : 2 elements
    - key : "closingTime"
    - value : 1495208399999
```

### Your model:

```swift
class BetEntityRealm: Object, Mappable {
    dynamic var id: Int64 = 0;
    dynamic var closingTime: Int = 0

   func mapping(map: Map) {
        id    <- map["id"]
        closingTime <- map["closingTime"]
}
```

### What you did:

```swift
   guard let bet = Mapper<BetEntityRealm>().map(JSON: params) else {
            return nil
        }
```

### What you expected:

I exepected something like:

```swift
bet.closingTime // =  1495208399999
```

### What you got:

```swift
bet.closingTime // =  559780991 ???!!!
```
I use ObjectMapper, and when try to convert string timestamp to Int , I see wrong value. It Looks like timestamp value doesn't fit in Int . So I try to use int64 but the value is the same . When I change my property to Double everything looking good. Whats the problem? I need  to use Int Property in my code with right values) . Thank for answer

**Comment by tristanhimmelman** [comment]
Hi there, I just released a new version that included a PR addressing some overflow issues with ints. I testing mapping the above value to Int64 and it was successful:
```
let jsonString = "{\"int64\": 1495208399999}"
let obj = mapper.map(JSONString: jsonString)
XCTAssertEqual(obj?.int64, 1495208399999)
```
