### ISSUE TITLE
Merging Two Objects

### ISSUE THREAD

**Issue by dwalks12** [Hearst-DD/ObjectMapper#813]
I'm just wondering if there is a way to merge two mappable objects replacing nil values in between them?

**Comment by tristanhimmelman** [comment]
No not exactly. There is a method in Mapper that allows mapping JSON onto an object. However this will add nil values to `object` if they are in the passed JSON. 
```
public func map(JSON: [String: Any], toObject object: N) -> N {
```
Hope this helps
