### ISSUE TITLE
Is it possible to simplify initialization methods?

### ISSUE THREAD

**Issue by hrscy** [Hearst-DD/ObjectMapper#821]
If a model has too many properties,does it's properties also need to create and assign ono by one like your framework?

Is it very troublesome like that?

Is there a simple way?

**Comment by devxoul** [comment]
Possibly duplicated with #179, #662, #685 and #779. ObjectMapper has no plans to support mapping via reflection.

**Comment by hrscy** [comment]
Thanks!
