### ISSUE TITLE
Version convention

### ISSUE THREAD

**Issue by azeff** [Hearst-DD/ObjectMapper#822]
What convention is used for versioning releases of ObjectMapper?

PR #816 introduced a change to existing public API and was released in version `2.2.7`. I did not expect to have failing build after installing 'patch' version update.

**Comment by tristanhimmelman** [comment]
@azeff that was just a slip up on my part. ObjectMapper uses Semantic Version so future patches should continue working in your code as expected.

**Comment by azeff** [comment]
@tristanhimmelman awesome, thanks for clarification.
