### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by HeyYouNotYouYou** [Hearst-DD/ObjectMapper#824]
When will there be swift 4 support?

**Comment by ro6lyo** [comment]
I'm also interesting about that, any info about Swift 4 support would be great. Thanks

**Comment by milesalex** [comment]
Any idea?

**Comment by tristanhimmelman** [comment]
Hey there, I just pushed up a new branch called `swift-4`. Please let me know if you come across any issues. I had to add some special handling for Float types as it seems they can no longer be casted from Any as they could previously.

**Comment by asilavistaVeesto** [comment]
Hey, how do i get this swift 4 update?

**Comment by adozenlines** [comment]
Codable is the way to go w/swift 4.

**Comment by chrisvanbuskirk** [comment]
...but that's not an answer to the swift 4 question.

**Comment by ripventura** [comment]
@tristanhimmelman I appreciate the swift-4 branch, but I have pods using ObjectMapper as dependency, and since .podspec doesn't allow ":git" / ":branch" tags, I can't reference the new branch.
Is there any ETA when the swift-4 branch gets released on cocoa pods?

**Comment by tristanhimmelman** [comment]
The swift 4 branch has now been released
