### ISSUE TITLE
Help: String to Int

### ISSUE THREAD

**Issue by JaleelNazir** [Hearst-DD/ObjectMapper#828]
### MY JSON dictionary:

Some objects "id" value is Int and some "id" value is String
```json
[
  {
    "name": "ObjectMapper",
    "url": "https://github.com/Hearst-DD/ObjectMapper",
    "id": "123"
  },
  {
    "name": "ObjectMapper",
    "url": "https://github.com/Hearst-DD/ObjectMapper",
    "id": 123
  }
]
```

### My model:

```swift
struct Repo: Mappable {
  var name: String!
  var url: URL!
  var id: Int64 = 0

  init(_ map: Map) {
    name <- map["name"]
    url <- map["url"]
    id <- map["id"]
  }
}
```

### What I did:

For some object "id" is Int and for some "id" is String
```swift
if let parsedSnapShot = snapshot.value.flatMap({$0 as? [String : Any]}) {
                if let messageOBJ = Mapper<Repo>().map(JSON: parsedSnapShot) {
      // adding to array
       }
}
```

### What I expected:

JSON value can be any type, I need to map into variables datatype
e.g:  
 var id: Int64 = 0
"Id" --> (Int, Float, Double or String or Any type) I want it as Int64

### What I got:

But, after mapping the id is nil in all string objects

**Comment by tristanhimmelman** [comment]
You can write a custom transform that inspects the type and if it is a String it converts it into an Int https://github.com/Hearst-DD/ObjectMapper#custom-transforms

Otherwise you can map the string value to a local variable and then process it inline.
```
var idString: String?
idString <- map["id"]
if let idString = idString {
    // process idString into an int value
} else {
   id <- map["id"]
}
```
