### ISSUE TITLE
Mapping nested objects from root node is not working

### ISSUE THREAD

**Issue by dinaraja** [Hearst-DD/ObjectMapper#829]
### JSON dictionary:

```json
user: {
  "name": "Dinesh",
  "url": "https://dinaraja.me",
  "company": "IIINC",
  "designation": "Developer"
}
```

### Model:

```swift
struct User: Mappable {
  var name: String!
  var url: URL!
  var profession: Profession!
  init(_ map: Map) {
    name <- map["name"]
    url <- map["url"]
    profession <- map   // FIXME: It's not working. Find out what we do here is right/wrong
  }
}

struct Profession: Mappable {
  var company: String!
  var designation: String!
  init(_ map: Map) {
    company <- map["company"]
    designation <- map["designation"]
  }
}
```

### What I did:

```
let user = Mapper<User>().map(myJSONDictionary)
print(user.profession.company) //FIXME: Crashes here
```

App is crashing while accessing `user.profession`. **Basically, I do not know how to parse another mappable object inside the model with same JSON map root node** I think, I'm doing it wrong. I can't find the documentation for the same anywhere. Please help me with it.

**Comment by tristanhimmelman** [comment]
`profession <- map` This is not accepted ObjectMapper syntax. There is no automatic mechanism for mapping another object on the same JSON level. My recommendation would be to map `company` and `designation` to local variables within the init function and then create your `Profession` model manually.
