### ISSUE TITLE
Compile error with DateTransform :(

### ISSUE THREAD

**Issue by jpmcglone** [Hearst-DD/ObjectMapper#830]
<img width="414" alt="screen shot 2017-06-19 at 11 24 48 am" src="https://user-images.githubusercontent.com/4998416/27292623-00bead46-54e2-11e7-85c8-aa3140d280a2.png">

I do not understand why this isn't compiling. 

The error is:

`Binary operator '<-' cannot be applied to operands of type 'Date?' and '(Map, DateTransform)'`

Any help would be greatly appreciated.

The method exists:
```
/// Optional object of basic type with Transform
public func <- <Transform: TransformType>(left: inout Transform.Object?, right: (Map, Transform)) {
	let (map, transform) = right
	switch map.mappingType {
	case .fromJSON where map.isKeyPresent:
		let value = transform.transformFromJSON(map.currentValue)
		FromJSON.optionalBasicType(&left, object: value)
	case .toJSON:
		left >>> right
	default: ()
	}
}
```

So I don't understand :(

**Comment by jpmcglone** [comment]
Bump. Can someone please work with me on this? I need these Transforms to work. They worked fine in past projects, but I can't get it to work now. I must be doing something really simple but stupid.

**Comment by tristanhimmelman** [comment]
Hi there, sorry but I don't have any insight into why that isn't working. The code looks good to me. Perhaps you can compare to the some of the tests. See CustomTransformTests.swift line 227.
Otherwise, maybe it has something to do with the `Member` superclass?
