### ISSUE TITLE
Map toObject property public access

### ISSUE THREAD

**Issue by grahamburgsma** [Hearst-DD/ObjectMapper#831]
### What you did:

```swift
if map.toObject {
   //Do something only when an object is being updated
}
```

### What you expected:

I expected this to work, but the toObject property is marked as internal. Please consider making this property public. I want to use this property to detect when an object is being updated as I don't want to allow some properties to be updated from a map. My current work-around is using a context but that's kinda clumsy when there is a property that does the same thing.

### What you got:

`'toObject' is inaccessible due to 'internal' protection level`

**Comment by tristanhimmelman** [comment]
I just merged a PR that included a fix for this issue.
