### ISSUE TITLE
Cannot call JSONString constructor when using StaticMappable in extension

### ISSUE THREAD

**Issue by kaomte** [Hearst-DD/ObjectMapper#835]
### Your JSON dictionary:

```json
let json = 
  "{\n" +
  "  \"sku\" : 2\n" +
  "}"
```

### Your model:

```swift
struct MyObject {
  var sku: Int
}

extension MyObject: StaticMappable {
  static func objectForMapping(map: Map) -> BaseMappable? {
    return MyObject(sku: 0)
  }

  mutating func mapping(map: Map) {
    sku <- map["sku"]
  }  
}
```

### What you did:

```swift
let repo = Mapper<Repo>().map(myJSONDictionary)
```

### What you expected:

I exepected something like:

```swift
let o: MyObject? = MyObject(JSONString: json)!
```

### What you got:

```swift
let o: MyObject? = MyObject(JSONString: json)! // Incorrect argument label in call (have 'JSONString:', expected 'sku:')
```

**Comment by tristanhimmelman** [comment]
Hi there, I'm not sure why this is the case but it seems that for Structs adding `StaticMappable` as an extension breaks the custom constructor functionality. If you define your struct in one block that conforms to StaticMappable you problem should go away. I will keep an eye on this but I believe it is a Swift issue.
