### ISSUE TITLE
Nil while mapping [EnumClass: Any]

### ISSUE THREAD

**Issue by quaddef** [Hearst-DD/ObjectMapper#836]
### Your JSON dictionary:

```json
{
    "exchange_rate":{
        "EUR":1,
        "USD":0.8903
    }
}
```

### Your model:

```swift
enum Currency: String {
    case USD = "USD"
    case EUR = "EUR"
}
class Point: BaseEntity, Mappable {
    var exchangeRate: [Currency: Double]!

    required init?(map: Map) {}

    func mapping(map: Map) {
        exchangeRate <- map["exchange_rate"]
    }
}
```

### What you did:

```swift
let repo = Mapper<Point>().map(myJSONDictionary)
```

### What you expected:

I exepected something like: exchangeRate != nil, but it is. It's ok, I can write transformer, but what if [Enum: Any] is nested?

**Comment by tristanhimmelman** [comment]
Hi there, currently ObjectMapper doesn't support enum values as keys to dictionaries. As you said, a transformer is the best approach to this issue
