### ISSUE TITLE
Mapping Array without key

### ISSUE THREAD

**Issue by yojin31** [Hearst-DD/ObjectMapper#844]
### Your JSON dictionary:

[{a:"123",b:"123",c:"123",d:"123"},
{a:"123",b:"123",c:"123",d:"123"}
{a:"123",b:"123",c:"123",d:"123"}
{a:"123",b:"123",c:"123",d:"123"}]

### Your model:

```swift
struct Repo: Mappable {
  var data = [any]


  init(_ map: Map) {
    name <- map["???"]
  }
}
I dont know what key to map , the JSON has no key?

**Comment by devxoul** [comment]
You should create a temporary dictionary wrapping those array:

```
let json: [String: Any] = [
  "data": yourArray
]
```

Then the json will be looked like:

```json
{
  "data": [
    {"a": 123, "b": 123, "c": 123, "d", 123},
    {"a": 123, "b": 123, "c": 123, "d", 123},
    {"a": 123, "b": 123, "c": 123, "d", 123}
  ]
}
```

You can now map this json dictionary to your model.
