### ISSUE TITLE
Multiple errors for swift 3

### ISSUE THREAD

**Issue by Ssrana** [Hearst-DD/ObjectMapper#849]
Multiple build time errors 
<img width="329" alt="a34fd7aa-7b59-11e6-875a-42e8267d0b9f" src="https://user-images.githubusercontent.com/3450500/28063151-d59a4724-664d-11e7-8018-b4554e0bc9dc.png">

Referred previous issue: https://github.com/Hearst-DD/ObjectMapper/issues/579
 I'm using v1.5.0 and Xcode 8.3.3
 I've cleaned the derived data folder and also cleaned project the tried building, still getting the same issue. Any suggestions?

**Comment by devxoul** [comment]
1.5.0 doesn't support Swift 3. Use at least 2.0.0 version for Swift 3
