### ISSUE TITLE
toJSONString add extra characters

### ISSUE THREAD

**Issue by zhouhao27** [Hearst-DD/ObjectMapper#854]
### Your JSON dictionary:

```json
 {
            "Name": "1707190010056-1-1500464727.jpg",
            "MimeType": "image/jpeg"
}
```

### Your model:

```swift
class Photo: Mappable {
  
  var name: String = ""
  var mimeType: String = "image/jpeg"

  init(_ map: Map) {
    name <- map["Name"]
    mimeType <- map["MimeType"]
  }
}
```

### What you did:

```swift
let string object.toJSONString()
```

### What you expected:

I exepected to get the correct json.

### What you got:

```
 {
            "Name": "1707190010056-1-1500464727.jpg",
            "MimeType": "image\\/jpeg"
}
```

There are some extra characters (\\)  added in my MimeType. I don't know why like this. Can explain and remove these special characters? Thanks.

**Comment by tristanhimmelman** [comment]
ObjectMapper uses the swift class `JSONSerialization` to convert dictionary objects to JSON. If you want to handle the mapping to string yourself, you can use `toJSON` to convert your object to a dictionary of primitives and then you can handle the conversion to string using another utility or perhaps other encoding settings in `JSONSerialization`
