### ISSUE TITLE
toIntMax() Unavailable in IntegerOperators.swift

### ISSUE THREAD

**Issue by MattiasBurstrom** [Hearst-DD/ObjectMapper#856]
### Your JSON dictionary:

```json
{
  "name": "ObjectMapper",
  "url": "https://github.com/Hearst-DD/ObjectMapper"
}
```

### Your model:

```swift
struct Repo: Mappable {
  var name: String!
  var url: URL!

  init(_ map: Map) {
    name <- map["name"]
    url <- map["url"]
  }
}
```

### What you did:

```swift
let repo = Mapper<Repo>().map(myJSONDictionary)
```

### What you expected:

I exepected something like:

```swift
Repo(name: "ObjectMapper", url: "https://github.com/Hearst-DD/ObjectMapper")
```

### What you got:

```swift
Repo(name: "ObjectMapper", url: nil)  // expected the url is mapped correctly
```

**Comment by MattiasBurstrom** [comment]
No idea where the above came from. Trying to report the issue with toIntMax() in IntegerOperators.swift causing a compiler error using Xcode 9/Swift 4 since it's been removed... Didn't see a previous report but maybe it's a known issue.

**Comment by tristanhimmelman** [comment]
Are you using the swift-4 branch of the project?

Also, URL type does not map automatically, you have to use `URLTransform`.

**Comment by MattiasBurstrom** [comment]
I totally missed the swift 4 branch but it works fine with that, thanks!
