### ISSUE TITLE
Throwing initializer for mutable mapping?

### ISSUE THREAD

**Issue by Iambecomeroot** [Hearst-DD/ObjectMapper#858]
Is it possible to use the throwing initializer with a mutable mapping? I like the immutable initalizer because it handlers errors and optionals better but I want certain properties to be mutable. For example:

```swift
struct Object: Mappable {
  var mutableInt: Int?
  let immutableInt: Int

  init(map: Map) throws {
    immutableInt = try map.value("immutableInt")
  }
}
```

I think there should be a way to get the superior init and still have `var` properties be mutable.

**Comment by devxoul** [comment]
It doesn't matter. The only thing you have to do is to make `Object` conform to `ImmutableMappable`.

```swift
struct Object: ImmutableMappable {
  var mutableInt: Int?
  let immutableInt: Int

  init(map: Map) throws {
    mutableInt = try? map.value("mutableInt")
    immutableInt = try map.value("immutableInt")
  }
}
```

**Comment by Iambecomeroot** [comment]
My bad. That's what I tried first but some the instance was immutable because I was trying to change it in a map.
