### ISSUE TITLE
ImmutableMappable final release date

### ISSUE THREAD

**Issue by ealymbaev** [Hearst-DD/ObjectMapper#859]
Hey,

First of all, thank you for the great library. I am using it in our project widely, and we are refactoring our project to get rid of "explicitly unwrapped" variables.

So we need ImmutableMappable feature urgently, but it is in Beta state right now (as written in readme).

So when are you planning to make a final release of it?

**Comment by devxoul** [comment]
I think we can ship ImmutableMappable as an official release. I've been using it about 9 months in my company project and personal projects and there's no problem. How do you think @tristanhimmelman?

**Comment by tristanhimmelman** [comment]
@devxoul I agree, i think it is in good enough shape to release officially. 

@ealymbaev the current version 2.2.8 has all the latest `ImmutableMappable` functionality so feel free to use that. I will update the ReadMe to remove the beta flag from the documentation.

**Comment by ealymbaev** [comment]
Thanks!
