### ISSUE TITLE
Mapping [String]

### ISSUE THREAD

**Issue by mergesort** [Hearst-DD/ObjectMapper#86]
Hi there,

I don't think this is a bug, just my ignorance.

I have a `var` in my class which I would like to map to via `mapping(map:)`, so I'm trying to do something along the lines of
```
// Where domains is of type [String]
self.domains <- map["domains"]
```

I tried writing a `TransformType`, `StringArrayTransform`, which I'm fairly certain isn't the right solution, to turn `[AnyObject]` into `[String]`, and still no luck.

Any thoughts?

Other than that, everything is working great, so thanks a lot for the library!

**Comment by tristanhimmelman** [comment]
Hey there,
It's hard to say what may be the issue here. Can you send a sample of the JSON you are trying to parse?

**Comment by mergesort** [comment]
Oh, jeez, I forgot to include the error. It's actually happening at compile time, so the JSON isn't relevant.

If I do:
```
self.domains <- map["domains"]
```
I get `'String' is not identical to 'AnyObject'`.

If I do:
```
self.domains = (map["domains"], StringArrayTransform())
```
I get `'(Map, StringArrayTransform)' is not convertible to '[String]'`, which makes more sense to me.

**Comment by tristanhimmelman** [comment]
If your domains variable is initialized as follows:
```
var domains: [String] = []
```
or 
```
var domains: [String]?
```
Everything should be fine.

If you are still having issues, please include your complete class definition.

Hope this helps!

**Comment by mergesort** [comment]
Yep, I had it initialized as `var domains: [String] = []`

Looks like this was just Xcode freaking out for a prolonged period of time. I wasn't able to get it to work by clearing derived data, cleaning, and the usual suspects, but eventually after restarting my computer it was fine. :cry: 

All's well that ends well I suppose, thanks for the help!

**Comment by tristanhimmelman** [comment]
No problem! Glad it's all sorted out. Unfortunately Xcode still seems to struggles with Swift

**Comment by mergesort** [comment]
Understatement of the century. :dizzy_face:
