### ISSUE TITLE
Insert Data to Database Using JSON

### ISSUE THREAD

**Issue by christ2702** [Hearst-DD/ObjectMapper#860]
For the first time, I want to say sorry, because I still a new in iOS programming.
Previously, I build an app in Android and I have to insert data to the server from application 
For your information, I inserted the data using a hash map in Android with this code 

`private void insert_erquest() {

        final Intent Intent = getIntent();
        final String PatientName = Intent.getStringExtra("PatientName").toString();
        final String GCQuestionerType = Intent.getStringExtra("GCType").toString();
        final String Critics = EditText1.getText().toString();

        String Url = getResources().getString(R.string.url) + "insert_erquest";

        final ProgressDialog ProgressDialog = new ProgressDialog(QuestERActivity.this);
        ProgressDialog.setMessage("Loading...");
        ProgressDialog.setCancelable(false);
        ProgressDialog.show();

        StringRequest StringRequest = new StringRequest(Request.Method.POST, Url, new Response.Listener<String>() {
            @Override
            public void onResponse(String response) {
                try {
                    JSONObject JSONObject = new JSONObject(response);
                    String message = JSONObject.getString("message");
                    Integer result = JSONObject.getInt("result");

                    if (result == 1) {
                        ProgressDialog.dismiss();
                        Toast.makeText(QuestERActivity.this, "Thank you", Toast.LENGTH_SHORT).show();
                        Intent Intent = new Intent(QuestERActivity.this, MainActivity.class);
                        startActivity(Intent);
                        finish();
                    } else {
                        ProgressDialog.dismiss();
                        Toast.makeText(QuestERActivity.this, "Not Saved", Toast.LENGTH_LONG).show();
                    }
                } catch (JSONException e) {
                    e.printStackTrace();
                }
            }
        }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
                ProgressDialog.dismiss();
                RelativeLayout RelativeLayout = (RelativeLayout) findViewById(R.id.RelativeLayout);
                Snackbar.make(RelativeLayout, "Cannot connect to database, please check your internet connection", Snackbar.LENGTH_SHORT).show();
            }
        }) {
            @Override
            protected Map<String, String> getParams() throws AuthFailureError {
                HashMap<String, String> HashMap = new HashMap<>();
                HashMap.put("GCQuestionerType", GCQuestionerType);
                HashMap.put("PatientName", PatientName);
                HashMap.put("Admission", Admission);
                HashMap.put("IG", IG);
                HashMap.put("Doctor", Doctor);
                HashMap.put("Nurse", Nurse);
                HashMap.put("Pharmacy", Pharmacy);
                HashMap.put("Facility", Facility);
                HashMap.put("Others", Others);
                HashMap.put("Critics", Critics);
                return HashMap;
            }
        };
        StringRequest.setRetryPolicy(new DefaultRetryPolicy(
                DefaultRetryPolicy.DEFAULT_TIMEOUT_MS,
                DefaultRetryPolicy.DEFAULT_MAX_RETRIES,
                DefaultRetryPolicy.DEFAULT_BACKOFF_MULT));

        RequestQueue RequestQueue = Volley.newRequestQueue(QuestERActivity.this);
        RequestQueue.add(StringRequest);
    }`

Now, the problem is I still don't understand how to implement it using swift

Please give me some advice

Thank you

### Your JSON dictionary:

```json
{
  "name": "ObjectMapper",
  "url": "https://github.com/Hearst-DD/ObjectMapper"
}
```

### Your model:

```swift
struct Repo: Mappable {
  var name: String!
  var url: URL!

  init(_ map: Map) {
    name <- map["name"]
    url <- map["url"]
  }
}
```

### What you did:

```swift
let repo = Mapper<Repo>().map(myJSONDictionary)
```

### What you expected:

I exepected something like:

```swift
Repo(name: "ObjectMapper", url: "https://github.com/Hearst-DD/ObjectMapper")
```

### What you got:

```swift
Repo(name: "ObjectMapper", url: nil)  // expected the url is mapped correctly
```

**Comment by tristanhimmelman** [comment]
Strings are not automatically converted to `URL` in ObjectMapper. The developer must define the mapping as follows:
```
url <- (map["url"], URLTransform())
```
