### ISSUE TITLE
Manage the incorrect map of object(using realm)

### ISSUE THREAD

**Issue by dromerobarria** [Hearst-DD/ObjectMapper#862]
Hi, sorry if this question is already asked.

How I can manage the error when I try to map the Json with my model in Realm and for some reason a value doesn't match the type of my model, I know it save it anyway but is there a way to manage if its not correctly map.

### Your JSON dictionary:
```json
{
  "name": "Juan",
  "amount": "1200"
}
```

### Your model:

```swift
struct Person: Object, Mappable {
  var name: String! = ""
  var amount: Int! = 0

   //Impl. of Mappable protocol
    required convenience init?(map: Map) {
        self.init()
    }

   func mapping(map: Map) {
    name <- map["name"]
    amount <- map["amount"]
  }
}
```

### What you did:

```swift
Alamofire.request(request)
                .responseObject(completionHandler: { (response:
                    DataResponse<Person>) in ......

```

###

It will save amount = 0, just cause its not Int.

**Comment by tristanhimmelman** [comment]
Unfortunately there is not validation errors on individual mappings. I think the best you can do is check you variables at the end of the `mapping` function

**Comment by tristanhimmelman** [comment]
Unfortunately there is not validation errors on individual mappings. I think the best you can do is check you variables at the end of the `mapping` function
