### ISSUE TITLE
Float issue on iOS 11

### ISSUE THREAD

**Issue by JanzTam** [Hearst-DD/ObjectMapper#865]
Hi,there. I had a issue when i used `map to Json`. 
And it only happened on iOS 11.

### Your model:
```swift
struct MyModel: Mappable {
    var price: Float?
    init?(map: Map) {
     }
    
    mutating func mapping(map: Map) {
        price <- map["price"]
    }
}
```

### What you did:
```swift
var model = MyModel(JSONString: "{}")
model.price = 63.70

let json = model.toJSONString()
print(json)
```

### What you expected:

I exepected something like:
```json
{
    "price" : 63.7
}
```

### What you got
```json
{
    "price" : 63.700000762939453
}
```

How can i fix it? Did Swift 4 cause it?

**Comment by gunhansancar** [comment]
I second that bug. Need a solution for that as well.

**Comment by JanzTam** [comment]
How to solve it 😭？

**Comment by saschagordner** [comment]
Looks like this is the intended functionality of converting values from JSON to Float (and Double):
https://openradar.appspot.com/34032848

This is not an issue of ObjectMapper.
