### ISSUE TITLE
Pass custom mapping context to nested objects

### ISSUE THREAD

**Issue by ealymbaev** [Hearst-DD/ObjectMapper#873]
Can I pass custom (different) context while mapping a nested object within the map() method. For example, now I am able to pass custom transformer, but not context.

**Comment by tristanhimmelman** [comment]
Using the standard map operator (`<-` ) this is not possible. You can only pass in a context when you explicitly use the Mapper.swift map function. With that said, you could use the `Mapper.map` function within an `Mappable` object to handle nested objects
