### ISSUE TITLE
How to determine if should map when some condition satisfy?

### ISSUE THREAD

**Issue by KittenYang** [Hearst-DD/ObjectMapper#880]
### Your JSON dictionary:

```json
{
  "statuses": [
         {
             "text":"sssss",
             "retweet_statuse":  {
                     "text":"sssss",
                     "retweet_statuse":{}
              },
         },
   ]
}
```

### Your model:

```swift
struct Status: Mappable {
  var text: String!
  var retweet_statuse: Status?

  init(_ map: Map) {
    text <- map["text"]
    retweet_statuse <- map["retweet_statuse"]
  }
}
```

### What you did:

```swift
let status = Mapper<Status>().map(myJSONDictionary)
```

### What you expected:

I exepected something like:

If property `text` equal some specific string , it should not map(exclude).

### What you got:

No idea how to deal with this situation. Can you give some advice? Thanks in advance.

**Comment by tristanhimmelman** [comment]
ObjectMapper does not support this type of validation during mapping. You will have to handle this after mapping has completed
