### ISSUE TITLE
ImmutableMappable TransformOf issue

### ISSUE THREAD

**Issue by jcooperation0137** [Hearst-DD/ObjectMapper#886]
### JSON dictionary:
{
  id: "3fd66200f964a520efe81ee3",
  name: "The River Café",
  contact: {},
  location: {},
  categories: [],
  verified: true,
  stats: {},
  url: "http://www.rivercafe.com",
  price: {},
  hasMenu: true,
  rating: 9,
  ratingColor: "00B551",
  ratingSignals: 465,
  menu: {},
  allowMenuUrlEdit: true,
  beenHere: {},
  hours: {},
  photos: {},
  venuePage: {},
  storeId: "",
  hereNow: {}
}

### Model:

class SEVenueObj : ImmutableMappable {
    var venueId:            String?
    var name:               String?
    var contact:            SEContactObj?
    var location:           SELocationObj?
    var categories:         [SECategoryObj]?
    var verified:           Bool?
    var stats:              SEStateObj?
    var url:                String?
    var price:              SEPriceObj?
    var hasMenu:            Bool?
    var rating:             Float?
    var ratingColor:        UIColor?
    var ratingSignals:      Int?
    var menu:               SEMenuObj?
    var allowMenuUrlEdit:   Bool?
    var beenHere:           SEBeenHereObj?
    var hours:              SEHoursObj?
    var photos:             [SEPhotoObj]?
    var venuePage:          String?
    var hereNow:            SEHereNowObj?
    
    required init(map: Map) throws {
        venueId             = try? map.value("id")
        name                = try? map.value("name")
        contact             = try? map.value("contact")
        location            = try? map.value("location")
        categories          = try? map.value("location")
        verified            = try? map.value("verified", using: SEGlobalService.boolTransform)
        stats               = try? map.value("stats")
        url                 = try? map.value("url")
        price               = try? map.value("price")
        hasMenu             = try? map.value("hasMenu", using: SEGlobalService.boolTransform)
        rating              = try? map.value("rating", using: SEGlobalService.floatTransform)
        ratingColor         = try? map.value("ratingColor", using: SEGlobalService.colorTransform)
        ratingSignals       = try? map.value("ratingSignals", using: SEGlobalService.intTransform)
        menu                = try? map.value("menu")
        allowMenuUrlEdit    = try? map.value("allowMenuUrlEdit", using: SEGlobalService.boolTransform)
        beenHere            = try? map.value("beenHere")
        hours               = try? map.value("hours")
        photos              = try? map.value("photos")
        venuePage           = try? map.value("venuePage")
        hereNow             = try? map.value("hereNow")
    }
    
    func mapping(map: Map) {
        venueId             >>> map["id"]
        name                >>> map["name"]
        contact             >>> map["contact"]
        location            >>> map["location"]
        categories          >>> map["location"]
        verified            >>> (map["verified"], SEGlobalService.boolTransform)
        stats               >>> map["stats"]
        url                 >>> map["url"]
        price               >>> map["price"]
        hasMenu             >>> (map["hasMenu"], SEGlobalService.boolTransform)
        rating              >>> (map["rating"], SEGlobalService.floatTransform)
        ratingColor         >>> (map["ratingColor"], SEGlobalService.colorTransform)
        ratingSignals       >>> (map["ratingSignals"], SEGlobalService.intTransform)
        menu                >>> map["menu"]
        allowMenuUrlEdit    >>> (map["allowMenuUrlEdit"], SEGlobalService.boolTransform)
        beenHere            >>> map["beenHere"]
        hours               >>> map["hours"]
        photos              >>> map["photos"]
        venuePage           >>> map["venuePage"]
        hereNow             >>> map["hereNow"]
    }
}

### My TransformOf function:
static let boolTransform = TransformOf<Bool, String>(fromJSON: { (value: String?) -> Bool? in
        return value == "1"
    }, toJSON: { (value: Bool?) -> String? in
        return value! ? "1" : "0"
    })

In SEVenueObj init function, the following statement always returns 0
because 'value' variable is nil in boolTransform, but the json shows me its not nil 'verified: true'.
verified            = try? map.value("verified", using: SEGlobalService.boolTransform)

I want to get a correct result, not always false.

**Comment by yunzixun** [comment]
I encountered with the same issue, but no solution yet.

**Comment by jcooperation0137** [comment]
I've found out myself what the issue is.
