### ISSUE TITLE
Fixing Swift 3.2 Warnings

### ISSUE THREAD

**Issue by arnopoulos** [Hearst-DD/ObjectMapper#889]
I work on a project that is planning on switching to swift 3.2 and has treat warnings as errors on. I was wondering if there is any plan to fix these warnings? I know there's a PR up to fix the warnings: https://github.com/Hearst-DD/ObjectMapper/pull/885. But will that be merged in before ObjectMapper upgrades to swift 4.0?

The reason I ask is because the team that I work on needs time to upgrade our CI environment to Xcode 9 and uptaking swift 3.2 gives us the time to uptake Xcode 9. If you guys aren't planning on fixing the swift 3.2 warnings we may need to fork the repo until the team I work with can uptake Xcode 9 and that is something that I would very much like to avoid.

**Comment by dclelland** [comment]
PR author here - in the same boat as arnopoulos - I'd love to see this merged and released before the Swift 4.0 work goes in, in order to support Xcode 9/Swift 3.2 projects.

**Comment by tristanhimmelman** [comment]
I have just merged the PR. Thanks!

**Comment by arnopoulos** [comment]
Thanks @tristanhimmelman!
