### ISSUE TITLE
toIntMax() is unavailable in swift 4

### ISSUE THREAD

**Issue by Vuong-Dao** [Hearst-DD/ObjectMapper#890]
Got those problem when build in swift 4

**Comment by SummerOO** [comment]
how to solve this problem........

**Comment by Vuong-Dao** [comment]
if you used xcode 9, please choose convert (swift 4) later, it will help you can build success right now.

**Comment by kubatruhlar** [comment]
You can select *Swift 3.2* under `Pods` -> `Targets` -> `ObjectMapper` -> `Swift language version` option. Or use [swift-4 branch](https://github.com/Hearst-DD/ObjectMapper/tree/swift-4)

**Comment by qingKaiWang** [comment]
怎么解决

**Comment by pilot34** [comment]
Add this to the bottom of your Podfile, until ObjectMapper won't be updated:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            # these libs work now only with Swift3.2 in Xcode9
            if ['ObjectMapper'].include? target.name
                configuration.build_settings['SWIFT_VERSION'] = "3.2"
            end
        end
    end
end
```

**Comment by mehulparmar4ever** [comment]
swift-4 branch
ObjectMapper/Sources/IntegerOperators.swift

Please replace file with this fiel, it will solve all the errors related to that. 
Happy coding

**Comment by tristanhimmelman** [comment]
Please use the latest release with swift 4 support
