### ISSUE TITLE
Swift 4 error

### ISSUE THREAD

**Issue by tahirSmartboy** [Hearst-DD/ObjectMapper#895]
### Method was obsoleted in Swift 4:

```swift
ObjectMapper/Sources/IntegerOperators.swift:100:68: 

'toIntMax()' is unavailable
```

**Comment by mdilaveroglu** [comment]
+1

**Comment by RtzX** [comment]
me too

**Comment by falkobuttler** [comment]
Use the `swift-4` branch

**Comment by tbechtum** [comment]
Swift 4 pre-downloading fails
pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git', :branch => 'swift-4' when using also AlamofireObjectMapper:

[!] Unable to satisfy the following requirements:

- `ObjectMapper (from `https://github.com/Hearst-DD/ObjectMapper.git`, branch `swift-4`)` required by `Podfile`
- `ObjectMapper (from `https://github.com/Hearst-DD/ObjectMapper.git`, branch `swift-4`)` required by `Podfile`
- `ObjectMapper (from `https://github.com/Hearst-DD/ObjectMapper.git`, branch `swift-4`)` required by `Podfile`
- `ObjectMapper (~> 0.10)` required by `AlamofireObjectMapper (0.1)`

**Comment by Sunspension** [comment]
+1

**Comment by phoney** [comment]
This works for me

   pod 'AlamofireObjectMapper', :git => 'https://github.com/tristanhimmelman/AlamofireObjectMapper.git', :branch => 'swift-4'
    pod 'ObjectMapper', '~> 3.0'

**Comment by tbechtum** [comment]
For me too:
Installing AlamofireObjectMapper 5.0.0 (was 4.1.0)
Installing ObjectMapper 3.0.0 (was 2.2.9)
Thanks a lot.

**Comment by tristanhimmelman** [comment]
Please use the latest release, your problems should be resolved.

**Comment by tahirSmartboy** [comment]
@phoney Thank You ... its working 👍
