### ISSUE TITLE
i have also faced this issue 

### ISSUE THREAD

**Issue by MuhammadHarisRafique** [Hearst-DD/ObjectMapper#896]
### Your JSON dictionary:

```json
{
  "name": "ObjectMapper",
  "url": "https://github.com/Hearst-DD/ObjectMapper"
}
```

### Your model:

```swift
struct Repo: Mappable {
  var name: String!
  var url: URL!

  init(_ map: Map) {
    name <- map["name"]
    url <- map["url"]
  }
}
```

### What you did:

```swift
let repo = Mapper<Repo>().map(myJSONDictionary)
```

### What you expected:

I exepected something like:

```swift
Repo(name: "ObjectMapper", url: "https://github.com/Hearst-DD/ObjectMapper")
```

### What you got:

```swift
Repo(name: "ObjectMapper", url: nil)  // expected the url is mapped correctly
```

**Comment by MuhammadHarisRafique** [comment]
if T.self ==   Int.self, let x = Int(exactly: number.int64Value)?.toIntMax() {
        return T.init(x)
    }

toIntMax is Unavailable

**Comment by tristanhimmelman** [comment]
Are you still having this issue. I believe it has been resolved. Closing this issue for now. Please reply if otherwise.
