### ISSUE TITLE
Swift 4 errors

### ISSUE THREAD

**Issue by malkouz** [Hearst-DD/ObjectMapper#897]
Hello,

Do you think to support swift 4 since the method toIntMax() will not available? if YES please push it to cocoa pods

if T.self ==   Int.self, let x = Int(exactly: number.int64Value)?.toIntMax() {
	return T.init(x)
}

**Comment by phoney** [comment]
This works for me

   pod 'ObjectMapper', '~> 3.0'

**Comment by tristanhimmelman** [comment]
Please use the latest release, your problems should be resolved.

**Comment by malkouz** [comment]
Thank you for your co-operation
