### ISSUE TITLE
Swift 4 migration issue (IntegerOperators.swift)

### ISSUE THREAD

**Issue by joelorenz20** [Hearst-DD/ObjectMapper#901]
Hi
I am trying to migrate to swift 4 but I am caught up with these error messages.
Any idea how I can fix this?

<img width="1280" alt="screen shot 2017-10-03 at 4 47 24 pm" src="https://user-images.githubusercontent.com/11159818/31117148-652cfcc0-a85b-11e7-8c78-93e97ed767d1.png">

**Comment by Chetanyg** [comment]
Yes, In Swift 4 (Xcode 9) getting the same error.

**Comment by francodriansetti** [comment]
@joelorenz20  Try to use swift-4 branch

**Comment by krishnameena** [comment]
I am getting following error while updating to swift-4 branch

[
<img width="710" alt="screen shot 2017-10-03 at 4 12 03 pm" src="https://user-images.githubusercontent.com/10487399/31121416-bec7b1cc-a855-11e7-94b7-a550ea86fda4.png">
](url)

**Comment by Chetanyg** [comment]
pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git',
:branch => 'swift-4'

Works for me.

**Comment by krishnameena** [comment]
It is working

**Comment by joelorenz20** [comment]
Yeah, :branch => 'swift-4' fixed the issue.

Thanks =)
