### ISSUE TITLE
'toIntMax()' is unavailable

### ISSUE THREAD

**Issue by uc43** [Hearst-DD/ObjectMapper#908]
hey...
Is this: 'toIntMax()' is unavailable,'toIntMax()' was obsoleted in Swift 4
version - 2.2.9
question file - IntegerOperators.swift

**Comment by iampkhan** [comment]
@uc43 I used 3.0.0 its working

**Comment by michaeldong** [comment]
+1 
who can fixed it ?

**Comment by michaeldong** [comment]
i found a not perfact solution.

https://github.com/Hearst-DD/ObjectMapper/issues/890

**Comment by michaeldong** [comment]
@uc43 temp change swift3.2 for the objectMapper framework.

**Comment by uc43** [comment]
@michaeldong Thanks！
In reading, didn't see here😓

**Comment by SheikhZayed** [comment]
updating the pod to 3.0.0 working for me !

**Comment by Ran-hub** [comment]
'toUIntMax()' is unavailabl
