### ISSUE TITLE
Map different value datatypes?

### ISSUE THREAD

**Issue by wbhminnt** [Hearst-DD/ObjectMapper#918]
Hi,

let's say I have a json object that might look like this:
Variant 1:
```json
{
  "name": "obj1",
  "value": 2
}
```
or like this:
```json
{
  "name": "obj2",
  "value": "myString"
}
```

or like this:
```json
{
  "name": "obj3",
  "value": false
}
```

As you can see the value data type might be different from time to time. 

My model looks like this:

    var name = String?
    var value = Any?

    required init?(map: Map) {
        if map.JSON["value"] != nil {
            if let val = map.JSON["value"] as AnyObject? as? Int {
                value = val
                return
            }
        
            if let val = map.JSON["value"] as AnyObject? as? String {
                value = val
                return
            }
        
            if let val = map.JSON["value"] as AnyObject? as? Bool {
                value = val
                return
            }
        }
    }

    func mapping(map: Map) {
        name <- map["name"]
    }

This actually works. 
Is there any more elegant way of solving this? By using inheritance maybe? 
I just wanted to make sure I didn't miss an existing feature that might suit better.

Thanks!

**Comment by tristanhimmelman** [comment]
Here is an example of how you could solve this found in the ClassClusterTests.swift file:
```
class Vehicle: StaticMappable {
	
	var type: String?
	
	class func objectForMapping(map: Map) -> BaseMappable? {
		if let type: String = map["type"].value() {
			switch type {
				case "car":
					return Car()
				case "bus":
					return Bus()
				default:
					return Vehicle()
			}
		}
		return nil
	}

	init(){
		
	}
	
	func mapping(map: Map) {
		type <- map["type"]
	}
}

class Car: Vehicle {
	
	var name: String?
	
	override class func objectForMapping(map: Map) -> BaseMappable? {
		return nil
	}
	
	override func mapping(map: Map) {
		super.mapping(map: map)
		
		name <- map["name"]
	}
}

class Bus: Vehicle {

	override func mapping(map: Map) {
		super.mapping(map: map)
	}
}
```
