### ISSUE TITLE
Accessing a value of parameter from parent node.

### ISSUE THREAD

**Issue by uditb** [Hearst-DD/ObjectMapper#920]
### Your JSON dictionary:

```json
"userdata": {
"user_id": 1,
"role": "self",
"first_name": "john",
"last_name": "Bush",
"dietry_routine": {
"breakfast_time": "08:55 AM", "lunch_time": "1:15 PM", "dinner_time": "7:30 PM"
        }
    }
```

### Your model:

class UserData: Object, Mappable {
   
    @objc dynamic var user_id: Int = Int(0)
    @objc dynamic var first_name: String? = nil
    @objc dynamic var last_name: String? = nil
    @objc dynamic var dietry_routine: DietaryRoutine?
 
    required convenience init?(map: Map) {
        self.init()
    }
    
    override class func primaryKey() -> String? {
        return "user_id"
    }
    
    // Mappable
    func mapping(map: Map) {
        user_id    <- map["user_id"]
        first_name    <- map["first_name"]
        last_name         <- map["last_name"]
        dietry_routine       <- map["dietry_routine"]
        sleep_time       <- map["sleep_time"]
    }
}

class DietaryRoutine: Object, Mappable {
    @objc dynamic var user_id: Int = Int(0)

    @objc dynamic var breakfast_time: String?
    @objc dynamic var lunch_time: String?
    @objc dynamic var dinner_time: String?
    
    required convenience init?(map: Map) {
        self.init()
    }
    
    // Mappable
    func mapping(map: Map) {
        breakfast_time    <- map["breakfast_time"]
        lunch_time         <- map["lunch_time"]
        dinner_time      <- map["dinner_time"]
    }
}

### What you expected:

I want to have a value of user_id with "DietaryRoutine" object as well to perform filters. Currently, I am getting user_id on "UserData" object. 
How to access user_id from DietaryRoutine

**Comment by tristanhimmelman** [comment]
This is not something ObjectMapper can do automatically. However you can simply set the userId on the DietaryRoutine object after it is mapped. See below:
```
class UserData: Object, Mappable {

@objc dynamic var user_id: Int = Int(0)
@objc dynamic var first_name: String? = nil
@objc dynamic var last_name: String? = nil
@objc dynamic var dietry_routine: DietaryRoutine?

required convenience init?(map: Map) {
    self.init()
}

override class func primaryKey() -> String? {
    return "user_id"
}

// Mappable
func mapping(map: Map) {
    user_id    <- map["user_id"]
    first_name    <- map["first_name"]
    last_name         <- map["last_name"]
    dietry_routine       <- map["dietry_routine"]
    sleep_time       <- map["sleep_time"]

    dietryRoutine.userId = user_id
}
}
```

**Comment by uditb** [comment]
Thanks. This worked for me.
Is there a way having a parameterized ini() function.
