### ISSUE TITLE
toIntMax() (and toUIntMax()) is unavailable

### ISSUE THREAD

**Issue by YunyueLin** [Hearst-DD/ObjectMapper#923]
Hi,I pod ObjectMapper to my project,but in the IntegerOperators.swift  has mang error that's "toIntMax() (and toUIntMax()) is unavailable", What should i do?
my swift version is 4.0

**Comment by AalokParikh** [comment]
Same issues with me too.
I got 10 errors all are pointing to the same issue.

> Swift.BinaryInteger:4:17: 'toIntMax()' was obsoleted in Swift 4

Please provide some update about this. 😀

**Comment by AalokParikh** [comment]
There is error in the read me file need to update that file 
The real latest version for this pod is 3.1 not 2.2 
After setting it to 3.1 all works fine

**Comment by YunyueLin** [comment]
Thanks
