### ISSUE TITLE
nil items not exported with  toJSONString 

### ISSUE THREAD

**Issue by FlorinSVN** [Hearst-DD/ObjectMapper#928]
Hello I have a json that I import with the ObjectMapper wich has null or 0 items
{"Item1":0,"Item2":false},{"Item1":0,"Item2":false},{"Item1":0,"Item2":false}]

The problem is that every time I convert it to a string  with toJSONString    every json Item that has null doesn't appear in the String
This is the output, Item1 dissapeared because it is nill
        {
          "Item2" : false
        },
        {
          "Item2" : false
        },
        {
          "Item2" : false
        },
What can I do so the  exported string contain also the null values?

Thanks

**Comment by vicorente** [comment]
I encountered the same problem, here it is my solution:
```swift
 mutating func mapping(map: Map) {
    map.shouldIncludeNilValues = true
    value >>> map["Item"]
    // Rest of values 
    // ...
  }

```

**Comment by tristanhimmelman** [comment]
`let mapper = Mapper(shouldIncludeNilValues: true)`

If you instantiate Mapper as above the nil values should be included when you output your JSON string
