### ISSUE TITLE
Can't map array from root node of json

### ISSUE THREAD

**Issue by Romixery** [Hearst-DD/ObjectMapper#93]
Hi. I have following json:
<code>
[
  {
    "id": 12,
    "name": "Alex",
    "age": 18
  },
  {
    "id": 13,
    "name": "John",
    "age": 23
  }
]
</code>

I parsed this json by "Jackson" java library and use this json in multiple app. And now i want parse this in swift in iOS app. I make each object of this array as Mappable, But i don't know how i can map this as Array<ProfileInfo> where "ProfileInfo" is my Mappable object. I wrote this code:
<code>
Mapper<[ProfileInfo]>().map(string: json);
</code>
But get error that say [ProfileInfo] is not Mappable.
Please help ! Thank's.

**Comment by tristanhimmelman** [comment]
Hi there,

When mapping an array of objects, you should use the following Mapper function:
`public func mapArray(string JSONString: String) -> [N] `

If that doesn't work, please paste your ProfileInfo object here so I can check if there are any issues there.

Tristan

**Comment by Romixery** [comment]
Thanks. Work's great !!!!.....
