### ISSUE TITLE
mapper swift

### ISSUE THREAD

**Issue by Behnoud** [Hearst-DD/ObjectMapper#931]
### Your JSON dictionary:

```json
{
  "name": "ObjectMapper",
  "url": "https://github.com/Hearst-DD/ObjectMapper"
}
```

### Your model:

```swift
struct Repo: Mappable {
  var name: String!
  var url: URL!

  init(_ map: Map) {
    name <- map["name"]
    url <- map["url"]
  }
}
```

### What you did:

```swift
let repo = Mapper<Repo>().map(myJSONDictionary)
```

### What you expected:

I exepected something like:

```swift
Repo(name: "ObjectMapper", url: "https://github.com/Hearst-DD/ObjectMapper")
```

### What you got:

```swift
Repo(name: "ObjectMapper", url: nil)  // expected the url is mapped correctly
```

**Comment by angelinec** [comment]
You expect the return type for url is URL but from your JSON, its type is a String. You may want to grab it as a String first and then convert it to URL type.

**Comment by tristanhimmelman** [comment]
@angelinec is correct. ALternatively you can use the URLTransform t handle the conversion:
```
url <- (map["url"], URLTransform())
```
