### ISSUE TITLE
Can't map json string into my class!

### ISSUE THREAD

**Issue by tmnd1991** [Hearst-DD/ObjectMapper#95]
I can't map the json string into my object.
I have two classes: Categoria (https://github.com/tmnd1991/poiuytrewq/blob/master/proprioluimix/Model/Categoria.swift)
and Registrazione (https://github.com/tmnd1991/poiuytrewq/blob/master/proprioluimix/Model/Registrazione.swift).
Then i try to run the following:
        let reg = Registrazione(n: "pane",fn: "cane")
        let cat = Categoria(_name: "Pippo", _registrazioni: [reg])
        let catJson = Mapper().toJSONString(cat,prettyPrint: true)
        println(catJson)
        let catBack = Mapper<Categoria>().map(catJson)
        println(catBack)
the first "println" prints the correct json string, but the second prints nil.
Am I making any mistake in the use of the library? Or it's an issue?

**Comment by ikesyo** [comment]
This is related to #74, I think you should use `map(string JSONString:)` like:

```swift
let catBack = Mapper<Categoria>().map(string: catJson)
```

**Comment by tmnd1991** [comment]
Right! thank you, it's ok to close the issue!
