### ISSUE TITLE
Problem with float values after update to Swift 4.1 Xcode 9.3

### ISSUE THREAD

**Issue by quetool** [Hearst-DD/ObjectMapper#955]
Hi, I was using a mappable model like this

```
struct BalanceData: Mappable {
    
    var balance = Float()
    
    init?(map: Map){
    }
    
    mutating func mapping(map: Map) {
        balance     <- map["balance"]
    }
    
}
```

And this is the response I am parsing into that model

```
{
  "status": 200,
  "message": "OK",
  "error": "",
  "data": {
    "balance": 797.76
  }
}
```
This was working just great until I update to Xcode 9.3 and macOS High Sierra this morning.
Now BalanceData.balance is getting 0 instead of 797.76, I have to change var balance = Float() to Double() in model in order to get the correct value.

**Comment by scott4arrows** [comment]
we just changed our Floats to Doubles

**Comment by bes** [comment]
This was quite a suprising bug! Also on Swift 4.1/XCode 9.3 here, and the app just completely stopped working because of this o_O

We also have a large number of Mappable objects and now I am sitting here and wondering are there more things that are broken? Did I find all the floats?

**Comment by tristanhimmelman** [comment]
Hi, I just merged a PR which should address this issue. Please see v3.2.0
