### ISSUE TITLE
post or PUT http request with list of objects as parameters

### ISSUE THREAD

**Issue by M0TRIX** [Hearst-DD/ObjectMapper#968]
var teacher=[teachers]()   // imagine this array is feeded

guard let url=URL(string: "google.com") else {return}

      
        var request=URLRequest(url: url)
        request.httpMethod="PUT"
        
 
        
        request.addValue("Application/Json", forHTTPHeaderField: "Content-Type")

   guard let httpbody=try? JSONSerialization.data(withJSONObject: teacher.toJSON(), options: []) else{return true}
        
        request.httpBody = httpbody
  
        URLSession.shared.dataTask(with: request) { (data, response, Error) in
            
            if let data=data {
    let convertedString=String(data: data, encoding: String.Encoding.utf8)
                print(convertedString)
}

the exception is  :

 "status\":400,\"error\":\"Bad Request\",\"exception\":\"org.springframework.http.converter.HttpMessageNotReadableException\",\"message\":\"JSON parse error: Can not deserialize

**Comment by Adrift001** [comment]
you can print json see see.
