### ISSUE TITLE
mapping to enum

### ISSUE THREAD

**Issue by nithin25** [Hearst-DD/ObjectMapper#969]
I have a dictionary like below
{accessories:[{"name":"mouse","price":"133"},{"name":"keyboard","price":"575"},{"name":"cable","price":"93"}]}

i would like to map it using object mapper and access the accessies as enum (like .keboard & get respective price)
How can i do it?

**Comment by nithin25** [comment]
I have array of dictionaries as above. But the Mappable class accepts dictionaries while initialising. How can pass these array of dictionaries?

**Comment by duyduong** [comment]
Then create an array of that mappable, for example:

class Accessory: Mappable {
   var name = ""
   var price = 0

   required init?(map: Map) {
      name <- map["name"]
      price <- map["price"]
   }
}

class Response: Mappable {
   var accessories = [Accessory]() // default is empty

   required init?(map: Map) {
      accessories <- map["accessories"]
   }
}
