### ISSUE TITLE
Invalid Redeclaration Error with Swift 4.x & Xcode 10 Beta  

### ISSUE THREAD

**Issue by anilabsinc-ajay** [Hearst-DD/ObjectMapper#975]
Hi Team,
That's called a great start with Xcode 10 beta. Now there is no warning for Invalid Redeclaration, instead, it shows Error...
![screen shot 2018-06-05 at 11 19 12 am](https://user-images.githubusercontent.com/33340773/40957344-514fc724-68b2-11e8-9be6-3ba61e3a20a1.png)

**Comment by Ad1991** [comment]
Changing Swift version to 3 does not make it compile either; neither does changing back to legacy build system. It fails in all conditions.

**Comment by anilabsinc-ajay** [comment]
Any Plan to resolve this issue or I have to move back to Xcode 9.4

**Comment by harisworld21** [comment]
Try commenting out duplicate declarations and compile.  It worked for me. And in implementation, use only one type of method call. It is a temporary solution. We need to wait anyways, till we get a fix.

**Comment by alecdoconnor** [comment]
Hi @harisworld21 
This is a working solution, the PR has removed these lines of code to conform to Swift Evolution's `SE-0054 Abolish ImplicitlyUnwrappedOptional`s

**Comment by anilabsinc-ajay** [comment]
@alecdoconnor Need a solution that should work on both xcode 9 and 10

**Comment by gcharita** [comment]
I tried my best to support both Xcode 9 and 10 beta in pull request #980 .

Invalid redeclarations removed from swift 4.2 and above. This means that the warnings in Xcode 9.3 and 9.4 will remain. (invalid redeclarations when removed in swift 4.1 causes some test to fail)

I even added support for Xcode 9.2 (compactMap)

Hope this helps.

**Comment by joshwoods** [comment]
Is there any timeline to be getting a fix in for this? I would like to be moving forward using Xcode 10 to prep for iOS 12, however, this is making it so I cannot even compile our main app. Thanks in advance!

**Comment by alecdoconnor** [comment]
Hi Josh! Feel free to contribute to the PRs to help us get closer to a working build. I believe there were two (the last time that I checked) that technically work, so you would be able to check the branch out directly into your project.

**Comment by anilabsinc-ajay** [comment]
@alecdoconnor Are you planning any timeline for this.

**Comment by alecdoconnor** [comment]
No, because I am not the maintainor of this repository.

**Comment by staz1000** [comment]
Aren't these warnings simply because one implementation of the function is marked for specific versions of Swift and the other is not? 

i.e. just add the following to the other implementation and the warning goes away:

`#if (swift(>=4.1.50))`

**Comment by anilabsinc-ajay** [comment]
@tristanhimmelman Any Plans to update This awesome mapping library for iOS

**Comment by gcharita** [comment]
@anilabsinc-ajay this issue has already been fixed in version 3.3.0. Just download the latest version.

**Comment by staz1000** [comment]
I'm using 3.3.0 and I'm getting these errors.

**Comment by gcharita** [comment]
@staz1000 I am not getting any error in an Xcode 10 project with version 3.3.0.
Maybe you should run a clean or delete DerivedData.

**Comment by wudijimao** [comment]
Update to 3.3.0 is OK!!!!!
`pod update ObjectMapper`

**Comment by wudijimao** [comment]
Any way, The document maybe need to update~   It still suggest us to use ver 3.2.0~

**Comment by tristanhimmelman** [comment]
The README has been updated with v3.3.0.

On Jun 21, 2018, at 10:02 PM, wudijimao <notifications@github.com<mailto:notifications@github.com>> wrote:


Any way, The document maybe need to update~ It still suggest us to use ver 3.2.0~

**Comment by XutongGithub** [comment]
you can update your Profile.
