### ISSUE TITLE
Support for different schema for serialization and deserialization?

### ISSUE THREAD

**Issue by Arvoreniad** [Hearst-DD/ObjectMapper#981]
I'm considering this library for an app I'm working on. However, we need to be able to deserialize some objects using a different JSON schema than the schema used for serialization. 

Is there a practical means of implementing such a pattern with ObjectMapper without requiring multiple object classes?

**Comment by mrdavidrees** [comment]
Yeah there is.

```
override open func mapping(map: Map) {
   super.mapping(map: map)

      propertyA <- map["propertyA"]

      switch map.mappingType {
         case .fromJSON:
           list <- map["list"]
           propertyB <- map["propertyC"]
                
         case .toJSON:
           list <- map["newList"]
           propertyC <- map["propertyB"]
      }

   }
}
```

It's a good library, very extensible. Served me well over the last 2 years.

**Comment by Arvoreniad** [comment]
Exactly what we need, thanks!
