### ISSUE TITLE
Swift 4.2 build error

### ISSUE THREAD

**Issue by medisean** [Hearst-DD/ObjectMapper#986]
please support Swift 4.2.
build in Xcode 10 beta occurs error as following:
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/zouliangming/Desktop/iOS\ 12/Carthage/Checkouts/ObjectMapper/ObjectMapper.xcworkspace -scheme ObjectMapper-iOS -configuration Release -derivedDataPath /Users/zouliangming/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10L213o/ObjectMapper/3.1.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/22/w36k5knn0xl3hsmbn3cz_j400000gn/T/ObjectMapper SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/zouliangming/Desktop/iOS 12/Carthage/Checkouts/ObjectMapper)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/22/w36k5knn0xl3hsmbn3cz_j400000gn/T/carthage-xcodebuild.kyrvS9.log

**Comment by fatevase** [comment]
i have same issue

**Comment by gcharita** [comment]
Just update to the latest version (this fixed in version 3.3.0)

**Comment by medisean** [comment]
Great!
