### ISSUE TITLE
Dynamic objects

### ISSUE THREAD

**Issue by TCNexmo** [Hearst-DD/ObjectMapper#991]
### Intro to issue

I looked around and I could not find any example of this structure, any suggestions on how to implement this with ObjectMapper are appreciated.

### Your JSON dictionary:

```
{
"data" : [
    {
        "inspectionInfo": [                        
                 {
                   "fieldId" : "field1",
                   "value" : "field1",
                   "serverOperation": null
                },
                 {
                   "fieldId" : "field2",
                   "value" : "field2",
                   "serverOperation": null
                }
             ]
       },
       {
        "generalView": [
                 {
                   "fieldId" : "field1",
                   "value" : "field1",
                   "serverOperation": null
                },
                 {
                   "fieldId" : "field2",
                   "value" : "field2.",
                   "serverOperation": null
                }
             ]
       }  
  ]
}
```

### Your model:

```

class InspectionResult: BaseResult {
    
    var inspection: Inspection?

    override func mapping(map: Map) {
        super.mapping(map: map)
        inspection <- map["data"]
    }
    
}


class Inspection: Mappable {
    var section: Array<Section>?
    required init?(map: Map) {
    }
 
    func mapping(map: Map) {
           //Assign the array
    }
 
 
}
class Section: Mappable {
    var fields: Array<Field>?
 
    required init?(map: Map) {
    }
 
    func mapping(map: Map) {
            //Assign the array
    }
}
class Field: Mappable {
    var fieldId: String?
    var serverOperation: String?
    var value: String?
 
    required init?(map: Map) {
    }
 
    func mapping(map: Map) {
        fieldId     <- map["fieldId"]
        serverOperation   <- map["serverOperation"]
        value   <- map["value"]

    }
 
}
```

### Problem

"inspectionInfo" and "generalView" are sections, this json file can change anytime, add more sections or remove them. Each section contains a number of fields. Since I can not hardcode it and do inspectionInfo<- map["inspectionInfo"], how can I approach this?

**Comment by gcharita** [comment]
@TCNexmo your JSON in invalid. Please, update your issue and check if the `data` property is indeed a JSON array. If it is, the `InspectionResult` class will probably need to be something like this:

```swift
class InspectionResult: BaseResult {
    
    var inspection: [Inspection]?

    override func mapping(map: Map) {
        super.mapping(map: map)
        inspection <- map["data"]
    }
}
```

otherwise the value of `inspection` will be always nil.

**Comment by TCNexmo** [comment]
You were correct the JSON was invalid, I have corrected it. it was missing a couple of brackets in the example.

**Comment by TCNexmo** [comment]
@gcharita corrected again, may I ask what do you use to validate it?

**Comment by gcharita** [comment]
@TCNexmo please check again. Any online JSON validator or JSON formatter will do the job. (for example https://jsonformatter.org/)

**Comment by TCNexmo** [comment]
Thank you for the tip, it should be correct now @gcharita

**Comment by TCNexmo** [comment]
I have not yet tried this solution, I will give some feedback once I have done it.

**Comment by TCNexmo** [comment]
This implementation seems to work perfectly, thanks @gcharita
